src/objects/Acknowledgment__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipName>Acknowledgements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Acknowledgments</relationshipLabel>
        <relationshipName>Acknowledgments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Acknowledgment</label>
    <nameField>
        <displayFormat>a-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acknowledgments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan__c.object
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AcknowledgmentTriggerHandler.cls
public with sharing class AcknowledgmentTriggerHandler {
    private boolean m_isExecuting = false;
    public AcknowledgmentTriggerHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    }
    
    public void OnAfterInsert(Acknowledgment__c[] newObjects){
        list<Id> updatedIds = new list<Id>();
        for(Acknowledgment__c ack :newObjects){
            if (ack.Action_Plan__c != null) updatedIds.add(ack.Action_Plan__c);
            if (ack.Assessment__c != null) updatedIds.add(ack.Assessment__c);
        }

        List<Task> updateTasks = [Select id, subject, WhatId, Description
                                    from Task
                                   where What.Type in ('Action_Plan__c','Assessment__c')
                                     And WhatId =: updatedIds  // the associated action plan or assessment(risk/issa)
                                     And status != 'Completed'
                                     And OwnerId = : UserInfo.getUserId()];

        for(Task t : updateTasks){
            t.status = 'Completed';
            t.Description = t.Description + '\r\n\r\n Acknowledged by ' + UserInfo.getName();
        }
        update updateTasks; 
    }

}