src/objects/Acknowledgment__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alias</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipLabel>Acknowledgments</relationshipLabel>
        <relationshipName>Acknowledgments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Acknowledged__c</fullName>
        <label>Date Acknowledged</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CM Census Detail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acknowledged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acknowledgements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Acknowledgment</label>
    <nameField>
        <displayFormat>a-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acknowledgments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Alias__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Operating_Group__c</fullName>
        <label>Alias_Operating_Group</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_unique__c</fullName>
        <externalId>true</externalId>
        <label>Alias_unique</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Authorization_Status__c</fullName>
        <description>Facilitates tracking delivery of services immediately, before authorization process is complete, by providing a temporary status.</description>
        <label>Authorization Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to funding source - optional</description>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payer_Effective_Date__c</fullName>
        <description>Date the authorization is effective according to the payer</description>
        <label>Payer Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer_End_Date__c</fullName>
        <description>=AUTH_END_DATE in Avatar</description>
        <label>Payer End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>1:1 Sitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Holds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Cost Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay - Open Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <recordTypes>
        <fullName>Funding_Source_Auth_CM</fullName>
        <active>true</active>
        <description>Authorization related to funding source</description>
        <label>Funding Source Auth CM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <formula>Service_Location__r.Alias__c</formula>
        <label>Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SA_Start_DateTime__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/rpt_CensusDetail_CM.cls
public class rpt_CensusDetail_CM {
    public date sDate {get; set;}
    public date eDate {get; set;}
    public List<SelectOption> sProgs { get; set; }
    public List<SelectOption> userConfimOptions { get; set; }

    public list<Alias__c> locs {get; set;}
    public string selectedAlias {get; set;}
    public clsReport Report {get; set;}
    public map<id, string> aliasLookup {get; set;}
    
    public boolean getShowParms (){ return ApexPages.currentPage().getParameters().get('ackID') == null;}

    public string getHost(){
    
    return URL.getSalesforceBaseUrl().getHost();
    }
        
    public rpt_CensusDetail_CM(){
        sProgs = new List<SelectOption>();
        eDate = system.today().addDays(-1);
        Report = new clsReport();
        aliasLookup = new map<id, string>();
        userConfimOptions = new list<selectoption>();
        //userConfimOptions.add(  new SelectOption( '',  ' ')  );
        userConfimOptions.add(  new SelectOption( 'Confirm',  'Confirm')  );
        userConfimOptions.add(  new SelectOption( 'Unknown',  'Unknown')  );
        
        id ackID = ApexPages.currentPage().getParameters().get('ackID');
        if(ackID != null){
        
            setReportData(ackID);
        }        
        
        locs = [select id, Alias_unique__c from Alias__c where Alias_Operating_Group__c ='Care Meridian' Order BY Alias_unique__c];
        list<service_location__c> servLocs = [select id, Alias_lookup__r.id,  Alias__c, Location_Nickname__c, iServe_Program__c from Service_Location__c where Alias_lookup__r.Alias_Operating_Group__c ='Care Meridian' AND Status__c = 'Active' Order BY Location_Nickname__c];
        for ( Alias__c L: locs ) {
            string myName = L.Alias_unique__c ;
            boolean addMe = false;
            
            for(service_location__c sl: servLocs){
                if(sl.Alias_lookup__r.id == l.id){
                    myName += ' (' + sl.Location_Nickname__c +')';
                    addME = true;
                }
            }            
            if(addMe){
                aliasLookup.put(l.id, myName);
                SelectOption option = new SelectOption( L.id,  myName );
                sProgs.Add( option );
            }
        }   
        
    
    }
    public void setReportData(id ackID){
        Attachment attach = [select id,  body from Attachment where parentId = :ackID AND name = 'Data.JSON' ];

        Blob myBlob = attach.body;
        String myString = myBlob.toString();

        report =  (clsReport)JSON.deserialize(myString , clsReport.class);

    
    }
    public boolean getHasResults(){
        return report.rptData.size() >0;
    }    

    public PageReference runRpt() {
        sDate = eDate;
        Report = new clsReport();
        Report.eDate = eDate;
        Report.sDate = sDate;
        Report.Program = aliasLookup.get(selectedAlias);
        list<Service_assignment__c> allSAs = [select id, SA_Start_DateTime__c,
                                                Person_Being_Served__r.Name, Person_Being_Served__r.id,
                                                Service_Location__r.Location_Nickname__c   
                                                    From Service_assignment__c 
                                                        Where Service_Location__r.Alias_lookup__r.id = :selectedAlias 
                                                            AND Status__c = 'Active'];
        
        
        list<authorization__c> auths = [select id, name , Funding_Source__r.Service_Assignment__r.id
                                                from authorization__c
                                                    where Type__c = 'Bed Hold' 
                                                        AND recordtype.developername = 'Funding_Source_Auth_CM'
                                                        AND Authorization_Status__c = 'Final'
                                                        AND 
                                                        
             ((Payer_Effective_Date__c >= :sDate and Payer_Effective_Date__c <= :eDate ) or
                (Payer_End_Date__c >= :sDate and Payer_End_Date__c <= :eDate ) or
                ( Payer_Effective_Date__c < :sDate and Payer_End_Date__c > :eDate)
                )                                                        
                                                        /*
                                                        (Payer_End_Date__c <= :eDate
                                                            AND
                                                        Payer_Effective_Date__c >= :sDate)
                                                        
                                                        */
                                                    
                                        ];        
        for(service_assignment__c sa: allSAs){
            rptRow row = new rptRow(sa);
                for(authorization__c a : auths){
                    if(a.Funding_Source__r.Service_Assignment__r.id == sa.id){
                        row.auths.add(a);
                    } 
                }
            Report.rptData.add(row);
        }
        
    
        return null;
    }  
    
    public pageReference signOff (){
        try{
            Acknowledgment__c ack = new Acknowledgment__c();
            ack.User__c = UserInfo.getUserId() ;
            ack.Date_Acknowledged__c = system.today();
            ack.type__c = 'CM Census Detail';
            ack.Alias__c = selectedAlias;
            insert ack;
            
            Attachment att = new Attachment();
            att.parentID = ack.id;
            att.body = Blob.valueOf( JSON.serialize(report) );
            att.name = 'Data.JSON';
            insert att;
            
            PageReference pr = new PageReference('/apex/rpt_CensusDetail_CM?ackId=' + ack.Id );
            pr.setRedirect( true);
            return pr;        
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }        
        return null;
    }
    public class clsReport{
        public date sDate {get; set;}
        public date eDate {get; set;}
        public string Program {get; set;}
        public list<rptRow> rptData {get; set;}

        public clsReport(){
            rptData = new list<rptRow>();
        }
    
    }
    public class rptRow{
        public Service_assignment__c sa     {get; set;}
        public list<authorization__c> auths {get; set;}
        public string userConf              {get; set;}
        public string getStatus(){
            if(auths.size()> 0)
                {return 'Admitted/BedHold';}
            
            return 'Admitted';
        }
        public string getIDforAuth(){
            
            if(auths.size()> 0){
                return auths[0].id;
            }
            
            return '';
        }
        public rptRow(service_assignment__c s){
             sa = s;
             auths = new list<authorization__c>();
        }
    
    }    

}