src/objects/Acknowledgment__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipName>Acknowledgements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acknowledged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Acknowledgements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Acknowledgment</label>
    <nameField>
        <displayFormat>a-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acknowledgments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will contain the Record type name of the referral from where the PBS is created. This value will be used by developers to conditionally render stuff on PBS page and related objects - Sravan: Sep 11, 2015</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals (Person Being Served)</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <recordTypes>
        <fullName>NeuroRestorative</fullName>
        <active>true</active>
        <label>NeuroRestorative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DocDueFromPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field to store the primary case document due from person.</description>
        <inlineHelpText>A field to store the primary case document due from person.</inlineHelpText>
        <label>DocDueFromPerson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will store the Recordtype name of the referral from where the service assignment is created. This will be used by developers to conditionally render stuff on SA page for various flavors. If an adhoc SA is created directly without referral, this field will copy over the value from existing service Assignment available for PBS - Sravan -Sep 11, 2015.</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to referral that converted to this service assignment</description>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/uploaderController.cls
/*
 * Controller for multi attachment component
 */

global with sharing class uploaderController
{
	/**
	 * This proxy class is used to add the Head Shot choosing ability, because
	 * we can't actually add custom fields to Attachment.
	 */
	private class ProxyAttachment {
		private Attachment attachment;
		public ID Id { get { return attachment.ID; } set { attachment.ID = value; } }
		public ID ParentId { get { return attachment.ParentId; } set { attachment.ParentId = value; } }
		public String Name { get { return attachment.Name; } set { attachment.Name = value; } }
		public Blob Body { get { return attachment.Body; } set { attachment.Body = value; } }
		public String Description { get { return attachment.Description; } set { attachment.Description = value; } }
		public Boolean isHeadShot { get; set; }
		public Boolean isPlanOfCare { get; set; }
		public Boolean isISP { get; set; }
		public ProxyAttachment(Attachment attachment) {
			this.attachment = attachment;
			isHeadShot = false;
			isPlanOfCare = false;
			isISP = false;
		}
		public Attachment getSObject() {
			return attachment;
		}
	}

	public Boolean showPersonalRecord{ get; set; }
	private ID whoforTask; // the PBS on the action plan ISP attachment 

	// the parent object
	public Id sobjId {get; set{
		sobjId = value;
		String sObjectName = sobjId.getSObjectType().getDescribe().getLocalName();
		// initialize all selectors to false
		showHeadShotSelection = false;
		showPersonalRecord = false;
		showPlanOfCareSelection = false;
		showISPSelection = false;
		
		if (sObjectName=='Contact') {
			showHeadShotSelection = true;
			showPersonalRecord = true;
		} else if(sObjectName=='Referral__c') {
			Referral__c ref = [ SELECT Id, RecordType.Name FROM Referral__c WHERE ID=:sObjId];
			if (ref.RecordType.Name == 'NeuroRestorative') {
				showPlanOfCareSelection = true;
			}
		} else if (sObjectName == 'Action_Plan__c') {
			Action_Plan__c ap = [ select id, service_assignment__r.flavor__c, service_assignment__r.service_location__r.state__c, service_assignment__r.service_location__r.network_offering__c, service_assignment__r.admission__r.person_being_served__c  from action_plan__c where id = :sObjId];
			if ( ap.service_assignment__r.service_location__r.state__c == 'OH' &&
				 ap.service_assignment__r.service_location__r.network_offering__c == 'IDD' ) { 
				showISPSelection = true;
				whoforTask = ap.service_assignment__r.admission__r.person_being_served__c;
				 } 
		} 
		//System.debug('fileUpload :::' + fileUpload);
		if ( fileUpload != null  && fileUpload.equals('true')){
			showHeadShotSelection = false;
		}
	}}
	public String fileUpload { get; set; }
	public Boolean showHeadShotSelection { get; set; }
	public Boolean showPlanOfCareSelection { get; set; }
	public Boolean showISPSelection { get; set; }
	public String headShotPhotoIndex { get; set; }
	public Boolean hideAddMoreButton { get; set; }
	public String loginUserId { 
    get {
        return UserInfo.getUserId();
    }}
	// list of existing attachments - populated on demand
	public List<Attachment> attachments;

	// list of new attachments to add
	public List<ProxyAttachment> newAttachments {get; set;}

	// the number of new attachments to add to the list when the user clicks 'Add More'
	public static final Integer NUM_ATTACHMENTS_TO_ADD=5;

	public uploaderController()
	{
		// instantiate the list with a single attachment
		newAttachments=new List<ProxyAttachment>{new ProxyAttachment(new Attachment())};
		
		whoforTask = null;
		
	}

	// retrieve the existing attachments
	public List<AttachmentView> getAttachments()
	{    List<AttachmentView> attchmentList = new List<AttachmentView>();
		attachments=[select Id, ParentId, Name, Description,CreatedDate,Owner.Name, OwnerID from Attachment where parentId=:sobjId order by createddate desc limit 10];
			for(Attachment att : attachments){
			attchmentList.add( new AttachmentView(att));
			}
		return attchmentList;
	}

	// Add more attachments action method
	public PageReference addMore()
	{
		// Clear out the current newAttachments first, otherwise we'll run into
		// View State maximum limit
		newAttachments.clear();
		// append NUM_ATTACHMENTS_TO_ADD to the new attachments list
		for (Integer idx=0; idx<NUM_ATTACHMENTS_TO_ADD; idx++)
		{
			newAttachments.add(new ProxyAttachment(new Attachment()));
		}
		hideAddMoreButton = true;
		return null;
	}

	// Save action method
	public PageReference save()
	{
		//System.debug('Save called!');
		List<Attachment> toInsert=new List<Attachment>();
		Integer index = 0;
		Integer ispIndex = -1;
		Boolean headShotFound = false; // only use 1 photo as the headshot
		Boolean planOfCareFound = false;
		Boolean ispFound = false;
		
		for (ProxyAttachment newProxyAtt : newAttachments)
		{
			Attachment newAtt = newProxyAtt.getSObject();
			if (newAtt.Body!=null)
			{
				//System.debug('Body not null');
				if (newProxyAtt.isHeadShot && !headShotFound) {
					//System.debug('This is the headshot');
					newAtt = manageHeadShotName(newAtt);
					headShotFound = true;
				}
				if (newProxyAtt.isPlanOfCare && !planOfCareFound) {
					newAtt = managePlanOfCareName(newAtt);
					planOfCareFound = true;
				}
				if (newProxyAtt.isISP && !ispFound) {
					newAtt = manageISPName(newAtt);
					ispFound = true;
					ispIndex = index;
				}
				newAtt.parentId=sobjId;
				toInsert.add(newAtt);
			}
			index++;
		}
		
		// need results of call to trigger acknowledgment for ISP
		Database.SaveResult[] res = Database.Insert( toInsert, false);
		
		// result array matches original array - find the ISP
		if ( ispIndex > -1 && res[ispIndex].isSuccess() )
			SetAcknowledgmentTasks(res[ispIndex].getId(), sobjId);  

		newAttachments.clear();
		newAttachments.add(new ProxyAttachment(new Attachment()));
		hideAddMoreButton = false;
		// null the list of existing attachments - this will be rebuilt when the page is refreshed
		attachments=null;
		return null;
	}

	public PageReference chooseHeadshot() {
		String attachmentId = Apexpages.currentPage().getParameters().get('aId');
		String attachmentName = Apexpages.currentPage().getParameters().get('aName');
		Attachment a = new Attachment(id=attachmentId, Name=attachmentName);
		a = manageHeadShotName(a);
		upsert a;
		return null;
	}

	public Attachment manageHeadShotName(Attachment a) {
		for (Attachment current: attachments) {
			if (current.Name.indexOf('HeadShot-Current')!=-1) {
				current.Name = 'HeadShot-' + Date.today().format() + findExtension(current.Name);
			}
		}
		upsert attachments;
		a.Name = 'HeadShot-Current' + findExtension(a.Name);
		return a;
	}

	public Attachment managePlanOfCareName(Attachment a) {
		a.Name = 'PlanOfCare-' + Datetime.now().format('MM-dd-yyyy hh:mm:ss a z') + findExtension(a.Name);
		return a;
	}

	public Attachment manageISPName(Attachment a) {
		a.Name = 'ISP-' + Datetime.now().format('MM-dd-yyyy hh:mm:ss a z') + findExtension(a.Name);
		return a;
	}

	private String findExtension(String fileName) {
		List<String> nameParts = fileName.split('\\.');
		if (nameParts.size()<=1) {
			return '';
		}
		return '.' + nameParts[nameParts.size()-1];
	}
	
	// OH-11 
	private void setAcknowledgmentTasks ( ID attachID, ID pId) {
		// for anyone who has acknowledged this action plan's last ISP, set task to re-ack
		Map<Id, Attachment> oldISPs = new Map<ID, Attachment>([ select id from Attachment where parentid = :pId and name like 'ISP%']);
		
		if ( oldISPs.size() == 0 ) 
			return;
		
		Set<ID> userids = new Set<ID>();
		
		// don't want duplicate tasks, so group by user__c - same as distinct
		for( Acknowledgment__c a : [Select user__c from Acknowledgment__c where attachment__c in :oldISPs.keyset() and user__r.isactive = true ]){
			userids.add( a.user__c);
		}
		
		List<Task> newtasks = new List<Task>();
		
		for ( User u : [ select id from User where id in :userids ]) {
            task tmpTask = new task();

            tmpTask.whatid= pID;
            tmptask.OwnerId = u.id;
            tmpTask.Subject = 'ISP Acknowledgment';
            tmpTask.Description = 'Please acknowledge that you have read the new version of the ISP (attached to Action Plan)';
            tmpTask.whoID = whoforTask ;
            newtasks.add(tmpTask);
        }
        insert newtasks;
        
	}

	// Action method when the user is done
	public PageReference done()
	{
		// send the user to the detail page for the sobject
		return new PageReference('/' + sobjId);
	}


		
	    class AttachmentView implements Comparable {
        public Attachment attachment { get; set; }
        public String Name { get {
            return this.attachment.Name;
        }}
        public String OwnerName { get {
            return this.attachment.Owner.Name;
        }}
        public String OwnerId { get {
            return this.attachment.OwnerId;
        }}
        public ID ID { get {
            return attachment.Id;
        }}
        public String LastModifiedDate { get {
            return attachment.LastModifiedDate.format('MM/dd/yyyy hh:mm a');
        }}
       public String CreatedDate { get {
            return attachment.CreatedDate.format('MM/dd/yyyy hh:mm a');
        }}
        public String Description { get {
            return attachment.Description;
        }}
        public AttachmentView(Attachment attachment) {
            this.attachment = attachment;
        }
        public Integer compareTo(Object objToCompare) {
            AttachmentView obj = (AttachmentView) objToCompare;
            if (this.CreatedDate == obj.CreatedDate) return 0;
            if (this.CreatedDate > obj.CreatedDate) return -1;
            return 1;
        }
    }
	
	
	
	
}