src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY()-Birthdate +1)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Picklist__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Aboriginal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>African</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Isles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caribbean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech and Slovak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East and Southeast Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indo-Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latin, Central, South American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maghrebi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oceania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scandinavian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western European</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Family_Member_Other__c</fullName>
        <label>Family Members / Other / Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guardian1_Name__c</fullName>
        <label>Guardian1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guardian_Phone_Number__c</fullName>
        <label>Guardian 1 Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Staff Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose a clinician from the list</errorMessage>
            <filterItems>
                <field>TMN_User__c.Operating_Group__c</field>
                <operation>equals</operation>
                <valueField>$User.Operating_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocDueFromPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field to store the primary case document due from person.</description>
        <inlineHelpText>A field to store the primary case document due from person.</inlineHelpText>
        <label>DocDueFromPerson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Only</fullName>
        <active>true</active>
        <description>This option is for Assessment Only Service Assignments. There will be no Plan/STGs.</description>
        <label>Assessment Only</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/PersonsBeingServedListController.cls
public with sharing class PersonsBeingServedListController {
    private final String PBS_REC_TYPE_ID = [select Id from RecordType where (DeveloperName='Person_Being_Served') and (SobjectType='Account') Limit 1].Id;
    private final String ASSESSMENT_ONLY_REC_TYPE_ID = [select Id from RecordType where (DeveloperName='Assessment_Only') and (SobjectType='Service_Assignment__c') Limit 1].Id;

	private ID argID;
	public boolean defaultToActive { get; set; }
	private List<Account> accountlist = new List<Account>();
	
    public String letterToStart { get; set; }
    public Admission__c[] admissions { get; set; }
    // A list of contact IDs that are available in this View.
    transient public List<String> contactIds;
    transient public List<String> accountIds { get; set; }
    transient public Map<String, Account> accountIdMap { get; set; }
    transient public Map<String, List<Action_Plan__c>> accountIdToJO { get; set; }
    // Because VF doesn't allow us to check the size of a list in a map
    transient public Map<String, Integer> accountIdToJOSize { get; set; }
    transient public Map<String, List<Admission__c>> accountIdToAdmission { get; set; }
    // The following three only contain admissions without plans
    transient public Map<String, Integer> accountIdToAdmissionSize { get; set; }
    transient public Map<String, List<Service_Assignment__c>> admissionIdToServiceAssignment { get; set; }
    transient public Map<String, Integer> admissionIdToServiceAssignmentSize { get; set; }
    private string pfilterID;
    public boolean canCreateNew { get; set; }
    public boolean seeWorksheets { get {
        boolean isRedwood = false;
        
        for(TMN_User__c TU: [select Operating_Group__c from TMN_User__c Where Salesforce_User_Account__r.id = :UserInfo.getUserId() limit 1]){
            if (TU.Operating_Group__c == 'Redwood'){isRedwood = true;} 
        }
        return isRedwood;
    } set; }

    private void getcanCreateNew() {
        
        Schema.DescribeSObjectResult acctSchema = Account.sObjectType.getDescribe();
        canCreateNew = acctSchema.IsCreateable();
        
    }
    public String filterId {
        get {
        	system.debug('GETTING - FILTER ID IS: ' + pFilterId);
            //return con.getFilterId();
            return pfilterID;
        }
        set {
        	system.debug('SETTING - FILTER ID IS: ' + value );
        	con.setFilterId(value);
        	pfilterID = value;
            this.updateCon();
        }
    }
    public List<System.SelectOption> listviewoptions {
        get {
            return con.getListViewOptions();
        }
    }
    Map<ID, String> filtermap = new map<ID, String>();
    
    public ApexPages.StandardSetController con { get; set; }
    public PersonsBeingServedListController() {
    	
        //System.debug('Inside constructor');
        
        // if an account ID is passed in on the url, change the basic query
        argID = ApexPages.CurrentPage().getParameters().get('id');
        if ( argID != null) {
        	// get just this 1 account 
        	accountlist= [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and ID=:argID];	
			System.Debug( 'Incoming account id: ' + argID );
			defaultToActive  = false;
        	
    	} else {
    		// get the default view - recently viewed
    		accountlist = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and lastvieweddate != null order by lastvieweddate desc LIMIT 200];
    		defaultToActive  = true;
        }
		
        // We call this here simply to get the filterId of the View
        this.con = new ApexPages.StandardSetController( accountlist );
        
        String inputFilterId = ApexPages.CurrentPage().getParameters().get('filterId');
        List<Account> filteredList;
        for ( selectoption so : listviewoptions ) {
        	filtermap.put( so.getValue(), so.getLabel());
        }
        
        
        // Kick off updateCon here
        String recentlyViewedId = '';
        
        // Set the default View
        for (SelectOption so: listviewoptions) {
            if (so.getLabel().indexOf('Recently Viewed')!=-1) {
                recentlyViewedId = so.getValue();
            }
        }
        
        if (inputFilterId != '' && inputFilterId != null) {
            System.debug('Setting filterId to inputFilterId ' + inputFilterId);
            this.con.setFilterId( inputFilterId );
            pfilterID = inputFilterId;
            filteredList = getListFromFilter( this.filterId);
        } else if (recentlyViewedId != '') {
            System.debug('Setting filterId to recently viewed');
            this.con.setfilterId (recentlyViewedId);
            pfilterID = recentlyViewedId;
            filteredList = getListFromFilter ( this.filterId);
        } else {  // theoretically this should not happen
            System.debug('Setting filterId to controller\'s default');
            // leave the query at all
            filteredList = this.con.getRecords();
        }
        
        system.debug( 'filtered size: ' + filteredList.size());
        this.con = new ApexPages.StandardSetController( filteredList );
        updateCon();
        getcanCreateNew();
    }


	List<Account> getListFromFilter(ID fID) {
		
		string filterlabel = '';
		List<Account> filteredAcct = new List<Account>();
		
		filterlabel = filterMap.get(fID);
		system.debug('asking for: ' + filterlabel);
		if ( filterlabel.indexOf('Recently Viewed') == 0)
			filteredAcct = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and lastvieweddate != null order by lastvieweddate desc LIMIT 200];
		else if ( filterlabel.indexOf( 'My') == 0 ) 
			filteredAcct = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and ( createdbyid = :UserInfo.getUserId() or ownerid = :UserInfo.getUserId()) ];
		else if ( filterlabel.indexOf('All') == 0 ) 
			filteredAcct = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID];
		else if ( filterlabel.indexOf('New This Week') == 0) 
			filteredAcct = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and createddate = THIS_WEEK];
		
		return filteredAcct;
		
	}
    public String getPBSRecTypeId() {
        return PBS_REC_TYPE_ID;
    }
    
    public String getAssessmentOnlyRecTypeId() {
        return ASSESSMENT_ONLY_REC_TYPE_ID;
    }

    public void updateCon() {
        // This method is so bloated because SF doesn't allow nested SOQL queries
        // for more than 1 level, so we have to do that stuff manually
        System.debug('Inside updateCon');
        String oldFilterId = null;
        contactIds = new List<String>();
        accountIds = new List<String>();
        accountIdMap = new Map<String, Account>();
        accountIdToJO = new Map<String, List<Action_Plan__c>>();
        accountIdToJOSize = new Map<String, Integer>();
        // Because we need to display Admission/Service Assignment without any
        // associated plan as well.
        accountIdToAdmission = new Map<String, List<Admission__c>>();
        accountIdToAdmissionSize = new Map<String, Integer>();
        admissionIdToServiceAssignment = new Map<String, List<Service_Assignment__c>>();
        admissionIdToServiceAssignmentSize = new Map<String, Integer>();


		List<Account> filteredList;
		
		if ( argID != null) {
        	// get just this 1 account 
        	filteredList = [SELECT ID, FirstName, LastName, Owner.ID, Owner.Name, PersonContactId From Account WHERE RecordTypeID=:PBS_REC_TYPE_ID and ID=:argID];	
			System.Debug( 'Incoming account id: ' + argID );
        	
    	} else {
	        system.debug('current filter is:' +  pFilterId );
    	    if (this.con!=null) {
            	//oldFilterId = this.con.getFilterId();
            	oldFilterId = pfilterID;
	        }
    		filteredList = getListFromFilter( oldfilterId);
    		
    	}


        
    	this.con = new ApexPages.StandardSetController( filteredList );
    	system.debug( 'num accts: ' + filteredList.size());	
    	
        // Make sure setPageSize is called BEFORE setFilterId, otherwise it won't work!
        // 06/19/14 - filter does not affect list of accounts in setcontroller because it was constructed using list, not querylocator
        // however, still need to call setfilterid to store the value of the filter
        if ( argID == null ) {
        
        	this.con.setPageSize(2000);
        	if (filterId!=null) {
	            this.con.setFilterId(oldfilterId);
        	}
        } else {
        	this.con.setPageSize(1);
        	this.con.setFilterId(null);
        	pfilterID= '';
        }
        	
	    // We have to make sure that all the records are fetched, regardless of pagination
        Account[] accts = new Account[] {};
        accts.addAll((Account[]) this.con.getRecords());
        while (this.con.getHasNext()) {
            this.con.next();
            accts.addAll((Account[]) this.con.getRecords());
        }
        System.debug('Total number of records: ' + accts.size());

        for (Account acct: accts) {
            accountIdMap.put(acct.ID, acct);
            accountIds.add(acct.ID);
            if (acct.PersonContactId!=null) {
                contactIds.add(acct.PersonContactId);
            }
        }

        for (String ID: accountIds) {
            accountIdToJO.put(ID, new List<Action_Plan__c>());
            accountIdToJOSize.put(ID, 0);
            accountIdToAdmission.put(ID, new List<Admission__c>());            
            accountIdToAdmissionSize.put(ID, 0);
        }        

        // This is a many-to-many model, so in order to uniquely identify
        // 1 pair of records we'll concatenate their IDs together
        Set<String> distinctPlansAndSAs = new Set<String>();
        // Because we don't want duplicate Service Assignment/Admission
        Set<String> admissionsWithPlans = new Set<String>();
        Set<String> saWithPlans = new Set<String>();
        for (Action_Plan__c jo: [
                SELECT ID, Service_Assignment__r.Person_Being_Served__r.Account.ID,
                    Service_Assignment__r.Person_Being_Served__c,
                    Service_Assignment__r.Person_Being_Served__r.Name,
                    Service_Assignment__r.Admission__c,
                    Service_Assignment__r.Admission__r.Effective_date__c,
                    Service_Assignment__r.Name, Service_Assignment__r.RecordType.ID,
                    Service_Assignment__r.Person_Being_Served__r.Account.Owner.Name,
                    Effective_Date__c, Target_Date__c, Status__c,
                    Service_Assignment__c,
                    Service_Assignment__r.Person_Being_Served__r.Account.OwnerID,
                    Service_Assignment__r.Admission__r.State__c,
                    Service_Assignment__r.Admission__r.Status__c,
                    Service_assignment__r.service_location__r.programid__c
                FROM action_plan__c
                WHERE Service_Assignment__r.Person_Being_Served__r.ID in :contactIds
                and     status__c = 'Active Final'
            ]
        ) {
            if (!distinctPlansAndSAs.contains(String.valueOf(jo.ID) + String.valueOf(jo.Service_Assignment__r.ID))) {
                accountIdToJO.get(jo.Service_Assignment__r.Person_Being_Served__r.Account.ID).add(jo);
                accountIdToJOSize.put(jo.Service_Assignment__r.Person_Being_Served__r.Account.ID,
                    accountIdToJOSize.get(jo.Service_Assignment__r.Person_Being_Served__r.Account.ID) + 1);
                distinctPlansAndSAs.add(String.valueOf(jo.ID) + String.valueOf(jo.Service_Assignment__c));
                admissionsWithPlans.add(jo.Service_Assignment__r.Admission__c);
                saWithPlans.add(jo.Service_Assignment__c);
            }
        }
        // EB-116: add status to service assignment subquery for later exclusion 
        for (Admission__c admission : [
                SELECT ID, Effective_Date__c, Person_Being_Served__r.Account.Name,
                       Person_Being_Served__r.Account.ID, State__c, Status__c,
                       Person_Being_Served__r.Account.Owner.ID,
                       Person_Being_Served__r.Account.Owner.Name,
                       (SELECT ID, Name, RecordType.ID, Status__c FROM Service_Agreements__r)
                FROM Admission__c
                WHERE Person_Being_Served__c IN :contactIds
            ]
        ) {        	                 	               	        	     	             	         
            if (!admissionIdToServiceAssignmentSize.containsKey(admission.ID)) {
                admissionIdToServiceAssignmentSize.put(admission.ID, 0);
                admissionIdToServiceAssignment.put(admission.ID, new List<Service_Assignment__c>());
            }            
            
            admissionIdToServiceAssignment.put(admission.ID, new List<Service_Assignment__c>());
            if (admission.Service_Agreements__r.size()==0) {
                accountIdToAdmission.get(admission.Person_Being_Served__r.Account.ID).add(admission);
                accountIdToAdmissionSize.put(admission.Person_Being_Served__r.Account.ID,
                    accountIdToAdmissionSize.get(admission.Person_Being_Served__r.Account.ID) + 1);
            }
            Integer index = 1;
            for (Service_Assignment__c sa: admission.Service_Agreements__r) {
                
                // EB-116: do not show inactive assessment only
                if ( (sa.RecordType.Id == ASSESSMENT_ONLY_REC_TYPE_ID) &&  (sa.Status__c != 'Active') )
                    continue;                   
                
                if (!saWithPlans.contains(sa.ID)) { // don't display duplicated stuff
                    if (index == 1) {
                        accountIdToAdmission.get(admission.Person_Being_Served__r.Account.ID).add(admission);
                        accountIdToAdmissionSize.put(admission.Person_Being_Served__r.Account.ID,
                            accountIdToAdmissionSize.get(admission.Person_Being_Served__r.Account.ID) + 1);
                    }
                    admissionIdToServiceAssignment.get(admission.ID).add(sa);
                    admissionIdToServiceAssignmentSize.put(admission.ID,
                        admissionIdToServiceAssignmentSize.get(admission.ID) + 1);
                    index++;
                }
                 
            }                                                       	
                                                           
        }                
            
    }
    
    @RemoteAction
    public static Contact getPersonBeingServed(String ID) {
        return [
            SELECT Name, Birthdate, Age__c, Ethnicity_Picklist__c, Phone,
                   Guardian1_Name__c, Guardian_Phone_Number__c, Family_Member_Other__c, ID 
            FROM Contact WHERE AccountID=:ID
        ];
    }

    @RemoteAction
    public static Admission__c getAdmission(String ID) {
        return [
            SELECT Name, Effective_Date__c, Network_Offering__c, State__c, Status__c
                   FROM Admission__c WHERE ID=:ID
        ];
    }
    
    @RemoteAction
    public static Service_Assignment__c getServiceAssignment(String ID) {
        return [
            SELECT Name, Admission__r.Name, Start_Date__c, Status__c
                   FROM Service_Assignment__c WHERE ID=:ID
        ];
    }
    
    @RemoteAction
    public static Action_Plan__c getPlan(String ID) {
        return [
            SELECT Name, Service_Assignment__r.Admission__r.Name, Service_Assignment__r.Name, Effective_Date__c,  Target_Date__c, Status__c
                   FROM Action_Plan__c WHERE ID=:ID
        ];
    }
}