src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finalized_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finalized By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finalized_Date__c</fullName>
        <label>Finalized Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Plan Actions</relationshipLabel>
        <relationshipName>Action_Plan_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5100</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Action</label>
    <nameField>
        <displayFormat>APA-{00000}</displayFormat>
        <label>Action Plan Actions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipLabel>Action Plan Goals</relationshipLabel>
        <relationshipName>Action_Plan_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <displayFormat>APG-{00000}</displayFormat>
        <label>Action Plan Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Goal__c</fullName>
        <label>Action Plan Goal</label>
        <referenceTo>Action_Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Plan Objectives</relationshipLabel>
        <relationshipName>Action_Plan_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Behavior - Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior - Duration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Narrative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Objective</label>
    <nameField>
        <displayFormat>APO-{00000}</displayFormat>
        <label>Action Plan Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Queue__c.object
<CustomObject>
    <description>Stores requests from user without permissions to be fulfilled by a login with higher auth</description>
    <fields>
        <fullName>Input_Params__c</fullName>
        <description>name/value pair of input vars.  json format</description>
        <label>Input Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Action Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledge Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Date_Time__c</fullName>
        <description>Date/time the initial request was made</description>
        <label>Requested Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requesting_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>user id that requested txn</description>
        <label>Requesting User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transaction_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Queue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ActionPlan_FormWithoutSharing_Test.cls
@isTest
private class ActionPlan_FormWithoutSharing_Test {
    private static TMN_Generic_Core_TestData testData;
    static testMethod void testForInvalidTxnInput() {
        User tester = Referral_createTestData.createTestUser('astest', 'astest@test.com', 'Action', 'Summary', 'Redwood');
        tester.Operating_Group__c = 'Redwood';
        update tester;
        System.runAs(tester) {
            createData();
            testData.loadData('MN');
            Transaction_Queue__c txn  = new Transaction_Queue__c( requesting_user__c = UserInfo.getUserId());
            txn.request_type__c = 'Action Plan';
            txn.requested_date_time__c = DateTime.Now();
            txn.input_params__c = string.valueOf(testData.ContactID);
            try {
                insert txn;  // a dmlException will be thrown here since there is not action plan created yet... and the Id being passed in is pbsID instead of apID 
                PageReference pageRef = Page.DSPActionPlan;
                Test.setCurrentPage(pageRef);
                pageRef.getParameters().put('txnID', txn.ID);
                TxnQueueResponseController controller = new TxnQueueResponseController();
                throw new DataCreateException('We should have never come to this line of code.');
            } catch(DMLException e) {
                system.assert(true);
            } catch(Exception e) {
                throw e ;
            } 
        }
    }
    public class DataCreateException extends Exception{
    } 
    
    static testMethod void myUnitTest() {
        User redwoodUser = TMN_Generic_Core_TestData.createUser('ESD General', 'joeSmith', 'joeSmith@tmn.com.joeSmith', 'joe', 'smith', 'Redwood');
        TMN_User__c redwoodtmnUser = [SELECT ID, Name FROM TMN_User__c WHERE Salesforce_User_Account__c =: redwoodUser.id];
        
        system.runas(redwoodUser){
            Action_Plan__c ap = createAction_Plan();
            ap.Status__c = 'Active Final';
            ap.finalized_by__c = UserInfo.getUserId();
            ap.Finalized_Date__c = system.today();
            update ap;
            
            Transaction_Queue__c txn  = new Transaction_Queue__c( requesting_user__c = UserInfo.getUserId());
            txn.request_type__c = 'Action Plan';
            txn.requested_date_time__c = DateTime.Now();
            txn.input_params__c = string.valueOf(ap.Id);
            insert txn;
            
            PageReference pageRef = Page.DSPActionPlan;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('txnID', txn.ID);
            
            TxnQueueResponseController controller = new TxnQueueResponseController();
            system.assert(controller.response.isRedwood);
            system.assert(controller.response.GETplanStuff().keySet().size() > 0);
            
            DSPSubmitTxn extension = new DSPSubmitTxn(controller);
            extension.ackAPID = ap.Id;
            extension.initials = 'Test';
            pageRef = extension.ackActionPlan();
            Test.setCurrentPage(pageRef);
            controller = new TxnQueueResponseController();
            
            // assert that the ack recrod exists for this assessment, and the page after ACK was indeed the ISSA page.
            system.assert(pageRef.getRedirect());
            system.assert(pageRef.getUrl().containsIgnoreCase('DSPActionPlan'));
            system.assert(controller.response.ackwraplist.size() == 1);
        }
    }
    
    private static void createData(){
        testData = new TMN_Generic_Core_TestData();
    }
    
    private static Action_Plan__c createAction_Plan(){
        createData();
        
        Action_Plan__c ap = new Action_Plan__c(
            Service_Assignment__c = testData.theSA.id,
            Target_Date__c = testData.theSA.Start_Date__c.addDays(1),
            Effective_Date__c = testData.theSA.start_Date__c
        );        
        insert ap; 
        
        Action_Plan_Goal__c apg = new Action_Plan_Goal__c(
            Description__c = 'a goal',
            Action_Plan__c = ap.id,
            sort_order__c = 'g'
        );
        insert apg;
        
        Action_Plan_Objective__c apo = new Action_Plan_Objective__c(
            Action_Plan_Goal__c = apg.id,
            Status__c = 'In Progress',
            Description__c = 'an Objective',
            Type__c = 'skill',
            Target_End_Date__c = testData.theSA.Start_Date__c.addDays(1),
            Effective_Date__c = testData.theSA.Start_Date__c,
            sort_order__c = 'o'
        );
        insert apo;
        
        Action_Plan_Action__c apa = new Action_Plan_Action__c ();
        apa.Action_Plan_Objective__c = apo.id;
        apa.Description__c = 'action';
        apa.sort_order__c = 'a';
        apa.Start_Date__c = testData.theSA.Start_Date__c;
        apa.End_Date__c = testData.theSA.Start_Date__c.addDays(1);
        apa.Status__c = 'New';
        insert apa;
        
        return ap;
    }
    
}