src/objects/Action_Behavior_Result__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Behavior Results</relationshipLabel>
        <relationshipName>Action_Behavior_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Action Behavior Result</label>
    <nameField>
        <label>Action Behavior Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Behavior Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Behavior - Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior - Duration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Narrative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Objective</label>
    <nameField>
        <displayFormat>APO-{00000}</displayFormat>
        <label>Action Plan Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Skill_Result__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Skill Results</relationshipLabel>
        <relationshipName>Action_Skill_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attempts__c</fullName>
        <label>Attempts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Skill Result</label>
    <nameField>
        <label>Action Skill Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Skill Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Medicaid_ID__c</fullName>
        <label>Medicaid ID</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Late_Entry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Late Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Narrative_Note__c</fullName>
        <label>Narrative Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Vocational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Habilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBSCL- Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCL (BI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCL (ID) - Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Based Habilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alone Time</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TMN_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Generic field to be used for Type across multiple eval response recordtypes</description>
        <label>Type</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Time_Log</fullName>
        <active>true</active>
        <description>Used to keep track of coming/going of day program attendees</description>
        <label>Time Log</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Late_Entry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Late Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>TEXT(Service_Assignment__r.Location_Region__c)</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>created for NeuroRestorative IL role and rec type called &quot;Therapy&quot;</description>
        <label>Type of Treatment</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Professional_Title__c</fullName>
        <description>User created/edited field, this is different from the Job Title field. Job Title is from HR.</description>
        <label>Professional Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IowaDailyDataSummary.cls
public virtual with sharing class IowaDailyDataSummary {
    public date serviceDate {get; set;}
    public Id sAId {get; set;}

    public Service_Assignment__c pbsObj {get; set;}  

    public list<TimeLog> timelogs {get;set;}
    
    public list<Action_Plan_Objective__c> skillObjectiveList {get;set;}
    public list<Action_Plan_Objective__c> behaviorObjectiveList {get;set;}
    public map<Id, list<Action_Skill_Result__c>> objectiveToSkillResultMap {get;set;}
    public map<Id, list<Action_Behavior_Result__c>> objectiveToBehaviorResultMap {get;set;}
    public map<id, list<BehaviorResultWrapper>> objectiveToBehaviorResultWrapperMap {get;set;}

    public list<Progress_Note__c> notes {get;set;}
    public Boolean eSignComplete {get; set;}
    
    
    public without sharing class NoSharingRecord {
        public NoSharingRecord(){}
        public TMN_User__c getTmnAccess(){
            return [SELECT Id, Name, Professional_Title__c FROM TMN_User__c WHERE Salesforce_User_Account__c =: UserInfo.getUserId() limit 1];
        }
    }
    public String title {get {return (new NoSharingRecord()).getTmnAccess().Professional_Title__c ;} }
    
    public list<TimeStamp> timeStamps {get;set;}
    
    public IowaDailyDataSummary(){
    	eSignComplete = false;
    	
        timelogs = new list<Timelog>();
        timeStamps = new list<TimeStamp>();
        timeStamps.add(new TimeStamp(Time.newInstance(8, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(9, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(10, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(11, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(12, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(13, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(14, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(15, 0, 0, 0)));
        timeStamps.add(new TimeStamp(Time.newInstance(16, 0, 0, 0)));
        
        skillObjectiveList = new list<Action_Plan_Objective__c>();
        behaviorObjectiveList = new list<Action_Plan_Objective__c>();
        objectiveToSkillResultMap = new map<Id, list<Action_Skill_Result__c>>();
        objectiveToBehaviorResultMap = new map<Id, list<Action_Behavior_Result__c>>();
        objectiveToBehaviorResultWrapperMap = new map<Id, list<BehaviorResultWrapper>>();
    
        this.sAId = ApexPages.CurrentPage().getParameters().get('saId');
        this.serviceDate = Date.parse(ApexPages.CurrentPage().getParameters().get('serviceDate'));
        
       
        TimeZone zone = UserInfo.getTimeZone();       
        datetime startDateTime = serviceDate;
        if(startDateTime !=null){startDateTime = startDateTime.addSeconds((zone.getOffset(startDateTime)/1000)*-1);}
        datetime endDateTime = serviceDate;
        if(endDateTime !=null){
           endDateTime = endDateTime.addSeconds((zone.getOffset(endDateTime)/1000)*-1);
           endDateTime = endDateTime.addDays(1);
           endDateTime = endDateTime.addseconds(-1);
        }
       
        pbsObj = [Select Name, Person_Being_Served__r.FirstName, Person_Being_Served__r.Middle_Name__c, Person_Being_Served__r.LastName, Person_Being_Served__r.Birthdate, Person_Being_Served__r.Medicaid_ID__c 
                    from Service_Assignment__c where id =: this.sAId];
        for (Evaluation_response__c log : [Select Start_Date_Time__c, End_Date_Time__c, CreatedById, tmn_user__r.Name, location__c, is_late_entry__c, service_type__c, Narrative_Note__c 
                    From Evaluation_response__c where Start_Date_time__c >=: startDateTime
                    AND End_date_time__c < : endDateTime
                    AND Service_Assignment__c =: this.sAId AND RecordType.DeveloperName = 'Time_Log' AND Disregard__c = false   
                    order BY start_Date_time__c, end_date_time__c] ) {
                    	if (log.Start_Date_Time__c.hour() >= 8 && log.End_Date_Time__c.hour() <= 16) timelogs.add(new Timelog(log));    
        }

        for (Action_Skill_Result__c skillResult: [SELECT Attempts__c, Status__c, Met_Objective__c, Initials__c, Day__c, Action_Plan_Objective__c,
                                                           Action_Plan_Objective__r.Former_Id__c, Action_Plan_Objective__r.Type__c, Action_Plan_Objective__r.Status__c, Action_Plan_Objective__r.Description__c,
                                                           Action_Plan_Objective__r.CreatedDate, Action_Plan_Objective__r.Effective_Date__c, Action_Plan_Objective__r.Target_End_Date__c
                                                      FROM Action_Skill_Result__c
                                                     WHERE Action_Plan_Objective__r.action_plan_goal__r.action_plan__r.Service_Assignment__c =: sAId 
                                                       AND Day__c =: serviceDate
                                                     order By Action_Plan_Objective__c, Day__c]) {
            if (!objectiveToSkillResultMap.containsKey(skillResult.Action_Plan_Objective__c)) {
                    skillObjectiveList.add(new Action_Plan_Objective__c(Id = skillResult.Action_Plan_Objective__c, Type__c = skillResult.Action_Plan_Objective__r.Type__c, 
                                               Status__c = skillResult.Action_Plan_Objective__r.Status__c, Description__c = skillResult.Action_Plan_Objective__r.Description__c));
                    objectiveToSkillResultMap.put(skillResult.Action_Plan_Objective__c, new List<Action_Skill_Result__c>());
            }
            objectiveToSkillResultMap.get(skillResult.Action_Plan_Objective__c).add(skillResult);
        }
        for (Action_Behavior_Result__c behaviorResult: [SELECT Day_time__c, Occurrences__c, Occurred__c, Action_Plan_Objective__c,
                                                               Action_Plan_Objective__r.Former_Id__c, Action_Plan_Objective__r.Type__c, Action_Plan_Objective__r.Status__c, Action_Plan_Objective__r.Description__c,
                                                               Action_Plan_Objective__r.CreatedDate, Action_Plan_Objective__r.Effective_Date__c, Action_Plan_Objective__r.Target_End_Date__c
                                                          FROM Action_Behavior_Result__c
                                                         WHERE Day_time__c <= : Datetime.newInstanceGMT(serviceDate, Time.newInstance(16, 0, 0, 0))
                                                           AND Day_time__c >= : Datetime.newInstanceGMT(serviceDate, Time.newInstance(8, 0, 0, 0))
                                                           AND Action_Plan_Objective__r.action_plan_goal__r.action_plan__r.Service_Assignment__c =: sAId
                                                         order By Action_Plan_Objective__c, Day_time__c]) {
            if (!objectiveToBehaviorResultMap.containsKey(behaviorResult.Action_Plan_Objective__c)) {
                    behaviorObjectiveList.add(new Action_Plan_Objective__c(Id = behaviorResult.Action_Plan_Objective__c, Type__c = behaviorResult.Action_Plan_Objective__r.Type__c, 
                                               Status__c = behaviorResult.Action_Plan_Objective__r.Status__c, Description__c = behaviorResult.Action_Plan_Objective__r.Description__c));
                    objectiveToBehaviorResultMap.put(behaviorResult.Action_Plan_Objective__c, new List<Action_Behavior_Result__c>());
            }
            objectiveToBehaviorResultMap.get(behaviorResult.Action_Plan_Objective__c).add(behaviorResult);
        }
        for (Action_Plan_Objective__c key : behaviorObjectiveList){
            objectiveToBehaviorResultWrapperMap.put(key.id, new list<BehaviorResultWrapper>());
            for(TimeStamp t : timeStamps) {
                boolean timeTokenAdded = false;
                for(Action_Behavior_Result__c res : objectiveToBehaviorResultMap.get(key.id)){
                    if (res.Day_time__c.addSeconds(zone.getOffset(res.Day_time__c)/1000*-1).time() ==  t.token ){
                        objectiveToBehaviorResultWrapperMap.get(key.id).add(new BehaviorResultWrapper(t.getLabel(),res));
                        timeTokenAdded = true;
                        break;
                    }
                }        
                if (!timeTokenAdded) objectiveToBehaviorResultWrapperMap.get(key.id).add(new BehaviorResultWrapper(t.getLabel(),new Action_Behavior_Result__c()));
            }
        }

        notes = [select name, id, Start_Time__c, End_time__c, Narrative__c,  createddate, createdby.name, Late_Entry__c, Approval_Status__c 
                  from Progress_Note__c where Service_Assignment__c =: this.sAId
                   AND Start_Time__c >=:  startDateTime
                   AND End_time__c <= : endDateTime
                   AND Disregard_Note__c = false order by Start_Time__c, End_time__c];
    }
    
    public PageReference prepareForPDF(){
    	return null;
    }
    
    public virtual PageReference exportToPDF(){
        PageReference pdf = Page.IowaDailyDataSummaryPDF;
        String file = pbsObj.Person_Being_Served__r.FirstName + ' ' + pbsObj.Person_Being_Served__r.LastName + ' - ' + String.valueOf(serviceDate).replace('-','') +  '.pdf';
        file = file.replaceAll('[|,||\\,||"||:|~|!|@|#|$|%|^|&|*|_|+|=|<|>|?|\\(|\\)|\\{|\\}|\\;|\\\'"]', ' ');
        pdf.getHeaders().put('content-disposition', 'attachment; filename="'+file+'"');
        return pdf;
    }
    
    public class BehaviorResultWrapper {
        public Action_Behavior_Result__c result {get;set;}
        public String timeLabel {get;set;}
        
        public BehaviorResultWrapper(String timeLabel, Action_Behavior_Result__c result){
            this.result = result;
            this.timeLabel = timeLabel;
        }
    } 

   
    public class TimeStamp {
        public Time token {get;set;}
        public String getLabel(){
            return convertToAmPmNoon(DateTime.newInstance(Date.today(), this.token));
        }
        
        public TimeStamp(Time token){
            this.token = token;
        }       
    } 
    

    public static string convertToAmPmNoon(DateTime dt){
            String[] parts = dt.format().split(' ');
            return (parts.size() == 3) ? (parts[1] + ' ' + parts[2]) : parts[1];
    }
            
    public class TimeLog{
        public Evaluation_response__c timeLog {get; set;}
        public String getStartTime(){
            return convertToAmPmNoon(this.timeLog.Start_Date_Time__c);
        }
        public String getEndTime(){
            return convertToAmPmNoon(this.timeLog.End_Date_Time__c);
        }
        public TimeLog(Evaluation_response__c log){
            this.timeLog = log;
        }
    }
}