src/objects/Action_Objective_Result__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Objective Results</relationshipLabel>
        <relationshipName>Action_Objective_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Leave/Absent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Objective Result</label>
    <nameField>
        <label>Action Objective Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Objective Results</pluralLabel>
    <recordTypes>
        <fullName>Service_Objective</fullName>
        <active>true</active>
        <label>Service_Objective</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipLabel>Action Plan Goals</relationshipLabel>
        <relationshipName>Action_Plan_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Former_ID__c</fullName>
        <externalId>true</externalId>
        <label>Former ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <displayFormat>APG-{00000}</displayFormat>
        <label>Action Plan Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Former_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Former ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Behavior - Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior - Duration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Narrative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Objective</label>
    <nameField>
        <displayFormat>APO-{00000}</displayFormat>
        <label>Action Plan Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Worksheet__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipLabel>Action Plan Worksheets</relationshipLabel>
        <relationshipName>Action_Plan_Worksheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Action Plan Worksheet</label>
    <nameField>
        <label>Action Plan Worksheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Worksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Summary__c.object
<CustomObject>
    <description>Provides a summary of Action Plan results</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>Action_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Summary</label>
    <nameField>
        <label>Action Plan Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServiceTrackingList.cls
public without sharing class ServiceTrackingList {
    public String actionPlanId {get; set;}
    public date serviceTrackingMonth {get; set;}
    public String objResultId {get; set;}
    public String wsId {get; set;}
    public transient Action_Summary__c summary {get; set;}
    
    public list<ServiceObj> serviceTrakingResults {get; set;}

    public ServiceTrackingList(ApexPages.StandardController controller) {
    	this(controller.getRecord().Id);
    }
    
    public ServiceTrackingList(ID input) {
    	map<Id,Action_Plan_Objective__c> objectives;
        map<String, ServiceObj> serDetails = new map<String, ServiceObj>();
            	
    	if (input.getSObjectType().getDescribe().getName() == 'Action_Plan_Worksheet__c'){
	    	this.wsId = input;
	        Action_Plan_Worksheet__c ws = [select Name, Start_Date__c, Action_Plan__c, action_Plan__r.Status__c,        
	                                             Action_Plan__r.Service_Assignment__r.Admission__r.State__c, Action_Plan__r.Service_Assignment__c, 
	                                             Action_Plan__r.Service_Assignment__r.Admission__c, Action_Plan__r.Service_Assignment__r.Admission__r.Person_Being_Served__c 
	                                        from Action_Plan_Worksheet__c
	                                        where Id = : this.wsId];
	
	        this.actionPlanId = ws.Action_Plan__c;
	        this.serviceTrackingMonth = ws.Start_Date__c;
	        
	        objectives = new map<Id, Action_Plan_Objective__c> ([select Id, Former_Id__c, Type__c, Status__c, Description__c,
                                                                        CreatedDate, Effective_Date__c, Target_End_Date__c, sort_order__c, action_plan_goal__r.sort_order__c
									                               from  Action_Plan_Objective__c
									                              where Action_Plan_Goal__r.Action_Plan__c = : ws.Action_Plan__c
									                                and ((effective_date__c >= : ws.Start_Date__c) or (effective_date__c = null))
									                                and ((target_end_date__c < : ws.Start_Date__c.addMonths(1)) or (target_end_date__c = null))
									                                and Type__c IN ('Yes/No', 'Yes/No w/time') 
									                              order by type__c, sort_order__c, action_plan_goal__r.sort_order__c ]);
        } else if (input.getSObjectType().getDescribe().getName() == 'Action_Summary__c') {
	        summary = [select Id, Name, Comments__c, Duration__c, End_Date__c, Service_Assignment__c, Start_Date__c, Status__c, 
	                                            Unique_Check__c, Finalized_By__c, Finalized_Date__c, New_Version__c, Approver__c 
	                                       from Action_Summary__c where id = : input];
	        objectives = new Map<Id, Action_Plan_Objective__c>([
												                SELECT Id, Former_Id__c, Type__c, Status__c, Description__c,
												                       CreatedDate, Effective_Date__c, Target_End_Date__c, sort_order__c, action_plan_goal__r.sort_order__c
												                  FROM Action_Plan_Objective__c
												                 WHERE Effective_Date__c <= :summary.End_Date__c
												                   AND Target_End_Date__c >= :summary.Start_Date__c
												                   AND action_plan_goal__r.action_plan__r.Service_Assignment__c = :summary.Service_Assignment__c
												                   AND (action_plan_goal__r.action_plan__r.Status__c = 'Inactive Final'
												                    OR action_plan_goal__r.action_plan__r.Status__c = 'Active Final')
												                   AND action_plan_goal__r.action_plan__r.Effective_Date__c < :summary.End_Date__c
												                   AND action_plan_goal__r.action_plan__r.Target_Date__c >= :summary.Start_Date__c
												                   AND type__c IN ('Yes/No', 'Yes/No w/time')
												                ORDER BY type__c, sort_order__c, action_plan_goal__r.sort_order__c 
												            ]);
												            
	        for(Action_Plan_Objective__c obj : objectives.values() ) {
	            if (! serDetails.containsKey(String.ValueOf(obj.Id))) 
	               serDetails.put(String.ValueOf(obj.Id), new ServiceObj(obj) );
	        }									            
        }

        set<Id> objectiveIds = objectives.keySet();
        list<string> selectFields = new list<string>();
        Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get('Action_Objective_Result__c').getDescribe().Fields.getMap();
            if (fMap != null) {
                for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
                    Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                    selectFields.add(fd.getName());
                }
            }
        selectFields.addAll(new List<String>{'Action_Plan_Objective__r.Action_Plan_Goal__r.Action_Plan__c','Action_Plan_Objective__r.Description__c','Action_Plan_Objective__r.Type__c'});
        String strSQL =  'SELECT ' + String.join(selectFields, ',') + ' FROM Action_Objective_Result__c WHERE RecordType.Name = '+ ' \'Service_Objective\' ' + ' And Action_Plan_Objective__c in :objectiveIds order by Service_Date_Part__c nulls last, Service_Time__c nulls last';
        list<Action_Objective_Result__c> objectiveResults = (list<Action_Objective_Result__c>) Database.query(strSQL);

        for(Action_Objective_Result__c objectiveResult : objectiveResults){
        	if (! serDetails.containsKey(String.ValueOf(objectiveResult.Action_Plan_Objective__c))) 
        	   serDetails.put(String.ValueOf(objectiveResult.Action_Plan_Objective__c), new ServiceObj(objectives.get(objectiveResult.Action_Plan_Objective__c)) );
        	   
        	ServiceObj service = serDetails.get(String.ValueOf(objectiveResult.Action_Plan_Objective__c));
        	service.trackingResults.add(new ServiceTracking.ObjResultWrapper(objectiveResult));
        }
        
        for (ServiceObj ser : serDetails.values()){
        	ser.trackingResults.sort();
        } 
        this.serviceTrakingResults = new list<ServiceObj>();
        this.serviceTrakingResults.addAll(serDetails.values());
    }

    public pagereference editServiceData(){
            PageReference pr = Page.ServiceTracking;
            pr.getParameters().put('Id', this.objResultId);
            pr.getParameters().put('Edit', 'true');
            pr.setRedirect(true);
            return pr;
    }

    public pagereference newServiceData(){
    	boolean isDspPage = ApexPages.currentPage().getUrl().containsIgnoreCase('DSP') ? true : false;
    	if (isDspPage){
	        DSPSubmitTxn txnService = new DSPSubmitTxn();
	        txnService.requestType = 'Service';
	        txnService.inputArgs = this.wsId;
	        return txnService.submitTxnRequest();
    	}else {
            PageReference pr = Page.ServiceTracking;
            pr.getParameters().put('Id', this.wsId);
            pr.setRedirect(true);
            return pr;
    	}    	
    }

    public pagereference submitTxnRequest(){
        Transaction_Queue__c txn  = new Transaction_Queue__c(requesting_user__c = UserInfo.getUserId());
        txn.request_type__c = 'Edit Service';
        txn.requested_date_time__c = DateTime.Now();
        txn.input_params__c = this.objResultId;
        try { 
            insert txn;
            PageReference pr = Page.DSPServiceTracking;
            pr.getParameters().put('txnID', txn.ID);
            pr.setRedirect(true);
            return pr;
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }              
    }
    
    public class ServiceObj {
        public string QuestionID {get; set;}
        public string description {get; set;}
        public date effective_Date {get; set;}
        public date target_end_date {get; set;}
        public string type {get; set;}
        public string Status {get; set;}
        public date revisedDate {get; set;}
        
        public list<ServiceTracking.ObjResultWrapper> trackingResults {get; set;}

        public ServiceObj(Action_Plan_Objective__c tmpObj){
        	this.QuestionID = tmpObj.Id;
            this.description = tmpObj.Description__c;
            this.effective_Date = tmpObj.effective_Date__c;
            this.target_end_date = tmpObj.Target_end_date__c;
            this.type = tmpObj.type__c;
            this.status = tmpObj.Status__c;
            this.trackingResults = new list<ServiceTracking.ObjResultWrapper>();
            this.revisedDate = (tmpObj.Former_ID__c instanceOf ID) ? date.newinstance(tmpObj.CreatedDate.year(), tmpObj.CreatedDate.month(), tmpObj.CreatedDate.day()) : null;
        }
        
        /* public Integer hashCode() {
            return this.QuestionID.hashCode();
        }
        public boolean equals(Object obj) {
            if (obj instanceof ServiceObj) {
                ServiceObj o = (ServiceObj) obj;
                return this.QuestionID == o.QuestionID;
            }
            return false;
        }*/

    }
    
}