src/objects/Action_Summary__c.object
<CustomObject>
    <description>Provides a summary of Action Plan results</description>
    <label>Action Plan Summary</label>
    <nameField>
        <label>Action Plan Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ActionPlanSummaryNew.cls
public with sharing class ActionPlanSummaryNew {
	public Action_Summary__c summary { get; set; }
	public ApexPages.standardController stdController;

	public final String operatingGroup = [
		SELECT operating_group__c From User
		WHERE ID=:UserInfo.getUserId() LIMIT 1
	].operating_group__c;

	public ActionPlanSummaryNew(ApexPages.standardController stdController) {
		this.stdController = stdController;
	}

	public PageReference redirect() {
		Map<String, String> parameters = ApexPages.currentPage().getParameters();
		PageReference returnURL;
		if (operatingGroup == 'Redwood') {
			returnURL = new PageReference('/apex/ActionSummaryCreate');
		} else {
			returnURL = new PageReference('/apex/ActionSummaryCreateV2');
		}
		for (String key: parameters.keySet()) {
			returnUrl.getParameters().put(key, parameters.get(key));
		}
		return returnURL;
	}
}