src/objects/Action_Summary__c.object
<CustomObject>
    <description>Provides a summary of Action Plan results</description>
    <fields>
        <fullName>No_Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows the Approval process to be bypassed.</description>
        <label>No Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Summary</label>
    <nameField>
        <label>Action Plan Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Action_Summary_ApprovalForm.cls
public with sharing class Action_Summary_ApprovalForm {
    private ApexPages.StandardController controller;
    private Action_Summary__c ActionSummary {get;set;}
    
    public Action_Summary_ApprovalForm(ApexPages.StandardController controller) {
        this.controller = controller;
        ActionSummary = (Action_Summary__c)controller.getrecord();
    }


    public boolean No_Approval_Needed {
    get {
        return ActionSummary.No_Approval_Needed__c;
    }
    }
    /////////////////
    // Actions
    /////////////////
    
    public PageReference myFinal(){
        Action_Summary__c ActionSummary = (Action_Summary__c)controller.getrecord();
        ActionSummary.status__c = 'Final';
        update ActionSummary;
        if (ActionSummary.No_Approval_Needed__c == false) {
            // Create an approval request for the this evaluation
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setObjectId(controller.getid());
            req1.setNextApproverIds(new Id[]{ActionSummary.Approver__c});
            Approval.ProcessResult result = Approval.process(req1);
        }
        return new PageReference('/' + ActionSummary.Id);
    }
}