src/objects/Action_Behavior_Result__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Behavior Results</relationshipLabel>
        <relationshipName>Action_Behavior_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Day_time__c</fullName>
        <label>Day time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Occurred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Occurred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Occurrences__c</fullName>
        <label>Occurrences</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Action Behavior Result</label>
    <nameField>
        <label>Action Behavior Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Behavior Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Narrative_Result__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Narrative</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Action Narrative Result</label>
    <nameField>
        <label>Action Narrative Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Narrative Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Plan Actions</relationshipLabel>
        <relationshipName>Action_Plan_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5100</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Action</label>
    <nameField>
        <displayFormat>APA-{00000}</displayFormat>
        <label>Action Plan Actions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipLabel>Action Plan Goals</relationshipLabel>
        <relationshipName>Action_Plan_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <displayFormat>APG-{00000}</displayFormat>
        <label>Action Plan Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Goal__c</fullName>
        <label>Action Plan Goal</label>
        <referenceTo>Action_Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Plan Objectives</relationshipLabel>
        <relationshipName>Action_Plan_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Behavior - Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior - Duration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Narrative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Objective</label>
    <nameField>
        <displayFormat>APO-{00000}</displayFormat>
        <label>Action Plan Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Skill_Result__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Objective__c</fullName>
        <label>Action Plan Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>Action Skill Results</relationshipLabel>
        <relationshipName>Action_Skill_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attempts__c</fullName>
        <label>Attempts</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <label>Day</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Met_Objective__c</fullName>
        <label>Met Objective</label>
        <picklist>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Skill Result</label>
    <nameField>
        <label>Action Skill Tracking Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Skill Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_End_Time__c</fullName>
        <label>Shift End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Start_Time__c</fullName>
        <label>Shift Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SA_Start_DateTime__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateGoalObjPDF_Test.cls
@isTest
private class GenerateGoalObjPDF_Test {


	private static Action_Plan__c thePlan;
	private static Evaluation__c theEval;
	

    static testMethod void simpleTest() {

		// create a plan with 1 objective of each type
		thePlan = createData();
		system.debug(thePlan);

		// create a result for each objective		
		createPlanResults( thePlan.id, thePlan.service_Assignment__c  );
		
		// create an evaluation to report against
		theEval = createEval(thePlan.service_assignment__c);
		system.debug(theEval);

		// test the generation of the goal reports
		GenerateGoalObjPDF getGoalPDF = new GenerateGoalObjPDF();
		getGoalPDF.evalId = theEval.Id;
		
		// just to get coverage - should exit without doing anything
		getGoalPDF.init(theEval.Id);
		
		
		System.Assert( getGoalPDF.objectives.size() > 0);
		for ( GenerateGoalObjPDF.objectivewrapper obj : getGoalPDF.objectives ) {
			system.assertequals( String.IsBlank(obj.objDesc), false );
			system.assertequals( String.IsBlank(obj.effdates), false );
		}
		
		
		
		

    }


	private static Evaluation__c createEval( Id theSAId) {
		
		ID rtID = [ select id from recordtype where sobjecttype= 'Evaluation__c' and developername like 'CNA%' LIMIT 1].Id;
		//Service_Assignment__c saID = 
		system.debug( rtID );
		
		Service_Assignment__c theSA = [ select id, SA_start_datetime__c from service_assignment__c where id = :theSAId];
		system.debug( 'The SA is: ' + theSA );
		// create a CNA eval
		Evaluation__c newEval = new Evaluation__c( ServiceAssignment__c = theSA.Id, shift_start_time__c = theSA.SA_Start_DateTime__c, shift_end_time__c = theSA.SA_Start_DateTime__c.addhours(6), recordtypeid = rtID );
		insert newEval;
		return newEval;
	}
	
    private static Action_Plan__c createData(){
     	Action_plan_Goal__c apg;
    	Action_plan_Objective__c apoSkill;
    	Action_plan_Objective__c apoBehaviorCount;
    	Action_plan_Objective__c apoBehaviorDuration;
    	Action_plan_Objective__c apoNarrative;
    	Action_plan_Action__c apa1;
    	Action_plan_Action__c apa2;
    	Action_plan_Action__c apa3;
    	Action_plan_Action__c apa4;


        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();

        myData.theSA.SA_Start_DateTime__c = Datetime.newInstance( 2015, 1, 1, 0, 0, 0);
        system.debug('about to update SA');
        update(myDAta.theSA);
        system.debug( myData.theSA);

        system.debug( mydata.thesa.sa_start_datetime__c);
        system.debug( mydata.thesa.start_date__c);

        Action_plan__c ap = new Action_Plan__c(
            Service_Assignment__c = myData.theSA.id,
            Target_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1),
            Effective_Date__c = myData.theSA.SA_Start_DateTime__c.Date()
        );
        insert ap;

        apg = new Action_Plan_Goal__c(
            Description__c = 'a goal',
            Action_Plan__c = ap.id,
            sort_order__c = 'g'
        );
        insert apg;

        apoSkill = new Action_Plan_Objective__c(
            Action_Plan_Goal__c = apg.id,
            Status__c = 'In Progress',
            Description__c = 'an Objective with a really long description so it has to be truncated by the class for display on the front end, unless they want to see it wrapping',
            Type__c = 'Skill',
            Target_End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1),
            Effective_Date__c = myData.theSA.SA_Start_DateTime__c.Date(),
            sort_order__c = 'o'
        );
        insert apoSkill;

        apa1 = new Action_Plan_Action__c ();
        apa1.Action_Plan_Objective__c = apoSkill.id;
        apa1.Description__c = 'skill action';
        apa1.sort_order__c = 'a';
        apa1.Start_Date__c = myData.theSA.SA_Start_DateTime__c.Date();
        apa1.End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1);
        apa1.Status__c = 'New';
        insert apa1;

        apoBehaviorCount = new Action_Plan_Objective__c(
            Action_Plan_Goal__c = apg.id,
            Status__c = 'In Progress',
            Description__c = 'Behavior Count Objective',
            Type__c = 'Behavior - Count',
            Target_End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1),
            Effective_Date__c = myData.theSA.SA_Start_DateTime__c.Date(),
            sort_order__c = 'o1'
        );
        insert apoBehaviorCount;

        apa2 = new Action_Plan_Action__c ();
        apa2.Action_Plan_Objective__c = apoBehaviorCount.id;
        apa2.Description__c = 'Behavior Count action';
        apa2.sort_order__c = 'a2';
        apa2.Start_Date__c = myData.theSA.SA_Start_DateTime__c.Date();
        apa2.End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1);
        apa2.Status__c = 'New';
        insert apa2;

        apoBehaviorDuration = new Action_Plan_Objective__c(
            Action_Plan_Goal__c = apg.id,
            Status__c = 'In Progress',
            Description__c = 'Behavior Duration Objective',
            Type__c = 'Behavior - Duration',
            Target_End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1),
            Effective_Date__c = myData.theSA.SA_Start_DateTime__c.Date(),
            sort_order__c = 'o2'
        );
        insert apoBehaviorDuration;


        apa3 = new Action_Plan_Action__c ();
        apa3.Action_Plan_Objective__c = apoBehaviorDuration.id;
        apa3.Description__c = 'Behavior Duration action';
        apa3.sort_order__c = 'a3';
        apa3.Start_Date__c = myData.theSA.SA_Start_DateTime__c.Date();
        apa3.End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1);
        apa3.Status__c = 'New';
        insert apa3;

        apoNarrative = new Action_Plan_Objective__c(
            Action_Plan_Goal__c = apg.id,
            Status__c = 'In Progress',
            Description__c = 'Narrative Objective',
            Type__c = 'Narrative',
            Target_End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1),
            Effective_Date__c = myData.theSA.SA_Start_DateTime__c.Date(),
            sort_order__c = 'o2'
        );
        insert apoNarrative;


        apa4 = new Action_Plan_Action__c ();
        apa4.Action_Plan_Objective__c = apoNarrative.id;
        apa4.Description__c = 'Narrative action';
        apa4.sort_order__c = 'a4';
        apa4.Start_Date__c = myData.theSA.SA_Start_DateTime__c.Date();
        apa4.End_Date__c = myData.theSA.SA_Start_DateTime__c.Date().addDays(1);
        apa4.Status__c = 'New';
        insert apa4;

        ap.status__c = 'Active Final';
        update ap;

        return ap;

    }
    
    private static void createPlanResults ( ID planID, ID saID ){
    	
    	List<Action_Plan_Objective__c> lstAPO = [ select id, description__c, type__c, effective_date__c, target_end_date__c from action_plan_objective__c where Action_Plan_Goal__r.Action_Plan__r.service_assignment__c = :saID
									and Status__c in ('In Progress', 'Revised', 'New')
									and action_plan_goal__r.action_plan__r.status__c = 'Active Final' ];
    	
    	
    	// create a result for each type
    	for ( Action_Plan_Objective__c apo : lstAPO ) {
    		if ( apo.type__c == 'Narrative') {
    			Action_Narrative_Result__c narr = new Action_Narrative_Result__c( action_plan_objective__c  = apo.Id, description__c = 'Narrative result');
    			insert narr;
    			
    			narr = new Action_Narrative_Result__c( action_plan_objective__c  = apo.Id, description__c = 'Narrative result 2');
    			insert narr;
    		}
    		if (apo.type__c == 'Behavior - Count') {
    			Action_Behavior_Result__c beh = new Action_Behavior_Result__c( action_plan_objective__c = apo.Id,  Day_time__c = DateTime.newInstance( apo.effective_Date__c, Time.newInstance(3,0,0,0)), Occurrences__c = 2 );
    			insert beh;
    			
    			beh = new Action_Behavior_Result__c( action_plan_objective__c = apo.Id,  Day_time__c = DateTime.newInstance( apo.effective_Date__c, Time.newInstance(4,0,0,0)), Occurrences__c = 1 );
    			insert beh;
    		}
    		if (apo.type__c == 'Behavior - Duration') {
    			Action_Behavior_Result__c beh2 = new Action_Behavior_Result__c( action_plan_objective__c = apo.Id,  Day_time__c = DateTime.newInstance( apo.effective_Date__c, Time.newInstance(3,0,0,0)), Occurred__c = true );
    			insert beh2;
    			
    			// insert another for better coverage
    			beh2 = new Action_Behavior_Result__c( action_plan_objective__c = apo.Id,  Day_time__c = DateTime.newInstance( apo.effective_Date__c, Time.newInstance(4,0,0,0)), Occurred__c = true );
    			insert beh2;
    			
    		}
    		if (apo.type__c == 'Skill') {
    			Action_Skill_Result__c skill = new Action_Skill_Result__c( action_plan_objective__c = apo.Id,  day__c = apo.Effective_Date__c, attempts__c = 2, initials__c = 'TEST', met_objective__c = 'Y', status__c = 'I');
    			insert skill;
    			
    			skill = new Action_Skill_Result__c( action_plan_objective__c = apo.Id,  day__c = apo.Effective_Date__c+1, attempts__c = 4, initials__c = 'TEST', met_objective__c = 'N', status__c = 'V');
    			insert skill;
    			
    		}
    		
    	}
    }

}