src/objects/Action_Summary__c.object
<CustomObject>
    <description>Provides a summary of Action Plan results</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>Action_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Action Plan Summary</label>
    <nameField>
        <label>Action Plan Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActionSummaryCreateFormV2.cls
public with sharing class ActionSummaryCreateFormV2 {
	public Action_Summary__c summary { get; set; }
	public Service_Assignment__c serviceAssignment { get; set; }
	public ApexPages.standardController controller { get; set; }
	public Id pbsId { get; set; }

	public ActionSummaryCreateFormV2(ApexPages.standardController controller) {
		this.controller = controller;
		if (!Test.isRunningTest()) {
			controller.addFields(new String[] {
				'Service_Assignment__r.Person_Being_Served__r.Name'
			});
		}
		summary = (Action_Summary__c) controller.getRecord();
		serviceAssignment = [
			SELECT Person_Being_Served__r.Id, Person_Being_Served__r.Name,
			       Admission__c
			  FROM Service_Assignment__c
			 WHERE Id = :summary.service_assignment__c
		];
		pbsId = serviceAssignment.Person_Being_Served__r.Id;
	}

	public PageReference save() {
		summary.Name = String.format('{0} - {1} - {2}', new List<String>{
			serviceAssignment.Person_being_served__r.name,
			Datetime.newInstance(summary.Start_Date__c, Time.newInstance(0, 0, 0, 0)).format('MM/dd/yyyy'),
			Datetime.newInstance(summary.End_Date__c, Time.newInstance(0, 0, 0, 0)).format('MM/dd/yyyy')
		});
		summary.New_Version__c = true;
		try {
			upsert summary;
			return new ApexPages.standardController(summary).view();
		} catch (Exception ex) {
			ApexPages.addMessages(ex);
		}
		return null;
	}
}