src/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <displayFormat>APG-{00000}</displayFormat>
        <label>Action Plan Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Action_Plan_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Plan Objective</label>
    <nameField>
        <displayFormat>APO-{00000}</displayFormat>
        <label>Action Plan Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled by User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>No_Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this field if this progress note can be self-approved.</description>
        <inlineHelpText>Check this field if this progress note can be self-approved.</inlineHelpText>
        <label>No Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <inlineHelpText>Location that the service took place.</inlineHelpText>
        <label>Service Location</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Mental Health Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MR Intermediate Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office/TRAC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProgressNote_ActionPlanChildren_mjo__c.object
<CustomObject>
    <description>Action Plan</description>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Action_Plan_Goal__c</referenceTo>
        <relationshipLabel>ProgressNote_ActionPlanChildren_mjos</relationshipLabel>
        <relationshipName>goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Action_Plan_Objective__c</referenceTo>
        <relationshipLabel>ProgressNote_ActionPlanChildren_mjos</relationshipLabel>
        <relationshipName>objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <referenceTo>Progress_Note__c</referenceTo>
        <relationshipLabel>ProgressNote_ActionPlanChildren_mjos</relationshipLabel>
        <relationshipName>ProgressNote_ActionPlanChildren_mjos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ProgressNote_ActionPlanChildren_mjo</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProgressNote_ActionPlanChildren_mjos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/shiftnote_summary_rpt_Test.cls
@isTest
public class shiftnote_summary_rpt_Test{
static testMethod void testReport() {

    TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
    myData.theSA.Service_Location__c =  Referral_CreateTestData.createServiceLocation('11111').Id;
    upsert myData.theSA;
    
    DateTime startDateTime = DateTime.NewInstance(2014,11,1,12,0,0);
    DateTime endDateTime = DateTime.NewInstance(2014,12,31,12,0,0);
    RecordType rt = [select id from recordtype where name='Shift Note'];
    
    Progress_Note__c thisProgressNote = new Progress_Note__c(Service_Assignment__c = mydata.thesa.Id,
                                                                    Service_Code__c = mydata.theservicecode.Id, 
                                                                    Admission__c = mydata.theadm.ID,
                                                                    Start_Time__c = startDateTime,
                                                                    End_Time__c = endDateTime,
                                                                    Person_Being_Served__c = mydata.contactID,
                                                                    No_Approval_Needed__c = true,
                                                                    Approval_Status__c = 'Approved',
                                                                    recordtypeId = rt.Id,
                                                                    Status__c = 'Final');
    insert thisProgressNote;

 	PageReference ref = new PageReference('/apex/ShiftNote_summary_rpt');
    Test.setCurrentPage(ref); 
    shiftnote_summary_rpt cntl = new shiftnote_summary_rpt();

    cntl.startdate =  Date.newInstance(2014,11,1);
	cntl.enddate = Date.newInstance(2014,10,1);

    cntl.enddate = Date.newInstance(2014,12,1);

    cntl.select2PrmIds = new List<ID>();
    cntl.selectedprograms = new List<ID>();
  
    if ( cntl.getprogramsList().size() > 0) {
    	for (SelectOption p : cntl.getprogramslist() ){
	    		cntl.selectedprograms.Add(p.getValue());
			}
    }
    cntl.AddPrograms();
    
    
    System.debug( cntl.getPBSList());
    
    List<ID> pbs = new List<ID>();
    pbs.Add( cntl.getPBSList().get(0).getValue());
    
    cntl.selectedPBS = pbs;
    cntl.runReport();
	// verify an error was thrown
	List<ApexPages.Message> msgList = ApexPages.getMessages();
	
	for(ApexPages.Message msg :  ApexPages.getMessages()) {
    	System.assertEquals('Please choose valid start and end dates', msg.getSummary());
    	System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity());
	}

	cntl.enddate = Date.NewInstance( 2014, 12, 1);	
	cntl.runreport();
    
    cntl.getNote_plan_joins();
    List<Progress_Note__c> notes = cntl.getnotes();
    Map<string, List<ProgressNote_ActionPlanChildren_mjo__c>> note_goals = cntl.getNote_Goals();
    Map<string, List<ProgressNote_ActionPlanChildren_mjo__c>> note_objs = cntl.getNote_Objs();
    
    string combiKey = '';
    List<ProgressNote_ActionPlanChildren_mjo__c> currgoals, currobjs;
    
    for ( Progress_Note__c n : notes) {
    	
    	currgoals = note_goals.get((string)n.Id);
    	
    	for (ProgressNote_ActionPlanChildren_mjo__c g : currgoals ) {
    		system.debug( g.Goal__r.Description__c);
    		
    		combiKey = (string)n.id + (string)g.goal__c;
    		currobjs = note_objs.get(combiKey);
    		
    		for ( ProgressNote_ActionPlanChildren_mjo__c o : currobjs ) 
    			system.debug( o.objective__r.description__c);
    	}
    	
    }

	cntl.runPDF();
	
    cntl.select2PrmIds.Add( cntl.selectedprograms[0]);
    cntl.RemovePrograms();

   	
}
}