src/objects/Action_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Action_Plan_Worksheet__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>Action_Plan__c</referenceTo>
        <relationshipLabel>Action Plan Worksheets</relationshipLabel>
        <relationshipName>Action_Plan_Worksheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Action Plan Worksheet</label>
    <nameField>
        <label>Action Plan Worksheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Worksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DSP_Worksheets.cls
public without sharing class DSP_Worksheets {

	public ID ActionPlanId { get; set; }
	public map<String, List<WorksheetWrapper>> mapSheets { get;  set; }
	public ID pbsID { get; set; }
	public ID saID { get; set; }
	public ID admID { get; set; }
	
	public DSP_Worksheets ( ID APId) {
		this.ActionPlanID = APId;
		mapSheets = new Map<String, List<WorksheetWrapper>>();
		
		getAPData();
		
		populateWorksheets();
	}
	
	public DSP_Worksheets(TxnQueueResponseController controller) {
	}

	public class worksheetWrapper {
		
		public ID wID { get; set; }
		public String wName { get; set; }
		public Date startdate { get; set; }
		public String wType { get; set; }
		public String CreatedBy { get; set; }
		public String LastModifiedBy { get; set; }
		public DateTime Created { get; set; }
		public DateTime LastModified { get; set; }
		
		public worksheetWrapper( Action_Plan_Worksheet__c ap ) {
			wID = ap.id;
			wName = ap.name;
			startdate = ap.start_date__c;
			wType = ap.recordtype.name;
			CreatedBy = ap.createdby.name;
			Created = ap.createddate;
			LastmodifiedBy = ap.lastmodifiedby.name;
			LastModified = ap.lastmodifieddate;
		}
		
		
	}
	public void getAPData() {
		
		Action_Plan__c ap = [ select service_assignment__r.person_being_served__c, service_assignment__r.admission__c, service_assignment__c
    						from Action_Plan__c
    						where id = :ActionPlanId ];
    						
    	if ( ap != null ) {
    		pbsID = ap.service_assignment__r.person_being_served__c;
    		saID = ap.service_assignment__c;
    		admID = ap.service_assignment__r.admission__c;
    	}
    	
	}
	public void populateWorksheets() {
    	List<Action_Plan_Worksheet__c> wks = [ select id, name, start_date__c, recordtype.name, createdby.name, createddate, lastmodifiedby.name, lastmodifieddate
    											from Action_Plan_Worksheet__c
    											where action_plan__c = :ActionPlanId 
    											order by recordtype.name, start_date__c desc];

		List<WorksheetWrapper> beh;
		List<WorksheetWrapper> skill;
		for ( Action_Plan_Worksheet__c a : wks ) {                     
    		
    		WorksheetWrapper w = new WorksheetWrapper( a );
    		 
    		if ( a.recordtype.name.contains('Behavior')) {
    			
    			if ( (beh = mapSheets.get('Behavior')) == null ) {
    				
    				beh = new List<WorksheetWrapper>();
    			}
    			beh.add( w );
    			mapSheets.put( 'Behavior', beh); 
    			
    		} else if ( a.recordtype.name.contains('Skill')) {
    			if ( (skill = mapSheets.get('Skill')) == null ) {
    				
    				skill = new List<WorksheetWrapper>();
    			}
    			skill.add( w ); 
    			mapSheets.put('Skill', skill);
    		}
    		
		}
	}
}