src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAD Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restraint Reduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Adult</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Domain__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Assessment_Type2__c</fullName>
        <label>Assessment Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAD Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restraint Reduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Adult</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Sort order for page / domain</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Domain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Question_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Title__c</fullName>
        <description>Title of the Question</description>
        <label>Question Title</label>
        <type>TextArea</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>85</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Sub_Type__c</fullName>
        <description>We may have to boolean types, one for a checkbox and another for a radio button...</description>
        <label>Field Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropdown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropdown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiselect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_No_Decimal__c</fullName>
        <label>Number No Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Text_Over_250__c</fullName>
        <label>Text Over 250</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text_Under_250__c</fullName>
        <label>Text Under 250</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID_Object__c</fullName>
        <label>What ID Object</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestraintReductionReportTests.cls
@isTest
public with sharing class RestraintReductionReportTests {
	public static testmethod void simpleTests() {
		// Set up test data
		TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();

		PageReference pageRef = Page.RestraintReductionReport;
		Test.setCurrentPage(pageRef);

		Evaluation__c evaluation = new Evaluation__c(
				ServiceAssignment__c = testData.theSA.Id
				);
		insert evaluation;

		Eval_type__c evalType = new Eval_Type__c(
				Name = 'Restraint Event',
				Category__c = 'Care Meridian'
				);
		insert evalType;

		Eval__c[] evals = new Eval__c[] {
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Dropdown',
					htmlid__c = 'testdropdown',
					Field_Type__c = 'Dropdown'
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Boolean Dropdown',
					htmlid__c = 'testbooleandropdown',
					Field_Type__c = 'Boolean',
					Field_Sub_Type__c = 'Dropdown'
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Multiselect Long',
					htmlid__c = 'testmultiselectlong',
					Field_Type__c = 'Multiselect',
					Field_Sub_Type__c = 'Checkbox',
					Length__c = 5000
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Multiselect Short',
					htmlid__c = 'testmultiselectshort',
					Field_Type__c = 'Multiselect',
					Field_Sub_Type__c = 'Checkbox',
					Length__c = 100
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Start Date/Time',
					htmlid__c = 'startTime',
					Field_Type__c = 'Datetime'
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Short String',
					htmlid__c = 'testshortstring',
					Field_Type__c = 'String',
					Length__c = 100
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Long String field',
					htmlid__c = 'testlongstringfield',
					Field_Type__c = 'String',
					Length__c = 5000
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Date Field',
					htmlid__c = 'testdatefield',
					Field_Type__c = 'Date'
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Int Field',
					htmlid__c = 'int',
					Field_Type__c = 'Int'
					),
				new Eval__c(
					Eval_Type__c = evalType.Id,
					Category__c = 'Pre-Restraint Review',
					Sub_Category__c = 'Pre-Restraint Review',
					Field_Name__c = 'Test Double Field',
					htmlid__c = 'testdoublefield',
					Field_Type__c = 'Double'
					)
		};
		insert evals;

		insert new Eval_Value__c[] {
				new Eval_Value__c(
						Eval__c = evals[0].Id,
						Text_Under_250__c = 'Dropdown Option 1',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[1].Id,
						Text_Under_250__c = '1',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[2].Id,
						Text_Over_250__c = 'Test Long Text',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[3].Id,
						Text_Under_250__c = 'Test Short Text',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[4].Id,
						Date_Time__c = DateTime.now(),
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[5].Id,
						Text_Under_250__c = 'Test Short String Value',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[6].Id,
						Text_Over_250__c = 'Test Long String Value',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[7].Id,
						Date_Time__c = DateTime.now(),
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[8].Id,
						Number_No_Decimal__c = 50,
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						),
				new Eval_Value__c(
						Eval__c = evals[9].Id,
						Text_Under_250__c = '350.54',
						What_Id_Object__c = 'Evaluation__c',
						Eval_Section_Id__c = 'section',
						What_Id__c = evaluation.Id
						)
		};

		Assessment_Domain__c restraintDomain = new Assessment_Domain__c(
				Name = 'Restraint Questions',
				Assessment_Type2__c = 'Restraint Reduction',
				Sort_Order__c = 1
		);
		insert restraintDomain;


		Assessment_Question__c[] questions = new Assessment_Question__c[] {
			new Assessment_Question__c(
					Question_Title__c = 'Res Test',
					Question_Domain__c = restraintDomain.Id
			),
			new Assessment_Question__c(
					Question_Title__c = 'Res Test 2',
					Question_Domain__c = restraintDomain.Id
			)
		};
		insert questions;

		String sectionId = Userinfo.getUserId()+'-' + DateTime.now().getTime();
		Assessment__c asmt = new Assessment__c(
				Name = sectionId,
				Evaluation__c = evaluation.Id,
				Service_Assignment__c = testData.theSA.Id,
				Admission__c = testData.theSA.Admission__c,
				Type__c = 'Restraint Reduction'
		);
		insert asmt;

		ApexPages.currentPage().getParameters().put('startDate', Date.Today().addDays(-1).format());
		ApexPages.currentPage().getParameters().put('endDate', Date.Today().addDays(1).format());
		ApexPages.currentPage().getParameters().put('type', 'Detailed');
		ApexPages.currentPage().getParameters().put('saId', testData.theSA.Id);

		RestraintReductionReport controller = new RestraintReductionReport();
		System.assertEquals(1, controller.restraints.size());
		System.assertEquals(1, controller.restraints.values()[0].reductions.size());
		System.assertEquals(10, controller.restraints.values()[0].preRestraintKeyOrder.size());
	}
}