src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AccountPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Person Relationship
Delete Me</description>
        <label>AccountPerson</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <description>Interval for the assessment</description>
        <label>Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <description>Calculated Score of the assessment</description>
        <label>Overall Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <description>Indication of the numbered quarter this assessment describes.</description>
        <inlineHelpText>Indication of the numbered quarter this assessment describes.</inlineHelpText>
        <label>Quarterly Assessment Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <picklist>
            <picklistValues>
                <fullName>CI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vistas Hi Ac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vistas Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vistas Therapeutic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wraparound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <formula>Question_Domain__r.Assessment_Type__r.Id</formula>
        <label>Assessment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>Number of the Question</description>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>COMPLIANCE SURVEY Stores all the questions for a compliance survey</description>
    <label>Compliance Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Compliance Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Report_CANS_PBSOverTimeGraph.cls
public with sharing class Report_CANS_PBSOverTimeGraph {
    
    list<integer> QuestionsInScope {
        get{ 
            if(selectedCluster == 'WellBeing'){return Assessment_CANS_Cluster_Defs.WellBeing;}
            if(selectedCluster == 'Behavior_and_Risk'){return Assessment_CANS_Cluster_Defs.Behavior_and_Risk;}
            if(selectedCluster == 'Education') {return Assessment_CANS_Cluster_Defs.Education;}
            return null;
        }
    }

	public transient Map<ID, Assessment_Question__c> QuestionsList{ get; set;}	// holds list of questions in scope - ID, name, number
    public List<SelectOption> optClusters{ get; set;}
    public string selectedCluster{get; set;}
    public List<SelectOption> optPBS{ get; set;}
    public String selectedPBS { get; set;}
    public boolean showData { get; set;}
    public transient List<CANSData> pbsCANS {get; set;}
    
    public Report_CANS_PBSOverTimeGraph() {
        
	   	optClusters =  new List<SelectOption>();
	    optClusters.Add( new SelectOption('','--None--'));
	    optClusters.Add( new SelectOption('Behavior_and_Risk','Behavior and Risk'));
	    optClusters.Add( new SelectOption('Education','Education'));
	    optClusters.Add( new SelectOption('WellBeing','Well Being'));
	
	        
	    QuestionsList = new Map<ID, Assessment_Question__c>();
	
	 	optPBS = new List<SelectOption>();
	 	optPBS.Add( new SelectOption('','--None--'));
	 	// get the list of people i can see who have final, non-diregarded cans
	 	List<AggregateResult> arCANSList = [select count(id), accountperson__c, accountperson__r.name, accountperson__r.lastname from assessment__c where assessment_type__r.name = 'CANS' and  disregard__c = false and status__c = 'Locked' group by accountperson__c, accountperson__r.name, accountperson__r.lastname  order by accountperson__r.lastname];
	 			
	 	for ( AggregateResult ar : arCANSList ) 
	 		optPBS.Add( new SelectOption((String)ar.get('account_person__c'), (String)ar.get('name')));
			
		showData = false;
	            
    }

    public PageReference runReport(){
        showData = false;
        boolean inputErr = false;
        ApexPages.getMessages().clear();
       
       if ( String.isEmpty(selectedPBS)  ){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,
                    'Please select the Person Being Served for this report');
                    ApexPages.addMessage(myMsg);
                    inputErr = true;
       }
       
       if ( !inputErr ) 
            buildRpt();
       
       
       return null;
        
    }

    public void buildRpt(){

		// get the CANS scores for this person being served
		pbsCANS = new List<CANSdata>();
            
       
		// if no cluster selected, get overall scores
		if (String.isEmpty( selectedCluster)) {
			
			for (Assessment__c asmt : [select id, name, assessment_date__c, interval__c, quarter__c, overall_score__c 
										from assessment__c 
										where accountperson__c = :selectedPBS 
										and disregard__c = false
										and status__c = 'Locked'
										order by assessment_date__c
										]) {
											
				CANSData newasmt = new CANSData( asmt.assessment_date__c, asmt.name, asmt.id, asmt.overall_score__c, asmt.quarter__c, asmt.interval__c);								
				pbsCANS.add( newasmt );							
											
			}
		}

         /*
        // count of qualifying 'actionable' = number of PBS with intake or discharge scoring 2 or 3 for any question in the cluster
        list<AggregateResult> QualifyingCountByState = [ 
                                            select count(accountperson__c), admission__r.state__c 
                                            from assessment__c 
                                            where id in (select assessment__c 
                                                         from assessment_response__c 
                                                         where score__c in (2, 6)
                                                         and question__r.question_number__c in :QuestionsInScope
                                                         and assessment__r.Interval__c = :selectedInterval
                                                         and assessment__r.assessment_type__r.name = 'CANS'
                                                         and assessment__r.disregard__c = false
                                                         and assessment__r.status__c = 'Locked'
                                                         and assessment__r.admission__r.state__c in :CANSStates  )
                                            and assessment_date__c >= :startDate 
                                            and assessment_date__c <= :endDate
                                            and service_line__c in :selectedSL
                                            group by admission__r.state__c
                                            ];

		integer totalPBS = 0, totalQual = 0;
        for ( AggregateResult ar : QualifyingCountByState ) {
            
            pbscount = (Integer)ar.get('expr0');
            pbstate = (String)ar.get('state__c');
            
            StateRowData stdata = srd.get(pbstate);
            stdata.PBSCount = pbscount;
            stdata.QualifyingCount = pbscount;
            totalPBS += pbscount;
            totalQual += pbscount;
            
        }
		
		
		        
        // count of qualifying 'actionable' = number of PBS with intake or discharge scoring 2 or 3 for any question in the cluster
        list<AggregateResult> QualifyingCountByQuestion = [ select count(score__c), 
        														   question__c, 
        														   assessment__r.admission__r.state__c 
        													from assessment_response__c 
        													where 
        													score__c in (2, 6) 
	                                                         and question__r.question_number__c in :QuestionsInScope
    	                                                     and assessment__r.Interval__c = :selectedInterval
        	                                                 and assessment__r.assessment_type__r.name = 'CANS'
            	                                             and assessment__r.disregard__c = false
                	                                         and assessment__r.status__c = 'Locked'
                                                         	 and assessment__r.admission__r.state__c in :CANSStates 
                                            and assessment__r.assessment_date__c >= :startDate 
                                            and assessment__r.assessment_date__c <= :endDate
                                            and assessment__r.service_line__c in :selectedSL
                                            group by question__c, assessment__r.admission__r.state__c
                                            ];
                                        
       Assessment_Question__c currQ;
       integer currcount;
       for ( AggregateResult ar : QualifyingCountByQuestion ) {
            
            pbscount = (Integer)ar.get('expr0');
            pbstate = (String)ar.get('state__c');
            
            StateRowData stdata = srd.get(pbstate);
 			currQ = QuestionsList.get((ID)ar.get('question__c'));
 			system.debug('Current Question: ' + currQ + ', state=' + pbstate + ', pbscount=' + pbscount);
 			if ( currQ != null ) { 
            	stdata.byQuestionCount.put((Integer)currQ.Question_number__c, pbscount);
				currcount = totdata.byQuestionCount.get((integer)currQ.Question_number__c);
            	totdata.byQuestionCount.put((integer)currQ.Question_number__c, currcount + pbscount );
 			}
        }   
        */
        
		showData = true;
              
    }
    
    

    public class CANSData{
        public Date Assessment_Date {get; set;}
        public Decimal Score{get;set;}
        public string Assessment_Name { get; set;}
        public ID AssessmentID { get; set;}
        public Decimal Quarter { get; set;}
        public String Interval { get; set;}

        public CANSData (Date dt, String nm, ID id, Decimal sc, Decimal q, String intv ){
            Assessment_Date = dt;
            Assessment_Name = nm;
            AssessmentID = id; 
            Score = sc;
            Quarter = q;
            Interval = intv;
        }
        
    }


}