src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_End_Time__c</fullName>
        <label>Shift End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <recordTypes>
        <fullName>CMShiftAssessment</fullName>
        <active>true</active>
        <description>This record type is used for Shift Assessments for Care Meridian.</description>
        <label>CMShiftAssessment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CMShiftAssessmentNotificationRunBatch.cls
public class CMShiftAssessmentNotificationRunBatch implements schedulable {
	public void execute(SchedulableContext sc){
		String dateTimeFormat = DateTime.now().format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
	
        String query = 'SELECT Id,Name,Owner.Id,ServiceAssignment__r.Admission__r.Person_Being_Served__c,Shift_End_time__c, Status__c FROM Evaluation__c WHERE RecordType.Name = \'CMShiftAssessment\' AND Status__c = \'Draft\' AND Shift_end_time__c <='+dateTimeFormat;
        ID batchprocessid = Database.executeBatch(new CMShiftAssessmentNotifications(query), 50);
    }

}