src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guardian1_Name__c</fullName>
        <label>Guardian1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guardian_Phone_Number__c</fullName>
        <label>Guardian 1 Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>NOTES Plan object is Master-detail to Persons Being Served. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guardian1_Name__c</fullName>
        <formula>Person_Being_Served__r.Guardian1_Name__c</formula>
        <inlineHelpText>Guardian or parent of person being served.</inlineHelpText>
        <label>Guardian1 Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guardian_Phone_Number__c</fullName>
        <formula>Person_Being_Served__r.Guardian_Phone_Number__c</formula>
        <inlineHelpText>Phone Number of a Guardian or Parent.</inlineHelpText>
        <label>Guardian Phone Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Expiration_Date__c</fullName>
        <label>Plan Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Admission__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Plan_ServiceAssignment_mJO__c.object
<CustomObject>
    <description>NOTES Junction Object between Service Assignments and Short-term goals, Objectives and Interventions.</description>
    <fields>
        <fullName>Guardian1_Name__c</fullName>
        <formula>Short_term_Goal__r.Plan__r.Guardian1_Name__c</formula>
        <label>Guardian1 Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guardian_Phone_Number__c</fullName>
        <formula>Short_term_Goal__r.Plan__r.Guardian_Phone_Number__c</formula>
        <label>Guardian Phone Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <formula>Short_term_Goal__r.Plan__r.Person_Being_Served__c</formula>
        <label>Person Being Served</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Expiration_Date__c</fullName>
        <formula>Short_term_Goal__r.Plan__r.Plan_Expiration_Date__c</formula>
        <label>Plan Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <formula>Short_term_Goal__r.Plan__c</formula>
        <label>Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>Service_Assignment_Relationship_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Short_term_Goal__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Short-term Goal</label>
        <referenceTo>Short_Term_Goal__c</referenceTo>
        <relationshipName>Service_Assignment_Relationship_JOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan ServiceAssignment mJO</label>
    <nameField>
        <displayFormat>SARJO-{00000000}</displayFormat>
        <label>Service Assignment Relationship JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan_ServiceAssignment_mJO</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Short_Term_Goal__c.object
<CustomObject>
    <description>NOTES Short-term Goals are the goals defined to achieve the Long-term Goals on a Plan. Short-term Goals are Master-detail to Plans. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <formula>Plan__r.Admission__c</formula>
        <label>Admission</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>The plan and long-term goals that this short-term goal supports.</description>
        <inlineHelpText>The plan and long-term goals that this short-term goal supports.</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Short-term Goals</relationshipLabel>
        <relationshipName>Short_Term_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Short-term Goal</label>
    <nameField>
        <label>Short-term Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Short-term Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Notes_Person_Tab.cls
public with sharing class Notes_Person_Tab {
    public ID currentLogedUserId = UserInfo.getUserId();
  //  public Set<ID> acctsCurrentUserIsMemberOf = new Set<ID>();
  //  public Set<ID> getacctsCurrentUserIsMemberOf(){return acctsCurrentUserIsMemberOf ;}

    public Notes_Person_Tab(){
        LoadData();
    }

    public void LoadData(){
       /* should be added at a time when account teams become used!
        for(AccountTeamMember local :[Select accountId from accountTeamMember where userId=:currentLogedUserId]){
            acctsCurrentUserIsMemberOf.add(local.accountID);
        }  
        
        */      
    }
    
    public List<Plan_ServiceAssignment_MJO__c> getMyPlans(){
        Map<string, Plan_ServiceAssignment_MJO__c> distinctPlans = new Map<string, Plan_ServiceAssignment_MJO__c>();
        
        //where clause should be added at a time when account teams become used!
        /*
        Where Service_Assignment__r.Person_Being_Served__r.OwnerId =:currentLogedUserId 
                        OR 
                    Service_Assignment__r.Person_Being_Served__r.AccountId IN :acctsCurrentUserIsMemberOf
        
        
        */
        for(Plan_ServiceAssignment_MJO__c local :
            [Select id, Service_Assignment__c, Service_Assignment__r.Person_Being_Served__c,  Short_term_Goal__r.Plan__r.OwnerID,
             Service_Assignment__r.Admission__r.State__c, Service_Assignment__r.Admission__c,
             Short_term_Goal__r.Plan__c, Guardian1_Name__c , Guardian_Phone_Number__c, Short_term_Goal__r.Plan__r.Plan_Expiration_Date__c 
                From Plan_ServiceAssignment_MJO__c 
                    Where Short_Term_Goal__r.Plan__r.Status__c = 'Active' AND Service_Assignment__r.Status__c = 'Active'])
        {                
            string tmp = string.Valueof(local.Service_Assignment__c) + string.Valueof(local.Short_term_Goal__r.Plan__c) ;
            distinctPlans.put(tmp, local);
        }
        return distinctPlans.Values();
    
    }
    
    public List<Service_Assignment__c> getMyAssessmentOnlyServiceAssignments(){
        /*
        
        (Person_Being_Served__r.OwnerID =:currentLogedUserID
                            OR
                        Person_Being_Served__r.AccountId IN :acctsCurrentUserIsMemberOf)
                            AND
        
        */    
        List<Service_Assignment__c> localServiceAssignments = new List<Service_Assignment__c>();
            
            for(Service_Assignment__c local :
                [Select id, Admission__c, Person_Being_Served__r.OwnerID,
                 Person_Being_Served__c, Person_Being_Served__r.Guardian_Phone_Number__c, Person_Being_Served__r.Guardian1_Name__c,
                  Admission__r.State__c, Name 
                    From Service_Assignment__c
                        Where RecordType.Name = 'Assessment Only' AND Status__c = 'Active'])
            {
               localServiceAssignments.add(local); 
            }
        
        
        return localServiceAssignments;
    
    }
}