src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled by User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>No_Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this field if this progress note can be self-approved.</description>
        <inlineHelpText>Check this field if this progress note can be self-approved.</inlineHelpText>
        <label>No Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <formula>Service_Code__r.Program_Rollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Notes_ProgressNote_Clone_test.cls
public with sharing class Notes_ProgressNote_Clone_test {
    static testMethod void myUnitTest() {
        
        Contact testContact = new Contact(
        LastName = 'TestLastName'
      );
      insert testContact;
      
      Admission__c testAdm = new Admission__c(
            Name = 'TEST ADM',
            Person_Being_Served__c = testContact.Id,
            Effective_Date__c = date.today()
      );
      insert testAdm;
        
        Service_Assignment__c testServAssignment = new Service_Assignment__c(
          Admission__c = testAdm.Id,
          Person_Being_Served__c = testContact.Id
        );
        insert testServAssignment;
        
        Service_Code__c testServCode = new Service_Code__c(
          Service_Code__c = 'TEST SVC CODE',
          FacilityID__c = 'TEST FAC ID',
          Program_Code__c = 'TEST PROGRAM CODE' 
          
        );
        testServCode.Start_Date__c = date.newInstance(2012, 1, 1);
        insert testServCode;
        
        Progress_Note__c testPN = new Progress_Note__c(
          Service_Assignment__c = testServAssignment.Id, 
          Service_Code__c = testServCode.Id, 
          Admission__c = testAdm.ID,
          Start_Time__c = datetime.newInstance(2012, 1, 1, 13, 0, 0),
          End_Time__c = datetime.newInstance(2012, 1, 1, 15, 0, 0),
          Person_Being_Served__c = testContact.Id,
          No_Approval_Needed__c = true,
          Approval_Status__c = 'Approved'
        );
        insert testPN;

        
       // Progress_Note__c pn = new Progress_Note__c();
        PageReference pageRef = Page.Notes_ProgressNote_Clone;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testPN);
        Notes_ProgressNote_Clone mee = new Notes_ProgressNote_Clone(sc);
        
        mee.getCreatableFieldsSOQL(testPN.id);
        mee.thePN = testPN;
        mee.newPN = testPN;
        mee.holdPN = testPN;
        
        mee.MyClone();
        
        
    }
}