src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status_Date__c</fullName>
        <label>Approval Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled by User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Healthcare_Medical_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Healthcare/Medical Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Required_Signatures__c</fullName>
        <label>Number of Required Signatures</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signature_on_File__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <label>Signature on File</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <recordTypes>
        <fullName>Shift_Note</fullName>
        <active>true</active>
        <label>Shift Note</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Shift_Note_Narrative.cls
public with sharing class Shift_Note_Narrative implements AuthenticatedAction {
    Progress_Note__c note = new Progress_Note__c();
    string userid  =UserInfo.getUserId() ;
    
    public string noteStart_DateTime {get;set;}
    public string noteEnd_DateTime {get;set;}
    
    public string retURL { get; private set;}
    
    public boolean canFinalize {get; set;}
    
    public boolean editMode {get ; set;}
    
    public Shift_Note_Narrative() {
    	// to support authentication handler
    }
    
    public Shift_Note_Narrative(ApexPages.StandardController controller) {
        
        if (!Test.isRunningTest()) {
            controller.AddFields (new List<String> {'Service_Assignment__c', 'Admission__c'});
        }
        note = (Progress_Note__c )controller.getRecord();
        
        note.Number_of_Required_Signatures__c = 0;
        note.Healthcare_Medical_Note__c = true;
        
        editMode = false;
        canFinalize = false;
        if(apexpages.currentpage().getparameters().get('edit')=='1' && !note.locked__c){
            editMode= true;
        }
        if(note.id ==null){
            note.service_assignment__c = apexpages.currentpage().getparameters().get('saID');
            note.admission__c = apexpages.currentpage().getparameters().get('admID');
            editMode = true;
            note.RecordTypeid = [select id from recordtype where DeveloperName='Shift_Note' and SobjectType='Progress_Note__c' limit 1].id;
            note.Person_Being_served__c = [select person_being_served__c from admission__c where id = :apexpages.currentpage().getparameters().get('admID')].person_being_served__c;    
        } 
        
        setPastNotes();
        retURL = apexpages.currentpage().getparameters().get('retURL');
		if (String.isBlank( retURL ))
			retURL = '/home';
        }
    
    
        
    public pagereference mySave(){

		if (string.isblank(noteStart_DateTime))
			ApexPages.addMessage( new ApexPages.Message(ApexPages.severity.ERROR, 'Start Time is required'));
		
		if (string.isBlank(noteEnd_DateTime))
			ApexPages.addMessage( new ApexPages.Message(ApexPages.severity.ERROR, 'End Time is required'));
		
		if (string.isBlank(note.narrative__c))
			ApexPages.addMessage( new ApexPages.Message(ApexPages.severity.ERROR, 'Narrative text is required'));
			
        try{
        	
        	note.Start_Time__c = DateTime.parse(noteStart_DateTime);
            note.End_Time__c = DateTime.parse(noteEnd_DateTime);
            system.debug('start times: ' + note.start_time__c + ' (' + notestart_datetime + ')');
            system.debug('end times: ' + note.end_time__c + ' (' + noteend_datetime + ')');
            upsert note;
            return null;
            }
            
        catch(DMLException e){
            ApexPages.addMessages(e);
            return null;
        }
        catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }
    }
    
    public pagereference myEdit(){
        editMode = true;
        
        return null;
    }

    
    public pagereference myCancel(){
        
        // get the return URL from the page
        PageReference pr = new PageReference( retURL);
        return pr;
        
    }    
    
    
    public List<Progress_note__c> pastnotes { get; private set; }
    private void setpastnotes () {
        
       pastnotes = [ select id, start_time__c, end_time__c, narrative__c, lastmodifieddate, lastmodifiedby.name from progress_note__c where service_assignment__c = :note.service_assignment__c and recordtype.developername='Shift_Note' and id != :note.id order by lastmodifieddate desc]; 
    }        
    
    public PageReference handle(Id recordId, Id userId) {
		Progress_Note__c thisnote = [
			SELECT Id, Status__c, locked__c, approval_status__c, approval_status_date__c, approval_user__c 
			  FROM Progress_Note__c WHERE Id=:recordId
		];
		
		if ( thisnote != null) {
			thisnote.status__c = 'Final';
			thisnote.approval_status__c = 'Approved';
			thisnote.approval_status_date__c = Date.Today();
			thisnote.Approval_User__c = UserInfo.getUserId();
			thisnote.locked__c = true;
			thisnote.signature_on_file__c = 'Y';
		}
			
		try {
			update thisnote;
		} catch (exception e) {
			system.debug( e );		
		}
		return null;
	}
    
    
}