src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <description>Interval for the assessment</description>
        <label>Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Past_Due_Date__c</fullName>
        <formula>TODAY() -  Assessment_Date__c &gt; 90</formula>
        <label>Past Due Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Assessment that this one is cloned from</description>
        <label>Previous</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Report_CANS_OverdueAssessments.cls
public with sharing class Report_CANS_OverdueAssessments {
	public List<Assessment__c> assessments { get; set; }

	public Report_CANS_OverdueAssessments() {
		List<Admission__c> admissions = [
			SELECT Id, (
				SELECT Id, Interval__c FROM Assessments__r
				WHERE Assessment_Type__r.Name = 'CANS'
				  AND Past_Due_Date__c = true
				ORDER BY Assessment_Date__c DESC LIMIT 1
			)
			FROM Admission__c
		];
		List<Id> assessmentIds = new List<Id>();
		for (Admission__c admission: admissions) {
			if (admission.Assessments__r != null && admission.Assessments__r.size() > 0 && admission.Assessments__r[0].Interval__c != 'Discharge') {
				assessmentIds.add(admission.Assessments__r[0].Id);
			}
		}
		assessments = [
			SELECT Id, Name, Admission__r.Person_Being_Served__r.Name,
			       Admission__r.Person_Being_Served__r.Owner.Name,
			       Admission__r.Person_Being_Served__r.Owner.Id,
			       Assessment_Date__c, Owner.Name, Owner.Id
			  FROM Assessment__c
			 WHERE Id IN :assessmentIds
		];
	}
}