src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IFCS_PBS_Count_Rpt_Ex.cls
public with sharing class IFCS_PBS_Count_Rpt_Ex {


    public Date fStartDate{get{return fStartDate;} set;}
    public Date fEndDate{get{return fEndDate;} set;}
    
    public List<Service_Assignment__c> Results = new List<Service_Assignment__c>();
    public List<Service_Assignment__c> getResults(){return Results;}
    
    public IFCS_PBS_Count_Rpt_Ex () {
       // fStartDate = system.today();
       allCount = 0;
    } 
    
    set<id> uniquePBS = new Set<id>();
    public integer allCount{get; set;}
    public Map<string, integer > ParsedData = new Map<string, integer >();
    
    public Map<string, integer > getParsedData(){return ParsedData;}
    
    public PageReference runReport(){
    if(fEndDate < fStartDate){
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Start Date must be before the End Date');//Same old drama 
        ApexPages.addMessage(myMsg);            
        return null;
    }
        ParsedData.clear();
        results.clear();
        uniquePBS.clear();
        
        Results = [Select  id, 
                        Admission__r.State__c,
                        Admission__r.Person_Being_Served__r.id,
                        Start_Date__c,
                        End_Date__c
                        From Service_Assignment__c
                        Where
                        
                         (
                            ((Start_Date__c >= :fStartDate OR End_Date__c >= :fStartDate) 
                              AND  
                            (Start_Date__c <= :fEndDate OR End_Date__c <= :fEndDate) )                         
                       OR
                           (Start_Date__c  <= :fEndDate AND End_Date__c = null ) 
                         )
                            ];
    
        /*
         
                                  
        
        */
        for(Service_Assignment__c SA: Results){
          //  List<Service_Assignment__c> tmpSA = new List<Service_Assignment__c>();
            ParsedData.put(SA.Admission__r.State__c, 0);
        }
        allCount = 0;
        for(Service_Assignment__c SA: Results){
            integer i = ParsedData.get(SA.Admission__r.State__c);            
            i +=1;
            if(!uniquePBS.contains(sa.Admission__r.Person_Being_Served__r.id)){
                ParsedData.put(SA.Admission__r.State__c, i);
                Allcount +=1;
            }
            uniquePBS.add(sa.Admission__r.Person_Being_Served__r.id);
        }
        fStartDate = null;
        fEndDate= null;
        return null;
    }       

}