src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ACK_Errors__c</fullName>
        <label>ACK_Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACK_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACK_isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agreement_Errors__c</fullName>
        <label>Agreement Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Agreement_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreement isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCMS_Errors__c</fullName>
        <label>CCMS Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCMS_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CCMS isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CDP_Errors__c</fullName>
        <label>Career Development Plan Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CDP_IsValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Career Development Plan IsValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CDP_NE_Check_Apply_Decision_Not_Explore__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CDP_WA_Check_Apply_int_Employment__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CDP_WA_Check_Apply_nonworking__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Outcomes_IsValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Desired Outcomes IsValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Desired_outcomes_Errors__c</fullName>
        <label>Desired_outcomes_Errors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Differences_Errors__c</fullName>
        <label>Differences Errors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Differences_Isvalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Differences_Isvalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPR_Additional_Services__c</fullName>
        <description>Additional K Plan services included in residential services</description>
        <label>K Plan Additional Services</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_Errors__c</fullName>
        <label>KPR Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_Included_Services__c</fullName>
        <defaultValue>&quot;Attendant care – ADL / IADL;Skill training;Community Transportation&quot;</defaultValue>
        <description>The K Plan services already included in residential services</description>
        <label>K plan Services Included</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KPR isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kplan_Errors__c</fullName>
        <label>Kplan Errors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kplan_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kplan isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leg_Errors__c</fullName>
        <label>Legal Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Leg_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NaturalSupports_Errors__c</fullName>
        <label>NaturalSupports_Errors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NaturalSupports_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NaturalSupports isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PD_Errors__c</fullName>
        <label>Plan Dates Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PD_Isvalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Plan Dates Isvalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Errors__c</fullName>
        <label>One Page Profile Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Profile_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>One Page Profile Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Risk_Errors__c</fullName>
        <label>Risk Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Risk_Isvalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Risk Isvalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPPC_Errors__c</fullName>
        <label>SPPC Errors</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SPPC_IsValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SPPC IsValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Case Management Plan</relationshipLabel>
        <relationshipName>Case_Management_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Waiver_Errors__c</fullName>
        <label>Waiver_Errors</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Waiver_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver isValid</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PRIME_Number__c</fullName>
        <label>PRIME Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ORriskTool.cls
public with sharing class ORriskTool {
	
	private Apexpages.StandardController 	controller;
	public Case_Management_Plan__c cmPlan 	{get;set;}
	public ID cmID 							{ get; set; }
	public Case_Management_Plan__c thisCM 	{ get; set; }
	public string evalType 					{ get; set; }
	public string subCat 					{ get; set; }
	public string cat 						{ get; set; }
	public string evalSecId 				{ get; set; }
	public string evalSecType 				{ get; set; }
	public Boolean canEdit 					{ get; set; }
	
	public String key 						{ get; set; }
	
	public Boolean isBatchInsert 			{ get; set; }
	public Boolean isBatchUpsert 			{ get; set; }
	
	
    
    public ORriskTool(Apexpages.StandardController controller){
    	this.controller = controller;
    	if(!test.isRunningTest()){
			controller.addFields(new List<string>{
				'Service_Assignment__c',
				'Service_Assignment__r.Admission__c',
				'Service_Assignment__r.Admission__r.Person_being_Served__c',
				'Service_Assignment__r.Admission__r.Person_being_Served__r.FirstName',
				'Service_Assignment__r.Admission__r.Person_being_Served__r.LastName',
				'Service_Assignment__r.Admission__r.Person_being_Served__r.Prime_Number__c',
				'Status__c',
				'CDP_WA_Check_Apply_int_Employment__c',
				'CDP_WA_Check_Apply_nonworking__c',
				'CDP_NE_Check_Apply_Decision_Not_Explore__c',
				'KPR_Included_Services__c',
				'KPR_Additional_Services__c',
				'CreatedBy.Name',
				'LastModifiedDate',
				'ACK_isValid__c',
				'Agreement_isValid__c',
				'CDP_IsValid__c',
				'CCMS_isValid__c',
				'Desired_Outcomes_IsValid__c',
				'Differences_Isvalid__c',
				'Kplan_isValid__c',
				'KPR_isValid__c',
				'Leg_isValid__c',
				'NaturalSupports_isValid__c',
				'Profile_isValid__c',
				'PD_Isvalid__c',
				'Risk_Isvalid__c',
				'SPPC_IsValid__c',
				'Waiver_isValid__c',
				'ACK_Errors__c',
				'Agreement_Errors__c',
				'CDP_Errors__c',
				'CCMS_Errors__c',
				'Desired_outcomes_Errors__c',
				'Differences_Errors__c',
				'Kplan_Errors__c',
				'KPR_Errors__c',
				'Leg_Errors__c',
				'NaturalSupports_Errors__c',
				'Profile_Errors__c',
				'PD_Errors__c',
				'Risk_Errors__c',
				'SPPC_Errors__c',
				'Waiver_Errors__c',
				'PCI_HD_Errors__c',
			 	'PCI_CN_Errors__c',
			 	'PCI_LL_Errors__c',
			 	'PCI_PE_Errors__c',
			 	'PCI_ES_Errors__c',
			 	'PCI_EP_Errors__c',
			 	'PCI_SL_Errors__c',
			 	'PCI_CS_Errors__c',
			 	'PCI_RM_Errors__c',
			 	'PCI_RL_Errors__c',
			 	'PCI_HW_Errors__c',
			 	'PCI_FL_Errors__c',
			 	'PCI_PA_Errors__c',
			 	'PCI_CC_Errors__c',
			 	'PCI_SR_Errors__c',
			 	'PCI_MH_Errors__c',
			 	'PCI_BH_Errors__c',
			 	'PCI_TP_Errors__c',
			 	'PCI_ADT_Errors__c',
			 	'PCI_EM_Errors__c',
			 	'PCI_OP_Errors__c'
			});
		}
    	this.cmPlan = (Case_Management_Plan__c) controller.getRecord();
    	
    	cmID =  this.cmPlan.Id;
		evalType = ApexPages.currentPage().getParameters().get('evaltype');
		cat = ApexPages.currentPage().getParameters().get('Category');
		subCat = ApexPages.currentPage().getParameters().get('SubCategory');
		evalSecType = ApexPages.currentPage().getParameters().get('Category');
		key = evalType+'~'+cat+'~'+subCat+'~'+evalSecType;
		
    }
    
    private void batchSetup() {
		canEdit = true;
		subCat = '';
		evalSecType = '';
		evalSecId = UserInfo.getUserId() + '-' + Datetime.now().getTime();
	}
	public void batchInsert() {
		isBatchInsert = true;
		isBatchUpsert = false;
		batchSetup();
		key = evalType+'~'+cat+'~'+subCat+'~'+evalSecType;
	
	}
	public void batchUpsert() {
		isBatchUpsert = true;
		isBatchInsert = false;
		batchSetup();
		key = evalType+'~'+cat+'~'+subCat+'~'+evalSecType;
		
	}
	
	
	
}