src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>CDP_NE_Check_Apply_Decision_Not_Explore__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CDP_WA_Check_Apply_int_Employment__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CDP_WA_Check_Apply_nonworking__c</fullName>
        <label>Check all that Apply</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_Additional_Services__c</fullName>
        <description>Additional K Plan services included in residential services</description>
        <label>K Plan Additional Services</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_Included_Services__c</fullName>
        <defaultValue>&quot;Attendant care – ADL / IADL;Skill training;Community Transportation&quot;</defaultValue>
        <description>The K Plan services already included in residential services</description>
        <label>K plan Services Included</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KPR_Residential_Secton_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residential Secton Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPR_isValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KPR isValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>K_Plan_Section_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>K Plan Section Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leg_Parents__c</fullName>
        <description>Parent(s) of minor child who retain parental rights</description>
        <label>Parent(s) of minor child</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PD_End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PD_Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Case Management Plan</relationshipLabel>
        <relationshipName>Case_Management_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Waiver_Section_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver Section Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Management Plan</label>
        <referenceTo>Case_Management_Plan__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Generic field to be used for Type across multiple eval response recordtypes</description>
        <label>Type</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Party__c.object
<CustomObject>
    <description>REFERRALS - Parties having a relationship with the Person Being Referred</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referring Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Payee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ORcombinedISPControllerTest.cls
@isTest
public class ORcombinedISPControllerTest {
	
	@testSetup
	static void setupData(){
		User caseManager = TMN_Generic_Core_TestData.createUser('ESD General', 'rwCMOR', 'rwCasemanager@mail.com', 'ORTEST', 'ORTEST', 'Redwood');
       //Assigning permission sets to the user.
        List<String> permsets = new List<String> {'ESD_Notes_Common','ESD_Referrals_Intaker_Light', 'ESD_Referrals_Common','ESD_Notes_Admission_Packet', 'iServe_Case_Management'};
        system.runas(new User(Id = Userinfo.getUserId())){ //Running the permissionset Assignment as a seperate user to avoid MIXED DML Operation error.
            TMN_Generic_Core_TestData.permsetAssign(permsets, caseManager.Id);
        }
        
       //caseManager = [SELECT ID FROM User WHERE alias = 'rwCMOR' LIMIT 1];
        system.runas(caseManager){
        	TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();
			Apexpages.StandardController sc = new Apexpages.StandardController(testData.theSA);
			ServiceAssignmentExt ext = new ServiceAssignmentExt(sc);
			PageReference dummyPage = ext.addORISP(); //Covers ServiceAssignmentExt Class as well.
        }
	}
	
	
	static testmethod void simpleTests(){
		
		User caseManager = [SELECT ID FROM User WHERE alias = 'rwCMOR' LIMIT 1];
		system.runAs(caseManager){
			Service_Assignment__c SA = [SELECT Id, Person_being_Served__c, Admission__r.Person_being_Served__c, Admission__r.Person_being_Served__r.FirstName, Admission__r.Person_being_Served__r.LastName FROM Service_Assignment__c WHERE CreatedDate = TODAY LIMIT 1];
			Case_Management_Plan__c isp = [SELECT Id, name, Status__c, Service_Assignment__c, CDP_WA_Check_Apply_int_Employment__c, CDP_WA_Check_Apply_nonworking__c, CDP_NE_Check_Apply_Decision_Not_Explore__c, 
											KPR_Included_Services__c, KPR_Additional_Services__c, CreatedBy.Name, KPR_Residential_Secton_Not_Applicable__c,KPR_IsValid__c  FROM Case_Management_plan__c WHERE Service_Assignment__c = : SA.Id AND createdDate = TODAY LIMIT 1];
											
			system.assert(isp.Status__c == 'Inactive Draft'); //Validate the initially created record
			
			PageReference pg = Page.ORcombinedISP;
			test.setCurrentPage(pg);
			ApexPages.CurrentPage().getParameters().put('mode', 'EDIT');
			
			Apexpages.StandardController sc = new Apexpages.StandardController(isp);
			ORcombinedISPController controller = new ORcombinedISPController(sc);
			system.assertEquals(true,  controller.isEditMode);
			system.assertEquals(false, controller.isViewMode);
			system.assertEquals(false,  controller.canEdit);
			system.assertEquals(false, controller.canFinalize); // because of edit mode
			system.assertEquals(false, controller.canRevise);
			//initial creation validations
			system.assert(controller.isp.Status__c == 'Inactive Draft');
			system.assert(controller.isp.KPR_Residential_Secton_Not_Applicable__c);
			system.assert(controller.isp.KPR_IsValid__c );
			
			
			//Plan Dates
			controller.section = 'planDates';
			controller.isp.PD_Start__c = Date.Today();
			controller.isp.PD_End__c = Date.Today().addDays(1);
			controller.save();
			
			ApexPages.CurrentPage().getParameters().put('mode', 'EDIT');
			controller.section = 'relparty';
			controller.showAddRelParty();
			Related_Party__c relParty = ORcombinedISPController.saveRelatedParty(null, 'Test', 'Parent', '', '', '', '', '', '', '', '', SA.Admission__r.Person_being_Served__c);
			controller.saveRelparty();
			ORcombinedISPController.loadRelatedParty(relParty.Id);
	        Related_Party__c rp2 = ORcombinedISPController.saveRelatedParty(relParty.Id, 'Test ', 'Parent', '', '', '', '', '', '', '', '', SA.Admission__r.Person_being_Served__c);
	        system.assertEquals(relParty.Type__c,rp2.Type__c);
	        //string s = controller.relPartiesJSON();
	        controller.save();
	        
	        
	       // ApexPages.CurrentPage().getParameters().put('mode', 'EDIT');
			controller.section = 'legal';
			controller.pullhealthCareReps();
	        controller.addorRefreshLegal();
	        controller.save();
	  	
	        //system.assert(controller.isp.Leg_Parents__c.contains('Test'));
	        //ApexPages.CurrentPage().getParameters().put('mode', 'EDIT');
			controller.section = 'agreement';
	        controller.showAddContributor();
	        Evaluation_Response__c contributor = ORcombinedISPController.saveContributor(null, 'Name', 'title', false, false, 'No', controller.isp.Id);
	        controller.savecontributor();
	        ApexPages.CurrentPage().getParameters().put('contributorID', contributor.Id);
	        controller.showEditContributor();
	        controller.save();
	        
	        
	        //ApexPages.CurrentPage().getParameters().put('mode', 'EDIT');
			controller.section = 'cdp';
			controller.selectedintEmployment =  new List<string>{'test1','test2'};
			controller.selectednonworking 	 =  new List<string>{'test1','test2'};
			controller.selectednotToExplore  =  new List<string>{'test1','test2'};
			controller.save();
			
			controller.section = 'kpr';
			controller.selectedKPRServices =  new List<string>{'test1','test2'};
			controller.selectedKPRAdditional 	 =  new List<string>{'test1','test2'};
			controller.save();
			
			
			controller.section = 'kplan';
			controller.isp.K_Plan_Section_Not_Applicable__c =  false;
			controller.save();
			
			controller.section = 'waiver';
			controller.isp.Waiver_Section_Not_Applicable__c =  true;
			controller.save();
			
			controller.section = 'desiredOutcomes';
			controller.save();
			
	        controller.cancel();
			controller.finalize();
	        controller.revise();
        
		}
		
	}
    
}