src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Comment__c</fullName>
        <description>Latest approval comment from the approval history.</description>
        <inlineHelpText>Latest approval comment from the approval history.</inlineHelpText>
        <label>Approval Comment</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled by User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Progressnote_updateComments_Batch.cls
global class Progressnote_updateComments_Batch implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		string query = 'SELECT id,Approval_Comment__c,Approval_User__c,(SELECT ID, TargetObjectID,Comments,ActorId FROM ProcessSteps Order by SystemModstamp desc LIMIT 1 ) FROM Progress_Note__c WHERE Approval_Status__c IN(\'Needs Refinement\',\'Approved\') AND Admission__r.State__c = \'AZ\'';
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext BC, List<Progress_Note__c>scope ){
		Map<Id, Progress_Note__c> pnMap = new Map<id,Progress_Note__c>(scope);
		List<Progress_note__c> toUpdate = new List<Progress_note__c>();
		for(Progress_Note__c pn : scope){
	    List<ProcessInstanceHistory> history = pn.ProcessSteps;
	    if(history.size()>0){
	    	Progress_Note__c p = pnMap.get(history[0].TargetObjectId);
            p.Approval_comment__c = history[0].Comments;
            p.Approval_User__c = history[0].ActorId;
	    	
	    	}
		}
		update pnMap.Values();
	}
	
	global void finish(Database.BatchableContext BC){
		List<String> toAddresses = new List<String>();
		toAddresses.add('contractor.sravan.pinninti@thementornetwork.com');
		Messaging.singleEmailMessage mail = new Messaging.singleEmailMessage();
		mail.setToAddresses(toAddresses);
		mail.setSenderDisplayName('Salesforce Batch to Update Approval Comments');
		mail.setSubject('Approval Comments Update Batch Run');
		mail.setUseSignature(false);
		string body = 'Approval Comments batch is completed';
		mail.setplainTextBody(body);
		mail.setSaveAsActivity(false);
		
		Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
	}
}