src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Staff Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose a clinician from the list</errorMessage>
            <filterItems>
                <field>TMN_User__c.Operating_Group__c</field>
                <operation>equals</operation>
                <valueField>$User.Operating_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Staff Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose a clinician from the list</errorMessage>
            <filterItems>
                <field>TMN_User__c.Operating_Group__c</field>
                <operation>equals</operation>
                <valueField>$User.Operating_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocDueFromPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field to store the primary case document due from person.</description>
        <inlineHelpText>A field to store the primary case document due from person.</inlineHelpText>
        <label>DocDueFromPerson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/saOwnershipBatch.cls
global class saOwnershipBatch implements Database.Batchable<sObject> 
{
	global final string targetState;
	
	global saOwnershipBatch (String st){
             targetState = st;
   }
	global Database.QueryLocator start( Database.BatchableContext BC) {
		String query = 'select id from service_assignment__c where admission__r.state__c = :targetState and clinician__c = null' ;
		
		system.debug( query + ', ' + targetState );
		return Database.getQueryLocator( query );
		
	}

	global void execute(Database.BatchableContext BC, List<Service_Assignment__c> scope) {

system.debug(scope.size());

		// get unique list of users for whom to get associated TMN User records
	Set<ID> userList = new Set<ID>();
	List<TMN_user__c> tmnList = new List<TMN_User__c>();
	Map<ID, ID> mapUsertoTMN = new Map<ID, ID>(); 
system.debug( targetState);	
	if ( targetState == 'NC' || targetState == 'FL' || targetState == 'GA') {
		// SAs needing clincians that don't have finalized progress notes
		List<Service_Assignment__c> saNoClinicianList = [ select id, clinician__c, person_being_served__r.ownerid from service_assignment__c where id in :scope ];
		
		// add users who are owners of SA list
		for ( Service_Assignment__c sa : saNoClinicianList )
			userList.add( sa.person_being_served__r.ownerid );
	
		// get the list of tmn_users so we can go from user id to tmn id
		tmnList = [ select id, salesforce_user_account__c from tmn_user__c where salesforce_user_account__c in :userList];
	
		for (TMN_user__c t : tmnList ) {
			mapUsertoTMN.put( t.salesforce_user_account__c, t.id );
		}
		for ( Service_Assignment__c sa: saNoClinicianList ) 
			sa.clinician__c = mapUsertoTMN.get( sa.person_being_served__r.ownerid);
		
		system.debug('NO CLINICIAN DATA: ' +  saNoClinicianList) ;	
		update saNoClinicianList;
		
	} else {	
		
//system.debug( targetState );
		
		Set<ID> saIDSet = new Set<Id>();
		List<Progress_Note__c> pnList = new List<Progress_Note__c>();
	
		system.debug( 'CHECKING FOR: ' + targetState );
		// get progress notes associated with the SAs needing clinicians 
		pnList = [ select id, service_assignment__c, clinician__c, staff_name__c, status__c, person_Being_served__r.ownerid, lastmodifieddate from progress_note__c where service_assignment__c in :scope and service_assignment__r.clinician__c = null and status__c = 'Final' order by lastmodifieddate desc];
		
		// create a unique list of SAs with progress notes needing update
		for ( Progress_note__c p : pnList ) 
			saIDSet.add( p.service_assignment__c);
			
		// get SAs needing clincians that don't have finalized progress notes
		List<Service_Assignment__c> saNoPNList = [ select id, clinician__c, person_being_served__r.ownerid from service_assignment__c where id in :scope and id not in :saIDSet and clinician__c = null];
		
		
		Map<ID, List<Progress_Note__c>> sawithPNList = new Map<ID, List<Progress_note__c>>();
		for ( Progress_note__c p : pnList ) {
		
			// add user-lookup staff to list to later match to tmn user based lookup
			if ( !string.isBlank(p.staff_name__c))
				userList.add( p.staff_name__c);
			
			// create the map of service assignment to list of progress notes for checking status and dates
			if ( sawithPNList.containsKey( p.service_assignment__c )) {
				List<Progress_Note__c> pnl = sawithPNLIst.get( p.service_assignment__c);
				pnl.Add( p );
				sawithPNList.put( p.service_assignment__c, pnl );
			} else {
				sawithPNList.put ( p.service_assignment__c, new List<Progress_Note__c> { p } );
			}
		}
		
		// add users who are owners of SA list
		for ( Service_Assignment__c sa : saNoPNList )
			userList.add( sa.person_being_served__r.ownerid );
		
		// get the list of tmn_users so we can go from user id to tmn id
		tmnList = [ select id, salesforce_user_account__c from tmn_user__c where salesforce_user_account__c in :userList];
		mapUsertoTMN = new Map<ID, ID>(); 
		for (TMN_user__c t : tmnList ) {
			mapUsertoTMN.put( t.salesforce_user_account__c, t.id );
		}
		
		
		// service assignments with no progress notes will take the PBS owner as the clinician
		for ( Service_Assignment__c sa: saNoPNList ) 
			sa.clinician__c = mapUsertoTMN.get( sa.person_being_served__r.ownerid);
		
		//system.debug( 'NO PN DATA: ' + saNoPNList) ;
		
		update saNoPNList;
			
		// service assignments with progress notes - get staff name off the most recent note
		List<Service_Assignment__c> saToUpdate = [ select id, clinician__c from service_assignment__c where id in :saWithPNList.keyset() ];
		
		for ( Service_Assignment__c sa : saToUpdate ) {
			// skip SA with no progress notes - this shouldn't happen
			if ( sawithPNList.get( sa.ID).size() == 0 ) {
				system.debug( 'The SA with id: ' + sa.ID + ' has no progress notes' );
				continue;
			} else {
				Progress_Note__c pn = sawithPNLIst.get(sa.ID).get(0);
				//system.debug( 'Latest progress note for ' + sa.ID + ' is ' + pn + '.  Setting clinician to ' + pn.staff_name__c );
				if ( String.IsBlank(pn.staff_name__c))
					sa.clinician__c = mapUsertoTMN.get( pn.person_being_served__r.ownerid );
				else
					sa.clinician__c = mapUsertoTMN.get( pn.staff_name__c );
			}
		
		}
	
		//system.debug( 'SA WITH PN: ' + sawithPNList );
		//system.debug( 'SA WITH CLINICIAN PN: ' + saToUpdate );
	
		update saToUpdate;
		}
	}
	global void finish(Database.BatchableContext BC)
    {
    }
    
}