src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Diagnosis__c.object
<CustomObject>
    <description>Diagnosis information at service assignment level.</description>
    <fields>
        <fullName>Axis_III__c</fullName>
        <label>Axis III</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Axis_II__c</fullName>
        <label>Axis II</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Axis_IV__c</fullName>
        <label>Axis IV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Axis_I__c</fullName>
        <label>Axis I</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Axis_V__c</fullName>
        <label>Axis V</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>date diagnosis is effective</description>
        <label>Date and Time of Diagnosis</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ICD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ICD-10 Code</label>
        <referenceTo>ICD__c</referenceTo>
        <relationshipLabel>Diagnoses</relationshipLabel>
        <relationshipName>Diagnoses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level_of_Disability__c</fullName>
        <label>Level of Disability</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Diagnosis__c</fullName>
        <label>Primary Diagnosis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Diagnosis__c</fullName>
        <label>Secondary Diagnosis</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Diagnoses</relationshipLabel>
        <relationshipName>Diagnoses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Diagnosis</label>
    <nameField>
        <label>Diagnosis</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnoses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ICD__c.object
<CustomObject>
    <description>Lists the International Classification of Diseases (ICD) 9 and 10 codes.</description>
    <label>ICD</label>
    <nameField>
        <label>ICD Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ICDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/stubController.cls
public with sharing class stubController {
	
	public stubController(Apexpages.StandardController controller){
		
		
	}
	
	public stubController(){
		
		
	}
	
	public static Boolean showdiagModal { get; set; }
    public string diagEditId {get; set; }
    
    public Boolean newDiagnosis{ get; set;} // comment after release
   
   public Boolean showDiagnosis { get {
    	//Returning a dummy value. Commented for easy deployment - Will delete after the release - Sravan - 11/13/2015
       /* if (! psetFlags ) {
            psetFlags = setShowFlags();
        }
        return pshowDiag;*/
        return false; 
    }}
    
    
    public list<Diagnosis__c> diagnoses{get; set;}

    public Diagnosis__c diag {
        get {
            if (diag == null)
                diag = new Diagnosis__c();
            return diag;
        }
        set;
    }
    
    public void showAddDiagnosis() {
       /* newDiagnosis = true;
        showdiagModal = true;
        diag = new Diagnosis__c();
        System.Debug('showdiagModal='+ showdiagModal);*/
    }

    public void showEditDiagnosis() {
       /* showdiagModal = true;
        System.Debug('showdiagModal=' + showdiagModal);*/
    }

    public void saveDiagnosis() {
       /* Boolean foundDiag = false;
        Diagnosis__c dgnew = this.diag;
        System.debug('dgnew: ' + dgnew);
        // if this diagnosis contains an ID, look for it to update
        if ( diagnoses != null ) {
            for ( Diagnosis__c dg : diagnoses ) {
                if ( dg.Id != null && dg.Id == dgnew.Id ) {
                    // update in place
                    dg.Effective_Date__c = dgnew.Effective_Date__c;
                    dg.Axis_I__c = dgnew.Axis_I__c;
                    dg.Axis_II__c = dgnew.Axis_II__c;
                    dg.Axis_III__c = dgnew.Axis_III__c;
                    dg.Axis_IV__c = dgnew.Axis_IV__c;
                    dg.Axis_V__c = dgnew.Axis_V__c;
                    dg.Primary_Diagnosis__c = dgnew.Primary_Diagnosis__c;
                    dg.Secondary_Diagnosis__c = dgnew.Secondary_Diagnosis__c;
                    dg.Level_of_Disability__c = dgnew.Level_of_Disability__c;
                    dg.Comments__c = dgnew.Comments__c;
                    system.debug('updating ' + dg.Id + ', ' + dgnew);
                    foundDiag = true;
                    break;
                }
            }
        }
        if ( !foundDiag )
            this.diagnoses.add(dgnew);

        this.diag= new Diagnosis__c();
        //newDiagnosis = false;*/
    }

    public void refreshDiagnoses() {
        // requery the diagnosis list
     /*   diagnoses = [select id, Service_Assignment__r.Name, Service_Assignment__c, Primary_Diagnosis__c, Secondary_Diagnosis__c, Axis_I__c,Axis_II__c,Axis_III__c,Axis_IV__c,Axis_V__c, Effective_Date__c, Comments__c from Diagnosis__c where Service_Assignment__c = :currentID order by createddate desc];
        newDiagnosis = false;*/

    }

    public void createDiagnoses() {
       /* if (diagnoses != null && this.theServAssign.Id != null) {
            for (Diagnosis__c dg : diagnoses ) {
                dg.Service_Assignment__c = this.theServAssign.Id;
            }
            System.Debug('DIAG LIST = ' + diagnoses);
            upsert diagnoses;
        }*/

    } 
    
      @RemoteAction
    public static Diagnosis__c loadDiagnosis(string diagnosisId) {
        /*Diagnosis__c dg =
                [select Id, Effective_Date__c, Axis_I__c, Axis_II__c, Axis_III__c, Axis_IV__c, Axis_V__c, Primary_Diagnosis__c, Secondary_Diagnosis__c, Level_of_Disability__c, Comments__c, Service_Assignment__c
                 from Diagnosis__c where id = :diagnosisId];
        system.debug('LOD:' + dg.Level_Of_disability__c);
        return dg;*/
        return new Diagnosis__c();
    }


    @RemoteAction
    public static boolean saveSingleDiagnosis (string diagId, long effDate, string axisI, string axisII, string axisIII, string axisIV, string axisV, string primDiag, string secondDiag, string lod, string comments, string saID) {
        /*Diagnosis__c dg;
        ID newID;
        if (diagId == '') {

            dg = new Diagnosis__c ( Effective_Date__c = datetime.newInstance(effDate), Axis_I__c = axisI, Axis_II__c = axisII, Axis_III__c = axisIII, Axis_IV__c = axisIV, Axis_V__c = axisV, Primary_Diagnosis__c = primDiag, Secondary_Diagnosis__c = secondDiag, Level_of_Disability__c = lod, Comments__c = comments, Service_Assignment__c = saID );
        }
        else {

            dg = [select Id, Effective_Date__c, Axis_I__c, Axis_II__c, Axis_III__c, Axis_IV__c, Axis_V__c, Primary_Diagnosis__c, Secondary_Diagnosis__c, Level_of_Disability__c, Comments__c, Service_Assignment__c
                  from Diagnosis__c where id = :diagId];

            dg.Effective_Date__c = datetime.newInstance(effDate);
            dg.Axis_I__c = axisI;
            dg.Axis_II__c = axisII;
            dg.Axis_III__c = axisIII;
            dg.Axis_IV__c = axisIV;
            dg.Axis_V__c = axisV;
            dg.Primary_Diagnosis__c = primDiag;
            dg.Secondary_Diagnosis__c = secondDiag;
            dg.Level_of_Disability__c = lod;
            dg.Comments__c = comments;
            dg.Service_Assignment__c = saID;
            system.debug('updating ' + dg.Id + ', ' + dg);
        }

        upsert dg;
        return true;*/
        return false;
    } 
    
    
    //FROM PBS EDIT CONTROLLER
     public string loadThisDiag {get; set;} // comment after dec23 release- sravan
    
    //Remove this method after Dec-23 release
    public PageReference loadDiagnosis(){
       /* for(Diagnosis__c dg : diagnosis){
            if(dg.id == loadThisDiag){
                diag = dg;
            }
        }*/
        return null;
    }
    
    //end
    
    public list<Diagnosis__c> diagnosis{get{
    	//Sravan - Commented this code for ease of deployment. Shoould remove the property after Dec 23, 2015 release
        /*return [select id, Status__c, ICD__c, Type__c, Service_Assignment__r.Name, Service_Assignment__c, Primary_Diagnosis__c, Secondary_Diagnosis__c, Axis_I__c,Axis_II__c,Axis_III__c,Axis_IV__c,Axis_V__c, Effective_Date__c, Comments__c from Diagnosis__c where Service_Assignment__r.Admission__r.Person_Being_Served__c=:Apexpages.currentpage().getparameters().get('Id')];*/
        return null;
    } set;}

}