src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Resident_Demonstrating_Issues__c</fullName>
        <label>Resident Demonstrating Issues</label>
        <picklist>
            <picklistValues>
                <fullName>Grieving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recent Life Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End-of-Life Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support System Not Coping Well</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Related_Party__c.object
<CustomObject>
    <description>REFERRALS - Parties having a relationship with the Person Being Referred</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referring Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Payee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CMShiftAssessmentView.cls
public with sharing class CMShiftAssessmentView {
	 public Evaluation__c evaluation { get; set; }
     public ApexPages.standardController stdController;
     public String selectedTab { get; set; }
     
     public List<selectOption>copingValues ;
     public List<string>selectedCoping {get;set;}
     
     public string getprimaryPhysician(){
    	List<Related_Party__c> rp = [SELECT Id, Name FROM Related_Party__c WHERE Person_Being_served__c=:this.evaluation.ServiceAssignment__r.Admission__r.Person_Being_Served__c AND Type__c='Physician - Primary' order by LastModifiedDate desc LIMIT 1];
    	if(rp.size()>0) return rp[0].Name;
    	else return null;
    }
	
	public CMShiftAssessmentView(Apexpages.StandardController controller){
		  this.stdController = controller;
		  evaluation = (Evaluation__c) stdController.getRecord();
		  selectedTab = ApexPages.currentPage().getParameters().get('tab');
		  copingValues = new List<selectOption>();
		  selectedCoping = new List<String>();
		  
		  if(!String.isBlank(this.evaluation.Resident_Demonstrating_Issues__c))
				selectedCoping = this.evaluation.Resident_Demonstrating_Issues__c.split(';');
	}
	
	 public List<selectoption> getcopingValues(){
   		List<Selectoption> copingValue = Utility.getPicklistValues(evaluation, 'Resident_Demonstrating_Issues__c');
   		return copingValue; 
   }

}