src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Admission_Effective_DateTime__c</fullName>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>No_Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this field if this progress note can be self-approved.</description>
        <inlineHelpText>Check this field if this progress note can be self-approved.</inlineHelpText>
        <label>No Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <formula>Service_Code__r.Program_Rollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose_Service_is_Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Default Check Box means this service is Billable, if this service is NOT Billable please Uncheck the box</inlineHelpText>
        <label>Purpose/Service is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <recordTypes>
        <fullName>NC_TFC</fullName>
        <active>true</active>
        <label>NC - TFC</label>
    </recordTypes>
    <recordTypes>
        <fullName>NC_Wks_1_6_TFC</fullName>
        <active>true</active>
        <label>NC - Wks 1-6 TFC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Therapy</fullName>
        <active>true</active>
        <description>Progress Note for NeuroRestorative IL</description>
        <label>Therapy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SA_Start_DateTime__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProgressNoteNotificationRunBatchTEST.cls
@isTest
private class ProgressNoteNotificationRunBatchTEST {

    static testMethod void myUnitTest() {
        Profile p = [SELECT Id FROM Profile WHERE Name='ESD General']; 
        User u = new User(Alias = 'testxxx1', Email='integration@testorg.com111', 
                    EmailEncodingKey='UTF-8',  LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', UserName='integration@testorg.com222', LastName='integration');
          
        List<User> users = [ select id, name from user where lastname = 'integration'];
        if ( users.size() == 0 )
        	insert u;
        	
        User usr = [ SELECT Id FROM User WHERE LastName = 'integration' LIMIT 1];        
        String RecTypeId= [select Id from RecordType where (DeveloperName='Person_Being_Served') and (SobjectType='Account') Limit 1].Id;
        
        Account Accnt = new Account(
            RecordTypeID=RecTypeId,
            FirstName= 'Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonMailingStateCode='AZ',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
        insert Accnt;
        
        Contact myContact = new Contact(
            LastName = 'TEST'
        );
        insert myContact;
        
        List<Account> testAcct = [Select Id, PersonContactId From Account a WHERE a.Id = :Accnt.Id];
        System.Debug('What is in testAcct: ' + testAcct);
        Id aContactId = testAcct[0].PersonContactId;
        Id aAccountId = testAcct[0].Id;
          
          
          Admission__c testAdm = new Admission__c(
                Name = 'TEST ADM',
                Person_Being_Served__c = aContactId,
                Effective_Date__c = date.today()-1,
                Admission_Effective_DateTime__c = DateTime.now().AddDays(-1)
          );
          insert testAdm;

          Admission__c testAdm2 = new Admission__c(
                Name = 'TEST ADM2',
                Person_Being_Served__c = myContact.Id,
                Effective_Date__c = date.today()-1,
                Admission_Effective_DateTime__c = DateTime.now().AddDays(-1)
          );
          insert testAdm2;
            
            Service_Assignment__c testServAssignment = new Service_Assignment__c(
              Admission__c = testAdm.Id,
              Person_Being_Served__c = aContactId,
              SA_Start_DateTime__c = DateTime.now()
              
            );
            insert testServAssignment;

            Service_Assignment__c testServAssignment2 = new Service_Assignment__c(
              Admission__c = testAdm2.Id,
              Person_Being_Served__c = myContact.Id,
              SA_Start_DateTime__c = DateTime.now()
            );
            insert testServAssignment2;
            
            Service_Code__c testServCode = new Service_Code__c(
              Service_Code__c = 'TEST SVC CODE',
              FacilityID__c = 'TEST FAC ID',
              Program_Code__c = 'TEST PROGRAM CODE',
              Start_Date__c = date.newInstance(2012,1,1) 
            );
            insert testServCode;
            
            
            List<RecordType> pnRecordTypes = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Progress_Note__c' AND IsActive = true];
            
            System.Debug('What is in pnRecordTypes: ' + pnRecordTypes);
            
            List<Progress_Note__c> pnsToInsert = new List<Progress_Note__c>();
            Integer pnsToInsertCounter = 0;             
            
            for(RecordType rt : pnRecordTypes){
                if(rt.DeveloperName != 'NC_TFC' && rt.DeveloperName != 'NC_Wks_1_6_TFC' && rt.DeveloperName != 'Therapy'){
                      pnsToInsert.add( 
                        new Progress_Note__c(
                          Service_Assignment__c = testServAssignment.Id, 
                          Service_Code__c = testServCode.Id, 
                          Admission__c = testAdm.ID,
                          Start_Time__c = datetime.now().addHours(-2),
                          End_Time__c = datetime.now(),
                          Person_Being_Served__c = aContactId,
                          No_Approval_Needed__c = false,
                          RecordTypeId = rt.Id,
                          Status__c = 'In Progress',
                          OwnerId = usr.Id)
                        );
                      pnsToInsert.add(
                        new Progress_Note__c(
                          Service_Assignment__c = testServAssignment.Id, 
                          Service_Code__c = testServCode.Id, 
                          Admission__c = testAdm.ID,
                          Start_Time__c = datetime.now().addHours(-2),
                          End_Time__c = datetime.now(),
                          Person_Being_Served__c = aContactId,
                          No_Approval_Needed__c = false,
                          RecordTypeId = rt.Id,
                          Status__c = 'Final',
                          OwnerId = usr.Id)
                      ); 
                    }
                if(rt.DeveloperName == 'NC_TFC' || rt.DeveloperName == 'NC_Wks_1_6_TFC' || rt.DeveloperName == 'Therapy'){
                    pnsToInsert.add( 
                    new Progress_Note__c(
                      Service_Assignment__c = testServAssignment.Id, 
                      Service_Code__c = testServCode.Id, 
                      Admission__c = testAdm.ID,
                      Start_Time__c = datetime.now().addHours(-2),
                      End_Time__c = datetime.now(),
                      Person_Being_Served__c = aContactId,
                      No_Approval_Needed__c = false,
                      RecordTypeId = rt.Id,
                      Status__c = 'In Progress',
                      Purpose_Service_is_Billable__c = false, //Avoid hitting validation rule.
                      OwnerId = usr.Id)
                    );
                  pnsToInsert.add(
                    new Progress_Note__c(
                      Service_Assignment__c = testServAssignment.Id, 
                      Service_Code__c = testServCode.Id, 
                      Admission__c = testAdm.ID,
                      Start_Time__c = datetime.now().addHours(-2),
                      End_Time__c = datetime.now(),
                      Person_Being_Served__c = aContactId,
                      No_Approval_Needed__c = false,
                      RecordTypeId = rt.Id,
                      Status__c = 'Final',
                      Purpose_Service_is_Billable__c = false, //Avoid hitting validation rule.
                      OwnerId = usr.Id)
                  ); 
                }           
            }

              pnsToInsert.add(
                new Progress_Note__c(
                  Service_Assignment__c = testServAssignment2.Id, 
                  Service_Code__c = testServCode.Id, 
                  Admission__c = testAdm2.ID,
                  Start_Time__c = datetime.now().addHours(-2),
                  End_Time__c = datetime.now(),
                  No_Approval_Needed__c = false,
                  Person_Being_Served__c = myContact.Id,
                  Status__c = 'Final',
                  OwnerId = usr.Id)
              );       
            
            insert pnsToInsert;
            
            SchedulableContext sc;
            ProgressNoteNotificationRunBatch pNNRB = new ProgressNoteNotificationRunBatch();
            
            Integer emailbefore = Limits.getEmailInvocations();
            pNNRB.execute(sc); 
            system.debug('emailbefore = ' + emailbefore + ';  Limits.getEmailInvocations() = ' + Limits.getEmailInvocations());

    }
}