src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Health_Wellness_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Health Wellness Checklists</relationshipLabel>
        <relationshipName>Health_Wellness_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Checklist</label>
        <referenceTo>Health_Wellness_Checklist__c</referenceTo>
        <relationshipLabel>Health Wellness Checklists</relationshipLabel>
        <relationshipName>Health_Wellness_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Health Wellness Checklist</label>
    <nameField>
        <label>Health Welness Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health Wellness Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HealthWellnessChecklistTriggeredActions.cls
public with sharing class HealthWellnessChecklistTriggeredActions {
	public void onAfterInsert(Health_Wellness_Checklist__c[] newObjects) {
		Set<Id> newIds = new Set<Id>();
		for (Health_Wellness_Checklist__c checklist: newObjects) {
			newIds.add(checklist.Id);
		}
		updateAdmissions(newIds);
	}

	public void onAfterUpdate(Health_Wellness_Checklist__c[] oldObjects, Health_Wellness_Checklist__c[] newObjects, Map<Id, Health_Wellness_Checklist__c> oldMap) {
		Set<Id> updatedIds = new Set<Id>();
		for (Health_Wellness_Checklist__c checklist: newObjects) {
			updatedIds.add(checklist.Id);
		}
		updateAdmissions(updatedIds);
	}
	public static void updateAdmissions(Set<Id> checklistIds) {
		// Update the admission field for reporting purpose
		Health_Wellness_Checklist__c[] checklists = [
			SELECT Id, Admission__c, Status__c
			  FROM Health_Wellness_Checklist__c
			 WHERE Id IN :checklistIds
		];
		Set<Id> admissionIds = new Set<Id>();
		for (Health_Wellness_Checklist__c checklist: checklists) {
			admissionIds.add(checklist.Admission__c);
		}
		Admission__c[] admissions = [
			SELECT Id, Status__c, (SELECT Id FROM Health_Wellness_Checklists__r WHERE Status__c = 'Inactive Draft')
			  FROM Admission__c
			 WHERE Id IN :admissionIds
		];
		List<Admission__c> admissionsToUpdate = new List<Admission__c>();
		for (Admission__c admission: admissions) {
			Boolean hasInactiveDraftChecklist = false;
			if (admission.Health_Wellness_Checklists__r.size() > 0) {
				hasInactiveDraftChecklist = true;
			}
			admission.Has_Inactive_Draft_Checklist__c = hasInactiveDraftChecklist;
		}
		System.debug(admissions);
		update admissions;
	}
}