src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Discharged_Date__c</fullName>
        <label>Discharged Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharged_Status__c</fullName>
        <label>Discharged Status</label>
        <picklist>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neutral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Discharge__c</fullName>
        <label>Reason for Discharge</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract_Document_JO__c.object
<CustomObject>
    <description>A cross-reference object that links contracts with the document profiles for documents expected in the client file for clients associated with that contract.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The document profile for this contract / document cross-reference.</description>
        <inlineHelpText>The document profile for this contract / document cross-reference.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Contract Document JOs</relationshipLabel>
        <relationshipName>Contract_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Document JO</label>
    <nameField>
        <displayFormat>ConDocXref-{0000000}</displayFormat>
        <label>Contract Document JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Document JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Document_Xref__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Program Document Xrefs</relationshipLabel>
        <relationshipName>Program_Document_Xrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program Document Xref</label>
    <nameField>
        <displayFormat>Program_Doc_Xref_{0000000}</displayFormat>
        <label>Program_Document_Xref__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Document Xrefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Service_Assignment__r.Program__c</formula>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_Treatment_End_Date__c</fullName>
        <inlineHelpText>This field is only required when associating Document types of Case and or Fidelity with a Service Assignment.</inlineHelpText>
        <label>Projected Treatment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Contract_JO__c.object
<CustomObject>
    <description>An object to hold records representing Service Assignment / Contract cross-references for the Document Tracker feature.</description>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment for this Service Assignment / Contract cross-reference.</description>
        <inlineHelpText>The Service Assignment for this Service Assignment / Contract cross-reference.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>ServiceAssignment_Contract_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>ServAssgn_Cntrct_JO-{0000000}</displayFormat>
        <label>ServiceAssignment_Contract_JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Contract__c.object
<CustomObject>
    <description>CAMBRIDGE CONTRACT</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>ApprovalStage__c</controllingField>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placement Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>-Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ServiceAssignmentValidationTEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ServiceAssignmentValidationTEST {

    static testMethod void myUnitTest() {
        String RecTypeId= [select Id from RecordType where (DeveloperName='Person_Being_Served') and (SobjectType='Account') Limit 1].Id;

        Account Accnt = new Account(
            RecordTypeID=RecTypeId,
            FirstName= 'Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonMailingStateCode='NC',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
        insert Accnt;

        List<Account> testAcct = [Select Id, PersonContactId From Account a WHERE a.Id = :Accnt.Id];
        System.Debug('What is in testAcct: ' + testAcct);
        Id aContactId = testAcct[0].PersonContactId;
        Id aAccountId = testAcct[0].Id;

        Admission__c Adm = new Admission__c(
            Name = 'TEST ADM',
            Person_Being_Served__c = aContactId,
            Effective_Date__c = date.newInstance(2013, 1, 1),
            Discharged_Date__c = date.newInstance(2013, 6, 30),
            Status__c = 'Discharged',
            Discharged_Status__c = 'Positive',
            Reason_for_Discharge__c = 'TEST REASON FOR DISCHARGE'
        );
        insert Adm;

        Service_Assignment__c ServAssign = new Service_Assignment__c(
            Name = 'TEST SERV ASSIGN',
            Admission__c = Adm.Id,
            Person_Being_Served__c = aContactId,
            Start_Date__c = date.newInstance(2013, 1, 1),
            End_Date__c = date.newInstance(2013, 1, 31),
            Status__c = 'Inactive'
        );

        Service_Assignment__c ServAssign2 = new Service_Assignment__c(
            Name = 'TEST SERV ASSIGN 2',
            Admission__c = Adm.Id,
            Person_Being_Served__c = aContactId,
            Start_Date__c = date.newInstance(2013, 6, 1),
            End_Date__c = date.newInstance(2013, 6, 30),
            Status__c = 'Inactive'
        );

        Progress_Note__c ProgNote = new Progress_Note__c(
            Name = 'TEST PROGRESS NOTE',
            Admission__c = Adm.Id,
            Service_Assignment__c = ServAssign.Id,
            Person_Being_Served__c = aContactId,
            Start_Time__c = datetime.newInstance(2013, 1, 1, 11, 30, 0),
            End_Time__c = datetime.newInstance(2013, 1, 1, 13, 30, 0)
        );
        Progress_Note__c ProgNote2 = new Progress_Note__c(
            Name = 'TEST PROGRESS NOTE 2',
            Admission__c = Adm.Id,
            Service_Assignment__c = ServAssign.Id,
            Person_Being_Served__c = aContactId,
            Start_Time__c = datetime.newInstance(2013, 1, 3, 11, 30, 0),
            End_Time__c = datetime.newInstance(2013, 1, 3, 13, 30, 0)
        );

        Progress_Note__c ProgNote3 = new Progress_Note__c(
            Name = 'TEST PROGRESS NOTE 3',
            Admission__c = Adm.Id,
            Service_Assignment__c = ServAssign.Id,
            Person_Being_Served__c = aContactId,
            Start_Time__c = datetime.newInstance(2013, 1, 30, 11, 30, 0),
            End_Time__c = datetime.newInstance(2013, 1, 30, 13, 30, 0)
        );


        test.startTest();
        insert ServAssign;
        ServAssign.End_Date__c = date.newInstance(2013,2,1);
        upsert ServAssign;
        insert ServAssign2;
        insert ProgNote;
        //insert ProgNote2;
        //insert ProgNote3;

        List<Service_Assignment__c> myListOfServAssigns = new List<Service_Assignment__c>();
        myListOfServAssigns.add(ServAssign);
        myListOfServAssigns.add(ServAssign2);

        ServiceAssignmentValidation.checkProgressNoteEndDates(myListOfServAssigns);

        delete ServAssign;
        undelete ServAssign;

        ServAssign.End_Date__c = date.newInstance(2013, 1, 29);
        test.stopTest();

        ServiceAssignmentValidation myObj = new ServiceAssignmentValidation(true);
        System.assert(myObj.IsTriggerContext==true,'The IsTriggerContext variable does not equal true as expected!');
    }

    static testMethod void insertDocAndUpdateSa() {

        String RecTypeId= [select Id from RecordType where (DeveloperName='Person_Being_Served') and (SobjectType='Account') Limit 1].Id;

        Account Accnt = new Account(
            RecordTypeID=RecTypeId,
            FirstName= 'Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonMailingStateCode='NC',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
        insert Accnt;

        List<Account> testAcct = [Select Id, PersonContactId From Account a WHERE a.Id = :Accnt.Id];
        System.Debug('What is in testAcct: ' + testAcct);
        Id aContactId = testAcct[0].PersonContactId;
        Id aAccountId = testAcct[0].Id;

        Admission__c Adm = new Admission__c(
            Name = 'TEST ADM',
            Person_Being_Served__c = aContactId,
            Effective_Date__c = date.newInstance(2013, 1, 1),
            Status__c = 'Active'
        );
        insert Adm;

        Service_Assignment__c ServAssign = new Service_Assignment__c(
            Name = 'TEST SERV ASSIGN',
            Admission__c = Adm.Id,
            Person_Being_Served__c = aContactId,
            Start_Date__c = date.newInstance(2013, 1, 1),
            Projected_Treatment_End_Date__c = date.newInstance(2013, 1, 31),
            Status__c = 'Active',
            Program__c = 'IFCS'
        );

        test.startTest();
        insert ServAssign;

        Document__c caseDoc = new Document__c(
            Name = 'Case Document',
            Active__c = true,
            Auto_Include__c = true,
            Relative_Due_Date_Event__c = 'Client Tx Start',
            Relative_Due_Date_UOM__c = 'Day(s)',
            Relative_Due_Date_Units__c = 1,
            Required_From_Date__c = date.newInstance(2013, 1, 1),
            Required_To_Date__c = date.newInstance(2013, 12, 31),
            State__c = 'NC',
            Type__c = 'Case Document'
        );

        insert caseDoc;

        Document__c caseDoc2 = new Document__c(
            Name = 'Case Document 2',
            Active__c = true,
            Auto_Include__c = true,
            Relative_Due_Date_Event__c = 'Calendar Month End',
            Relative_Due_Date_UOM__c = 'Day(s)',
            Relative_Due_Date_Units__c = 3,
            Required_From_Date__c = date.newInstance(2013, 1, 1),
            Required_To_Date__c = date.newInstance(2013, 12, 31),
            State__c = 'NC',
            Type__c = 'Case Document'
        );

        insert caseDoc2;

        ServiceAssignment_Document_JO__c mySadjo = new ServiceAssignment_Document_JO__c(
            Document__c = caseDoc.Id,
            Service_Assignment__c = ServAssign.Id,
            Filed_Date_Time__c = datetime.newInstance(2013,10,20,12,30,00),
            File_Status__c = 'Filed',
            Relative_Due_Date_Event__c = 'Client Tx Start',
            Relative_Due_Date_UOM__c = 'Day(s)',
            Relative_Due_Date_Units__c = 1,
            Relative_Due_Date_Resolved__c = date.newInstance(2013,1,2)
        );
        insert mySadjo;

        ServiceAssignment_Document_JO__c mySadjo2 = new ServiceAssignment_Document_JO__c(
            Document__c = caseDoc2.Id,
            Service_Assignment__c = ServAssign.Id,
            Filed_Date_Time__c = datetime.newInstance(2013,10,20,12,30,00),
            File_Status__c = 'Filed',
            Relative_Due_Date_Event__c = 'Client Tx Start',
            Relative_Due_Date_UOM__c = 'Day(s)',
            Relative_Due_Date_Units__c = 7,
            Relative_Due_Date_Resolved__c = date.newInstance(2013,1,8)
        );
        insert mySadjo2;

        ServiceAssignment_Document_JO__c mySadjo3 = new ServiceAssignment_Document_JO__c(
            Document__c = caseDoc2.Id,
            Service_Assignment__c = ServAssign.Id,
            File_Status__c = 'Not Filed',
            Relative_Due_Date_Event__c = 'Client Tx Start',
            Relative_Due_Date_UOM__c = 'Day(s)',
            Relative_Due_Date_Units__c = 7
        );
        insert mySadjo3;

        ServAssign.End_Date__c = null;
        ServAssign.Projected_Treatment_End_Date__c = date.newInstance(2013,7,1);

        update ServAssign;

        TMN_Contract__c myContract = new TMN_Contract__c(
            Name = 'Name',
            ApprovalStage__c = 'Approved',
            Status__c = 'Active'
        );
        insert myContract;

        ServiceAssignment_Contract_JO__c mySacjo = new ServiceAssignment_Contract_JO__c(
            Service_Assignment__c = ServAssign.Id,
            Contract__c = myContract.Id
        );
        insert mySacjo;

        Contract_Document_JO__c myContractDocJo = new Contract_Document_JO__c(
            Contract__c = myContract.Id,
            Document__c = caseDoc.Id
        );
        insert myContractDocJo;

        Contract_Document_JO__c myContractDocJo2 = new Contract_Document_JO__c(
            Contract__c = myContract.Id,
            Document__c = caseDoc2.Id
        );
        insert myContractDocJo2;

        Program_Document_Xref__c myProgramDocXref = new Program_Document_Xref__c(
            Program__c = 'IFCS',
            Document__c = caseDoc.Id
        );
        insert myProgramDocXref;

        Program_Document_Xref__c myProgramDocXref2 = new Program_Document_Xref__c(
            Program__c = 'IFCS',
            Document__c = caseDoc2.Id
        );
        insert myProgramDocXref2;

        myContract.Status__c = 'Cancelled';
        ServAssign.Projected_Treatment_End_Date__c = date.newInstance(2013,1,30);
        caseDoc2.Required_To_Date__c = date.newInstance(2013,1,2);
        update caseDoc2;

        update ServAssign;
/*
        ServAssign.Program__c = 'Miami';
        delete myContractDocJo;
        delete myContractDocJo2;

        update ServAssign;
*/
        test.stopTest();
    }
}