src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objective__c.object
<CustomObject>
    <description>NOTES Objectives represent the milestones needed to complete a Short-term Goal on a Plan. Objectives relate to Plans by way of Short-term Goals. Objectives are Master-detail to Short-term Goals.</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Objective Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>NOTES Plan object is Master-detail to Persons Being Served. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Date the Plan should be implemented</description>
        <inlineHelpText>The date the Plan can be implemented providing all approvals are on file</inlineHelpText>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Admission__r.State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates note was marked to be diregarded</description>
        <label>Disregard Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interventions__c</fullName>
        <inlineHelpText>Any Interventions. – Required</inlineHelpText>
        <label>Interventions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>TEXT(Service_Assignment__r.Location_Region__c)</formula>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Approval_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this field if this progress note can be self-approved.</description>
        <inlineHelpText>Check this field if this progress note can be self-approved.</inlineHelpText>
        <label>No Approval Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_For_Next_Visit__c</fullName>
        <description>Describe goals for next meeting</description>
        <inlineHelpText>Any notes that may be helpful for the next visit. – Required</inlineHelpText>
        <label>Notes For Next Visit</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <formula>Service_Code__r.Program_Rollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <description>Progress towards goals selected.</description>
        <inlineHelpText>Progress made towards goals selected. – Required</inlineHelpText>
        <label>Progress</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Purpose_Service_is_Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Default Check Box means this service is Billable, if this service is NOT Billable please Uncheck the box</inlineHelpText>
        <label>Purpose/Service is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <recordTypes>
        <fullName>NC_TFC</fullName>
        <active>true</active>
        <label>NC - TFC</label>
    </recordTypes>
    <recordTypes>
        <fullName>NC_Wks_1_6_TFC</fullName>
        <active>true</active>
        <label>NC - Wks 1-6 TFC</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Short_Term_Goal__c.object
<CustomObject>
    <description>NOTES Short-term Goals are the goals defined to achieve the Long-term Goals on a Plan. Short-term Goals are Master-detail to Plans. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <formula>Plan__r.Admission__c</formula>
        <label>Admission</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Short-term Goal</label>
    <nameField>
        <label>Short-term Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Short-term Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Notes_ProgressNote_AddlActionsTEST.cls
@isTest
private class Notes_ProgressNote_AddlActionsTEST {

    static testMethod void myUnitTest() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='ESD General']; 
        
        User u = new User(Alias = 'testxxx1', Email='standarduser@testorg.com111', 
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com222');
        insert u;           
        
        // update permissions
        PermissionSet ps = [ select Id from PermissionSet where name='ESD_Notes_Clinical_Data_User'];
        PermissionSetAssignment psa = new PermissionSetAssignment( assigneeid=u.id, permissionsetid= ps.id);
        insert psa;
        
        // user is not in correct permission set yet
        System.runAs(u) {      
        // create a progress note
        
        List<RecordType> personAccountIds = new List<RecordType>();
        personAccountIds = [SELECT Id, Name from recordtype where SobjectType = 'Account' and IsPersonType = true and IsActive = true and Name = 'Person Being Served'];
        
        List<RecordType> rtypes =  new List<RecordType>();
        rtypes = [SELECT id, DeveloperName from RecordType where SobjectType = 'Progress_note__c' AND IsActive = true AND DeveloperName Not IN ('NC_TFC','NC_Wks_1_6_TFC') LIMIT 1 ]; //Added by Sravan to Prevent validation error due to  Purpose_Service_is_Billable__c = true. 10/22/2014 4:15 PM.  
        Integer counter = 0;
        Boolean even = false;
        test.startTest();
        for(RecordType record_type: rtypes){
            counter++;
            TMN_Generic_Core_TestData myLoopData = new TMN_Generic_Core_TestData();
            
            /*
            Date myDate = date.newinstance(1960, 2, 17);
            
            Account acct = new Account(
            RecordTypeID=personAccountIds[0].id,
            FirstName= 'Test FName' + counter,
            LastName='Test LName' + counter,
            PersonBirthdate = myDate,
            PersonMailingStreet='test'  + counter + '@yahoo.com222',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SF',
            PersonMailingStateCode='NC',
            PersonEmail='test'  + counter + '@yahoo.com222',
            PersonHomePhone='1234567899',
            PersonMobilePhone='1234567899',
            Other_ID__pc = 'Other' + counter
            );
            insert acct;
            
           Id aPersonContactId;
           List<Account> myPersonContactIdList = [SELECT PersonContactId FROM Account WHERE Id = :acct.Id];
           aPersonContactId = myPersonContactIdList[0].PersonContactId;
                        
            Admission__c testAdm = new Admission__c(
                Name = 'TEST ADM' + counter,
                Person_Being_Served__c = aPersonContactId,
                Effective_Date__c = date.today(),
                state__c  = 'NC'
                
            );
            
            insert testAdm;
            
            Service_Assignment__c testServAssignment = new Service_Assignment__c(
                Admission__c = testAdm.Id,
                Person_Being_Served__c = aPersonContactId
            );
            insert testServAssignment;
            */    
            Service_Code__c testServCode = new Service_Code__c(
                Start_Date__c = date.newInstance(2012,1,1),
                FacilityID__c = '7',
                Program_Code__c = 'TEST PROGRAM CODE' + counter ,
                Location__c = 'TEST LOC CODE' + counter,
                Service_Line__c = 'TEST SVC LINE' + counter
            );
            insert testServCode;
            
            Progress_Note__c testPN = new Progress_Note__c(
                Service_Assignment__c = myLoopData.theSA.Id,
                Admission__c = myLoopData.theAdm.ID,
                Purpose_Service_is_Billable__c = true,
                Disregard_note__c = false,
                RecordTypeId = record_type.id,
              //  Start_Time__c = myLoopData.theSA.start_date__c.addDays(1),
                Start_Time__c = DateTime.newInstance(myLoopData.theSA.start_date__c.addDays(1),Time.newInstance(0, 0, 0, 0)),
              //  End_Time__c = myLoopData.theSA.start_date__c.addMinutes(30),
                End_time__c = DateTime.newInstance(myLoopData.theSA.start_date__c.addDays(1),Time.newInstance(0, 0, 30, 0)),
                Person_Being_Served__c = myLoopData.contactID ,
                No_Approval_Needed__c = true,
                Interventions__c = 'test',
                Notes_For_Next_Visit__c ='test',
                Progress__c ='test',
                Approval_Status__c = 'Approved'
            );
            insert testPN;  
            
            testPN.No_Approval_Needed__c  = true;
            update testPN;
                
            Plan__c testPlan = new Plan__c(
            Total_Interventions__c = 1,
            Total_Objectives__c = 1,
            Total_Short_Term_Goals__c = 1,
            Status__c = 'Inactive',
            Admission__c = myLoopData.theAdm.ID,
            Long_term_Goal_1__c = 'TEST LONG TERM GOAL'         
            );
            insert testPlan;
            Short_Term_Goal__c testSTG = new Short_Term_Goal__c(
                Plan__c = testPlan.Id
            );
            insert testSTG;
            
            Objective__c testOBJ = new Objective__c(
                Plan__c = testPlan.Id,
                Short_Term_Goal__c = testSTG.Id
            );
            insert testOBJ;
            
            Intervention__c testINT = new Intervention__c(
                Objective__c = testOBJ.Id
            );
            insert testINT;
            
        }
        
        Progress_Note__c newtestPN = [ select id, Purpose_Service_Is_Billable__c, Disregard_Note__c, approval_status__c, ownerid from Progress_Note__c LIMIT 1];
        
        // now attempt the update
        System.AssertEquals(newtestPN.Purpose_Service_is_Billable__c, true);
        System.AssertEquals(newtestPN.Disregard_note__c, false);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(newtestPN);
        Notes_ProgressNote_AddlActions objTestExt = new Notes_ProgressNote_AddlActions(sc);
        objTestExt.updateLocked();
        newtestPN = [ select id, Purpose_Service_Is_Billable__c, disregard_note__c, approval_status__c, ownerid from Progress_Note__c LIMIT 1];
        
        System.AssertEquals(newtestPN.Purpose_Service_is_Billable__c, false);
        System.AssertEquals(newtestPN.Disregard_note__c, true);
        
        Boolean userallowed = objTestExt.canDisregard;
        System.AssertEquals(true, userallowed);
        
        // update permissions to allow again
        ps = [ select Id from PermissionSet where name='ESD_Notes_Supervisor'];
        psa = new PermissionSetAssignment( assigneeid=u.id, permissionsetid= ps.id);
        insert psa;

        userallowed = objTestExt.canDisregard;
        System.AssertEquals(true, userallowed); 

        }
    }

}