src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies the current episode for an individual. Only one episode for an individual may be active at one time. TODO: Use a workflow to sychronize the active state with the Episode.Status</description>
        <inlineHelpText>Identifies the current episode for an individual. Only one episode for an individual may be active at one time.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>A checkbox to indicate a document profiles active status.</description>
        <inlineHelpText>Check if the document is active, uncheck if the document is inactive.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Include__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This box should be checked if you want this document to be automatically included when creating a new Service Assignment for clients associated with a state(s) this document is associated with.</description>
        <inlineHelpText>This box should be checked if you want this document to be automatically included when creating a new Service Assignment for clients associated with a state(s) this document is associated with.</inlineHelpText>
        <label>Auto Include</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Event__c</fullName>
        <description>The event that serves as the baseline for relative due dates.</description>
        <inlineHelpText>Select an event to server as the baseline for this document&apos;s relative due date.</inlineHelpText>
        <label>Relative Due Date Event</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar Month End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Quarter End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MENTOR Fiscal Year End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Anniversary of Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Anniversary of Client Tx Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_UOM__c</fullName>
        <description>The Unit of Measure (UOM) specified for the relative due date for a document profile.</description>
        <inlineHelpText>Select a Unit of Measure (UOM) for the relative due date for a document profile.</inlineHelpText>
        <label>Relative Due Date Unit of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Units__c</fullName>
        <description>The number of units of the unit of measure specified for the relative due date value.</description>
        <inlineHelpText>The number of units of the unit of measure specified for the relative due date value.</inlineHelpText>
        <label>Relative Due Date Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_From_Date__c</fullName>
        <description>The start date of the date range within which the document is required.</description>
        <inlineHelpText>The start date of the date range within which the document is required.</inlineHelpText>
        <label>Required From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Required_To_Date__c</fullName>
        <description>The end date of the date range within which the document is required.</description>
        <inlineHelpText>The end date of the date range within which the document is required.</inlineHelpText>
        <label>Required To Date</label>
        <type>Date</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_Treatment_End_Date__c</fullName>
        <inlineHelpText>This field is only required when associating Document types of Case and or Fidelity with a Service Assignment.</inlineHelpText>
        <label>Projected Treatment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Event__c</fullName>
        <label>Relative Due Date Event</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar Month End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Quarter End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MENTOR Fiscal Year End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other - Describe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Anniversary of Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Anniversary of Client Tx Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_UOM__c</fullName>
        <label>Relative Due Date UOM</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weeks(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Units__c</fullName>
        <label>Relative Due Date Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServAssignExpectedDocsExtTEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ServAssignExpectedDocsExtTEST {

    static testMethod void myUnitTest() {

        String RecTypeId= [select Id from RecordType where (DeveloperName='Person_Being_Served') and (SobjectType='Account') Limit 1].Id;
        
        Account Accnt = new Account(
            RecordTypeID=RecTypeId,
            FirstName= 'Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonMailingStateCode='NC',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678'
        );
        insert Accnt;
        
        List<Account> testAcct = [Select Id, PersonContactId From Account a WHERE a.Id = :Accnt.Id];
        System.Debug('What is in testAcct: ' + testAcct);
        Id aContactId = testAcct[0].PersonContactId;
        Id aAccountId = testAcct[0].Id;

        Admission__c Adm = new Admission__c(
            Name = 'TEST ADM',
            Person_Being_Served__c = aContactId,
            Effective_Date__c = date.today(),
            Status__c = 'Active'
        );
        insert Adm;
        
        Service_Assignment__c ServAssign = new Service_Assignment__c(
        	Name = 'TEST SERV ASSIGN',
        	Admission__c = Adm.Id,
        	Person_Being_Served__c = aContactId,
        	Start_Date__c = date.today(),
        	Projected_Treatment_End_Date__c = date.today() + 180,
        	Status__c = 'Active',
        	Program__c = 'IFCS'
        );
        
        test.startTest();
        insert ServAssign;
		
    	Document__c caseDoc = new Document__c(
			Name = 'Case Document',
			Active__c = true,
			Auto_Include__c = true,
			Relative_Due_Date_Event__c = 'Client Tx Start',
			Relative_Due_Date_UOM__c = 'Day(s)',
			Relative_Due_Date_Units__c = 1,
			Required_From_Date__c = date.newInstance(date.today().year(), 1, 1),
			Required_To_Date__c = date.newInstance(date.today().year(), 12, 31),
			State__c = 'NC',
			Type__c = 'Case Document'
		);

		insert caseDoc;

    	Document__c caseDoc2 = new Document__c(
			Name = 'Case Document 2',
			Active__c = true,
			Auto_Include__c = true,
			Relative_Due_Date_Event__c = 'Calendar Month End',
			Relative_Due_Date_UOM__c = 'Day(s)',
			Relative_Due_Date_Units__c = 3,
			Required_From_Date__c = date.newInstance(date.today().year(), 1, 1),
			Required_To_Date__c = date.newInstance(date.today().year(), 12, 31),
			State__c = 'NC',
			Type__c = 'Case Document'
		);

		insert caseDoc2;

		ServiceAssignment_Document_JO__c mySadjo = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			File_Status__c = 'Filed',
			Relative_Due_Date_Event__c = 'Client Tx Start',
			Relative_Due_Date_UOM__c = 'Day(s)',
			Relative_Due_Date_Units__c = 1,
			Relative_Due_Date_Resolved__c = date.newInstance(date.today().year(),date.today().month(),date.today().day())
		);
		insert mySadjo;

		ServiceAssignment_Document_JO__c mySadjo2 = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			File_Status__c = 'Not Filed',
			Fixed_Due_Date__c = date.today() + 15
		);
		insert mySadjo2;

		ServiceAssignment_Document_JO__c mySadjo3 = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			File_Status__c = 'Not Filed',
			Fixed_Due_Date__c = date.today() + 5
		);
		insert mySadjo3;

		ServiceAssignment_Document_JO__c mySadjo4 = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			File_Status__c = 'Not Filed',
			Fixed_Due_Date__c = date.today() - 1
		);
		insert mySadjo4;

		ServiceAssignment_Document_JO__c mySadjo5 = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			Fixed_Due_Date__c = date.today() - 1,
			File_Status__c = ''
		);
		insert mySadjo5;

		//Use the PageReference Apex class to instantiate a page
       	PageReference pageRef = Page.ServAssignExpectedDocs;

       	//In this case, the Visualforce page named 'ServAssignExpectedDocs' is the starting point of this test method.
       	Test.setCurrentPage(pageRef);

       	//Instantiate and construct the controller class.  
       	ApexPages.StandardController sc = new ApexPages.StandardController(ServAssign);
       	ServAssignExpectedDocsExt myConExt = new ServAssignExpectedDocsExt(sc);
        
        // INSERT a ServiceAssignment_Document_JO__c record with the saveFilings method.
        myConExt.sadjToSave = mySadjo.Id;
        myConExt.saveFilings();
        
        // SELECT the ServiceAssignment_Document_JO__c record into a variable.
        List<ServiceAssignment_Document_JO__c> testSadjo = [ SELECT Id FROM ServiceAssignment_Document_JO__c WHERE Id = :mySadjo.Id ];
        
        // Confirm that there is a saved record in the variable.
        System.assert(testSadjo.size()==1);
        
        // Confirm that the record(s) in the variable have the same ID as the test record(s) created in this test method.
        for(ServiceAssignment_Document_JO__c tS : testSadjo) {
        	System.assert(tS.Id==mySadjo.Id);
        }
        

        myConExt.sadjToSave = mySadjo2.Id;
		//myConExt.saveFilings();
		ServAssignExpectedDocsExt.saveSadjoRemote(mySadjo2.Id,'TEST NA REASON','Filed');
		// Confirm that the listOfDocFilings now contains one record.
		//System.assert(myConExt.listOfDocFilings.size()==1);
		System.debug('listOfDocFilings size: ' + myConExt.listOfDocFilings.size());
		
		myConExt.sadjToDelete = mySadjo2.Id;
		myConExt.RemoveDoc();
		
		
		// Try to select the document filing just deleted into a variable.
		List<ServiceAssignment_Document_JO__c> theDocFiling = [ SELECT Id FROM ServiceAssignment_Document_JO__c WHERE Id = :mySadjo2.Id ];
		
		// Confirm that the deleted document is gone by asserting that theDocFiling has size 0.
		System.assert(theDocFiling.size()==0);
		
		myConExt.RemoveDoc();
		

		ServiceAssignment_Document_JO__c mySadjo6 = new ServiceAssignment_Document_JO__c(
			Document__c = caseDoc.Id,
			Service_Assignment__c = ServAssign.Id,
			Filed_Date_Time__c = datetime.now(),
			Fixed_Due_Date__c = date.today()
		);
		insert mySadjo6;

		ServAssignExpectedDocsExt.saveSadjoRemote(mySadjo6.Id,'TEST NA REASON','Filed');
		ServAssignExpectedDocsExt.loadSadjo(mySadjo6.Id);
        
    }
}