src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Time__c</fullName>
        <description>Duration (In Minutes) = End Time - Start Time</description>
        <formula>(End_Time__c  -Start_Time__c)*24*60</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Duration (In Minutes) = End Time - Start Time</inlineHelpText>
        <label>Total Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DocDueFromPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field to store the primary case document due from person.</description>
        <inlineHelpText>A field to store the primary case document due from person.</inlineHelpText>
        <label>DocDueFromPerson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/DocumentedActualStaffHrsRpt.cls
public with sharing class DocumentedActualStaffHrsRpt {

    public Date fStartDate{get{return fStartDate;} set;}
    public Date fEndDate{get{return fEndDate;} set;}
    
    public List<StaffHrsInfo> listStaffHrsInfo = new List<StaffHrsInfo>();
    public List<StaffHrsInfo> getListStaffHrsInfo(){return listStaffHrsInfo;}
        
    List<AggregateResult> PNResults = new List<AggregateResult>();            
        
    public DocumentedActualStaffHrsRpt () {
       //fStartDate = system.today();
       allCount = 0;
    } 
    
    public integer allCount{get; set;}
    
    public Map<string, integer > ParsedData = new Map<string, integer >();    
    public Map<string, integer > getParsedData(){return ParsedData;}
    
    public PageReference runReport(){
        if(fEndDate < fStartDate){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Start Date must be before the End Date');//Same old drama 
            ApexPages.addMessage(myMsg);            
            return null;
        }
        
        ParsedData.clear();                
        
        PNResults.clear();
        listStaffHrsInfo.clear();                                                                                     
                                        
        PNResults = [ SELECT 
           			 	Owner.FirstName ofn,
           			 	Owner.LastName oln,
                      	Staff_Name__r.Name,
         				Person_Being_Served__r.FirstName pbsfn,
         				Person_Being_Served__r.LastName pbsln,
         				//Service_Assignment__r.Phase__c,         				
                       	SUM(Total_Time__c) sum                      
                       FROM Progress_Note__c 
                       WHERE 
                         (
                            ((Service_Assignment__r.Start_Date__c >= :fStartDate OR 
                              Service_Assignment__r.End_Date__c >= :fStartDate) 
                           AND  
                            (Service_Assignment__r.Start_Date__c <= :fEndDate OR 
                             Service_Assignment__r.End_Date__c <= :fEndDate) )                         
                           OR
                            (Service_Assignment__r.Start_Date__c  <= :fEndDate AND 
                             Service_Assignment__r.End_Date__c = null ) 
                         )
                       GROUP BY Owner.FirstName, Owner.LastName, Staff_Name__r.Name,
                                Person_Being_Served__r.FirstName, Person_Being_Served__r.LastName 
                    ];    
                                           
            StaffHrsInfo dataRow;
                                                                                           
            for(AggregateResult pn : PNResults) {     
            	 dataRow = new StaffHrsInfo();
            	        	            	
            	// if pseudo notes then Staff Name
            	/*if ((pn.Service_Assignment__r.Admission__r.State__c == 'IN' ||
            	     Service_Assignment__r.Admission__r.State__c == 'MA' ||
            	     Service_Assignment__r.Admission__r.State__c == 'MD' ||
            	     Service_Assignment__r.Admission__r.State__c == 'OH') && 
            	     pn.get('Staff_Name__r.Name') != null)
            	      dataRow.clinician = (String)pn.get('Staff_Name__r.Name');            	                  	    
            	else               	              	               	         
            	      dataRow.clinician = (String)pn.get('Owner.FirstName') + ' ' + (String)pn.get('Owner.FirstName');
                  
                Integer phase = (Integer)pn.get('Service_Assignment__r.Phase__c');                                  
                     
                if (phase == 1) {
                    dataRow.phase = 'J';                
                }
                if (phase == 2) {
                    dataRow.phase = 'R';
                }
                if (phase == 3) {
                    dataRow.phase = 'VC'; 
                }
                if (phase == 4) {
                    dataRow.phase = 'G'; 
                } */
                                                
                dataRow.clinician = (String)pn.get('ofn') + ' ' + (String)pn.get('oln');
                dataRow.pbs = (String)pn.get('pbsfn') + ' ' + (String)pn.get('pbsln');
                
                Decimal totalMinutes = (Decimal)pn.get('sum'); 
                dataRow.totalMinutes = String.valueOf(totalMinutes);   
                dataRow.hours = String.valueOf((totalMinutes/60).setscale(2));
                
                System.debug(dataRow);          
                listStaffHrsInfo.add(dataRow);                                                                                                   
            }                                                                                                                                               
            allCount = listStaffHrsInfo.size();
        
            fStartDate = null;
            fEndDate= null;
            return null; 
    }
    
    // Inner Class to store the row data detail of the report 
    public class StaffHrsInfo {
        public String clinician {get; set;}
        public String pbs {get; set;}
        public String phase {get; set;}
        public String totalMinutes {get; set;} 
        public String hours{get; set;}
    }   

}