src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AccountPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Person Relationship
Delete Me</description>
        <label>AccountPerson</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <description>Interval for the assessment</description>
        <label>Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Assessment_CANS_Notes_Sch.cls
global class Assessment_CANS_Notes_Sch implements Schedulable {
	global void execute(SchedulableContext sc) {
			string devMsg = '';
			string devMsg2 = '';
			Assessment__c[] assessReqNote = [select id, name, status__c, assessment_date__c, 
								admission__c, Interval__c,
								accountperson__c, accountperson__r.PBS_Identifier__pc, AccountPerson__r.PersonContactId,
								owner.id, owner.isActive, Owner.LastName, Owner.FirstName
									from Assessment__c 
										Where Status__c = 'Locked'
											AND Disregard__c = false 
											AND Admission__r.status__c = 'Active'
											AND Assessment_Type__r.name = 'CANS'];
	   			
	   			system.debug(assessReqNote);
   				devMsg += 'initail scope size = ' + assessReqNote.size();
   				devMsg2 += 'Inital recs:' + Assessment_CANS_Notes_Batch_Ex.getIDfromList(assessReqNote);
			assessReqNote = Assessment_CANS_Notes_Batch_Ex.mostRecentAssessments( assessReqNote);

				system.debug('starting requires email');
				system.debug(assessReqNote);
				devMsg += '<br/> after finding most recent assessment size = ' + assessReqNote.size();
				devMsg2 += 'most recenet recs:' + Assessment_CANS_Notes_Batch_Ex.getIDfromList(assessReqNote);
			// now with the most recent assessment we'll find out if they need an email/task note
			assessReqNote = Assessment_CANS_Notes_Batch_Ex.requiresEmail(assessReqNote);

				system.debug('starting remove inactive users');
				system.debug(assessReqNote);
				devMsg += '<br/> requiring email size = ' + assessReqNote.size();
				devMsg2 += 'req email recs:' + Assessment_CANS_Notes_Batch_Ex.getIDfromList(assessReqNote);

			assessReqNote = Assessment_CANS_Notes_Batch_Ex.removeAndProcessInactiveUsers(assessReqNote );

				system.debug('starting emails');
				system.debug(assessReqNote);				
				devMsg += '<br/> after inactive users removed size = ' + assessReqNote.size();	
				devMsg2 += 'after inactive removed recs:' + Assessment_CANS_Notes_Batch_Ex.getIDfromList(assessReqNote);	

		Assessment_CANS_Notes_Batch b = new Assessment_CANS_Notes_Batch(assessReqNote, devMsg, devMsg2);
		database.executebatch(b);
	}

}