src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorization_Status__c</fullName>
        <description>Facilitates tracking delivery of services immediately, before authorization process is complete, by providing a temporary status.</description>
        <label>Authorization Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to funding source - optional</description>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Authorization_Type__c</fullName>
        <label>Other Authorization Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Authorization_ID__c</fullName>
        <description>ID uniquely identifying an authorized service in the payer&apos;s system.</description>
        <label>Payer Authorization ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Effective_Date__c</fullName>
        <description>Date the authorization is effective according to the payer</description>
        <label>Payer Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer_End_Date__c</fullName>
        <description>=AUTH_END_DATE in Avatar</description>
        <label>Payer End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer_Name__c</fullName>
        <description>Name of payer authorizing the service</description>
        <label>Payer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <description>contract rate for auth</description>
        <label>Rate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_unit__c</fullName>
        <label>Per</label>
        <picklist>
            <picklistValues>
                <fullName>Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_New_Authorization__c</fullName>
        <label>Reason for New Authorization</label>
        <picklist>
            <picklistValues>
                <fullName>New Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Payer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level/Rate Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error on Finalized Authorization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Being_Funded_String__c</fullName>
        <label>Item/Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>1:1 Sitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Holds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Cost Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay - Open Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Authorization_Type__c</fullName>
        <label>Other Authorization Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Being_Funded_String__c</fullName>
        <description>Used to help populate picklist value from UI. DO NOT DISPLAY</description>
        <label>Service Being Funded String</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AuthorizationExt.cls
// Extension class to handle CMAUTH tickets - Sept 2015
public with sharing class AuthorizationExt {

public ID saID { get; set; }
public ID admID { get; set; }
public ID pbsID { get; set; }
public Authorization__c authorization { get; set; }
public List<Funding_Source__c> fsList { get; set; }

public Boolean canEditAuth { get; private set; }
public Boolean canCreateAuth { get; private set; }
public Boolean canFinalize { get; private set; }
public Boolean hasDraft { get; private set;}

public List<Authorization__c> relatedAuthsList { get; set; }
    
public AuthorizationExt(ApexPages.StandardController controller) {

     // service assignment ID is passed in - get the other params needed for personal record connection
    saID = ApexPages.currentPage().getParameters().get('saID');
    
    if ( saID != null ) {
        fsList =  [ select id, name from funding_source__c where service_assignment__c = :saID and status__c != 'Inactive'];
        Service_Assignment__c sa = [ select id, admission__c, admission__r.person_being_served__c from service_assignment__c where id = :saID LIMIT 1];
        if ( sa != null ) {
            admID = sa.Admission__c;
            pbsID = sa.Admission__r.Person_Being_Served__c;
        }
    }
    else
        fsList = new LIst<Funding_Source__c>(); 
    
    if (controller.getId() != null ) {
        authorization = (Authorization__c)controller.getRecord();
        authorization = [ select id, authorization_status__c, type__c, other_authorization_type__c, reason_for_new_authorization__c, service_being_funded_string__c, payer_authorization_id__c,
                            rate__c, received_date_time__c, rate_unit__c, rate_unit_other__c, payer_effective_date__c, payer_end_date__c, funding_source__c, funding_source__r.payer_name__c, contract_used__c, 
                            received_from__c, taken_by__c, level__c, justification__c, representing_received__c,  auth_given_method__c, comments__c, 
                            bed_hold_type__c, bed_hold_type_detail__c, bed_hold_additional_detail__c, bed_hold_classification__c, parent_auth__c, original_auth__c
                            from authorization__c
                            where id = :controller.getRecord().Id ];
    }
    else
        authorization = new Authorization__c();


    Schema.DescribeSObjectResult oSchema = Authorization__c.sObjectType.getDescribe();
    canCreateAuth = oSchema.isCreateable();
    canEditAuth = oSchema.isUpdateable();
    canFinalize = true; //udpate with perms later
    
    hasDraft = false;
    
    // get a list of auths with the same ultimate parent auth   
    relatedAuthsList = [ select id, received_date_time__c, type__c, authorization_status__c, Reason_for_New_Authorization__c, rate__c, rate_unit__c, level__c, payer_effective_date__c, payer_end_Date__c, contract_used__c from authorization__c where original_auth__c = :authorization.original_auth__c and isRootAuth__c = false order by payer_effective_Date__c desc ];    //for ( Authorization__c r : relatedAuthsList) {
    for (Authorization__c r : relatedAuthsList ) {
            
        if ( r.Authorization_Status__c == 'Draft') {
            hasDraft = true;
            break;
        }
    }
    
}
    
    public pageReference editAuth() {
        PageReference pr = new PageReference('/apex/AuthorizationView?id=' + authorization.Id + '&saID=' + saID);
        pr.setRedirect( true);
        return pr;
        
    }
    
    public pageReference saveAuth() {
        System.debug('Before upsert, auth: ' + authorization );
        // When we use Id fields in conjunction with Visualforce's assignTo, it
        // becomes a blank string - which will trigger a system error (because it's
        // not a valid ID)
        if (String.valueOf(authorization.Id) == '') {
            authorization.Id = null;
        }

        try {
            authorization.Authorization_Status__c = 'Inactive Draft';
            upsert authorization;
            
            if ( authorization.original_auth__c == null )
                authorization.original_auth__c = authorization.id;
                
            PageReference pr = new PageReference('/apex/AuthorizationView?id=' + authorization.Id + '&saID=' + saID);
            pr.setRedirect( true);
            return pr;
            
        }
        catch (Exception e) {
            return null;
        }

    }
    
    public PageReference finalizeAuth(){
        try{
            
            // TO DO: check for required fields before finalizing
            // set status to final and save, then redirect to view page
            authorization.Authorization_Status__c = 'Final';  
            authorization.Finalized_at__c = DateTime.Now();
            authorization.Finalized_by__c = UserInfo.getUserId();
            
            upsert authorization;
            PageReference pr = new PageReference('/apex/AuthorizationView?id=' + authorization.Id + '&saID=' + saID);
            pr.setRedirect( true);
            return pr;
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
    
    public PageReference cloneAuth() {
        try {
            Authorization__c newauth = authorization.clone(false, true);
            
            // clear out revision history
            newauth.parent_auth__c = null;
            newauth.original_auth__c = null;
            newauth.person_being_served__c = pbsID;	// set the parent of master-detail
            newauth.authorization_status__c = 'Draft';
            system.debug(newauth);
            upsert newauth;
            PageReference pr = new PageReference('/apex/AuthorizationView?id=' + newauth.Id + '&saID=' + saID);
            pr.setRedirect(true);
            return pr;
        } 
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to clone this authorization.'));
            return null;
        }
    }
    
    public PageReference reviseAuth() {
        try {
            // revision is a clone of the original with Draft status
            Authorization__c newauth = authorization.clone(false, true);
            newauth.Authorization_Status__c = 'Draft';
            
            // link up original to revision
            newauth.Parent_Auth__c = authorization.Id;  //direct parent
            newauth.Original_Auth__c = ( authorization.original_auth__c == null ) ? authorization.ID : authorization.original_auth__c;
            newauth.person_being_served__c= pbsID;
            upsert newauth;
            PageReference pr = new PageReference('/apex/EditAuthorization?id=' + newauth.Id + '&saID=' + saID);
            pr.setRedirect( true);
            return pr;
        } 
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to revise this authorization.'));
            return null;
        }
    }
    
    public pageReference disregardAuth(){
        try{
            // get the auth without any other changes that may be present on the screen
            Authorization__c a = [SELECT Id, Authorization_Status__c FROM Authorization__c WHERE Id =:authorization.Id ]; // To make sure only Status field is in scope.
            a.Authorization_Status__c = 'Disregard';  
            update a;
            PageReference pr = new PageReference('/apex/AuthorizationView?id=' + a.Id + '&saID=' + saID);
            pr.setRedirect(true);
            return pr;
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
            
        
}