src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AccountPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Person Relationship
Delete Me</description>
        <label>AccountPerson</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <description>Interval for the assessment</description>
        <label>Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <description>Indication of the numbered quarter this assessment describes.</description>
        <inlineHelpText>Indication of the numbered quarter this assessment describes.</inlineHelpText>
        <label>Quarterly Assessment Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Assessment_CANSdetail_Ex.cls
public without sharing class Assessment_CANSdetail_Ex {	//keep this without sharing so the quarterly numbering sees all assessments regardless of ownership
    assessment__c assess = new assessment__c();
    
    public Assessment_CANSdetail_Ex(ApexPages.StandardController controller) {
        assess= (assessment__c)controller.getRecord();
        id adminID = apexpages.currentpage().getparameters().get('admission');
        assess.Admission__c = adminID ;
        assess.Assessment_Type__c = apexpages.currentpage().getparameters().get('type');
        
        assess.accountperson__c = [select id, Person_Being_Served__r.Accountid from admission__c where id = :adminID].Person_Being_Served__r.Accountid;
        
        
    }
    
  
    public void getNextQuarter( ) {
    	
    	// if interval is quarterly and it's a new assessment, default to next quarter
    	if ( assess.interval__c == 'Quarterly' && assess.id == null ) {
	    	// get list of other quarterlies for this Admission
	    	List <Assessment__c> otherQ = [select id, quarter__c from assessment__c where admission__c= :assess.Admission__c and Interval__c = 'Quarterly' and disregard__c = false order by quarter__c desc];
	    	decimal lastQ = 0;
	    	
	    	if ( otherQ.size() > 0 ) 
	    		lastQ = otherQ[0].quarter__c;
	    		
	    	assess.quarter__c = lastQ + 1;
    	} else { // either not new or not quarterly
    		if ( assess.interval__c != 'Quarterly')
    			assess.quarter__c = null;
    		// otherwise leave it unchanged
    	}
    	
    }

}