src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract_Document_JO__c.object
<CustomObject>
    <description>A cross-reference object that links contracts with the document profiles for documents expected in the client file for clients associated with that contract.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The document profile for this contract / document cross-reference.</description>
        <inlineHelpText>The document profile for this contract / document cross-reference.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Contract Document JOs</relationshipLabel>
        <relationshipName>Contract_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Document JO</label>
    <nameField>
        <displayFormat>ConDocXref-{0000000}</displayFormat>
        <label>Contract Document JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Document JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase_or_Level__c</fullName>
        <label>Phase or Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Units__c</fullName>
        <description>The number of units of the unit of measure specified for the relative due date value.</description>
        <inlineHelpText>The number of units of the unit of measure specified for the relative due date value.</inlineHelpText>
        <label>Relative Due Date Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The state(s) to which a document is related</description>
        <inlineHelpText>Pick a state(s) to which the document profile will be associated.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Document_Xref__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Program Document Xrefs</relationshipLabel>
        <relationshipName>Program_Document_Xrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program Document Xref</label>
    <nameField>
        <displayFormat>Program_Doc_Xref_{0000000}</displayFormat>
        <label>Program_Document_Xref__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Document Xrefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Contract_JO__c.object
<CustomObject>
    <description>An object to hold records representing Service Assignment / Contract cross-references for the Document Tracker feature.</description>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment for this Service Assignment / Contract cross-reference.</description>
        <inlineHelpText>The Service Assignment for this Service Assignment / Contract cross-reference.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>ServiceAssignment_Contract_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>ServAssgn_Cntrct_JO-{0000000}</displayFormat>
        <label>ServiceAssignment_Contract_JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document_Name__c</fullName>
        <formula>Document__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_From_Employee_Name__c</fullName>
        <formula>Due_From_Employee__r.myFullName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due From Employee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_From_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Status__c</fullName>
        <label>File Status</label>
        <picklist>
            <picklistValues>
                <fullName>Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filed - Not Contract Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - File Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - Document In Initial File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filed - Unrecoverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - Non-FCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Filed_Date_Time__c</fullName>
        <label>Filed Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>N_A_Reason__c</fullName>
        <label>N/A Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ServAssignFidelityChecklistExt.cls
public class ServAssignFidelityChecklistExt  {

    public Service_Assignment__c theServAssign { get; set; }
    public List<ServiceAssignment_Contract_JO__c> servAssignContractXrefs { get; set; }
    public List<Contract_Document_JO__c> contractDocXrefs { get; set; }
    public List<ServiceAssignment_Document_JO__c> servAssignDocXrefs { get; set; }
    public List<Id> docIds { get; set; }
    public List<Document__c> docs { get; set; }
    public List<FidDocWrapper> listOfFidDocFilings { get; set; }
    public String baseUrl { get; set; }
    public Map<Decimal,Integer> numDocsPerPhaseOrLevel { get; set; }
    public Map<Decimal,Integer> numFiledDocsPerPhaseOrLevel { get; set; }
    public Integer thePhase { get; set; }
    public String phaseErrorString { get; set; }
    
    public ServAssignFidelityChecklistExt(ApexPages.StandardController controller) {
        this.theServAssign = (Service_Assignment__c)controller.getRecord();
        
        Service_Assignment__c tempSa = [ SELECT Phase__c FROM Service_Assignment__c WHERE Id = :theServAssign.Id LIMIT 1];
        
        if(tempSA.Phase__c!=null) {
                thePhase = tempSa.Phase__c.intValue();
        }
        
        findFidelityDocs();
        listOfFidDocFilings = new List<FidDocWrapper>();
        
        for(ServiceAssignment_Document_JO__c sadJ : servAssignDocXrefs) {
            listOfFidDocFilings.add(new FidDocWrapper(sadJ));
        }
        
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        
        if(thePhase==null) {
                phaseErrorString = 'You must assign a phase to the Service Assignment before you can check off Fidelity Documents.';
        }
        
    }


    class FidDocWrapper {
        public String docName { get; set; }
        public Integer phzOrLvl { get; set; }
        public String phzOrLvlString { get; set; }
        public Integer order { get; set; }
        public Integer numberOfPhases { get; set; }
        public Boolean selectedFidDoc { get; set; }
        public Boolean selectFidDocStatusBeforeSave { get; set; }
        public Boolean waivedFidDoc { get; set; }
        public Boolean waivedFidDocStatusBeforeSave { get; set; }       
        public String sAOwner { get; set; }
        public String sAOwnerName { get; set; }
        public String fileStatus { get; set; }
        public String fileStatusStyle { get; set; }
        public String fileStatusBeforeSave { get; set; }
        public ServiceAssignment_Document_JO__c sadjToUpdate { get; set; }
        public Datetime filedDateTime { get; set; }
        public String naComment { get; set; }
        public String naCommentBeforeSave { get; set; }
        
        public FidDocWrapper(ServiceAssignment_Document_JO__c sadJ) {         
            
            sAOwner = sadJ.Due_From_Employee__c;
            sAOwnerName = sadJ.Due_From_Employee_Name__c;
            docName = sadJ.Document_Name__c;
                        
            fileStatus = sadJ.File_Status__c;
            if(fileStatus=='Filed') {
                selectedFidDoc = true;
                selectFidDocStatusBeforeSave = true;
            }
            else {
                selectedFidDoc = false;
                selectFidDocStatusBeforeSave = false;
            }
 
             if(fileStatus=='Waived') {
                waivedFidDoc = true;
                waivedFidDocStatusBeforeSave = true;
            }
            else {
                waivedFidDoc = false;
                waivedFidDocStatusBeforeSave = false;
            }           
            
            fileStatusBeforeSave = sadJ.File_Status__c;
            
            naComment = sadJ.N_A_Reason__c;
            naCommentBeforeSave = sadJ.N_A_Reason__c;
            
            sadjToUpdate = sadJ;
            phzOrLvl = sadJ.Document__r.Phase_Or_Level__c.intValue();
            phzOrLvlString = string.valueof(phzOrLvl);
            order = sadJ.Document__r.Order__c.intValue();
            filedDateTime = sadj.Filed_Date_Time__c;       
            
        }
    }
    
    public void addError(String msg) {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, msg));
    }
        
 
    public PageReference findFidelityDocs(){
        
        // A list of the "expected document" xrefs...
        servAssignDocXrefs = new List<ServiceAssignment_Document_JO__c>();
        
        // A list to hold documents...
        List<Document__c> someDocs = new List<Document__c>();
        
        Service_Assignment__c fetchedServAssign = [ SELECT Id, Name, Program__c, Admission__r.state__c, Service_Line__c FROM Service_Assignment__c WHERE Id = :theServAssign.Id LIMIT 1 ]; 
    
        // Select all cross-references between Contracts and this Service Assignment.
        servAssignDocXrefs = [ SELECT Id, Name, Document__c, Document_Name__c, File_Status__c, Relative_Due_Date_Units__c, Relative_Due_Date_UOM__c, 
                                        Relative_Due_Date_Event__c, Relative_Due_Date_Resolved__c, Due_From_Employee__c, Due_From_Employee_Name__c, 
                                        Document__r.Type__c, Document__r.Phase_or_Level__c, Document__r.Order__c, Filed_Date_Time__c, Filed_By__c,
                                        Filed_By__r.Name, N_A_Reason__c
                                FROM ServiceAssignment_Document_JO__c 
                                WHERE Service_Assignment__c = :fetchedServAssign.Id 
                                        AND Document__r.Type__c = 'Fidelity Document'
                                        AND Document__r.State__c = :fetchedServAssign.Admission__r.state__c
                                        AND Document__c IN (SELECT Document__c FROM Program_Document_Xref__c WHERE Program__c = :fetchedServAssign.Program__c)
                                       // AND Document__c IN (SELECT Document__c FROM Program_Document_Xref__c WHERE Service_Line__c = :fetchedServAssign.Service_Line__c)
                                ORDER BY Document__r.Phase_Or_Level__c, Document__r.Order__c ];
       
        docIds = new List<Id>();
        Set<Decimal> uniquePhasesOrLevels = new Set<Decimal>();
        
        for(ServiceAssignment_Document_JO__c sAdJo : servAssignDocXrefs) {
            docIds.add(sAdJo.Document__c);
            uniquePhasesOrLevels.add(sAdJo.Document__r.Phase_Or_Level__c);
        }
        
        numDocsPerPhaseOrLevel = new Map<Decimal,Integer>();
        numFiledDocsPerPhaseOrLevel = new Map<Decimal,Integer>();
        
        for(Decimal pORl : uniquePhasesOrLevels) {
            Integer lvlCounter = 0;
            Integer lvlFiledCounter = 0;
            for(ServiceAssignment_Document_JO__c sxs : servAssignDocXrefs){
                if(sxs.Document__r.Phase_or_Level__c==pORl){
                    lvlCounter++;
                }
                if(sxs.Document__r.Phase_or_Level__c==pORl && (sxs.File_Status__c=='Filed' || sxs.File_Status__c=='Waived')){
                    lvlFiledCounter++;
                }
            }
            numDocsPerPhaseOrLevel.put(pORl,lvlCounter);
            numFiledDocsPerPhaseOrLevel.put(pORl,lvlFiledCounter);
        }
        
        docs = [ SELECT Id, Name FROM Document__c WHERE Id = :docIds ];
        
        return null;
    }
    
    
    public PageReference saveFidDocSelections() {
      
      Savepoint sp = Database.setSavepoint();
      
      try {
          
        List<ServiceAssignment_Document_JO__c> sadjUpdateList = new List<ServiceAssignment_Document_JO__c>(); 
        
        for (FidDocWrapper f : listOfFidDocFilings) {

            if(f.selectedFidDoc==f.selectFidDocStatusBeforeSave && f.waivedFidDoc==f.waivedFidDocStatusBeforeSave){
                //DO NOTHING
            }
            else {
                if(f.selectedFidDoc==true && f.waivedFidDoc==true){
                    ApexPages.Message fileStatusMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'A fidelity document cannot be both filed and waived.  Please check the filing for this document: ' + f.docName);
                    ApexPages.addMessage(fileStatusMessage);
                }
                else if(f.selectedFidDoc==true){
                    f.sadjToUpdate.File_Status__c = 'Filed';    
                }
                else if(f.waivedFidDoc==true) {
                    f.sadjToUpdate.File_Status__c = 'Waived';
                }
                else {
                    f.sadjToUpdate.File_Status__c = 'Not Filed';
                }
                
                f.sadjToUpdate.N_A_Reason__c = f.naComment;
                f.sadjToUpdate.Filed_Date_Time__c = datetime.now();
                f.sadjToUpdate.Filed_By__c = UserInfo.getUserId();
                
                sadjUpdateList.add(f.sadjToUpdate);
            
                ApexPages.Message myMessage = new ApexPages.Message(ApexPages.Severity.INFO, 'Fidelity Document checkoff status change saved: ' + f.docName);
                ApexPages.addMessage(myMessage);
            }
        }
    
        update sadjUpdateList;
           
      }
      catch(DmlException e) {
          addError('Could not save changes: ' + e.getMessage());
          Database.rollback(sp);
      }
  
      findFidelityDocs();
  
      return null;
    }

    public PageReference refreshListOfDocFilings() {

                PageReference pageRef = new PageReference('/apex/ServAssignFidelityChecklist?id=' + theServAssign.Id);
                pageRef.setRedirect(true);
                return pageRef;
/*

        PageReference backToFidCheckPage = new PageReference('/apex/ServAssignFidelityChecklist?id=' + theServAssign.Id);
        return backToFidCheckPage;

        findFidelityDocs();
        listOfFidDocFilings = new List<FidDocWrapper>();
        
        for(ServiceAssignment_Document_JO__c sadJ : servAssignDocXrefs) {
            listOfFidDocFilings.add(new FidDocWrapper(sadJ));
        }
*/
    }

    @RemoteAction
    public static ServiceAssignment_Document_JO__c loadSadjo(string sadjoId) {
        ServiceAssignment_Document_JO__c naCommentSadjo = [SELECT Id, Name, N_A_Reason__c, File_Status__c FROM ServiceAssignment_Document_JO__c WHERE Id= :sadjoId];
        return naCommentSadjo;
    }

    @RemoteAction
    public static void saveSadjoRemote(string sadjoId, string sadjoNaReason, string sadjoFileStatus, Boolean checkStatus) {

      ServiceAssignment_Document_JO__c sadjoForRemoteSave;                                        
      Id sadjToSave;
      
        sadjoForRemoteSave = [SELECT ID, Name, N_A_Reason__c, Document__r.Phase_or_Level__c, Service_Assignment__r.Phase__c FROM ServiceAssignment_Document_JO__c WHERE Id=:sadjoId ];
      
                if(sadjoForRemoteSave.Service_Assignment__r.Phase__c > sadjoForRemoteSave.Document__r.Phase_or_Level__c) {
                        throw new fidException('FAIL!');
                }
                else {
                if(checkStatus==false) {
                        sadjoForRemoteSave.File_Status__c = null;
                        sadjoForRemoteSave.N_A_Reason__c = null;
                }
                else if(sadjoFileStatus=='Filed'){
                        sadjoForRemoteSave.File_Status__c = sadjoFileStatus;
                        sadjoForRemoteSave.N_A_Reason__c = null;                
                }
                else {
                        sadjoForRemoteSave.File_Status__c = sadjoFileStatus;
                        sadjoForRemoteSave.N_A_Reason__c = sadjoNaReason;
                }     
                sadjoForRemoteSave.Filed_by__c = UserInfo.getUserId();        
                sadjoForRemoteSave.Filed_Date_Time__c = Datetime.now();
                
                upsert sadjoForRemoteSave;      
                }
   }

        public class fidException extends Exception {}

}