src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Discharged_Date__c</fullName>
        <label>Discharged Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AccountPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Person Relationship
Delete Me</description>
        <label>AccountPerson</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval__c</fullName>
        <description>Interval for the assessment</description>
        <label>Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <formula>Question_Domain__r.Assessment_Type__r.Id</formula>
        <label>Assessment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>Number of the Question</description>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Assessment_CANS_RPT_ImpAtDischarge.cls
public with sharing class Assessment_CANS_RPT_ImpAtDischarge {

    list<Admission__c> allAdmins = new list<Admission__c>();
    list<Assessment__c> allAssess = new list<Assessment__c>();

    list<integer> QuestionsInScope {
        get{ 
            if(selectedCluster == 'Well-Being'){return Assessment_CANS_Cluster_Defs.WellBeing;}
            if(selectedCluster == 'Behavior & Risk'){return Assessment_CANS_Cluster_Defs.Behavior_AND_Risk;}
            if(selectedCluster == 'Education'){return Assessment_CANS_Cluster_Defs.Education;}
            return null;
        }
    }
//return Assessment_CANS_Cluster_Defs.WellBeing;
    public date StartDate {get; set;}
    public date EndDate {get; set;}
    public string selectedCluster{get; set;}
    public string jsonPersonRowData{get; set;}
    public string jsonStateData{get; set;}
    public integer PBScount {get; set;}

    public Assessment_CANS_RPT_ImpAtDischarge() {
        //runRpt();
    }

    public PageReference runRpt(){
        //StartDate = system.today().addDays(-1000);
        //EndDate = system.today();
        buildRpt();
        return null;
        
    }

    public void buildRpt(){
        // this list should be order ASC by admission effective date so that when the items are put in the map the most recent one is put last (it will override any preivous entires)
        list<AggregateResult> statesWithIntakeAssess = [select Admission__r.State__c
                                        from Assessment__c 
                                        where Interval__c = 'Intake' 
                                        and assessment_type__r.name = 'CANS'
                                        and disregard__c = false
                                        group by Admission__r.state__c];
        
        map<string, StateRowData> mapStateRowData = new map<string, StateRowData>();
        for(AggregateResult item : statesWithIntakeAssess){
            string state =  string.valueof(item.get('state__c'));
            mapStateRowData.put(state, new StateRowData(state));
        }
        //this is for column Number of PBS Discharged per state
        list<AggregateResult> intakeAssess = [select Admission__r.state__c, count(name) myCount
                                                from Assessment__c 
                                                    where Interval__c = 'Intake' 
                                                        AND Admission__r.Status__c = 'Discharged'
                                                        AND assessment_type__r.name = 'CANS'
                                                        AND Admission__r.Discharged_Date__c >= :StartDate
                                                        AND Admission__r.Discharged_Date__c <= :EndDate

                                                    group by Admission__r.state__c

                                                    ];                                                  

        for(AggregateResult item : intakeAssess){
            string state =  string.valueof(item.get('state__c'));
            mapStateRowData.get(state).NumberPBSDisCharge = integer.valueof(item.get('myCount'));
        }


        list<Assessment__c> disChargeAssess = [select id, name, AccountPerson__r.Id, Admission__r.State__c
                                                from Assessment__c 
                                                where Interval__c = 'Discharge' 
                                                    AND assessment_type__r.name = 'CANS'
                                                    AND Assessment_Date__c >= :StartDate 
                                                    AND Assessment_Date__c <= :EndDate

                                                    ];

        map<string, PersonRowData> mapPersonRowData = new map<string, PersonRowData>();
        set<id> disChargeAssessPBSes = new set<id>();
        for(Assessment__c item : disChargeAssess){
            mapPersonRowData.put(item.AccountPerson__r.Id, new PersonRowData(item.AccountPerson__r.Id, item.Admission__r.State__c));
            mapStateRowData.get(item.Admission__r.State__c).NumberPBSDisChargeWithCANS +=1;
            disChargeAssessPBSes.add(item.AccountPerson__r.Id);
        }

        list<AggregateResult> intakeAssessScore = [select sum(score__c) score, Assessment__r.AccountPerson__r.Id 
                                                            from Assessment_Response__c 
                                                                Where Assessment__r.AccountPerson__r.Id IN : disChargeAssessPBSes 
                                                                    AND Assessment__r.Interval__c = 'Intake'
                                                                    AND Question__r.Question_Number__c IN :QuestionsInScope
                                                                    AND Assessment__r.assessment_type__r.name = 'CANS'

                                                                    Group By Assessment__r.AccountPerson__r.Id
                                                                    ];
        list<AggregateResult> disChargeAssessScore = [select sum(score__c) score, Assessment__r.AccountPerson__r.Id 
                                                            from Assessment_Response__c 
                                                                Where Assessment__r.AccountPerson__r.Id IN : disChargeAssessPBSes 
                                                                    AND Assessment__r.Interval__c = 'Discharge'
                                                                    AND Question__r.Question_Number__c IN :QuestionsInScope
                                                                    AND Assessment__r.assessment_type__r.name = 'CANS'

                                                                    Group By Assessment__r.AccountPerson__r.Id
                                                                    ];      

        for(AggregateResult item : intakeAssessScore){
            string theKey = string.valueof(item.get('ID'));
            mapPersonRowData.get(theKey).IntakeScore = integer.valueof(item.get('score'));
        }
        for(AggregateResult item : disChargeAssessScore){
            string theKey = string.valueof(item.get('ID'));
            mapPersonRowData.get(theKey).disChargeScore = integer.valueof(item.get('score'));
        }

        for(PersonRowData item : mapPersonRowData.values()) {
            if(item.disChargeScore > item.IntakeScore){mapStateRowData.get(item.state).NumberPBSWithImprovement += 1;}
        }

        for(StateRowData item : mapStateRowData.values()){
            if(item.NumberPBSDisChargeWithCANS != 0){
                item.PercentPBSWithImprovement = (decimal.valueof(item.NumberPBSWithImprovement) / decimal.valueof(item.NumberPBSDisChargeWithCANS)).setScale(4);
                item.PercentPBSWithImprovement = item.PercentPBSWithImprovement * 100;
                item.PrettyPercentPBSWithImp = string.valueof(item.PercentPBSWithImprovement) + '%';
            }
        }   
        jsonStateData = JSON.serializePretty(mapStateRowData.values());
        jsonPersonRowData = JSON.serializePretty(mapPersonRowData.values());

    }


    public class PersonRowData{
        public string State;
        public string PBS;
        public integer IntakeScore;
        public integer disChargeScore;



        public PersonRowData(string PBSID, string var_state){
                IntakeScore = 0;
                disChargeScore = 0;
                PBS = PBSID;
                state = var_state;
            
        }   
    }

    public class StateRowData{
        public string State;
        public integer NumberPBSDisCharge;
        public integer NumberPBSDisChargeWithCANS;
        public integer NumberPBSWithImprovement;
        public decimal PercentPBSWithImprovement;
        public string PrettyPercentPBSWithImp;


        public StateRowData(string var_State){
            state = var_State;
            NumberPBSDisCharge = 0;
            NumberPBSDisChargeWithCANS = 0;
            NumberPBSWithImprovement = 0;
            PercentPBSWithImprovement = 0;
        }
    }





    

}