src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Domain__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessment Domains</relationshipLabel>
        <relationshipName>Assessment_Domains</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Domain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <formula>Question_Domain__r.Assessment_Type__r.Id</formula>
        <label>Assessment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Description__c</fullName>
        <description>Description of the Question</description>
        <label>Question Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Title__c</fullName>
        <description>Title of the Question</description>
        <label>Question Title</label>
        <type>TextArea</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score entered by user</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Response__c.object
<CustomObject>
    <description>COMPLIANCE SURVEY Stores all the individual completed survey for a compliance survey</description>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <description>User operating group</description>
        <inlineHelpText>Redwood, Cambridge, NeuroRestorative, CareMeridian, Corporate</inlineHelpText>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>Cambridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CareMeridian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NeuroRestorative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redwood</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed with Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed with Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed without Exceptions</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Response</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction_Queue__c.object
<CustomObject>
    <description>Stores requests from user without permissions to be fulfilled by a login with higher auth</description>
    <fields>
        <fullName>Input_Params__c</fullName>
        <description>name/value pair of input vars.  json format</description>
        <label>Input Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Action Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill Worksheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acknowledge Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Date_Time__c</fullName>
        <description>Date/time the initial request was made</description>
        <label>Requested Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requesting_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>user id that requested txn</description>
        <label>Requesting User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transaction_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Queue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Assessment_RiskFormWithoutSharing_Test.cls
@isTest
private class Assessment_RiskFormWithoutSharing_Test {
    private static TMN_Generic_Core_TestData myData;
    
    static testMethod void myUnitTestForInvalidTxn() {
        User tester = Referral_createTestData.createTestUser(
            'astest', 'astest@test.com', 'Action', 'Summary', 'Redwood'
        );
        tester.Operating_Group__c = 'Redwood';
        update tester;
        System.runAs(tester) {
            createData();
            myData.loadData('MN');
            Transaction_Queue__c txn  = new Transaction_Queue__c( requesting_user__c = UserInfo.getUserId());
            txn.request_type__c = 'Risk';
            txn.requested_date_time__c = DateTime.Now();
            txn.input_params__c = string.valueOf(string.valueOf(myData.theAdm.Id));
            try {
                insert txn;  // a dmlException will be thrown here since there is no Risk assessment created yet. 
                PageReference pageRef = Page.DSP_Assessment_RiskForm;
                Test.setCurrentPage(pageRef);
                pageRef.getParameters().put('txnID', txn.ID);
                TxnQueueResponseController controller = new TxnQueueResponseController();
                throw new DataCreateException('We should have never come to this line of code.');
            } catch(DMLException e) {
                system.assert(true);
            } catch(Exception e) {
                throw e ;
            } 
        }
    }
    public class DataCreateException extends Exception{
    } 
    static testMethod void myUnitTest() {
        User tester = Referral_createTestData.createTestUser(
            'astest', 'astest@test.com', 'Action', 'Summary', 'Redwood'
        );
        tester.Operating_Group__c = 'Redwood';
        update tester;
        System.runAs(tester) {
            createData();
            myData.loadData('MN');
            
            //create RISK assessment
	        Assessment_Type__c testAssmtType = new Assessment_Type__c(
	            Name = 'RISK'           
	        );
	        insert testAssmtType;
	        
	        Assessment_Domain__c testDomain = new Assessment_Domain__c(
	            Name = 'TEST DOMAIN',
	            Assessment_Type__c = testAssmtType.Id
	        );
	        insert testDomain;
	        
	        Assessment_Question__c testQuestion = new Assessment_Question__c(
	            Question_Title__c = 'TEST QUESTION',
	            Question_Description__c = 'A TEST QUESTION',
	            Question_Domain__c = testDomain.Id
	        );
	        insert testQuestion;
	   
	        Assessment__c assessment = new assessment__c(Assessment_Type__c = testAssmtType.id, Admission__c = myData.theAdm.id, Assessment_Date__c = myData.theSA.Start_Date__c, Service_Assignment__c = myData.theSA.id);      
	        insert (assessment);
        
            List<Assessment_Response__c> ars = [ SELECT Response__c, Rating__c FROM Assessment_Response__c WHERE Assessment__c = : assessment.Id ];
            for(Assessment_Response__c ar : ars) {
                ar.Response__c = 'TEST';
                ar.Rating__c = 'Presents a Risk';
            }
            update ars;
            assessment.Status__c = 'Active Final';
            assessment.Approval_Date__c = date.newInstance(2014, 01, 01);
            update assessment;
            
            Transaction_Queue__c txn  = new Transaction_Queue__c( requesting_user__c = UserInfo.getUserId());
            txn.request_type__c = 'Risk';
            txn.requested_date_time__c = DateTime.Now();
            txn.input_params__c = string.valueOf(string.valueOf(myData.theAdm.Id));
            
            insert txn;  
            PageReference pageRef = Page.DSP_Assessment_RiskForm;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('txnID', txn.ID);
            TxnQueueResponseController controller = new TxnQueueResponseController();

            system.assert(controller.assessmentResponse != null);
            system.assert(controller.assessmentResponse.getMapCurrentResps() != null);
            system.assert(controller.assessmentResponse.getAssessmentWrapper() != null);
            system.assert(controller.assessmentResponse.getMapQuestions() != null);
            system.assert(controller.assessmentResponse.getDomainsInScope().size() > 0);
            
            system.assert(controller.assessmentResponse.getLevel_Required_ResidentialServices().size() == 0);
            system.assert(controller.assessmentResponse.getLevel_Required_DayServices().size() == 0);
            
            DSPSubmitTxn extension = new DSPSubmitTxn(controller);
            pageRef = extension.ackAssessment();
            Test.setCurrentPage(pageRef);
            controller = new TxnQueueResponseController();
            extension = new DSPSubmitTxn(controller);
            
            // assert that the ack recrod exists for this assessment, and the page after ACK was indeed the Risk page.
            system.assert(pageRef.getRedirect());
            system.assert(pageRef.getUrl().containsIgnoreCase('DSP_Assessment_RiskForm'));
            system.assert(controller.assessmentResponse.ackwrapList.size() == 1);
            
            
        }
    }
    
    private static void createData(){
        myData = new TMN_Generic_Core_TestData();
    }
    
}