src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who approved this assessment?</description>
        <label>Finalized By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Question_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Title__c</fullName>
        <description>Title of the Question</description>
        <label>Question Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>external_id__c</fullName>
        <externalId>true</externalId>
        <label>external id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Assessment_AbstractForm.cls
public abstract class Assessment_AbstractForm {
    protected list<string> selectFields = new list<string>();
    protected list<string> selectFieldsAssessResp = new list<string>();	
    protected Assessment__c assessment { get; set; }
	
	protected Assessment_AbstractForm(Id assessmentId){
	    // Get a map of field name and field token
        Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get('Assessment__c').getDescribe().Fields.getMap();
        if (fMap != null) {
            for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
                Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                    selectFields.add(fd.getName());
            }
        }
        selectFields.addAll(new List<String>{ 'Admission__r.Name', 'Admission__r.State__c', 'LastModifiedBy.Name', 'CreatedBy.Name', 'Approved_By__r.Name', 'Admission__r.Person_Being_Served__r.Name'});
        String strSQL =  'SELECT ' + String.join(selectFields, ',') + ' FROM Assessment__c WHERE Id = \'' + assessmentId + '\'';
        this.assessment = (Assessment__c) Database.query(strSQL)[0];


        fMap = Schema.getGlobalDescribe().get('Assessment_Response__c').getDescribe().Fields.getMap();
        if (fMap != null) {
            for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
                Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                    selectFieldsAssessResp.add(fd.getName());
            }
        }
        selectFieldsAssessResp.addAll(new List<String>{'Question__r.External_Id__c', 'Question__r.Question_Domain__c', 'Question__r.Question_Title__c'});
    }

    protected void updateMapWithRelationshipKeys(Map<String, Object> m, String jsonString, String relationshipKey){
            Map<String, Object> temp = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            Map<String, Object> newMap = new Map<String, Object>(); 
            for(String k : temp.keySet()){
                if(k.endsWithIgnoreCase('__r') || k == 'LastModifiedBy' || k == 'CreatedBy') updateMapWithRelationshipKeys(m, JSON.serialize(temp.get(k)), k);
                else {
                    if (String.IsBlank(relationshipKey) ) newMap.put(k, temp.get(k));
                    else newMap.put(relationshipKey + '.' + k,  temp.get(k));
                }
            }
            m.putAll(newMap);
            m.remove(String.IsBlank(relationshipKey) ? 'attributes' : relationshipKey + '.attributes'); // this is to remove this key, SF adds this when serializing the sObject.
    }
    
    
}