src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <description>The official date for this assessment.</description>
        <inlineHelpText>The official date for this assessment.</inlineHelpText>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Question_Title__c</fullName>
        <description>Title of the Question</description>
        <label>Question Title</label>
        <type>TextArea</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score entered by user</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Report_CANS_ActionableItems.cls
public with sharing class Report_CANS_ActionableItems {
	public List<Assessment_Response__c> responses { get {
		return Database.query('SELECT Id, Name, Rating__c, Question__r.Question_Title__c, CreatedBy.Name, CreatedById, Assessment__r.Owner.Id, Assessment__r.Owner.Name, Assessment__r.Assessment_Date__c, Assessment__r.Id, Assessment__r.Name, Assessment__r.Admission__r.Person_Being_Served__r.Name, Assessment__r.Admission__r.Person_Being_Served__r.Id FROM Assessment_Response__c WHERE ' + scoreQuery);
	} set; }
	public String scoreQuery = '';
	public String scoreChosen { get;
		set {
			if (value == '2 or 3') {
				scoreQuery = 'Rating__c = \'2\' OR Rating__c = \'3\'';
			} else {
				scoreQuery = 'Rating__c = \'3\'';
			}
			scoreChosen = value;
		}
	}
	public List<SelectOption> scoreOptions {
		get {
			List<SelectOption> options = new List<SelectOption>();
			options.add(new SelectOption('2 or 3', '2 or 3'));
			options.add(new SelectOption('Only 3', 'Only 3'));
			return options;
		}
	}
}