src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Used in Apex and VisualForce for item like Drop-downs menus.  Allows central management.</description>
        <formula>Name &amp;
&apos; - &apos; &amp;
TEXT(MONTH(Payer_Effective_Date__c))  &amp; &apos;/&apos; &amp;
TEXT(DAY(Payer_Effective_Date__c))  &amp;  &apos;/&apos; &amp;
TEXT(YEAR(Payer_Effective_Date__c))  &amp;
&apos; - &apos; &amp;
TEXT(MONTH(Payer_End_Date__c))  &amp; &apos;/&apos; &amp;
TEXT(DAY(Payer_End_Date__c))  &amp;  &apos;/&apos; &amp;
TEXT(YEAR(Payer_End_Date__c))  &amp;
&apos; - &apos; &amp;
&apos; ($ &apos; &amp;
 TEXT(Remaining_Dollars__c) &amp;
&apos; ) &apos; &amp;
&apos; (U  &apos; &amp;
 TEXT( Remaining_Units__c ) &amp;
&apos; ) &apos; &amp;
&apos; ( V &apos; &amp;
 TEXT( Remaining_Visits__c ) &amp;
&apos; ) &apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Effective_Date__c</fullName>
        <description>Date the authorization is effective according to the payer</description>
        <label>Payer Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer_End_Date__c</fullName>
        <description>=AUTH_END_DATE in Avatar</description>
        <label>Payer End Date</label>
        <type>Date</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Authorization_ServiceCode_JO__c.object
<CustomObject>
    <description>Notes - Joins an auth to a service code</description>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <referenceTo>Authorization__c</referenceTo>
        <relationshipLabel>Authorization Service Codes</relationshipLabel>
        <relationshipName>Authorization_ServiceCode_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Authorization ServiceCode JOs</relationshipLabel>
        <relationshipName>Authorization_ServiceCode_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Service_Value__c</fullName>
        <formula>Service_Code__r.Service_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Value</label>
        <type>Text</type>
    </fields>
    <label>Authorization ServiceCode JO</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Authorization ServiceCode JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorization ServiceCode JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The authorized service which was utilized to deliver the service on which progress is being documented.</description>
        <label>Authorization</label>
        <referenceTo>Authorization__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DocDueFromPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field to store the primary case document due from person.</description>
        <inlineHelpText>A field to store the primary case document due from person.</inlineHelpText>
        <label>DocDueFromPerson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SA_Start_DateTime__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Value__c</fullName>
        <label>Service Value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_ServiceCode_JO__c.object
<CustomObject>
    <description>Notes - joins a service assignment to a code</description>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment Service Code JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Service_Code_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>ServiceAssignment Service Code JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Service_Code_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>ServiceAssignment Service Code JO</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ServiceAssignment Service Code JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceAssignment Service Code JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Notes_ProgressNote_Svc_Code_Selection.cls
public with sharing class Notes_ProgressNote_Svc_Code_Selection {
    public Progress_Note__c CurrentRecord {get; set;}
    public string dispMode{get;set;}
    public Notes_ProgressNote_Svc_Code_Selection(ApexPages.StandardController controller) {
    	//Added by amruth for EB-513
        dispMode = ApexPages.currentPage().getParameters().get('Mode');
        if(dispMode != 'New'){
            loadData((Progress_Note__c)Controller.getRecord());
        }
    } 
    public void loadData(Progress_Note__c localRecord){
        CurrentRecord = [Select Service_Assignment__c,Service_Assignment__r.SA_Start_DateTime__c, Approval_User__c, Service_Code__c, Admission__c, start_time__c,recordtype.Name From Progress_Note__c Where ID = :localRecord.id Limit 1];
    }
    public List<SelectOption> Codes = new List<SelectOption>();
    public List<SelectOption> getCodes(){
    	//Added by amruth for EB-513
    if(dispMode != 'New'){
        loadData(CurrentRecord);
        Codes.clear();
        SelectOption SOtmp = new SelectOption('', '--None--');
        Codes.Add(SOtmp);
        for(Service_code__c local : 
                    [SELECT Id, Service_Code__c, Service_Value__c From Service_Code__c
                    where id in (select service_code__c from ServiceAssignment_ServiceCode_Jo__c where service_assignment__c = :currentRecord.Service_Assignment__c)
                    and start_date__c <= :Date.valueOf(CurrentRecord.Start_Time__c) and (end_date__c = null or end_date__c >= :Date.valueOf(CurrentRecord.Start_Time__c))  
                    ])
            {  SelectOption SO = new SelectOption(local.ID, local.Service_Value__c);
                Codes.Add(SO);
            }
        
      }else if(dispMode == 'New'){
           id ServAssignId ;
           servAssignId = ApexPages.currentPage().getParameters().get('ServAssignId');
           service_assignment__c sa = [select id, SA_Start_DateTime__c from service_assignment__c where Id =: servAssignId ];
           Codes.clear();
            SelectOption SOtmp = new SelectOption('', '--None--');
            Codes.Add(SOtmp);
           for(Service_code__c local : 
                    [SELECT Id, Service_Code__c, Service_Value__c From Service_Code__c
                    where id in (select service_code__c from ServiceAssignment_ServiceCode_Jo__c where service_assignment__c = : servAssignId )
                    and start_date__c <= : Date.valueof(System.now()) and (end_date__c = null or end_date__c >= :Date.valueOf(System.now()))  
                    ])
            {  SelectOption SO = new SelectOption(local.ID, local.Service_Value__c);
                Codes.Add(SO);
            }
      }  
        return Codes;
    }
    
    public List<SelectOption> Auths = new List<SelectOption>();
    public List<SelectOption> getAuths(){
        Auths.clear();
        SelectOption SOtmp = new SelectOption('', '--None--');
        Auths.Add(SOtmp);
        //Added by amruth for EB-513
        if(dispMode != 'New'){
            loadData(CurrentRecord);
        
        
            System.Debug( 'START_TIME=' + CurrentRecord.Start_Time__c);
            
            // CTEAE-50 03/11/14 - make sure auth dates are valid for date of service.  User Start Time field as DOS is not calculated until save
            for(Authorization_ServiceCode_Jo__c local : 
                    [Select Service_Code__r.ID, Service_Code__r.Service_Value__c, Authorization__c, Authorization__r.Display_Name__c
                        From Authorization_ServiceCode_Jo__c 
                            Where Service_Code__c = :currentRecord.Service_Code__c 
                            AND Authorization__r.Admission__c = :currentRecord.Admission__c
                            and Authorization__r.Payer_Effective_Date__c <=:currentRecord.Start_Time__c.date()  
                            and Authorization__r.Payer_End_Date__c >= :currentRecord.Start_Time__c.date() 
                            ])
            {                                   
                SelectOption SO = new SelectOption(local.Authorization__c, local.Authorization__r.Display_Name__c);
                Auths.Add(SO);
            }        
        }return Auths ;
    }    
}