src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location_Region__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <recordTypes>
        <fullName>Assessment_Only</fullName>
        <active>true</active>
        <description>This option is for Assessment Only Service Assignments. There will be no Plan/STGs.</description>
        <label>Assessment Only</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>Assessment_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assessment Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_ServiceCode_JO__c.object
<CustomObject>
    <description>Notes - joins a service assignment to a code</description>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment Service Code JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Service_Code_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>ServiceAssignment Service Code JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Service_Code_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>ServiceAssignment Service Code JO</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ServiceAssignment Service Code JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceAssignment Service Code JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Notes_ServAssign_CodeSel_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Notes_ServAssign_CodeSel_TEST {

    static testMethod void myUnitTest() {
             
        Contact testContact = new Contact(
    		LastName = 'TestLastName'
    	);
    	insert testContact;
    	
    	Admission__c testAdm = new Admission__c(
            Name = 'TEST ADM',
            Person_Being_Served__c = testContact.Id,
            Effective_Date__c = date.today(),
            state__c = 'NC'
    	);
    	insert testAdm;
        
        Service_Assignment__c testServAssignment = new Service_Assignment__c(
        	Admission__c = testAdm.Id,
        	Person_Being_Served__c = testContact.Id,
        	Program__c = 'TEST PROGRAM',
        	Location_Region__c = 'TEST LOCATION'
        );
        insert testServAssignment;
  
  
  		RecordType assessID = [Select id, developername from recordtype where developername='Assessment_only' limit 1];
        Service_Assignment__c testServAssignmentAssess = new Service_Assignment__c(
        	Admission__c = testAdm.Id,
        	Person_Being_Served__c = testContact.Id,
        	Program__c = 'TEST PROGRAM',
        	Location_Region__c = 'TEST LOCATION',
        	RecordTypeID = assessID.Id 
        );
        insert testServAssignmentAssess;
              
        Service_Code__c testServCode = new Service_Code__c(
        	Service_Code__c = 'TEST SVC CODE',
        	FacilityID__c = 'TEST FAC ID',
        	Program_Code__c = 'TEST PROGRAM CODE',
        	Program__c = 'TEST PROGRAM',
        	Location__c = 'TEST LOCATION',
        	Service_Line__c = 'TEST SERVICE LINE',
        	start_Date__c = date.newinstance(2012,1,1) ,
        	state__c = 'NC'
        	        );
        insert testServCode;
        
        Service_Code__c testServCode2 = new Service_Code__c(
        	Service_Code__c = 'TEST SVC CODE-OH',
        	FacilityID__c = 'TEST FAC ID-OH',
        	Program_Code__c = 'TEST PROGRAM CODE-OH',
        	Program__c = 'TEST PROGRAM-OH',
        	Location__c = 'TEST LOCATION-OH',
        	Service_Line__c = 'TEST SERVICE LINE-OH',
        	start_Date__c = date.newinstance(2012,1,1) ,
        	state__c = 'OH'
        	        );
        insert testServCode2;
        
        
        ServiceAssignment_ServiceCode_JO__c testSASCJO = new ServiceAssignment_ServiceCode_JO__c(
        	Service_Code__c = testServCode.Id,
        	Service_Assignment__c = testServAssignment.Id
        );
        insert testSASCJO;
        
        
        PageReference pageRef = Page.Notes_ServiceAssignment_CodeSelection;
        Test.setCurrentPageReference(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testServAssignment);
        Notes_ServiceAssignment_CodeSelection objTestNSACS = new Notes_ServiceAssignment_CodeSelection(sc);
        
        // add the JO refrence to the SA object
        objTestNSACS.currentRecord = testServAssignment;
        objTestNSACS.currentState = objTestNSACS.currentRecord.Admission__r.state__c; 
        objTestNSACS.SelectedCodeID = testServCode.Id;
        objTestNSACS.SelectedJoID = testSASCJO.Id;
        objTestNSACS.CreateCodeJO();
        
        // get current service codes - should be 2 including --NONE--
        objTestNSACS.getCurrentCodes();
        system.debug ('Available Codes: ' +objTestNSACS.CurrentCodes);
        system.debug( 'My Locations: ' + objtestNSACS.MyLocations);
        
        System.AssertEquals( objTestNSACS.CurrentCodes.Size(), 2);
        
        // get available service codes - should be 0
        objTestNSACS.getMyServiceCodes();
        System.AssertEquals( objTestNSACS.MyServiceCodes.Size(), 0);
        
        // get current programs - should be 2 including --NONE--
        objTestNSACS.getMyPrograms();
        System.AssertEquals( objTestNSACS.myPrograms.size(), 2);
        
        // get current locations - should be 1 including --NONE--
        objTestNSACS.getMyLocations();
        System.AssertEquals( objTestNSACS.myLocations.size(), 1);
        
        // now delete the JO
        objTestNSACS.DeleteCodeJO();
        system.debug ( 'My Codes: ' + objTestNSACS.MyServiceCodes );
        
        // re test size
        // get current service codes - should be 1 including --NONE--
        objTestNSACS.getCurrentCodes();
        System.AssertEquals( objTestNSACS.CurrentCodes.Size(), 1);
        system.debug ( 'Available codes: ' + objTestNSACS.currentCodes );
        
        
        // add the JO refrence to the SA object
        objTestNSACS.currentRecord = testServAssignmentAssess;
        objTestNSACS.currentState = objTestNSACS.currentRecord.Admission__r.state__c; 
		objTestNSACS.assessmentonly = true;
		objTestNSACS.getMyLocations();
        System.AssertEquals(objTestNSACS.myLocations.size(), 1 );
        
            Service_Code__c testServCode3 = new Service_Code__c(
        	Service_Code__c = 'TEST SVC CODE- ASSESS',
        	FacilityID__c = 'TEST FAC ID-ASSESS',
        	Program_Code__c = 'TEST PROGRAM CODE-ASSESS',
        	Program__c = 'TEST PROGRAM-ASSESS',
        	Location__c = 'TEST LOCATION-ASSESS',
        	Service_Line__c = 'TEST SERVICE LINE-ASSESS',
        	start_Date__c = date.newinstance(2012,1,1) ,
        	state__c = 'NC',
        	assessment_only__c = true
        	        );
        insert testServCode3;
        
        
        objTestNSACS.selectedCodeID = testServCode3.id;
		objTestNSACS.CreateCodeJO();        
        
		objTestNSACS.getMyLocations();
        System.AssertEquals(objTestNSACS.myLocations.size(), 1 );
        
        
        
    }
}