src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Discharged_Date__c</fullName>
        <label>Discharged Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharged_Status__c</fullName>
        <label>Discharged Status</label>
        <picklist>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neutral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Discharge__c</fullName>
        <label>Reason for Discharge</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Intervention__c.object
<CustomObject>
    <description>NOTES Interventions are the actual things done to meet an Objective under a Plan. Interventions are related to a Plan by way of Objectives. Interventions are master-detail to Objectives.</description>
    <fields>
        <fullName>Objective__c</fullName>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_term_Goal__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The parent objective which this intervention contributes to achieving</description>
        <label>Short-term Goal</label>
        <referenceTo>Short_Term_Goal__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>I-{000000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Objective__c.object
<CustomObject>
    <description>NOTES Objectives represent the milestones needed to complete a Short-term Goal on a Plan. Objectives relate to Plans by way of Short-term Goals. Objectives are Master-detail to Short-term Goals.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>PlanObjectives</relationshipLabel>
        <relationshipName>PlanObjectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_term_Goal__c</fullName>
        <label>Short-term Goal</label>
        <referenceTo>Short_Term_Goal__c</referenceTo>
        <relationshipLabel>Objectives</relationshipLabel>
        <relationshipName>Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Objective Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>NOTES Plan object is Master-detail to Persons Being Served. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_term_Goal_1__c</fullName>
        <label>Long-term Goal 1</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <description>A short summary of the plan</description>
        <label>Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_term_Goal_1__c</fullName>
        <label>Long-term Goal 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Short_Term_Goal__c.object
<CustomObject>
    <description>NOTES Short-term Goals are the goals defined to achieve the Long-term Goals on a Plan. Short-term Goals are Master-detail to Plans. (PENDING SECURITY MODEL FINALIZATION)</description>
    <fields>
        <fullName>Admission__c</fullName>
        <formula>Plan__r.Admission__c</formula>
        <label>Admission</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <formula>Plan__r.Plan_Name__c</formula>
        <label>Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>The plan and long-term goals that this short-term goal supports.</description>
        <inlineHelpText>The plan and long-term goals that this short-term goal supports.</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Short-term Goals</relationshipLabel>
        <relationshipName>Short_Term_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Term_Goal_Description__c</fullName>
        <description>A detailed description of the short term goal.</description>
        <label>Short Term Goal Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Ended Prior to Completion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Short-term Goal</label>
    <nameField>
        <label>Short-term Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Short-term Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/V2SA_ConstructSTG_Test.cls
/**
    Test class for controller V2SA_ConstructSTG.cls (Plan Management)
 */
@isTest
private class V2SA_ConstructSTG_Test {

    static testMethod void myUnitTest() {
      Date startDate = Date.today();
        Date endDate = Date.today().addDays(50);
        
        //Creation of Contact (person being served)
        Contact objContactServed = new Contact();
        objContactServed.FirstName = 'Test Person';
        objContactServed.LastName = 'Served';
        insert objContactServed;
        
        // Creation of Admission
        Admission__c objAdmission = new Admission__c();
        objAdmission.Name = 'Test Admission';
        objAdmission.Person_Being_Served__c = objContactServed.Id;
        objAdmission.Discharged_Date__c = system.today();
        objAdmission.Status__c = 'Discharged';
        objAdmission.Reason_for_Discharge__c ='just because';
        objAdmission.Discharged_Status__c = 'Positive';
        insert objAdmission;
        
        Admission__c objAdmission2 = new Admission__c();
        objAdmission2.Name = 'Test Admission';
        objAdmission2.Person_Being_Served__c = objContactServed.Id;
        
        insert objAdmission2;        
        
        // Creation of Plan
        Plan__c objPlan = new Plan__c();
        objPlan.Plan_Name__c = 'Test Plan';
        objPlan.Admission__c = objAdmission.Id;
        objPlan.Person_Being_Served__c = objContactServed.Id;
       // objPlan.Status__c = 'Active';
        objPlan.Status__c = 'Inactive';
        objPlan.Long_term_Goal_1__c = '1245dfgsd';
        insert objPlan;
        
        Plan__c objPlan2 = new Plan__c();
        objPlan2.Plan_Name__c = 'Test Plan';
        objPlan2.Admission__c = objAdmission.Id;
        objPlan2.Person_Being_Served__c = objContactServed.Id;
        objPlan2.Status__c = 'Inactive';
        objPlan2.Read_Only__c = true;
        objPlan2.Long_term_Goal_1__c = '1245dfgsd';
        insert objPlan2;



        
                
        
        // Creation of Service Assignments(select list options) - lookup to Admission
        Service_Assignment__c objServAssignment1 = new Service_Assignment__c();
        objServAssignment1.Name = 'Test Service Assignment1';
        objServAssignment1.Admission__c = objAdmission2.Id;
        objServAssignment1.Person_Being_Served__c = objContactServed.Id;
        insert objServAssignment1;
        
        Service_Assignment__c objServAssignment2 = new Service_Assignment__c();
        objServAssignment2.Name = 'Test Service Assignment2';
        objServAssignment2.Admission__c = objAdmission2.Id;
        objServAssignment2.Person_Being_Served__c = objContactServed.Id;
        insert objServAssignment2;
        
        Service_Assignment__c objServAssignment3 = new Service_Assignment__c();
        objServAssignment3.Name = 'Test Service Assignment3';
        objServAssignment3.Admission__c = objAdmission2.Id;
        objServAssignment3.Person_Being_Served__c = objContactServed.Id;
        insert objServAssignment3;
        
        // Creation of Objective (Short-term Goal) - lookup to Plan
        Short_Term_Goal__c objObjective = new Short_Term_Goal__c();
        objObjective.Name = 'Test Short-term Goal Name';
        objObjective.Short_Term_Goal_Description__c = 'Test Short-term Goal Description';
        objObjective.Plan__c = objPlan.Id;
        insert objObjective;
        
        // Creation of Plan Objective - lookup to Short Term Goal
        Objective__c objPlanObjective = new Objective__c();
        objPlanObjective.Short_Term_Goal__c = objObjective.Id;
        insert objPlanObjective;
        
        //Creation of Intervention - lookup to Objective (Short-term Goal)
        Intervention__c objIntervention = new Intervention__c();
        objIntervention.Short_Term_Goal__c = objObjective.Id;
        objIntervention.Objective__c = objPlanObjective.Id;
        insert objIntervention;
        
        System.currentPageReference().getParameters().put('id', objPlan.Id);
        V2SA_ConstructSTG stg = new V2SA_ConstructSTG();
       
        stg.Nothing();
        stg.CheckExternalPlan();
        stg.backExternal();
        stg.AddNewObjectiveCancel();
        stg.AddNewObjective();
        stg.lstInnObjective.get(0).EndEditObjective();
        
        stg.lstInnObjective.get(0).AddNewPlanObjective(); 
        stg.lstInnObjective.get(0).AddNewPlanObjectiveCancel();
        //important must add new service assignment twice first time is for fail
        stg.lstInnObjective.get(0).AddNewServiceAssignment();
        stg.lstInnObjective.get(0).newServiceAssignment =objServAssignment1.id;
        stg.lstInnObjective.get(0).AddNewServiceAssignment();
        stg.lstInnObjective.get(0).AddNewServiceAssignmentCancel();
        
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).EndEditPlanObjective();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).AddNewIntervention();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).AddNewInterventionCancel();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).AddNewServiceAssignment();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).newServiceAssignment = objServAssignment1.id;
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).AddNewServiceAssignment();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).AddNewServiceAssignmentCancel();
        
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).lstInnIntervention.get(0).EndEditIntervention();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).lstInnIntervention.get(0).AddNewServiceAssignmentCancel();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).lstInnIntervention.get(0).AddNewServiceAssignment();
        
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).lstInnIntervention.get(0).deleteIntervention();
        stg.lstInnObjective.get(0).lstInnPlanObjective.get(0).DeletePlanObjective();        
        stg.lstInnObjective.get(0).DeleteObjective();
        
        /*
        //start my plans view
        V2SA_MyPlans myPlans = new V2SA_MyPlans();
        myPlans.newPlan();
        System.currentPageReference().getParameters().put('id', objPlan.Id);
        myPlans.newPlan();
        */
        //end my plans view
       // Progress_Note__c thisPn = new Progress_Note__c();
       // insert thisPn ;
        //start my persons view
        
        
        
        
     /*   
       Notes_Plan_Approval npai = new Notes_Plan_Approval(objPlan);
        
        npai.MarkApproved();
        
        System.currentPageReference().getParameters().put('id', objPlan.Id);
        System.currentPageReference().getParameters().put('state', 'nc');
        Notes_ProgressNote_Create tmp = new Notes_ProgressNote_Create();
        */        
        //
        
    }
}