src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Event__c</fullName>
        <description>The event that serves as the baseline for relative due dates.</description>
        <inlineHelpText>Select an event to server as the baseline for this document&apos;s relative due date.</inlineHelpText>
        <label>Relative Due Date Event</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar Month End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Quarter End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MENTOR Fiscal Year End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Anniversary of Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Anniversary of Client Tx Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_UOM__c</fullName>
        <description>The Unit of Measure (UOM) specified for the relative due date for a document profile.</description>
        <inlineHelpText>Select a Unit of Measure (UOM) for the relative due date for a document profile.</inlineHelpText>
        <label>Relative Due Date Unit of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Units__c</fullName>
        <description>The number of units of the unit of measure specified for the relative due date value.</description>
        <inlineHelpText>The number of units of the unit of measure specified for the relative due date value.</inlineHelpText>
        <label>Relative Due Date Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The state(s) to which a document is related</description>
        <inlineHelpText>Pick a state(s) to which the document profile will be associated.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Region__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_Treatment_End_Date__c</fullName>
        <inlineHelpText>This field is only required when associating Document types of Case and or Fidelity with a Service Assignment.</inlineHelpText>
        <label>Projected Treatment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_From_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Due From Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fixed_Due_Date__c</fullName>
        <label>Fixed Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Event__c</fullName>
        <label>Relative Due Date Event</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar Month End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar Quarter End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MENTOR Fiscal Year End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Tx End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other - Describe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Anniversary of Client Tx Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Anniversary of Client Tx Start</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_UOM__c</fullName>
        <label>Relative Due Date UOM</label>
        <picklist>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weeks(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relative_Due_Date_Units__c</fullName>
        <label>Relative Due Date Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DocumentDetailsExt.cls
public class DocumentDetailsExt {
    public ServiceAssignment_Document_JO__c theSadjo { get; private set; }
    public Service_Assignment__c theServAssign { get; private set; }
    public String rddUnits { get; set; }
    public String rddUom { get; set; }
    public String rddEvent { get; set; }
    public String isFixedActiveStyle { get; set; }
    public String isFixedInactiveStyle { get; set; }
    public String isRelativeActiveStyle { get; set; }
    public String isRelativeInactiveStyle { get; set; }
    public String fixedCheckedStatus { get; set; }
    public String relativeCheckedStatus { get; set; }
    public List<SelectOption> selectOptionsRddUom { get; set; }
    public List<SelectOption> selectOptionsRddEvent { get; set; }
    public Boolean updateAllUnfiledDueFroms { get; set; }
        
    public DocumentDetailsExt(ApexPages.StandardController controller) {
        theSadjo = (ServiceAssignment_Document_JO__c)controller.getRecord();
               
        theServAssign = [ SELECT Id, Name, Admission__c, Admission__r.State__c, Program__c, Admission__r.Person_Being_Served__c, Admission__r.Name,
                    Admission__r.Effective_Date__c, Person_Being_Served__c, Start_Date__c, End_Date__c, Projected_Treatment_End_Date__c, 
                    Location_Region__c, Person_Being_Served__r.Owner.Id
                     FROM Service_Assignment__c WHERE Id = :theSadjo.Service_Assignment__c ];
                     
        rddUnits = String.valueOf(theSadjo.Relative_Due_Date_Units__c);
        rddUom = theSadjo.Relative_Due_Date_UOM__c;
        rddEvent = theSadjo.Relative_Due_Date_Event__c;
        
        isFixedActiveStyle = 'display:none';
        isFixedInactiveStyle = 'display:inline';
        isRelativeActiveStyle = 'display:inline';
        isRelativeInactiveStyle = 'display:none';
        fixedCheckedStatus = '';
        relativeCheckedStatus = 'checked';
        if(theSadjo.Relative_Due_Date_Units__c==null) {
            isFixedActiveStyle = 'display:inline';
            isFixedInactiveStyle = 'display:none';
            isRelativeActiveStyle = 'display:none';
            isRelativeInactiveStyle = 'display:inline';            
            fixedCheckedStatus = 'checked';
            relativeCheckedStatus = '';             
        }
/*
        if(theSadjo.Fixed_Due_Date__c==null) {
            isFixedActiveStyle = 'display:none';
            isFixedInactiveStyle = 'display:inline';
            isRelativeActiveStyle = 'display:inline';
            isRelativeInactiveStyle = 'display:none';            
            fixedCheckedStatus = '';
            relativeCheckedStatus = 'checked';            
        }
*/
        
        Schema.DescribeFieldResult fieldInfo = Schema.SObjectType.Document__c.fields.Relative_Due_Date_UOM__c;
        List<Schema.PicklistEntry> picklistValues = fieldInfo.getPicklistValues();
        selectOptionsRddUom = new List<SelectOption>();
        selectOptionsRddUom.add(new SelectOption('--None--','--None--')); 
        for (Schema.PicklistEntry picklistValue : picklistValues) {
            selectOptionsRddUom.add(new SelectOption(picklistValue.getLabel(),picklistValue.getLabel()));
        }      

        Schema.DescribeFieldResult fieldInfo2 = Schema.SObjectType.Document__c.fields.Relative_Due_Date_Event__c;
        List<Schema.PicklistEntry> picklistValues2 = fieldInfo2.getPicklistValues();
        selectOptionsRddEvent = new List<SelectOption>();
        selectOptionsRddEvent.add(new SelectOption('--None--','--None--')); 
        for (Schema.PicklistEntry picklistValue2 : picklistValues2) {
            selectOptionsRddEvent.add(new SelectOption(picklistValue2.getLabel(),picklistValue2.getLabel()));
        }        
    }

    
    public PageReference resetToDefaults() {
        
        Document__c dD = [ SELECT Id, Name, Relative_Due_Date_Units__c, 
                        Relative_Due_Date_UOM__c, Relative_Due_Date_Event__c
                        FROM Document__c WHERE Id = :theSadjo.Document__c ];
        
        
        rddUnits = String.valueOf(dD.Relative_Due_Date_Units__c);
        rddUom = dD.Relative_Due_Date_UOM__c;
        rddEvent = dD.Relative_Due_Date_Event__c;
        theSadjo.Due_From_Employee__c = theServAssign.Person_Being_Served__r.Owner.Id;
        theSadjo.Fixed_Due_Date__c = null;
        isFixedActiveStyle = 'display:none';
        isFixedInactiveStyle = 'display:inline';
        isRelativeActiveStyle = 'display:inline';
        isRelativeInactiveStyle = 'display:none';            
        relativeCheckedStatus = 'checked';
        fixedCheckedStatus = '';

        PageReference refreshPageRef = new PageReference('/apex/DocumentDetails?id=' + theSadjo.Id);
        
        return refreshPageRef;
        
    }

    
    public PageReference saveUpdateXrefs() {
        
        // Add logic for handling saves...
        System.debug('AT SAVE theServAssign: ' + theServAssign);
        System.debug('AT SAVE theSadjo: ' + theSadjo);
        System.debug('AT SAVE theSadjo.Fixed_Due_Date__c: ' + theSadjo.Fixed_Due_Date__c);
        if(rddUnits==null || rddUnits=='') {
            theSadjo.Relative_Due_Date_Units__c = null;
        }
        else {
            theSadjo.Relative_Due_Date_Units__c = Decimal.valueOf(rddUnits);
        }
        theSadjo.Relative_Due_Date_UOM__c = rddUom;
        theSadjo.Relative_Due_Date_Event__c = rddEvent;
        
        System.debug('What is in theSadjo.Due_From_Employee__c at DocumentDetailsExt.saveUpdateXrefs() before docPop() call: ' + theSadjo.Due_From_Employee__c);
        
        DocumentMethods.docPop(theServAssign, theSadjo, theSadjo.Fixed_Due_Date__c, false, true, false, false);
        if(updateAllUnfiledDueFroms==true) {
            DocumentMethods.ChangeDueFrom(theServAssign, theSadjo.Due_From_Employee__c);
        }
        PageReference pageRef = new PageReference('/apex/ServAssignExpectedDocs?id='+theServAssign.Id);
        return pageRef;         
    }


    public void ClearRelativeDueDateFields() {
          rddUnits = null;
          rddUom = '--None--';
          rddEvent = '--None--';     
    }

    
    public void ClearFixedDueDateField() {
          theSadjo.Fixed_Due_Date__c = null;
    }
    
}