src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Admission_Effective_DateTime__c</fullName>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Referred_Out_Agency_Name__c</fullName>
        <description>Name of the agency the individual was referred-out to</description>
        <inlineHelpText>Name of the agency the individual was referred-out to</inlineHelpText>
        <label>Referred-Out Agency Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referred Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdmissionEditExtensionTest.cls
@isTest
private class AdmissionEditExtensionTest {
    static testmethod void simpleTest() {
        
        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
        
        PageReference ref = new PageReference('/apex/AdmissionEdit?id='+ myData.theAdm.id);
        Test.setCurrentPage(ref); 
        AdmissionEditExtension controller = new AdmissionEditExtension(new ApexPages.StandardController(myData.theAdm));
        System.assertEquals(myData.theAdm.id, controller.admission.ID);
        
        controller.admission.status__c = 'Discharged';
        controller.admission.discharged_to_subcategory__c = 'Other';
        controller.admission.discharged_to_category__c = 'Another Facility';
        controller.admission.discharged_reason_additional__c = 'Other';
        controller.useDischargeSection = true;
        controller.saveAdmission();
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        system.assert( msgList.size() > 0);
        
        controller.useDischargeSection = false;
        controller.admission.status__c = 'Active';
        controller.admEffDateTime = myData.theAdm.Admission_Effective_DateTime__c.format();
        controller.admDischargeDateTime = '';
        controller.admission.Referred_Out_Agency_Name__c = 'Test Agency';
        controller.saveAdmission();
        msgList = ApexPages.getMessages();
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            system.debug( msg.getSummary());
        }
                 
        myData.theAdm = [
            SELECT Referred_Out_Agency_Name__c FROM Admission__c
            WHERE ID=:myData.theAdm.id
        ];
        
        System.assertEquals('Test Agency', myData.theAdm.Referred_Out_Agency_Name__c);
        
        
        
        ref = new PageReference('/apex/AdmissionEdit?pbsId='+myData.contactID);
        Test.setCurrentPage(ref);
        controller = new AdmissionEditExtension(new ApexPages.StandardController(New Admission__c()));
        
    }
}