src/objects/Admission__c.object
<CustomObject>
    <description>NOTES Admissions track a Person Being Served&apos;s relationship with The MENTOR Network. There is a validation rule that allows only one active Admission per state per person.</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Admission effective date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Admission</label>
    <nameField>
        <label>Admission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract_Document_JO__c.object
<CustomObject>
    <description>A cross-reference object that links contracts with the document profiles for documents expected in the client file for clients associated with that contract.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>The contract for this contract / document cross-reference.</description>
        <inlineHelpText>The contract for this contract / document cross-reference.</inlineHelpText>
        <label>-Contract</label>
        <referenceTo>TMN_Contract__c</referenceTo>
        <relationshipLabel>Contract Document JOs</relationshipLabel>
        <relationshipName>Contract_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <description>The document profile for this contract / document cross-reference.</description>
        <inlineHelpText>The document profile for this contract / document cross-reference.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Contract Document JOs</relationshipLabel>
        <relationshipName>Contract_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Document JO</label>
    <nameField>
        <displayFormat>ConDocXref-{0000000}</displayFormat>
        <label>Contract Document JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Document JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The state(s) to which a document is related</description>
        <inlineHelpText>Pick a state(s) to which the document profile will be associated.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fidelity Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Document_Xref__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Program Document Xrefs</relationshipLabel>
        <relationshipName>Program_Document_Xrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program Document Xref</label>
    <nameField>
        <displayFormat>Program_Doc_Xref_{0000000}</displayFormat>
        <label>Program_Document_Xref__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Document Xrefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Admission__c</fullName>
        <label>Admission</label>
        <referenceTo>Admission__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Region__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_Treatment_End_Date__c</fullName>
        <inlineHelpText>This field is only required when associating Document types of Case and or Fidelity with a Service Assignment.</inlineHelpText>
        <label>Projected Treatment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Contract_JO__c.object
<CustomObject>
    <description>An object to hold records representing Service Assignment / Contract cross-references for the Document Tracker feature.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <description>The Contract for this Service Assignment / Contract cross-reference.</description>
        <inlineHelpText>The Contract for this Service Assignment / Contract cross-reference.</inlineHelpText>
        <label>-Contract</label>
        <referenceTo>TMN_Contract__c</referenceTo>
        <relationshipName>ServiceAssignment_Contract_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment for this Service Assignment / Contract cross-reference.</description>
        <inlineHelpText>The Service Assignment for this Service Assignment / Contract cross-reference.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipName>ServiceAssignment_Contract_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>ServAssgn_Cntrct_JO-{0000000}</displayFormat>
        <label>ServiceAssignment_Contract_JO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/DocumentAddExt.cls
public class DocumentAddExt {
    public ServiceAssignment_Document_JO__c theServAssignDocJo { get; set; }
    public Id theServAssignId { get; set; }
    public final Service_Assignment__c theServAssign { get; private set; }
    public Set<Id> setOfIdsForDocsUserCanAdd { get; set; }
    public Set<Id> setOfDocIdsForRelatedContracts { get; set; }
    public Set<Id> setOfDocIdsForRelatedPrograms { get; set; }
    public Set<Id> intersectionSetOfDocIds { get; set; }
    public List<Document__c> listOfDocsUserCanAdd { get; set; }
    public Map<Id,Document__c> mapOfDocsUserCanAdd { get; set; }
    public List<SelectOption> selectOptionsForDocAdd { get; set; }
    public Document__c selectedDoc { get; set; }
    public Id currentSelectedDocId { get; set; }
    public Boolean docIsSelected { get; set; }
    public Integer units { get; set; }
    public String rddUnits { get; set; }
    public String rddUom { get; set; }
    public String rddEvent { get; set; }
    public Date fixedDueDate { get; set; }
    public List<SelectOption> selectOptionsRddUom { get; set; }
    public List<SelectOption> selectOptionsRddEvent { get; set; }
    public Boolean dateType { get; set; }
    ApexPages.StandardController sadjoController;
    
    public DocumentAddExt(ApexPages.StandardController controller) {
        sadjoController = controller;
        theServAssignDocJo = (ServiceAssignment_Document_JO__c)sadjoController.getRecord();
        
        
        theServAssignId = ApexPages.currentPage().getParameters().get('ServAssignIdParam');
        theServAssign = [ SELECT Id, Name, Admission__c, Admission__r.State__c, Program__c, Admission__r.Person_Being_Served__c, Admission__r.Name,
                            Admission__r.Effective_Date__c, Person_Being_Served__c, Start_Date__c, End_Date__c, Projected_Treatment_End_Date__c, 
                            Location_Region__c
                             FROM Service_Assignment__c WHERE Id = :theServAssignId ];
                             
        
        // Populate a list of documents that are not auto-include documents that the user can add to the Service Assignment.        
        List<Id> listOfContractIds = new List<Id>();
        List<ServiceAssignment_Contract_JO__c> servAssignContractXrefs = new List<ServiceAssignment_Contract_JO__c>();
        servAssignContractXrefs = [ SELECT Id, Name, Contract__c FROM ServiceAssignment_Contract_JO__c WHERE Service_Assignment__c = :theServAssignId ];

        for(ServiceAssignment_Contract_JO__c sAJC : servAssignContractXrefs) {
            listOfContractIds.add(sAJC.Contract__c);
        }

        List<Contract_Document_JO__c> contractDocXrefs = [ SELECT Id, Name, Document__c, Contract__c FROM Contract_Document_JO__c WHERE Contract__c = :listOfContractIds AND Document__r.Type__c = 'Case Document' AND Document__r.Auto_Include__c = false AND (Document__r.State__c = :theServAssign.Admission__r.State__c OR Document__r.State__c = NULL) ];
        List<Program_Document_Xref__c> programDocXrefs = [ SELECT Id, Name, Document__c FROM Program_Document_Xref__c WHERE Program__c = :theServAssign.Program__c AND Document__r.Type__c = 'Case Document' AND Document__r.Auto_Include__c = false AND (Document__r.State__c = :theServAssign.Admission__r.State__c OR Document__r.State__c = NULL) ];
    
        // Populate a set of Document IDs expected for this Service Assignment by looping through the lists of Contract / Doc Xrefs and Program / Doc Xrefs created above.
        setOfIdsForDocsUserCanAdd = new Set<Id>();
        setOfDocIdsForRelatedContracts = new Set<Id>();
        setOfDocIdsForRelatedPrograms = new Set<Id>();
        intersectionSetOfDocIds = new Set<Id>();
        for(Contract_Document_JO__c cdj : contractDocXrefs) {
            setOfDocIdsForRelatedContracts.add(cdj.Document__c);
        }
        for(Program_Document_Xref__c pdx : programDocXrefs) {
            setOfDocIdsForRelatedPrograms.add(pdx.Document__c);
        }
        
        intersectionSetOfDocIds = setOfDocIdsForRelatedContracts.clone();
        intersectionSetOfDocIds.retainAll(setOfDocIdsForRelatedPrograms);
        
        setOfIdsForDocsUserCanAdd = intersectionSetOfDocIds;
        
        // Get the documents that match up with that set of IDs.
        listOfDocsUserCanAdd = [SELECT Id, Name, Relative_Due_Date_Units__c, Relative_Due_Date_UOM__c, Relative_Due_Date_Event__c, Type__c FROM Document__c WHERE Id = :setOfIdsForDocsUserCanAdd ];
        mapOfDocsUserCanAdd = new Map<Id,Document__c>();
        for(Document__c loduca : listOfDocsUserCanAdd) {
            mapOfDocsUserCanAdd.put(loduca.Id,loduca);
        }
        
        List<ServiceAssignment_Document_JO__c> listOfPreExistingServAssignDocXrefs = [ SELECT Document__c, File_Status__c, Relative_Due_Date_Resolved__c FROM ServiceAssignment_Document_JO__c WHERE Service_Assignment__c = :theServAssign.Id ];
        
        Set<Id> docsToRemoveFromListOfDocsUserCanAdd = new Set<Id>();
        for(Document__c d : listOfDocsUserCanAdd) {
            for(ServiceAssignment_Document_JO__c sadj : listOfPreExistingServAssignDocXrefs) {                      
                if(sadj.Document__c == d.Id) {                                                          
                    docsToRemoveFromListOfDocsUserCanAdd.add(d.Id);
                }
            }
        }   
        
        for(Id i : docsToRemoveFromListOfDocsUserCanAdd) {
            mapOfDocsUserCanAdd.remove(i);  
        }
        
        selectOptionsForDocAdd = new List<SelectOption>();
        selectOptionsForDocAdd.add(new SelectOption('--None--','--None--'));
        for(Id md : mapOfDocsUserCanAdd.keySet()) {
            selectOptionsForDocAdd.add(new SelectOption(md,mapOfDocsUserCanAdd.get(md).Name));
        }
        
        Schema.DescribeFieldResult fieldInfo = Schema.SObjectType.Document__c.fields.Relative_Due_Date_UOM__c;
        List<Schema.PicklistEntry> picklistValues = fieldInfo.getPicklistValues();
        selectOptionsRddUom = new List<SelectOption>();
        selectOptionsRddUom.add(new SelectOption('--None--','--None--')); 
        for (Schema.PicklistEntry picklistValue : picklistValues) {
            selectOptionsRddUom.add(new SelectOption(picklistValue.getLabel(),picklistValue.getLabel()));
        }      

        Schema.DescribeFieldResult fieldInfo2 = Schema.SObjectType.Document__c.fields.Relative_Due_Date_Event__c;
        List<Schema.PicklistEntry> picklistValues2 = fieldInfo2.getPicklistValues();
        selectOptionsRddEvent = new List<SelectOption>();
        selectOptionsRddEvent.add(new SelectOption('--None--','--None--')); 
        for (Schema.PicklistEntry picklistValue2 : picklistValues2) {
            selectOptionsRddEvent.add(new SelectOption(picklistValue2.getLabel(),picklistValue2.getLabel()));
        }

      
    }
    
    
    private void addError(String msg) {
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, msg));
    }
    
    
    public void defaultDueDateInfo() {
        
        System.debug('Value of currentSelectedDocId: ' + selectedDoc);
        
        Document__c dD = [ SELECT Id, Name, Relative_Due_Date_Units__c, 
                        Relative_Due_Date_UOM__c, Relative_Due_Date_Event__c
                        FROM Document__c WHERE Id = :currentSelectedDocId ];
        
        
        rddUnits = String.valueOf(dD.Relative_Due_Date_Units__c);
        rddUom = dD.Relative_Due_Date_UOM__c;
        rddEvent = dD.Relative_Due_Date_Event__c;
        
        docIsSelected = true;
        
    }


    public PageReference resetToDefaults() {
        
        PageReference refreshPageRef = new PageReference('/apex/AddDoc?id=' + theServAssignDocJo.Id);
        defaultDueDateInfo();
        return refreshPageRef;
        
    }

    public PageReference saveDocXref() {
        /*
        System.debug('Document__c value at save: ' + theServAssignDocJo.Document__c);
        System.debug('Relative_Due_Date_Units__c value at save: ' + theServAssignDocJo.Relative_Due_Date_Units__c); 
        
        theServAssignDocJo.Service_Assignment__c = theServAssign.Id;
        
        insert theServAssignDocJo;
        */
        
        System.Debug('THE SAVE FUNCTION IS RUNNING!');
        System.Debug('What is in currentSelectedDocId? ' + currentSelectedDocId);

        
        theServAssignDocJo.Document__c = currentSelectedDocId;
//        theServAssignDocJo.Fixed_Due_Date__c = fixedDueDate;
//        theServAssignDocJo.Relative_Due_Date_Units__c = rddUnits;
        
        if(theServAssignDocJo.Relative_Due_Date_Event__c!=NULL && theServAssignDocJo.Fixed_Due_Date__c!=NULL){
                addError('You cannot have both a Relative Due Date and a Fixed Due Date.  Please make corrections to the data entry and try again.');
        }
        
        if(rddUnits!=null && rddUnits!='') {
                theServAssignDocJo.Relative_Due_Date_Units__c = Decimal.valueOf(rddUnits);
        }
        else {
                theServAssignDocJo.Relative_Due_Date_Units__c = null;
        }
        theServAssignDocJo.Relative_Due_Date_UOM__c = rddUom;
        theServAssignDocJo.Relative_Due_Date_Event__c = rddEvent;
        
        System.debug('saveDocXref; theServAssign: ' + theServAssign);
        System.debug('saveDocXref; theServAssignDocJo: ' + theServAssignDocJo);
        System.debug('saveDocXref; theServAssignDocJo.Fixed_Due_Date__c' + theServAssignDocJo.Fixed_Due_Date__c);
        
        DocumentMethods.docPop(theServAssign, theServAssignDocJo, theServAssignDocJo.Fixed_Due_Date__c, true, false, false, false);
        
        PageReference pageRef = new PageReference('/apex/ServAssignExpectedDocs?id='+theServAssign.Id);
        return pageRef;
        
    }
    
    public void ClearRelativeDueDateFields() {
          rddUnits = null;
          rddUom = '--None--';
          rddEvent = '--None--';     
    }
    
    public void ClearFixedDueDateField() {
          theServAssignDocJo.Fixed_Due_Date__c = null;
    }
    
    public PageReference CancelAddDoc() {
        PageReference cancelPageRef = new PageReference(sadjoController.cancel().getUrl());
        return cancelPageRef;
    }
}