src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/rptProviderTrackingTest.cls
@isTest
private class rptProviderTrackingTest {
	
	private static rptProviderTracking ctrl = new rptProviderTracking();
	
	@testSetup
	static void setUp() {
		Service_Location__c servLoc = new Service_Location__c();
		servLoc.Alias__c = '029435';
		servLoc.FacilityId__c = 13.0;
		servLoc.UniqueID__c = '1234';
		servLoc.Program__c = 'Test Program 1';
		servLoc.Name = 'Service Location 1';
		servLoc.ProgramId__c = '029435000';
		servLoc.Location_Nickname__c = 'Loc 1';
		servLoc.State__c = 'OR';
		servLoc.Service_Type__c = 'CM - Case Management';
		insert servLoc;
		
		servLoc = new Service_Location__c();
		servLoc.Alias__c = '564423';
		servLoc.FacilityId__c = 13.0;
		servLoc.UniqueID__c = '5678';
		servLoc.Program__c = 'Test Program 2';
		servLoc.Name = 'Service Location 2';
		servLoc.ProgramId__c = '564423000';
		servLoc.Location_Nickname__c = 'Loc 2';
		servLoc.State__c = 'OR';
		servLoc.Service_Type__c = 'CM - Case Management';
		insert servLoc;
		
		servLoc = new Service_Location__c();
		servLoc.Alias__c = '789546';
		servLoc.FacilityId__c = 13.0;
		servLoc.UniqueID__c = '9012';
		servLoc.Program__c = 'Test Program 3';
		servLoc.Name = 'Service Location 3';
		servLoc.ProgramId__c = '789546000';
		servLoc.Location_Nickname__c = 'Loc 3';
		servLoc.State__c = 'OR';
		servLoc.Service_Type__c = 'CM - Case Management';
		insert servLoc;
	}

	/**
	 * Validating default value for provider status
	 */
    static testMethod void initializingStatusFieldTest() {
    	String[] provStatus = ctrl.providerStatus;
		system.assertEquals(4, provStatus.size());
		system.assertEquals(new String[] {'Pending Approval', 'Approved', 'Expired', 'Disqualified'}, 
				provStatus);
    }
    
    /**
     * Ensuring that brokerages are initialized upon creation
     */
    static testMethod void initializingBrokerageFieldTest() {
		Service_Location__c[] locIds = [
                     SELECT Id
                       FROM Service_Location__c
                     WHERE State__c = 'OR'
                        AND Service_Type__c = 'CM - Case Management'
                     ORDER BY ProgramId__c
              ];
		
    	List<SelectOption> options = ctrl.getBrokerageOptions();
    	system.assertEquals(3, options.size());
    	system.assertEquals(locIds[0].Id, options[0].getValue());
    	system.assertEquals(locIds[1].Id, options[1].getValue());
    	system.assertEquals(locIds[2].Id, options[2].getValue());
    	
    	String[] brokerage = ctrl.brokerages;
    	
    	system.assertEquals(3, brokerage.size());
    	system.assertEquals(locIds[0].Id, brokerage[0]);
    	system.assertEquals(locIds[1].Id, brokerage[1]);
    	system.assertEquals(locIds[2].Id, brokerage[2]);
    }
    
    /**
     * Validate that the controller returns an error when no statuses are selected.
     */
    static testMethod void testNoStatus() {
    	ctrl.providerStatus = new String[]{};
    	
    	ctrl.runRpt();
    	
    	List<ApexPages.Message> messages = ApexPages.getMessages();
    	
    	system.assertEquals(1, messages.size());
    	system.assertEquals(ApexPages.Severity.ERROR, messages[0].getSeverity());
    	system.assertEquals('Please choose at least one status value', messages[0].getSummary());
    }
    
    /**
     * Validate that the controller returns an error when no brokerages are selected
     */
    static testMethod void testNoBrokerages() {
    	ctrl.brokerages = new String[]{};
    	
    	ctrl.runRpt();
    	
    	List<ApexPages.Message> messages = ApexPages.getMessages();
    	
    	system.assertEquals(1, messages.size());
    	system.assertEquals(ApexPages.Severity.ERROR, messages[0].getSeverity());
    	system.assertEquals('Please choose at least one brokerage', messages[0].getSummary());
    }
}