src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Refinement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled by User</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Progress_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>The date the clinician administered the service.</description>
        <label>Date of Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Required_Signatures__c</fullName>
        <label>Number of Required Signatures</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Service_Assignment__r.Program__c</formula>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose_Service_is_Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Default Check Box means this service is Billable, if this service is NOT Billable please Uncheck the box</inlineHelpText>
        <label>Purpose/Service is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <inlineHelpText>Location that the service took place.</inlineHelpText>
        <label>Service Location</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Mental Health Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MR Intermediate Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office/TRAC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sleep_Check_Conducted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sleep Check Conducted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <formula>Service_Location__r.Alias__c</formula>
        <label>Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/Notes_Progressnote_CaseManagementTest.cls
@isTest
public with sharing class Notes_Progressnote_CaseManagementTest {
    @testSetup static void testData() {
        User testUser = TMN_Generic_Core_TestData.createUser('ESD General','tUser', 'tUser@tmn.com' + System.currentTimeMillis(), 'CaseManagement', 'Test', 'Redwood');
        System.runas(new User(Id = UserInfo.getUserId())){
            permsetAssign(new list<String>{'ESD_Notes_Common','iServe_Case_Management','ESD_Referrals_Common','ESD_Referrals_Intaker','ESD_Referrals_Intaker_Light'}, testUser.id);
        }
    }
    static testMethod void simpleTests() {
        User u = [Select id from User where FirstName = 'CaseManagement' Limit 1];
        system.runas( u ) {
            TMN_Generic_Core_TestData coredata = new TMN_Generic_Core_TestData();
            coredata.loadData( 'OR');
            ID newSLid1 = createServiceLocation( '123456', '123456001', 'New Service Location 1', 1, 'OR', '1-123456' );
            coredata.theSA.service_location__c = newSLid1;
            update coredata.theSA;
            
            Progress_Note__c p = new Progress_Note__c(start_time__c = system.now().addhours(-1),end_time__c=system.now());
            ApexPages.StandardController sc = new ApexPages.StandardController(p);
            PageReference pageRef = Page.Notes_Progressnote_CaseManagement;
            Test.setCurrentPageReference(pageRef);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Id', P.id);
            ApexPages.currentPage().getParameters().put('Mode', 'New'); 
            Progress_Note__c pt = new Progress_Note__c(approval_user__c = u.id, Number_of_Required_Signatures__c=2, start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70),Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID);
            insert pt;
            Notes_ProgressNote_CaseManagementExt objNpncTest = new Notes_ProgressNote_CaseManagementExt(sc);
            list<progress_note__c> pnote = New list<progress_note__c>();
            pnote.add(pt);
            objNpncTest.loaddata(pt);
            pagereference pr = objnpnctest.saveprogressnote();
            objNpncTest.showPopupComp();
            objNpncTest.closepopup();
            objNpncTest.closepopupcomp();
            List<Attachment> att = objnpnctest.Attachments;
            system.assertEquals(att.size()<1, true);
            Test.startTest();
            try{
                objnpnctest.showpopup();
            }
            catch(exception e){
                system.assertEquals(e.getmessage().contains('E-Signature is required before finalizing the note'), true);
            }
            pagereference editInline = objNpncTest.editInline();
            system.assertEquals(string.valueof(editInline).contains('Notes_Progressnote_CaseManagemen'), true);
            pagereference cancel = objNpncTest.cancelEditNote();
            system.assertEquals(string.valueof(cancel).contains(ApexPages.currentPage().getParameters().get('ServAssignId')), true);
            
            //2
            Progress_Note__c pt3 = new Progress_Note__c(Number_of_Required_Signatures__c=2,start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70),Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID);
            insert pt3;
            Progress_Note__c p3 = new Progress_Note__c(start_time__c = system.now().addhours(-1),end_time__c=system.now());
            ApexPages.StandardController sc3 = new ApexPages.StandardController(p3);
            PageReference pageRef3 = Page.Notes_Progressnote_CaseManagement;
            Test.setCurrentPageReference(pageRef3);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Id', pt3.id);
            ApexPages.currentPage().getParameters().put('Mode', 'Edit');
            Notes_ProgressNote_CaseManagementExt objNpncTest3 = new Notes_ProgressNote_CaseManagementExt(sc3);
            objNpncTest3.RenderSelectedIds();
            List<recordType> testRecTypeList = objNpncTest3.getmyRTS();
            String SelKys = objNpncTest3.selectedKeys;
            Progress_note__c testPn = objNpncTest3.getthePN();
            try{objNpncTest3.myfinal();}
            catch( exception e){}
            try{objNpncTest3.disregardNote();}
            catch( exception e){}
            
            //3
            Progress_Note__c pt4 = new Progress_Note__c(Number_of_Required_Signatures__c=2, start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70), Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID,Date_of_Service__c=date.today().adddays(1));
            insert pt4;
            Progress_Note__c p4 = new Progress_Note__c(start_time__c = system.now().addhours(-1),locked__c = true,end_time__c=system.now(),Sleep_Check_Conducted__c= true,Purpose_Service_is_Billable__c = true);
            ApexPages.StandardController sc4 = new ApexPages.StandardController(p4);
            PageReference pageRef4 = Page.Notes_Progressnote_CaseManagement;
            Test.setCurrentPageReference(pageRef4);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Id', pt4.id);
            ApexPages.currentPage().getParameters().put('Mode', 'InlineEdit'); 
            Notes_ProgressNote_CaseManagementExt objNpncTest4 = new Notes_ProgressNote_CaseManagementExt(sc4);
            try{objNpncTest4.saveProgressNote();}
            catch(exception e){}
            try{objNpncTest4.disregardnote();}
            catch(exception e){}
            
            //4
            Progress_Note__c pt12 = new Progress_Note__c(Number_of_Required_Signatures__c=2,start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70),Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID);
            insert pt12;
            Progress_Note__c p12 = new Progress_Note__c(start_time__c = system.now().addhours(-1),end_time__c=system.now());
            ApexPages.StandardController sc5 = new ApexPages.StandardController(p12);
            PageReference pageRef5 = Page.Notes_ProgressNote_CaseManagement;
            Test.setCurrentPageReference(pageRef5);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Id', pt12.id);
            ApexPages.currentPage().getParameters().put('Mode', 'Edit');
            Notes_ProgressNote_CaseManagementExt objNpncTest125 = new Notes_ProgressNote_CaseManagementExt(sc5);
            
            //5
            Progress_Note__c pt15 = new Progress_Note__c(Number_of_Required_Signatures__c=2,Approval_user__c= u.id,start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70),Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID);
            insert pt15;
            Progress_Note__c p15 = new Progress_Note__c(start_time__c = system.now().addhours(-1),end_time__c=system.now());
            ApexPages.StandardController sc6 = new ApexPages.StandardController(p15);
            PageReference pageRef6 = Page.Notes_ProgressNote_CaseManagement;
            Test.setCurrentPageReference(pageRef6);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Id', pt15.id);
            ApexPages.currentPage().getParameters().put('Mode', 'Edit');
            Notes_ProgressNote_CaseManagementExt objNpncTest1256 = new Notes_ProgressNote_CaseManagementExt(sc6);
            objNpncTest1256.submitforapp();
            objNpncTest1256.getApprovalHistory();
            string s = objNpncTest1256.personselectedIds;
            string t = objNpncTest1256.srvcLocationName;
            string u1 = objNpncTest1256.HomePageData;
            string v = objNpncTest1256.relatedpbstring;
            string W = objNpncTest1256.searchresultPBS;
            string X = objNpncTest1256.searchresultSA;
            id i = objNpncTest1256.ProcessId;
            boolean b1 = objNpncTest1256.updatePBs;
            boolean b2 = objNpncTest1256.canDisregard;
            boolean b3 = objNpncTest1256.showPBS;
            pt15.status__c = 'Final';
            pt15.approval_status__c = 'Pending';
            update pt15;
            list<progress_note__c> pnt = New List<progress_note__c>();
            pnt.add(pt15);
            objNpncTest1256.validateFinalizeEsign(pnt,'Yes');
            objNpncTest1256.validateesign();
            
            //6
            Progress_Note__c pt1512 = new Progress_Note__c(Number_of_Required_Signatures__c=2,start_time__c = system.now().addMinutes(-72),end_time__c=system.now().addMinutes(-70),Service_Assignment__c =coredata.theSA.ID,Person_Being_Served__c=coredata.contactID);
            insert pt1512;
            Progress_Note__c p2 = new Progress_Note__c(Service_Assignment__c =coredata.theSA.ID,start_time__c =system.now().addhours(1),end_time__c = system.now());
            ApexPages.StandardController sc2 = new ApexPages.StandardController(p2);
            PageReference pageRef2 = Page.Notes_ProgressNote_CaseManagement;
            Test.setCurrentPageReference(pageRef2);
            ApexPages.currentPage().getParameters().put('state', 'OR');
            ApexPages.currentPage().getParameters().put('person', coredata.contactID);
            ApexPages.currentPage().getParameters().put('ServAssignId', coredata.theSA.ID);
            ApexPages.currentPage().getParameters().put('admission', coredata.theAdm.id);
            ApexPages.currentPage().getParameters().put('Mode', 'Inlineedit'); 
            ApexPages.currentPage().getParameters().put('Id', pt1512.id);
            Notes_ProgressNote_CaseManagementExt objNpncTest22 = new Notes_ProgressNote_CaseManagementExt(sc2);
            pagereference pr2 = objnpnctest22.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest231 = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest231.pn.start_time__c = Null;
            pagereference pr31 = objNpncTest231.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest232 = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest232.pn.Date_of_Service__c = system.today().adddays(2);
            pagereference pr32 = objNpncTest232.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest23 = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest23.pn.Narrative__c = Null;
            pagereference pr3 = objNpncTest23.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest23a = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest23a.pn.start_time__c = system.now().addHours(1);
            pagereference pr32a = objNpncTest23a.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest232d = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest232d.pn.Purpose_Service_is_Billable__c = True;
            pagereference pr32d = objNpncTest232d.saveprogressnote();
            Notes_ProgressNote_CaseManagementExt objNpncTest233ab = new Notes_ProgressNote_CaseManagementExt(sc2);
            objNpncTest233ab.pn.Approval_user__c = u.id;
            objNpncTest233ab.submitforApp();
        }
        Test.stopTest();
    } 
    
    
    static ID createServiceLocation( string alias, string pgmCode, string pgmVal, integer facility, string slState, string uid ) {
        Service_location__c newSL = new Service_location__c( alias__c = alias, programid__c = pgmCode, program__c = pgmVal, facilityid__c = facility, state__c = slState, uniqueid__c = uid);
        insert newSL;
        return newSL.Id;
    }
    static void permsetAssign(string[]permSets, Id assigntoId){
        system.debug('calling permsetassign');
        List<PermissionSet> theSets = [SELECT ID, Name FROM PermissionSet WHERE Name IN :permSets];
        List<PermissionSetAssignment> thepermAssigns = new List<PermissionSetAssignment>();
        for(PermissionSet ps : theSets){
            thepermAssigns.add(new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = assigntoId));
        }
        insert thepermAssigns;
    }
}