src/objects/Alias__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Operating_Group__c</fullName>
        <label>Alias_Operating_Group</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Parent__c</fullName>
        <label>Alias Parent</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Region__c</fullName>
        <label>Alias Region</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Service_Line__c</fullName>
        <label>Alias Service Line</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_State__c</fullName>
        <label>Alias State</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_unique__c</fullName>
        <externalId>true</externalId>
        <label>Alias_unique</label>
        <length>6</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Value__c</fullName>
        <label>Service Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/rpt_CensusDetail_CM_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class rpt_CensusDetail_CM_Test {

    static testMethod void myUnitTest() {
        Alias__c b = new Alias__c();
        b.Name = '99999';
        b.Alias_unique__c = '99999';
        b.Alias_State__c = 'MA';
        b.Alias_Parent__c = 'test';
        b.Alias_Region__c = 'test';
        b.Alias_Service_Line__c = 'test';
        b.Alias_Operating_Group__c ='Care Meridian';
        
        insert b;
        
        Service_location__c s = new Service_Location__c();
        s.Alias_lookup__c = b.iD;
        s.Alias__c = '99999';
        s.Name = '99999';
        s.ProgramId__c = 'test';
        s.FacilityId__c = 999;
        s.Program__c = 'test Program';
        s.Service_value__c = 'test';
        s.source_System__c = 'AVATAR';
        s.UniqueID__c = '999||test Program';
        s.Physical_location__c = 'test';
        s.City__c = 'test';
        s.Status__c = 'Active';
        
        insert s; 
        rpt_CensusDetail_CM control = new rpt_CensusDetail_CM ();
        control.runRpt();
        control.signOff();
        
        boolean nothing = control.getHasResults();
        nothing = control.getShowParms ();
        string str = control.getHost();
        
    }
}