src/objects/Alias__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Business_Unit__c</fullName>
        <label>Alias Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Description__c</fullName>
        <label>Alias Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Alias_Level__c</fullName>
        <label>Alias Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Operating_Group__c</fullName>
        <label>Alias_Operating_Group</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Region__c</fullName>
        <label>Alias Region</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Service_Line__c</fullName>
        <label>Alias Service Line</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_State__c</fullName>
        <label>Alias State</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceLocationNew.cls
public with sharing class ServiceLocationNew {
	private Apexpages.StandardController controller;
	public Service_Location__c location {get; set;}
	public Alias__c alias{get; set;}
	
	public ServiceLocationNew(Apexpages.StandardController controller){
		this.controller = controller;
		this.location = (Service_location__c) controller.getRecord();
		this.location.Source_System__c = 'iServe';
		this.alias = new Alias__c();
		
	}
	
	public pageReference save(){
		this.alias = [SELECT Id, Name, Alias_Operating_Group__c,Alias_Business_Unit__c,Alias_Description__c, Alias_Level__c,  Alias_Region__c, Alias_State__c, Alias_Service_Line__c FROM Alias__c WHERE Id= :this.location.Alias_lookup__c];
		this.location.Name = alias.Name;
		this.location.Alias__c = alias.Name;
		this.location.UniqueID__c = location.FacilityID__c+'||'+location.ProgramID__c;
		try{
			insert location;
			PageReference pg = new PageReference('/apex/ServiceLocationEdit?id='+location.Id);
			pg.setRedirect(true);
			return pg;
		}catch(exception e){
			apexpages.addmessage(new apexpages.message(ApexPages.Severity.ERROR, e.getMessage()));
			return null;
		}
		
	}

}