src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <formula>Service_Location__r.Alias__c</formula>
        <label>Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Personal_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Personal_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Agent</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment Personal Agent</label>
    <nameField>
        <label>Service Assignment Personal Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment Personal Agent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Provider_JO__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TMN_Provider__c</fullName>
        <label>TMN Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service_Assignment_Provider_JO</label>
    <nameField>
        <displayFormat>PJO-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Assignment_Provider_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>TMN Providers</relationshipLabel>
        <relationshipName>TMN_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Providers</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_Provider_Application__c.object
<CustomObject>
    <fields>
        <fullName>Disqualification_Date__c</fullName>
        <label>Disqualification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disqualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>TMN Provider Applications</relationshipLabel>
        <relationshipName>TMN_Provider_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Disqualification__c</fullName>
        <label>Reason for Disqualification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Provider Applications</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TmnProviderTest.cls
@isTest
public with sharing class TmnProviderTest {
	@testSetup
	public static void setUpData() {
		TestUtils.CoreDataGenerator generator = new TestUtils.CoreDataGenerator();
		generator.aliasBuilder.setState('OR');
		generator.serviceLocationBuilder.setState('OR');
		generator.serviceLocationBuilder
			.setServiceType('CM - Case Management')
			.setProgramId('111111000')
			.setLocationNickname('Brokerage 1');
		TestUtils.CoreData coreData = generator.persistData();

		insert generator.serviceAssignmentBuilder.getInstance();
	}

	public static testmethod void testDisqualifyingTriggers() {
		Tmn_Provider__c[] providers = new Tmn_Provider__c[]{
			new Tmn_Provider__c(
				First_Name__c = 'First',
				Last_Name__c = 'Person',
				Status__c = 'Approved'
			),
			new Tmn_Provider__c(
				First_Name__c = 'Second',
				Last_Name__c = 'Human',
				Status__c = 'Approved'
			)
		};
		insert providers;

		Tmn_Provider_Application__c[] applications = new Tmn_Provider_Application__c[]{
			new Tmn_Provider_Application__c(
				Provider__c = providers[0].Id,
				Status__c = 'Approved'
			),
			new Tmn_Provider_Application__c(
				Provider__c = providers[1].Id,
				Status__c = 'Approved'
			)
		};
		insert applications;

		TestUtils.UserBuilder userBuilder = new TestUtils.UserBuilder();
		User[] users = new User[]{
			userBuilder.setFirstName('No1').setLastName('User').setUserAlias('no1u').setEmail('no1@test.com').getInstance(),
			userBuilder.setFirstName('No2').setLastName('User').setUserAlias('no2u').setEmail('no2@test.com').getInstance()
		};
		insert users;

		Alias__c alias = [SELECT Id, Name FROM Alias__c];
		TestUtils.TmnUserBuilder tmnUserBuilder = new TestUtils.TmnUserBuilder();
		Tmn_User__c[] personalAgents = new Tmn_User__c[]{
			tmnUserBuilder.setUserId(users[0].Id).setAlias(alias).getInstance(),
			tmnUserBuilder.setUserId(users[1].Id).setAlias(alias).getInstance()
		};
		insert personalAgents;

		Service_Assignment__c[] serviceAssignments = [
			SELECT Id FROM Service_Assignment__c
		];

		Service_Assignment_Provider_JO__c[] associations = new Service_Assignment_Provider_JO__c[]{
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Tmn_Provider__c = providers[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Tmn_Provider__c = providers[1].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Tmn_Provider__c = providers[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Tmn_Provider__c = providers[1].Id,
				Status__c = 'Active'
			)
		};
		insert associations;

		Service_Assignment_Personal_Agent__c[] paAssociations = new Service_Assignment_Personal_Agent__c[] {
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Personal_Agent__c = personalAgents[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Personal_Agent__c = personalAgents[1].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Personal_Agent__c = personalAgents[0].Id,
				Status__c = 'Active'
			)
		};
		insert paAssociations;
		for (Tmn_Provider_Application__c application: applications) {
			application.Status__c = 'Disqualified';
			application.Disqualified__c = true;
		}
		update applications;
		System.assertEquals(6, [SELECT Id FROM Task].size());
	}

	public static testmethod void testExpiringTriggers() {
		Tmn_Provider__c[] providers = new Tmn_Provider__c[]{
			new Tmn_Provider__c(
				First_Name__c = 'First',
				Last_Name__c = 'Person',
				Status__c = 'Approved'
			),
			new Tmn_Provider__c(
				First_Name__c = 'Second',
				Last_Name__c = 'Human',
				Status__c = 'Approved'
			)
		};
		insert providers;

		Tmn_Provider_Application__c[] applications = new Tmn_Provider_Application__c[]{
			new Tmn_Provider_Application__c(
				Provider__c = providers[0].Id,
				Status__c = 'Approved'
			),
			new Tmn_Provider_Application__c(
				Provider__c = providers[1].Id,
				Status__c = 'Approved'
			)
		};
		insert applications;

		TestUtils.UserBuilder userBuilder = new TestUtils.UserBuilder();
		User[] users = new User[]{
			userBuilder.setFirstName('No1').setLastName('User').setUserAlias('no1u').setEmail('no1@test.com').getInstance(),
			userBuilder.setFirstName('No2').setLastName('User').setUserAlias('no2u').setEmail('no2@test.com').getInstance()
		};
		insert users;

		Alias__c alias = [SELECT Id, Name FROM Alias__c];
		TestUtils.TmnUserBuilder tmnUserBuilder = new TestUtils.TmnUserBuilder();
		Tmn_User__c[] personalAgents = new Tmn_User__c[]{
			tmnUserBuilder.setUserId(users[0].Id).setAlias(alias).getInstance(),
			tmnUserBuilder.setUserId(users[1].Id).setAlias(alias).getInstance()
		};
		insert personalAgents;

		Service_Assignment__c[] serviceAssignments = [
			SELECT Id FROM Service_Assignment__c
		];

		Service_Assignment_Provider_JO__c[] associations = new Service_Assignment_Provider_JO__c[]{
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Tmn_Provider__c = providers[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Tmn_Provider__c = providers[1].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Tmn_Provider__c = providers[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Provider_JO__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Tmn_Provider__c = providers[1].Id,
				Status__c = 'Active'
			)
		};
		insert associations;

		Service_Assignment_Personal_Agent__c[] paAssociations = new Service_Assignment_Personal_Agent__c[] {
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Personal_Agent__c = personalAgents[0].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[0].Id,
				Personal_Agent__c = personalAgents[1].Id,
				Status__c = 'Active'
			),
			new Service_Assignment_Personal_Agent__c(
				Service_Assignment__c = serviceAssignments[1].Id,
				Personal_Agent__c = personalAgents[0].Id,
				Status__c = 'Active'
			)
		};
		insert paAssociations;
		for (Tmn_Provider_Application__c application: applications) {
			application.Status__c = 'Expired';
		}
		update applications;
		System.assertEquals(6, [SELECT Id FROM Task].size());
	}

	public static testmethod void testExpiringBatchJob() {
		Tmn_Provider__c[] providers = new Tmn_Provider__c[]{
			new Tmn_Provider__c(
				First_Name__c = 'First',
				Last_Name__c = 'Person',
				Status__c = 'Approved'
			),
			new Tmn_Provider__c(
				First_Name__c = 'Second',
				Last_Name__c = 'Human',
				Status__c = 'Approved'
			)
		};
		insert providers;

		Tmn_Provider_Application__c[] applications = new Tmn_Provider_Application__c[]{
			new Tmn_Provider_Application__c(
				Provider__c = providers[0].Id,
				Status__c = 'Approved',
				Expiration_Date__c = Date.Today().addDays(-1)
			),
			new Tmn_Provider_Application__c(
				Provider__c = providers[1].Id,
				Status__c = 'Approved',
				Expiration_Date__c = Date.Today().addDays(2)
			)
		};
		insert applications;

		Test.startTest();
		Database.executeBatch(new TmnProviderExpirationBatch(), 100);
		Test.stopTest();

		Tmn_Provider_Application__c application1 = [
			SELECT Id, Status__c, Provider__r.Status__c FROM Tmn_Provider_Application__c WHERE Id=:applications[0].Id
		];
		System.assertEquals('Expired', application1.Provider__r.Status__c);
		System.assertEquals('Expired', application1.Status__c);

		Tmn_Provider_Application__c application2 = [
			SELECT Id, Status__c, Provider__r.Status__c FROM Tmn_Provider_Application__c WHERE Id=:applications[1].Id
		];
		System.assertEquals('Approved', application2.Provider__r.Status__c);
		System.assertEquals('Approved', application2.Status__c);
	}

	public static testmethod void simpleTests() {
		Tmn_Provider__c provider = new Tmn_Provider__c();
		TmnProvider controller = new TmnProvider(new ApexPages.StandardController(provider));
		System.assertEquals(false, controller.isViewMode);
		System.assertEquals(true, controller.isNewMode);
		System.assertEquals(true, controller.isEditMode);
		System.assertEquals(false, controller.getIsLocked());
		System.assertEquals('New Applicant', controller.getTitle());
		System.assertEquals(1, controller.getBrokerageOptions().size());

		controller.provider.Brokerage__c = controller.getBrokerageOptions()[0].getValue();
		System.assertEquals('111111000 - Brokerage 1', controller.getBrokerage());
		controller.provider.First_Name__c = 'First';
		controller.provider.Last_Name__c = 'Last';
		controller.provider.Gender__c = 'Male';

		System.assertNotEquals(null, controller.save());

		Tmn_Provider_Application__c[] applications = new Tmn_Provider_Application__c[]{
			new Tmn_Provider_Application__c(
				Status__c = 'Approved',
				Provider__c = controller.provider.Id
			),
			new Tmn_Provider_Application__c(
				Status__c = 'Pending Approval',
				Provider__c = controller.provider.Id
			)
		};
		insert applications;

		Service_Assignment__c serviceAssignment = [SELECT Id FROM Service_Assignment__c LIMIT 1];
		Service_Assignment_Provider_JO__c[] associations = new Service_Assignment_Provider_JO__c[]{
			new Service_Assignment_Provider_JO__c(
				Tmn_Provider__c = controller.provider.Id,
				Service_Assignment__c = serviceAssignment.Id,
				Status__c = 'Active'
			)
		};
		insert associations;

		provider = [SELECT Id, Name, First_Name__c, Last_Name__c, Gender__c FROM Tmn_Provider__c WHERE Id=:controller.provider.Id];
		controller = new TmnProvider(new ApexPages.StandardController(provider));
		System.assertEquals(true, controller.isViewMode);
		System.assertNotEquals(null, controller.currentDisqualifiableApplication);
		System.assertNotEquals(null, controller.currentPendingApplicationId);
		System.assertEquals('First Last', controller.getTitle());

		System.assertEquals(null, controller.disqualify());  // trigger the validation error

		controller.currentDisqualifiableApplication.Disqualification_Date__c = Date.today();
		controller.currentDisqualifiableApplication.Reason_for_Disqualification__c = 'Test Reason';
		controller.disqualify();

		System.assertEquals(true, [SELECT Id, Disqualified__c FROM Tmn_Provider_Application__c WHERE Id=:applications[0].Id].Disqualified__c);
		System.assertEquals(1, controller.getAssociations().size());
		controller.getAssociations();  // just to trigger the cache

		Tmn_Provider__c oldProvider = controller.provider;
		provider = new Tmn_Provider__c();
		controller = new TmnProvider(new ApexPages.StandardController(provider));
		// Trigger the dedupe here
		controller.provider.First_Name__c = 'First';
		controller.provider.Last_Name__c = 'Last';
		controller.provider.Gender__c = 'Male';

		System.assertEquals(null, controller.save());
		System.assertEquals(oldProvider.Id, controller.similarProviders[0].Id);
		controller.saveWithoutDedupe();
		System.assertNotEquals(null, controller.provider.Id);

		provider = new Tmn_Provider__c();
		controller = new TmnProvider(new ApexPages.StandardController(provider));
		System.assertEquals('N/a', controller.getBrokerage());
		controller.getBrokerage(); // Just to trigger the cache
		// Trigger validation here
		System.assertEquals(null, controller.save());
	}
}