src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>PD_End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Case Management Plan</relationshipLabel>
        <relationshipName>Case_Management_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <recordTypes>
        <fullName>OR_Combined_ISP</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>OR Combined ISP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <formula>Service_Location__r.Alias__c</formula>
        <label>Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Personal_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Personal_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Agent</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment Personal Agent</label>
    <nameField>
        <label>Service Assignment Personal Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment Personal Agent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for alias. Used to set alias and related fields.</description>
        <label>Alias Lookup</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Mid(UserRole.Name,1,2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/rptCurrentPersonalAgentAssignmentsTest.cls
@isTest
private class rptCurrentPersonalAgentAssignmentsTest {
    
    private static rptCurrentPersonalAgentAssignments ctrl = new rptCurrentPersonalAgentAssignments();
    
    @testSetup
    static void setUp() {
        Service_Location__c servLoc = new Service_Location__c();
        servLoc.Alias__c = '029435';
        servLoc.FacilityId__c = 13.0;
        servLoc.UniqueID__c = '1234';
        servLoc.Program__c = 'Test Program 1';
        servLoc.Name = 'Service Location 1';
        servLoc.ProgramId__c = '029435000';
        servLoc.Location_Nickname__c = 'Loc 1';
        servLoc.State__c = 'OR';
        servLoc.Service_Type__c = 'CM - Case Management';
        insert servLoc;
        
        servLoc = new Service_Location__c();
        servLoc.Alias__c = '564423';
        servLoc.FacilityId__c = 13.0;
        servLoc.UniqueID__c = '5678';
        servLoc.Program__c = 'Test Program 2';
        servLoc.Name = 'Service Location 2';
        servLoc.ProgramId__c = '564423000';
        servLoc.Location_Nickname__c = 'Loc 2';
        servLoc.State__c = 'OR';
        servLoc.Service_Type__c = 'CM - Case Management';
        insert servLoc;
        
        servLoc = new Service_Location__c();
        servLoc.Alias__c = '789546';
        servLoc.FacilityId__c = 13.0;
        servLoc.UniqueID__c = '9012';
        servLoc.Program__c = 'Test Program 3';
        servLoc.Name = 'Service Location 3';
        servLoc.ProgramId__c = '789546000';
        servLoc.Location_Nickname__c = 'Loc 3';
        servLoc.State__c = 'OR';
        servLoc.Service_Type__c = 'CM - Case Management';
        insert servLoc;
    }
    static testMethod void BrokerageTest() {
        List<SelectOption> br = ctrl.getSelectedBroList();
        system.assertEquals(0, br.size());
        
        List<SelectOption> br2 = ctrl.getBrokerageList();
        system.assertEquals(3, br2.size());
        ctrl.runRpt();
        
        Service_Location__c[] locIds = [
            SELECT Id
            FROM Service_Location__c
            WHERE State__c = 'OR'
            AND Service_Type__c = 'CM - Case Management'
            ORDER BY ProgramId__c
        ];
        
        if ( ctrl.selectedBrokerage == null )
            ctrl.selectedBrokerage = new List<Id>();
        ctrl.selectedBrokerage.add( ctrl.brokerageList[0].getValue());
        ctrl.selectedBrokerage.add( ctrl.brokerageList[1].getValue());
        ctrl.selectedBrokerage.add( ctrl.brokerageList[2].getValue());
        ctrl.RemoveBrokerage();
        ctrl.runRpt();
        
        if ( ctrl.select2Brokerage == null )
            ctrl.select2Brokerage = new List<Id>();
        ctrl.select2Brokerage.add( ctrl.selectedBroList[0].getValue());
        ctrl.AddBrokerage();
        ctrl.Reset();
    }
    static testMethod void personalAgentTest() {
        TestUtils.CoreDataGenerator generator = new TestUtils.CoreDataGenerator();
        generator.aliasBuilder.setState('OR');
        generator.serviceLocationBuilder.setState('OR');
        generator.serviceLocationBuilder
            .setServiceType('CM - Case Management')
            .setProgramId('111111000')
            .setLocationNickname('Brokerage 1');
        TestUtils.CoreData coreData = generator.persistData();
        
        insert generator.serviceAssignmentBuilder.getInstance();
        
        TestUtils.UserBuilder userBuilder = new TestUtils.UserBuilder();
        User[] users = new User[]{
            userBuilder.setFirstName('No1').setLastName('User').setUserAlias('no1u').setEmail('no1@test.com').getInstance(),
                userBuilder.setFirstName('No2').setLastName('User').setUserAlias('no2u').setEmail('no2@test.com').getInstance()
                };
                    insert users;
        
        Alias__c alias = [SELECT Id, Name FROM Alias__c];
        TestUtils.TmnUserBuilder tmnUserBuilder = new TestUtils.TmnUserBuilder();
        Tmn_User__c[] personalAgents = new Tmn_User__c[]{
            tmnUserBuilder.setUserId(users[0].Id).setAlias(alias).getInstance(),
                tmnUserBuilder.setUserId(users[1].Id).setAlias(alias).getInstance()
                };
                    insert personalAgents;
        
        test.startTest();
        Service_Location__c[] locIds = [
            SELECT Id,Alias_lookup__c
            FROM Service_Location__c
            WHERE State__c = 'OR'
            AND Service_Type__c = 'CM - Case Management'
            ORDER BY ProgramId__c
        ];
        
        personalAgents[0].Job_Title__c = 'Case Manager';
        personalAgents[0].Alias_lookup__c = locIds[0].Alias_lookup__c;
        update personalAgents[0];        
        
        Service_Assignment__c[] serviceAssignments = [
            SELECT Id FROM Service_Assignment__c
        ];
        
        serviceAssignments[0].service_location__c = locIds[0].id;
        update serviceAssignments[0];
        
        Service_Assignment_Personal_Agent__c[] paAssociations = new Service_Assignment_Personal_Agent__c[] {
            new Service_Assignment_Personal_Agent__c(
                Service_Assignment__c = serviceAssignments[0].Id,
                Personal_Agent__c = personalAgents[0].Id,
                Status__c = 'Active'
            ),
                new Service_Assignment_Personal_Agent__c(
                    Service_Assignment__c = serviceAssignments[0].Id,
                    Personal_Agent__c = personalAgents[1].Id,
                    Status__c = 'Active'
                ),
                new Service_Assignment_Personal_Agent__c(
                    Service_Assignment__c = serviceAssignments[1].Id,
                    Personal_Agent__c = personalAgents[0].Id,
                    Status__c = 'Active'
                )
                };
                    insert paAssociations;        
        
        List<SelectOption> pa = ctrl.getSelectedPAList();
        system.assertEquals(0, pa.size());
        
        ctrl.UpdatePersonalAgents();
        List<SelectOption> pa2 = ctrl.getPAgentList();
        system.assertEquals(1, pa2.size());
        
        if ( ctrl.selectedPA == null )
            ctrl.selectedPA = new List<Id>();
        ctrl.selectedPA.add( ctrl.pAgentList[0].getValue());
        ctrl.RemovePAgent();
        
        if ( ctrl.select3PA == null )
            ctrl.select3PA = new List<Id>();
        ctrl.select3PA.add( ctrl.selectedPAList[0].getValue());
        ctrl.AddPAgent();
        
        ctrl.runRpt();
        ctrl.toDate = Date.today();
        ctrl.fromDate = null;
        ctrl.allCheck = true;
        ctrl.runRpt();
        
        list<rptCurrentPersonalAgentAssignments.rptRow> rptRows = ctrl.rptData;
        system.assertEquals(1, rptRows.size());
        System.assertEquals(0, ctrl.rptData[0].compareTo(ctrl.rptData[0]));
        
        //Testing with Case Management ISP End Date Range
        List<RecordType> rt = [ select id from Recordtype where sobjecttype = 'Case_Management_Plan__c' and developername = 'OR_Combined_ISP' ];
        system.assertEquals(1, rt.size());
        Case_Management_Plan__c testIsp;
        testIsp = new Case_Management_Plan__c( recordtypeid = rt[0].Id);
        testIsp.Name = 'Test plan 1';
        testIsp.Service_Assignment__c = serviceAssignments[0].id;
        testIsp.Status__c = 'Active Final';
        testIsp.PD_End__c = Date.today();
        insert testIsp;
        
        ctrl.toDate = Date.today();
        ctrl.fromDate = Date.today();
        ctrl.runRpt();
        System.assertEquals(0, ctrl.rptData[0].compareTo(ctrl.rptData[0]));
        test.stopTest();
    } 
    
}