src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_Text__c</fullName>
        <formula>CASE( 1,
IF( (YEAR(TODAY())- Year(Birthdate)) ==1,1,100),&quot;1 Year&quot;,
IF( (YEAR(TODAY())- Year(Birthdate)) &gt; 1,1,200), TEXT(FLOOR(((TODAY()) - (Birthdate)+1)/365.2425)) + &quot; Years&quot; ,
IF(YEAR(TODAY()) -Year(Birthdate)==0 &amp;&amp; DAY(Birthdate) - DAY(TODAY())&lt;=0 &amp;&amp; MONTH(TODAY()) - MONTH(Birthdate)==1 ,1,300 ) , &quot;1 Month&quot;,

IF(YEAR(TODAY()) -Year(Birthdate)==0 &amp;&amp; MONTH(TODAY()) - MONTH(Birthdate)&gt;1,1,400), TEXT(MONTH(TODAY()) - MONTH(Birthdate)) +&quot; Months&quot;,
IF( (YEAR(TODAY()) -Year(Birthdate)==0) &amp;&amp; (MONTH(TODAY()) - MONTH(Birthdate)==0 || MONTH(TODAY()) - MONTH(Birthdate)==1) &amp;&amp; (DAY(TODAY() -DAY(Birthdate) )==1),1,500), &quot;1 Day&quot;,

IF( (YEAR(TODAY()) -Year(Birthdate)==0) &amp;&amp; (MONTH(TODAY()) - MONTH(Birthdate)==0 || MONTH(TODAY()) - MONTH(Birthdate)==1) &amp;&amp; (DAY(TODAY() -DAY(Birthdate) )&gt;1),1,600), TEXT( DAY(TODAY() -DAY(Birthdate) ))+&quot; Days&quot;,
&quot;0&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will contain the Record type name of the referral from where the PBS is created. This value will be used by developers to conditionally render stuff on PBS page and related objects - Sravan: Sep 11, 2015</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Select the person&apos;s legal gender</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Associated to Event</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Im_Incidents</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_InvolvedParty__c.object
<CustomObject>
    <description>The individuals involved with the event/incident.</description>
    <fields>
        <fullName>Im_Incident__c</fullName>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served Involved</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Involved</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Person Being Served</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Host Home Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Family Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Im_InvolvedParty</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_InvolvedParties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Alias__c</fullName>
        <formula>Service_Location__r.Alias__c</formula>
        <label>Alias</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will store the Recordtype name of the referral from where the service assignment is created. This will be used by developers to conditionally render stuff on SA page for various flavors. If an adhoc SA is created directly without referral, this field will copy over the value from existing service Assignment available for PBS - Sravan -Sep 11, 2015.</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pbsFirstName__c</fullName>
        <formula>Person_Being_Served__r.FirstName</formula>
        <label>pbsFirstName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pbsLastName__c</fullName>
        <formula>Person_Being_Served__r.LastName</formula>
        <label>pbsLastName</label>
        <type>Text</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for alias. Used to set alias and related fields.</description>
        <label>Alias Lookup</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approval Level</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <description>By default, this will be Active for any person in the database. As time goes and the feed only puts in Active users, we&apos;ll need to update the ones in the database but are not in the feed to Inactive.</description>
        <label>Job Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyRemoteMethods.cls
//do not make this without sharing... or else it would not return the correct list of programs for the logged in user
public with sharing class MyRemoteMethods {
	private transient TxnQueueResponseController parentCntrller;

    class Im_partyData{
        Id id;
        String DT_RowId;
        String name;
        String type;
        String action = '<a class="btn AddEvent" href="javascript:void(0);">Add Events</a>';
        Im_partyData(Im_InvolvedParty__c party){
            this.involvedParty = party;
            this.DT_RowId = String.valueOf(party.id);
            this.id = party.id;
            this.type = party.Type__c;
            if (party.Type__c == 'Person Being Served') this.name = party.Person_Being_Served_Involved__r.pbsFirstName__c + ' ' + party.Person_Being_Served_Involved__r.pbsLastName__c;
            else if (party.Type__c == 'Staff') this.name = party.Staff_Involved__r.name;
            else this.name = party.name;
        }
        Im_InvolvedParty__c involvedParty;
    }
    
	@ReadOnly @RemoteAction public static list<Im_partyData> getInvolvedParties(String EventId) {
        Id event = (EventId instanceof Id) ? (Id) EventId : null;
        list<Im_partyData> dataObj = new list<Im_partyData>();
        for (Im_InvolvedParty__c imPrty : [select id, Type__c, name, Person_Being_Served_Involved__r.pbsFirstName__c, Person_Being_Served_Involved__r.pbsLastName__c, 
        									Staff_Involved__r.name from Im_InvolvedParty__c where Im_Incident__c =: event order by Type__c]){
            dataObj.add(new Im_partyData(imPrty));
        }
        return dataObj;		 
    }

    public list<SelectOption> getMyService_Locations(){
        list<SelectOption> programslist = new list<SelectOption>();
        if (parentCntrller != null &&  String.isEmpty(parentCntrller.incident.event.Service_Location)) programslist.add(new SelectOption('','') );
        list<AggregateResult> slPrgms = [SELECT service_location__r.id slID, service_location__r.Alias__c alias, service_location__r.program__c prgm
                                         FROM service_assignment__c
                                         GROUP BY service_location__r.id, service_location__r.program__c, service_location__r.Alias__c 
                                         HAVING COUNT(service_location__r.id) > 0
                                         ORDER BY service_location__r.program__c];
        for (AggregateResult slPrgm : slPrgms) {
            programslist.add(new SelectOption((Id)slPrgm.get('slID'), String.valueOf(slPrgm.get('alias')) + '-' + String.valueOf(slPrgm.get('prgm')) ));
        }
        return programslist;
    }
    

    
    public MyRemoteMethods(TxnQueueResponseController controller){
    	this.parentCntrller = controller;
    }
    public MyRemoteMethods(){}
    
    class SelOption {
        String id;
        String text;
        String email;
        String jobTitle;
        sobject obj;
        SelOption(sobject obj){
            this.id = String.valueOf(obj.get('Id'));
			if (obj instanceof TMN_User__c){
            	TMN_User__c tmnUser = (TMN_User__c) obj;
	            this.text = tmnUser.name;
	            this.email = tmnUser.email__c;
	            this.jobTitle = tmnUser.job_title__c;
            }
            else if (obj instanceof Service_Assignment__c){
//  					obj.put('HelloThere','HelloThere');          		
            }
            this.obj = obj;
        }
    }
    
    @RemoteAction public static list<SelOption> getPBSFortheProgram(String params){
        map<String, String> values = (Map<String, String>) JSON.deserialize(params, map<String, String>.class);
        if ((!values.keySet().contains('programLocation') || String.IsEmpty(values.get('programLocation')) || !(values.get('programLocation') instanceof Id) )) { throw new CustomException('Missing program location.'); return null; }
        Id sl = ( (Id) values.get('programLocation') );
        String searchTerm = '%' + String.ValueOf(values.get('q')).trim() + '%' ;
        
        list<SelOption> retVal = new list<SelOption>();
        map<Id, Service_Assignment__c> pbsSASet = new map<Id, Service_Assignment__c>();

        list<Service_Assignment__c> sAs = [select Id, person_being_served__c, pbsLastName__c, pbsFirstName__c, person_being_served__r.Age_Text__c, person_being_served__r.Gender__c 
        									 from Service_Assignment__c 
        									where service_location__c =: sl and Status__c = 'Active' 
        									 and (pbsFirstName__c like : searchTerm OR pbsLastName__c like : searchTerm) order by Name];
		for(Service_Assignment__c sa : sAs){
			pbsSASet.put(sa.person_being_served__c, sa);
			retVal.add(new SelOption(sa));
		}        
        for(Attachment headShot : [SELECT Id, Name,  ParentId from Attachment where Name LIKE 'HeadShot-Current%' and ParentId IN : pbsSASet.keySet()]){
			Service_Assignment__c sa = (Service_Assignment__c) pbsSASet.get(headShot.ParentId);
			//chose a dummy on the SA object to carrry the pbs headShot attachment id 
			sa.Flavor__c = '/servlet/servlet.FileDownload?file=' + headShot.id;
        }        
        return retVal;
    }
    
        
    class CustomException extends Exception {}
    
    @RemoteAction public static list<SelOption> getStaffFortheProgram(String params){
        map<String, String> values = (Map<String, String>) JSON.deserialize(params, map<String, String>.class);
        if ((!values.keySet().contains('programLocation') || String.IsEmpty(values.get('programLocation')) || !(values.get('programLocation') instanceof Id) )) { throw new CustomException('Missing program location.'); return null; }   
        Id sl = ( (Id) values.get('programLocation') );
        Id aliasForPrgram = [select Alias_lookup__c from Service_Location__c where id =: sl limit 1].Alias_lookup__c;
        String searchTerm = '%' + String.ValueOf(values.get('q')).trim() + '%' ;
        
        list<SelOption> retVal = new list<SelOption>();
        // get the list of tmn users for the alias based on the service location user must have proviced to call this method else throw exception.  
        for (TMN_User__c t : [select Id, Name, email__c, job_title__c from TMN_User__c where Alias_Lookup__c =: aliasForPrgram and Job_Status__c = 'Active' and Name like : searchTerm order by Name]){
            retVal.add(new SelOption(t));
        } 
        //return JSON.serialize(retVal);
        return retVal;
    }
    
    @RemoteAction public static list<SelOption> getEventReviewerForProgram(String params){
        map<String, String> values = (Map<String, String>) JSON.deserialize(params, map<String, String>.class);
        if ((!values.keySet().contains('programLocation') || String.IsEmpty(values.get('programLocation')) || !(values.get('programLocation') instanceof Id) )) { throw new CustomException('Missing program location.'); return null; }   
        Id sl = ( (Id) values.get('programLocation') );
        Id aliasForPrgram = [select Alias_lookup__c from Service_Location__c where id =: sl limit 1].Alias_lookup__c;
        String searchTerm = '%' + String.ValueOf(values.get('q')).trim() + '%' ;
        
        list<SelOption> retVal = new list<SelOption>();
        // get the list of tmn users for the alias based on the service location user must have proviced to call this method else throw exception.  
        for (TMN_User__c t : [select Id, Name, email__c, job_title__c from TMN_User__c 
                              where Salesforce_User_Account__c != null 
                              and Salesforce_User_Account__c !=: UserInfo.getUserId()
                              and Job_Status__c = 'Active' 
                              and Alias_Lookup__c =: aliasForPrgram
                              and Approval_Level__c > 2 
                              and Name like : searchTerm 
                              order by Name] ){
                                  retVal.add(new SelOption(t));
                              } 
        //return JSON.serialize(retVal);
        return retVal;
    }
    
}