src/objects/Alias__c.object
<CustomObject>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <formula>Service_Code__r.Program_Rollup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <formula>Service_Code__r.Program_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Detail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Service_Assignment__r.Program__c</formula>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <inlineHelpText>Location that the service took place.</inlineHelpText>
        <label>Service Location</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Mental Health Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MR Intermediate Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office/TRAC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Value__c</fullName>
        <label>Program Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacilityID__c</fullName>
        <label>FacilityID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueID__c</fullName>
        <description>unique id from source db</description>
        <externalId>true</externalId>
        <label>UniqueID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DocumentedActualStaffHrsReportTest.cls
@isTest
private class DocumentedActualStaffHrsReportTest {

	static ID createServiceLocation( string alias, string pgmCode, string pgmVal, integer facility, string slState, string uid ) {
		
		Service_location__c newSL = new Service_location__c( alias__c = alias, programid__c = pgmCode, program__c = pgmVal, facilityid__c = facility, state__c = slState, uniqueid__c = uid);
		insert newSL;
		
		return newSL.Id;
		
	}
	
	static testMethod void testStateProgList() {
		
		ID newSLid1a = createServiceLocation( '123456', '123456001', 'New Service Location 1a', 1, 'AZ', '1-123456a' );
		ID newSLid1b = createServiceLocation( '123456', '123456002', 'New Service Location 1b', 1, 'AZ', '1-123456b' );
		ID newSLid2 = createServiceLocation( '223456', '223456001', 'New Service Location 2', 1, 'CA', '223456a' );
		
		DocumentedActualStaffHrsRpt dashRpt = new DocumentedActualStaffHrsRpt();
        
        List<SelectOption> states = dashRpt.states;
        System.AssertEquals(2, states.size());
		
		List<SelectOption> progs = dashRpt.programs;
		System.AssertEquals(3, progs.size());	
	
	
	}
	
	static testMethod void testStartEndDateVal() {
		
        DocumentedActualStaffHrsRpt dashRpt = new DocumentedActualStaffHrsRpt();
        dashRpt.fStartDate = Date.newInstance(2014, 4, 1);
        dashRpt.fEndDate = Date.newInstance(2013, 6, 1);
        
        PageReference rpt = dashRpt.runReport();
        System.AssertEquals( rpt, null);         
		
	}
    static testMethod void myUnitTest() {
        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();                        
        
        DocumentedActualStaffHrsRpt dashRpt = new DocumentedActualStaffHrsRpt();
        dashRpt.getListStaffHrsInfo();
        dashRpt.fStartDate = Date.newInstance(2013, 1, 1);
        dashRpt.fEndDate = Date.newInstance(2014, 6, 1);
        dashRpt.selStates = new List<string>{'AZ'};
        
        ID slId = createServiceLocation( '123456', '123456001', 'New Service Location 1a', 1, 'AZ', '1-123456a' );
        
        Service_code__c theServiceCode = new Service_Code__c(
            Service_Code__c = 'H2022',
            FacilityID__c = '1',
            Program_Code__c = '123456001',
            Program_Value__c = 'New Service Location 1a',
            Start_Date__c = date.newInstance(2000, 1, 1),
            state__c = 'AZ'
        );
        insert theServiceCode;
        theServiceCode= [select service_code__c, facilityid__c, program_code__c, program_value__c, start_date__c, state__c from service_code__c where id = :theServiceCode.Id LIMIT 1];

        myData.theSA.program_detail__c = 'New Service Location 1a';
        update myData.theSA;
        
        dashRpt.selPrograms = new List<string>{'New Service Location 1a'};
        
        // create a progress note
        Progress_note__c myPN = TMN_Generic_Core_TestData.createProgressNote(myData.theSA, myData.theAdm, theServiceCode, myData.theSA.Person_being_served__c);
       
        dashRpt.runReport();         
        
        DocumentedActualStaffHrsRpt.StaffHrsInfo staffHrsInfo =
        new DocumentedActualStaffHrsRpt.staffHrsInfo();
        System.assertEquals(null, staffHrsInfo.clinician);
        System.assertEquals(null, staffHrsInfo.pbs);
        System.assertEquals(null, staffHrsInfo.phase);
        System.assertEquals(null, staffHrsInfo.totalMinutes); 
        System.assertEquals(null, staffHrsInfo.hours);         
        
        DocumentedActualStaffHrsRpt.StaffHrsInfo staffHrsInfo2 =
            new DocumentedActualStaffHrsRpt.staffHrsInfo();
            
        staffHrsInfo2.clinician = 'Jack Jones';
        staffHrsInfo2.pbs = myData.theSA.Person_Being_Served__c;
        staffHrsInfo2.phase = String.valueOf(myData.theSA.Phase__c);
        staffHrsInfo2.totalMinutes = '120'; 
        staffHrsInfo2.hours = '2';    
        
        DocumentedActualStaffHrsRpt.StaffHrsInfo staffHrsInfo3 =
            new DocumentedActualStaffHrsRpt.staffHrsInfo();
            
        staffHrsInfo3.clinician = 'Jack Jones';
        staffHrsInfo3.pbs = myData.theSA.Person_Being_Served__c;
        staffHrsInfo3.phase = String.valueOf(myData.theSA.Phase__c);
        staffHrsInfo3.totalMinutes = '120'; 
        staffHrsInfo3.hours = '2';    
        
            
        System.assert(staffHrsInfo.compareTo(staffHrsInfo2) != 0);  
        System.assert(staffHrsInfo2.compareTo(staffHrsInfo) != 0);
        System.assert(staffHrsInfo3.compareTo(staffHrsInfo2) == 0);
                                    
    }
}