src/objects/Alias__c.object
<CustomObject>
    <fields>
        <fullName>Alias_State__c</fullName>
        <label>Alias State</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Alias</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Annotation_Height__c</fullName>
        <label>Annotation Height</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annotation_Shape__c</fullName>
        <label>Annotation Shape</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annotation_Source__c</fullName>
        <label>Annotation Source</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Annotation_Text__c</fullName>
        <label>Annotation Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Annotation_Width__c</fullName>
        <label>Annotation Width</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annotation_X__c</fullName>
        <label>Annotation X</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annotation_Y__c</fullName>
        <label>Annotation Y</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ImInvolvedPartyAnnotations__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ImInvolvedPartyAnnotations</label>
        <referenceTo>Im_InvolvedParty__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TMN_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Annotation</fullName>
        <active>true</active>
        <label>Annotation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Evaluation</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Evaluation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>ReportedEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the id of the initial event... need to populated it on the copy of the reported event that the qualifier will work on.</description>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>ReportedEvent</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supervisor_for_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Not required if Supervisor field is the same.</description>
        <inlineHelpText>Not required if Supervisor field is the same.</inlineHelpText>
        <label>Supervisor for Location</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_Incidents (Supervisor for Location)</relationshipLabel>
        <relationshipName>LocationSupervisorIncidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_InvolvedParty__c.object
<CustomObject>
    <description>The individuals involved with the event/incident.</description>
    <fields>
        <fullName>Im_Incident__c</fullName>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Involved</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_InvolvedParty</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_InvolvedParties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for alias. Used to set alias and related fields.</description>
        <label>Alias Lookup</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approval Level</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <description>By default, this will be Active for any person in the database. As time goes and the feed only puts in Active users, we&apos;ll need to update the ones in the database but are not in the feed to Inactive.</description>
        <label>Job Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncidentModel.cls
public with sharing class IncidentModel {
	public enum Stage { EVENT, QUALIFYING, INCIDENT, RESPONSE }

	public static Boolean checkLocked(IncidentModel.Stage stage, Im_Incident__c incident) {
		if (incident.Id == null) {
			return false;
		}
		if (stage == IncidentModel.Stage.EVENT) {
			// if the event is disregarded or submitted
			// OR this is the event that is a result of of an event submit
			// OR if there is a lock on the event because of its submit
			return incident.Status__c == 'Event-Submitted'
				|| incident.Status__c == 'Event-Disregarded'
				|| String.IsNotBlank(incident.ReportedEvent__c)
				|| Approval.isLocked(incident.Id);
		} else if (stage == IncidentModel.Stage.QUALIFYING) {
			return incident.Status__c == 'Event-Closed'
				|| Approval.isLocked(incident.Id);
		} else if (stage == IncidentModel.Stage.INCIDENT) {
			return incident.Status__c == 'Incident-Final'
				|| incident.Status__c == 'Incident-Disregarded'
				|| Approval.isLocked(incident.Id);
		} else {
			return false;
		}
	}

	public static Task[] createIncidentFinalizationTasks(Im_Incident__c[] incidents) {
		System.debug('create incident finalization tasks for: ' + incidents);
		Task[] newTasks = new Task[]{};
		for (Im_Incident__c incident: incidents) {
			newTasks.add(new Task(
				Status = 'Not Started',
				Subject = 'Please submit the Incident report for review',
				ActivityDate = incident.CreatedDate.addDays(2).date(),
				Priority = 'High',
				OwnerId = incident.OwnerId,
				WhatId = incident.Id
			));
		}
		insert newTasks;
		return newTasks;
	}

	/**
	 * Find reviewers for a certain state.
	 * @param the name of the reviewer to search for.
	 * @param state a 2 letter abbreviation for a state.
	 * @return a list of Tmn_User__c who can review an incident.
	 */
	public static Tmn_User__c[] findReviewers(String query, String state) {
		return [
			SELECT Id, Name, Job_Title__c, Email__c
			  FROM Tmn_User__c
			 WHERE Approval_Level__c >= 4
			   AND Salesforce_User_Account__c != null
				 AND Salesforce_User_Account__c != :UserInfo.getUserId()
				 AND Job_Status__c = 'Active'
			   AND Alias_Lookup__r.Alias_State__c = :state
			   AND Name LIKE :query
		];
	}

	public static void cloneIncidents(Map<Id,Im_Incident__c> incidentsToClone) {
		list<String> selectFields = new list<string>();
		set<Id> incidentIds = incidentsToClone.keySet();
		Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe()
			.get('Im_Incident__c').getDescribe().Fields.getMap();
		if (fMap != null) {
			for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
				Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
				selectFields.add(fd.getName());
			}
		}
		selectFields.addAll(
			new List<String> { 'Supervisor_for_Location__r.Salesforce_User_Account__c' }
		);

		list<String> selectFields2 = new list<string>();
		Map<String, Schema.SObjectField> fMap2 = Schema.getGlobalDescribe().get('Im_InvolvedParty__c').getDescribe().Fields.getMap();
		if (fMap2 != null) {
			for (Schema.SObjectField ft : fMap2.values()){ // loop through all field tokens (ft)
				Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
				selectFields2.add(fd.getName());
			}
		}
		String strSQL =  'SELECT ' + String.join(selectFields, ',')
			+ ', (SELECT ' + String.join(selectFields2, ',')
			+ ' FROM Im_InvolvedParties__r )'
			+ ' FROM Im_Incident__c WHERE Id IN :incidentIds ';
		system.debug('Incident clone strSQL: ' + strSQL);
		list<Im_Incident__c> incidents = Database.query(strSQL);

		map<id,Im_InvolvedParty__c> oldToNewInvPrtyMap = new map<id,Im_InvolvedParty__c>();
		for (Im_Incident__c incident : incidents){
			//clone(Boolean preserveId, Boolean isDeepClone, Boolean preserveReadonlyTimestamps, Boolean preserveAutonumber)
			Im_Incident__c incidentClone = incident.clone(false, true, false, false);
			incidentClone.Status__c = 'Event-Qualifying';
			incidentClone.ReportedEvent__c = incident.id; // the orignal incident reported
			incidentClone.OwnerId = incident.Supervisor_for_Location__r.Salesforce_User_Account__c; // we need to do this so that the task is created for this user
			insert incidentClone;
			for(Im_InvolvedParty__c invPrty : incident.Im_InvolvedParties__r){
				Im_InvolvedParty__c involvedParty = invPrty.clone(false, true, false, false);
				involvedParty.Im_Incident__c = incidentClone.id;
				oldToNewInvPrtyMap.put(invPrty.id, involvedParty);
			}
			insert oldToNewInvPrtyMap.values();
		}

		//clone evalValues
		list<String> selectFields3 = new list<string>();
		Map<String, Schema.SObjectField> fMap3 = Schema.getGlobalDescribe()
			.get('Eval_Value__c').getDescribe().Fields.getMap();
		if (fMap3 != null) {
			for (Schema.SObjectField ft : fMap3.values()){ // loop through all field tokens (ft)
				Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
				selectFields3.add(fd.getName());
			}
		}
		Set<Id> invPryIds = new set<Id>(oldToNewInvPrtyMap.keySet());
		String strSQL2 =  'SELECT ' + String.join(selectFields3, ',') + ', Eval__r.HtmlId__c FROM Eval_Value__c WHERE what_id__c IN : invPryIds';
		system.debug('eval_values to clone strSQL: ' + strSQL2);
		list<Eval_Value__c> evalValues = Database.query(strSQL2);

		list<Eval_Value__c> evalValuesClones = new list<Eval_Value__c>();
		for(Eval_Value__c ev : evalValues){
			Eval_Value__c evClone = ev.clone(false, true, false, false);
			if (evClone.eval__r.htmlId__c.equalsIgnoreCase('isValid')) {
				// Turn all the sections to invalid, since there will be additional Qualifier questions
				evClone.Boolean__c = false;
			}
			evClone.what_id__c = oldToNewInvPrtyMap.get(ev.what_id__c).id;
			evalValuesClones.add(evClone);
		}
		insert evalValuesClones;

		// clone evaluation responses - for the body map annotations
		list<Evaluation_Response__c> evalResponsesClone = new list<Evaluation_Response__c>();
		for(Evaluation_Response__c evalResp : [
				SELECT ID, Annotation_Height__c, Annotation_Width__c, Annotation_X__c,
				       Annotation_Y__c, Annotation_Source__c, Annotation_Shape__c,
				       Annotation_Text__c, ImInvolvedPartyAnnotations__c
				  FROM Evaluation_Response__c WHERE ImInvolvedPartyAnnotations__c IN :oldToNewInvPrtyMap.keySet()
				    AND RecordType.Name = 'Annotation'
		]){
			Evaluation_Response__c evalRespClone = evalResp.clone(false, true, false, false);
			evalRespClone.ImInvolvedPartyAnnotations__c = oldToNewInvPrtyMap.get(evalResp.ImInvolvedPartyAnnotations__c).id;
			evalRespClone.Annotation_Source__c = evalRespClone.Annotation_Source__c.replace(String.ValueOf(evalResp.ImInvolvedPartyAnnotations__c), String.ValueOf(oldToNewInvPrtyMap.get(evalResp.ImInvolvedPartyAnnotations__c).id));
			evalResponsesClone.add(evalRespClone);
		}
		insert evalResponsesClone;
	}
}