src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AssessmentQuestionCount__c</fullName>
        <label>AssessmentQuestionCount</label>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AssessmentResponseCount__c</fullName>
        <description>A field to roll-up and count the number of &quot;answers&quot; that have been dropped into the child Assessment_Response__c object so we can use an Apex trigger to then count the expected &quot;answers&quot; for a given assessment, make a comparison, and prevent changing the Status__c field of the Assessment object to &quot;locked&quot; if the count of expected answers is less than the count of answers entered.</description>
        <label>AssessmentResponseCount</label>
        <summaryFilterItems>
            <field>Assessment_Response__c.Response_Has_Value__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Assessment that this one is cloned from</description>
        <label>Previous</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAD Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restraint Reduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Adult</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Domain__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Sort order for page / domain</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Domain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Domain_Result__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Assessment_Domain__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Domain Results</relationshipLabel>
        <relationshipName>Assessment_Domain_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Domain Results</relationshipLabel>
        <relationshipName>Assessment_Domain_Results_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment_Domain_Result__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>Assessment_Domain__r.Sort_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Assessment_Domain__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Assessment Domain Result</label>
    <nameField>
        <label>Assessment Domain Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domain Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Is_MultiSelect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MultiSelect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Question_Option__c.object
<CustomObject>
    <description>ASSESSMENT  - Potential Question Responses and Detailed Descriptions</description>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Relationship to Question Table</description>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Question Options</relationshipLabel>
        <relationshipName>Assessment_Question_Option</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score potential Values</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The Score for this Rating</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Question Option</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionDetailID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment_Domain_Result__c</fullName>
        <label>Assessment Domain Result</label>
        <referenceTo>Assessment_Domain_Result__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score entered by user</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>85</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>MAR_Section_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MAR Section Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>COMPLIANCE SURVEY Stores all the questions for a compliance survey</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Y/N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Question</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Compliance Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/fallAssessmentComponentController.cls
public with sharing class fallAssessmentComponentController {
	public Evaluation__c evaluation { get; set; }

	//  private Apexpages.StandardController controller { get; set; }
	public Assessment__c asmt { get; set; }
	public Id thisevaluationId { get; set; }
	public string domainName { get; set; }
	public Boolean displayError { get; set; }

	//Maps
	public Map<ID, Assessment_Domain__c> MapDomains = new Map<ID, Assessment_Domain__c>();
	public Map<ID , Assessment_Domain__c> getMapDomains() {
		return MapDomains;
	}
	//the id is from the question
	public Map<ID , Assessment_Response__c> MapAnswers = new Map<ID , Assessment_Response__c>();
	public Map<ID , Assessment_Response__c> getMapAnswers ()
	{return MapAnswers;}
	public Map<ID , Assessment_Question__c> MapQuestions = new Map<ID , Assessment_Question__c>();
	public Map<ID , Assessment_Question__c> getMapQuestions() {
		return MapQuestions;
	}
	//VF args
	public id questionID { get; set; }
	public id DomainResultID { get; set; }
	public string MyRating { get; set; }
	public string MyColor { get; set; }
	public double MyScore { get; set; }
	//end VF args

	//Constructor
	public fallAssessmentComponentController() {
		thisevaluationId = ApexPages.currentPage().getParameters().get('evalID');
		evaluation = [SELECT Id, Name, MAR_Section_Completed__c  FROM Evaluation__c WHERE Id = :thisevaluationId];
		Assessment__c[] assmts = [
			SELECT Id, Name,Previous__c, Type__c, Evaluation__c, AssessmentQuestionCount__c, AssessmentResponseCount__c
			  FROM Assessment__c where Evaluation__c = :thisevaluationId AND Type__c = 'Resident Assessment' limit 1];
		if (assmts.size() > 0) {
			this.asmt = assmts[0];
		}
		displayError = false;
	}

	//Initialization
	public void LoadData(Assessment__c TheVoidsAssessment){
		//Loops to set maps up
		for (Assessment_Domain__c me : ListForMapDomains){
			MapDomains.put(me.id,  me);
		} //End Loop

		for (Assessment_Question__c mee : ListForMapQuestions){
			MapQuestions.put(mee.ID,  mee);
		}
		//End loop

		for(Assessment_Response__c meee : getListForMapCurrentResponses()) {
			MapAnswers.put(meee.Question__c,  meee);
		}
	}

	//End of Initialization
	//Action from VF Page
	public pageReference myUpsert() {
		Assessment_Question__c aq = new Assessment_Question__c();
		aq = MapQuestions.get(questionID);
		Assessment_Response__c ar = new Assessment_Response__c();
		ar = MapAnswers.get(questionID);
		ar.Color__c = MyColor;

		if (aq.Is_MultiSelect__c && ar.Rating__c != null){
			ar.Rating__c += ';'+MyRating;
			ar.Score__c += MyScore;
		} else {
			ar.Rating__c = MyRating;
			ar.Score__c = MyScore;
		}

		if (aq.Is_MultiSelect__c && ar.Rating__c.Contains('None')){
			ar.Rating__c = MyRating;
			ar.Score__c = MyScore;
		}
		try {
			upsert ar;
			updateEvalValue(this.domainName);

		} catch(DMLException e) {
			ApexPages.addMessages(e);
		}
		//odd that this isn't needed ->  MapAnswers.put(questionID, AR);
		return null;

	}

	public PageReference clearSelection() {
		Assessment_Response__c ar = new Assessment_Response__c();
		ar = MapAnswers.get(questionID);
		ar.Rating__c = null;
		ar.Score__c = null;
		try {
			update ar;
			updateEvalValue(this.domainName);
		} catch(DMLException e) {
			ApexPages.addMessages(e);
		}

		return null;
	}

	public void updateEvalValue(string domainName) {
		if (domainName == 'Fall Risk Assessment Domain') {
			displayError = fallAssessmentComponentController.validateError(this.evaluation.Id, 'Fall Risk Assessment Domain');
			Eval_Value__c[] value = [
				SELECT Id, Boolean__c
				  FROM Eval_Value__c
				 WHERE What_Id__c = :this.evaluation.Id AND Eval__r.Field_Name__c = 'IsValid'
				   AND Eval__r.Category__c = 'Fall Risk Assessment'
				   AND Eval__r.Sub_Category__c = 'Fall Assessment'
			];
			if (value.size() > 0) {
				value[0].Boolean__c = !displayError;
				update value[0];
			}
		}

		if (domainName == 'Skin Assessment Domain') {
			displayError = fallAssessmentComponentController.validateError(this.evaluation.Id, 'Skin Assessment Domain');
			Eval_Value__c[] value = [
				SELECT Id, Boolean__c
				  FROM Eval_Value__c
				 WHERE What_Id__c = :this.evaluation.Id
				   AND Eval__r.Field_Name__c = 'IsValid'
				   AND Eval__r.Category__c = 'Skin/Body'
				   AND Eval__r.Sub_Category__c = 'Skin Assessment'
			];
			if (value.size() > 0) {
				value[0].Boolean__c = !displayError;
				update value[0];
			}
		}
	}

	public static boolean validateError(Id evalId, string DomainName) {
		Boolean error = false;
		List<Assessment_Response__c> currentResponses = [
			SELECT Id, Rating__c
			  FROM Assessment_Response__c
			 WHERE Assessment__r.Evaluation__c = :evalId
			   AND Question__r.Question_Domain__r.Name = :DomainName
		];
		for(Assessment_Response__c resp: currentResponses){
			if(resp.Rating__c == null){
				error = true;
				break;
			}
		}
		return error;
	}

	//This is used in the VF Page, it is the root repeat.

	public List<Assessment_Domain_Result__c> ThisRecordsDomains;
	public List<Assessment_Domain_Result__c> getThisRecordsDomains() {
		LoadData(this.asmt);
		return [
			Select Name, ID, Sort_Order__c, Assessment_Domain__c, Title__c, Total_Questions__c,
			       Answered_Questions__c, Score__c
			  From Assessment_Domain_Result__c
			 Where Assessment__c = :this.asmt.Id
			   And Assessment_Domain__r.Name = :domainName Order By Sort_Order__c
		];
	}



	//This is loaded into a map
	//Get a list of current responses.

	public List<Assessment_Response__c> getListForMapCurrentResponses(){
		return [
			Select ID,  Name, Question__c,Score__c, Rating__c, Color__c,
			       Question__r.Question_Domain__r.Name, Question__r.Question_Title__c
			  From Assessment_Response__c
			 Where Assessment__c = :this.asmt.id
			   And Assessment_Domain_Result__r.Assessment_Domain__r.Name = :domainName
		];
	}



	//This is loaded into a map
	//The Inner Select is used to loop through on the VF page. The sort by is key
	public List<Assessment_Question__c> ListForMapQuestions
	{
		get {
			return [
				Select ID, Question_Number__c, Question_Title__c, Name, Question_Description__c,
				       Assessment_Type__c, Is_MultiSelect__c, Question_Domain__r.Name,
				       (Select Name, Score__c, Rating__c, Color__c, Rating_Description__c
				          From Assessment_Question_Option__r
				        Order By sort_order__c asc)
				  From Assessment_Question__c
				 Where Question_Domain__r.Assessment_Type2__c = 'Resident Assessment'
				   And Question_Domain__r.Name= :domainName
			];
		}
		set;
	}

	//Same as all questions

	public List<Assessment_Domain__c> ListForMapDomains
	{
		get {
			return [
				Select ID,  Name, Description__c, Assessment_Type__c,
				       (Select Name, ID, Question_Description__c, Is_MultiSelect__c, Question_Title__c, Question_Number__c
				          From Question__r
				        Order By Question_Number__c)
				  From Assessment_Domain__c
				 Where Assessment_Type2__c = 'Resident Assessment'
				   And Name= :domainName
			];
		}
		set;
	}
}