src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Domain__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Assessment_Type2__c</fullName>
        <label>Assessment Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAD Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restraint Reduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immunization - Adult</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Type</label>
        <referenceTo>Assessment_Type__c</referenceTo>
        <relationshipLabel>Assessment Domains</relationshipLabel>
        <relationshipName>Assessment_Domains</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Sort order for page / domain</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Domain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domains</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Domain_Result__c.object
<CustomObject>
    <description>ASSESSMENT</description>
    <fields>
        <fullName>Assessment_Domain__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assessment Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Domain Results</relationshipLabel>
        <relationshipName>Assessment_Domain_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <formula>Assessment_Domain__r.Assessment_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assessment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Domain Results</relationshipLabel>
        <relationshipName>Assessment_Domain_Results_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment_Domain_Result__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <formula>Assessment_Domain__r.Sort_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Domain Result</label>
    <nameField>
        <label>Assessment Domain Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Domain Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <formula>Question_Domain__r.Assessment_Type__r.Id</formula>
        <label>Assessment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_MultiSelect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MultiSelect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Description__c</fullName>
        <description>Description of the Question</description>
        <label>Question Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Domain</label>
        <referenceTo>Assessment_Domain__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>Number of the Question</description>
        <label>Question Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Title__c</fullName>
        <description>Title of the Question</description>
        <label>Question Title</label>
        <type>TextArea</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Question_Option__c.object
<CustomObject>
    <description>ASSESSMENT  - Potential Question Responses and Detailed Descriptions</description>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Relationship to Question Table</description>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Question Options</relationshipLabel>
        <relationshipName>Assessment_Question_Option</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating_Description__c</fullName>
        <description>Detailed description of the rating</description>
        <label>Rating Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score potential Values</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The Score for this Rating</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Question Option</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionDetailID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Question Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment_Domain_Result__c</fullName>
        <label>Assessment Domain Result</label>
        <referenceTo>Assessment_Domain_Result__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score entered by user</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_Type__c.object
<CustomObject>
    <description>ASSESSMENT -</description>
    <label>Assessment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>COMPLIANCE SURVEY Stores all the questions for a compliance survey</description>
    <label>Compliance Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Compliance Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/restraintReductionController.cls
public with sharing class restraintReductionController {
	
	public ID assId{get;  set;}
	
	public List<Assessment_Question__c> questions{get{
		
			if(questions == null){
				List<Assessment_Question__c> restraintQuestions= [Select ID, Question_Number__c, Question_Title__c, Name, Question_Description__c, Assessment_Type__c, Is_MultiSelect__c,Question_Domain__c, Question_Domain__r.Name, 
                            		(Select Name, Score__c, Rating__c, Color__c, Rating_Description__c 
                                    From Assessment_Question_Option__r 
                                    Order By sort_order__c asc)  
                   					From Assessment_Question__c 
                    				Where Question_Domain__r.Name = 'Restraint Questions' AND  Question_Domain__r.Assessment_Type2__c = 'Restraint Reduction'];
				return restraintQuestions;
			}
				return null;
				
		}
		
		set;}
		
	public Assessment__c assessment{get{
		if(assessment == null){
			assessment = [SELECT Id, Name, Status__c, Disregard__c FROM Assessment__c WHERE Id=: assId];
			
		}
		return assessment;
		}
		set;}
	
	//VF Args
	public id questionID {get;set;}
    //public id DomainResultID {get; set;}
    public string MyRating {get;set;}
    public string MyColor {get; set;}
    public double MyScore {get;set;}
    
	public Map<id,Assessment_Response__c> questionResponseMap {get{
		Map<id,Assessment_Response__c> respMap = new Map<id,Assessment_Response__c>();
		List<Assessment_Response__c> restraintResponses =  [Select ID,  Name, Question__c,Score__c, Rating__c, Color__c, Question__r.Question_Domain__r.Name, Question__r.Question_Title__c
                            								From Assessment_Response__c 
                           									Where Assessment__c = :assId AND Assessment_Domain_Result__r.Assessment_Domain__r.Name = 'Restraint Questions'];
		
		for(Assessment_Response__c ar: restraintResponses){
			respMap.put(ar.Question__c, ar);
		}
		
		return respMap;
	}
	 set;}
		 
	public Map<id,Assessment_Question__c> questionsMap{get{
		
		Map<id,Assessment_Question__c> qMAp = new Map<id,Assessment_Question__c>();
			for(Assessment_Question__c q: questions){
      			qMAp.put(q.Id,q);
      		}
		
			return qMAp;
	}	
	set;}
	//public List<Assessment_Question__c> questions{get;set;}
	
	public restraintReductionController(){
	//Nothing in Constructor because attribute value loads after constructor is executed
	
	}
	
	public pageReference myUpsert() {
        system.debug('I am inside Upserttttttttt');
        Assessment_Question__c aq = new Assessment_Question__c();
        aq = questionsMap.get(questionID);
        Assessment_Response__c ar = new Assessment_Response__c();
            ar = questionResponseMap.get(questionID); 
            ar.Color__c = MyColor;
           
            if(aq.Is_MultiSelect__c && ar.Rating__c != null){
                ar.Rating__c += ';'+MyRating;
                ar.Score__c += MyScore;
            }
            else{
                ar.Rating__c = MyRating;
                 ar.Score__c = MyScore;
            }
            
            if(aq.Is_MultiSelect__c && ar.Rating__c.Contains('None')){
                ar.Rating__c = MyRating;
                 ar.Score__c = MyScore; 
            }
            try{
                    upsert ar;
                    //updateevalValue(this.domainName);
                    
            }
            catch(DMLException e){
                    ApexPages.addMessages(e);
            }
            
        return null;

    }
    
    public pageReference disregard(){
    	assessment.Status__c = 'Disregard';
    	assessment.Disregard__c = true;
    	update assessment;
    	return null;
    }
    
    

}