src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Assessment_Response__c.Score__c</summarizedField>
        <summaryForeignKey>Assessment_Response__c.Assessment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assessment_Question__c.object
<CustomObject>
    <description>ASSESSMENT  - Question for Assessment</description>
    <fields>
        <fullName>Dev_Name__c</fullName>
        <label>Dev Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>QuestionID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Assessment_Response__c.object
<CustomObject>
    <description>ASSESSMENT  - Individual score valiues for a person&apos;s assessmemt</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <description>Relationship to Assessment Junction Object</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Assessment_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Assessment_Question__c</referenceTo>
        <relationshipLabel>Assessment Response</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Rating / Score entered by user</description>
        <label>Rating</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yes_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Yes/No</label>
        <type>Checkbox</type>
    </fields>
    <label>Assessment Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AssessmentResponseID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Assessment_FAD_Form_Ex_Test.cls
@isTest
private class Assessment_FAD_Form_Ex_Test {

    static testMethod void myUnitTest() {
    	
    	User theCurrentUser = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
    	List<PermissionSet> thePermSets = [ SELECT Id FROM PermissionSet WHERE Name IN ('ESD_Notes_Organizer', 'ESD_Notes_Supervisor') ];
    	
    	List<PermissionSetAssignment> thePermSetAssigns = new List<PermissionSetAssignment>();
    	List<PermissionSetAssignment> existingPermSetAssignsForUser = [ SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = :theCurrentUser.Id ];
    	
    	
    	for(PermissionSet p : thePermSets) {
    		Boolean skipTheInsert = false;
    		for(PermissionSetAssignment pSA : existingPermSetAssignsForUser) {
    			if(p.Id==pSA.PermissionSetId) {
    				skipTheInsert = true;
    			}    			
    		}
    		if(skipTheInsert==false) {
    			thePermSetAssigns.add(new PermissionSetAssignment(PermissionSetId = p.Id, AssigneeId = theCurrentUser.Id));
    		}
    	}
    	insert thePermSetAssigns;
    	
        Assessment_Fad_TestData.createTestData();
        
        Assessment__c assess=  Assessment_Fad_TestData.createAssessment();
        Assessment_FAD_Form_Ex controller = new Assessment_FAD_Form_Ex(new ApexPages.StandardController(assess)); 
        
        controller.getCanSubmit();
        controller.myCG_is_same_as_other_assessment();
        controller.getRelParty();
        
        controller.myDisregard();    
        system.assertEquals(assess.Disregard__c,true);
    
        system.assertEquals(controller.getCanSubmit(),true);
        system.assertEquals(controller.getcanUnlock(),true);
        
        controller.myUnlock();
        system.assertEquals(assess.status__c, 'Open');
        
        controller.mapRes.get('PBS_Problem_Solving').Score__c = 1.23;
        controller.mySave();
        assessment_response__c testAR = new assessment_response__c();
        testAR = [select score__c from assessment_response__c where assessment__c = :assess.id AND Question__r.Dev_Name__c = 'PBS_Problem_Solving'];
        system.assertEquals(testAR.score__c, 1.23);        
        
        controller.myEdit();
        //the record is locked so edit mode should be alloweed
        system.assertEquals(controller.mode,'edit');

		controller.mapRes.get('PBS_Problem_Solving').Score__c = null;
		controller.mapRes.get('CG_Could_Not_complete').Yes_No__c = true;
		controller.mapRes.get('PBS_Could_Not_complete').Yes_No__c = true;
		controller.myLock();		
        //we're not answering any questions so the record should not lock		
		system.assertEquals(assess.status__c, 'Open');
		
		controller.mapRes.get('CG_Could_Not_complete').Yes_No__c = false;
		controller.mapRes.get('PBS_Could_Not_complete').Yes_No__c = false;
		controller.mapRes.get('PBS_Problem_Solving').Score__c = 1.23;
		controller.mapRes.get('PBS_Communication').Score__c = 1.2;
		controller.mapRes.get('PBS_Roles').Score__c = 1.2;
		controller.mapRes.get('PBS_Affective_Responses').Score__c = 1.2;
		controller.mapRes.get('PBS_Affective_Involvement').Score__c = 1.2;
		controller.mapRes.get('PBS_Behavior_Control').Score__c = 1.2;
		controller.mapRes.get('PBS_General_Functioning').Score__c = 1.2;
		controller.mapRes.get('CG_Problem_Solving').Score__c = 1.2;
		controller.mapRes.get('CG_Communication').Score__c = 1.2;
		controller.mapRes.get('CG_Roles').Score__c = 1.2;
		controller.mapRes.get('CG_Affective_Responses').Score__c = 1.2;
		controller.mapRes.get('CG_Affective_Involvement').Score__c = 1.2; 
		controller.mapRes.get('CG_Behavior_Control').Score__c = 1.2;
		controller.mapRes.get('CG_General_Functioning').Score__c = 1.2;
		controller.mapRes.get('CG_is_same_as_other_assessment').Rating__c = 'Yes';
			
        controller.myLock();
        //now we have answered questions the record should lock
        system.assertEquals(assess.status__c, 'Locked');        
        
        controller.myCancel();
        assessment__c[] allassess = [select id from assessment__c];
        system.assertEquals(allassess.size(),0);
    }

    

    
}