src/objects/Assessment__c.object
<CustomObject>
    <description>ASSESSMENT - Stores basic assessment info</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <description>Gets the Account ID from the admission lookup and sets the accountperson field in the trigger</description>
        <formula>Admission__r.Person_Being_Served__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountPerson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Person Relationship
Delete Me</description>
        <label>AccountPerson</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessments</relationshipLabel>
        <relationshipName>Assessment_Junction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Assessment_BeforeInsert_BeforeUpdate.cls
public with sharing class Assessment_BeforeInsert_BeforeUpdate {
    
     public static void setAccountPerson(List<Assessment__c> assess){
     
         for(Assessment__c item : assess){
             system.debug('hhheerrreee');
             system.debug('test'+item.AccountId__c);
             item.AccountPerson__c = item.AccountId__c; 
             //item.adderror('test');       
         
         }
     
     }
     
     public static void setCount(List<Assessment__c> assess){
     //Assessment_Count
     
     
     
     }


}