src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to funding source - optional</description>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Days_Authorized_From__c</fullName>
        <label>Days Authorized From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Authorized_To__c</fullName>
        <label>Days Authorized To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Coverage__c</fullName>
        <label>Coverage Level</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Authorization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The authorized service which was utilized to deliver the service on which progress is being documented.</description>
        <label>Authorization</label>
        <referenceTo>Authorization__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <description>Please indicate the funding source.</description>
        <inlineHelpText>Please indicate the funding source.</inlineHelpText>
        <label>Funding Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <recordTypes>
        <fullName>Therapy</fullName>
        <active>true</active>
        <description>Progress Note for NeuroRestorative IL</description>
        <label>Therapy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Sch_rpt_Auth_Utilization_helper_Test.cls
@isTest
public with sharing class Sch_rpt_Auth_Utilization_helper_Test {
	public static testmethod void simpleTests() {
		Tmn_Generic_Core_TestData testData = new Tmn_Generic_Core_TestData();

		Map<String, Schema.RecordTypeInfo> progressNoteRTMap = Progress_Note__c.SObjectType.getDescribe().getRecordTypeInfosByName();
		TestUtils.ProgressNoteBuilder progressNoteBuilder = new TestUtils.ProgressNoteBuilder();
		Progress_Note__c[] progressNotes = new Progress_Note__c[] {
			progressNoteBuilder
				.setServiceAssignmentId(testData.theSA.Id)
				.setServiceCodeId(testData.theServiceCode.Id)
				.setAdmissionId(testData.theAdm.Id)
				.setStartTime(Date.today().addDays(-5))
				.setEndTime(Date.today())
				.setPersonBeingServedId(testData.contactId)
				.setNoApprovalNeeded(true)
				.setApprovalStatus('Approved')
				.setStatus('Final')
				.setPurposeServiceIsBillable(false)
				.setTherapyDiscipline('PT')
				.setRecordType('Therapy')
				.getInstance(),
			progressNoteBuilder.setTherapyDiscipline('OT').getInstance(),
			progressNoteBuilder.setTherapyDiscipline('SLP').getInstance(),
			progressNoteBuilder.setTherapyDiscipline('Counseling').getInstance(),
			progressNoteBuilder.setTherapyDiscipline('BIT').getInstance()
		};
		insert progressNotes;

		Funding_Source__c fundingSource = new Funding_Source__c(
			Service_Assignment__c = testData.theSA.Id,
			Type_of_Coverage__c='Primary'
		);
		insert fundingSource;
		Map<String, Schema.RecordTypeInfo> authorizationRTMap = Authorization__c.SObjectType.getDescribe().getRecordTypeInfosByName();
		Authorization__c authorization = new Authorization__c(
			Person_Being_Served__c = testData.contactID,
			Service_Assignment__c = testData.theSA.Id,
			Funding_Source__c = fundingSource.id,
			RecordTypeId = authorizationRTMap.get('Costs_TherapyNR').getRecordTypeId(),
			Days_Authorized_From__c = Date.today().addDays(-5),
			Days_Authorized_To__c = Date.today()
		);
		insert authorization;

		Date startDate = Date.today().addDays(-30);
		Date endDate = Date.today().addDays(30);
		Sch_rpt_Auth_Utilization_helper controller = new Sch_rpt_Auth_Utilization_helper(startDate, endDate);

		System.assertNotEquals('', controller.getAttach());
		System.assertEquals('6/24/2016', controller.simpleDate(Date.newInstance(2016, 6, 24)));
	}
}