src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Authorization_Status__c</fullName>
        <description>Facilitates tracking delivery of services immediately, before authorization process is complete, by providing a temporary status.</description>
        <label>Authorization Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to funding source - optional</description>
        <label>Funding Source</label>
        <referenceTo>Funding_Source__c</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Authorization_Type__c</fullName>
        <label>Other Authorization Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Authorizations</relationshipLabel>
        <relationshipName>Authorized_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Authorization Type</label>
        <picklist>
            <picklistValues>
                <fullName>1:1 Sitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed Holds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defined Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Cost Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open Ended Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stay - Open Ended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Authorization_Type__c</fullName>
        <label>Other Authorization Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Coverage__c</fullName>
        <label>Coverage Level</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AuthorizationExtTest.cls
@isTest
private class AuthorizationExtTest {
    static testmethod void simpleTests(){
        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
		List<Authorization__c> auths = new List<Authorization__c>();
        
        For(integer i=0; i < 5; i++){
       		Funding_Source__c f = new Funding_Source__c(Service_Assignment__c = myData.theSA.Id, Type_of_Coverage__c='Primary');
			insert f;
			Authorization__c s = new Authorization__c(
      			Person_Being_Served__c = myData.contactID,
       			Funding_Source__c = f.id
       		);
        	auths.add(s);
        }
        insert auths;
        
        Funding_Source__c f = new Funding_Source__c(Service_Assignment__c = myData.theSA.Id, Type_of_Coverage__c='Primary');
		insert f;
        Authorization__c authoriza = new Authorization__c(
       		Person_Being_Served__c = myData.contactID,
       		Authorization_Status__c = 'Draft',
       		type__c='Other',
       		other_authorization_type__c='Test',
       		Funding_Source__c = f.id
       );
            insert authoriza;
       
       
        PageReference pageRef = Page.AuthorizationEdit;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getParameters().put('saID', myData.theSA.Id); 
        AuthorizationExt controller = new AuthorizationExt(new ApexPages.StandardController(authoriza));
       	controller.changeAuthType();
       	
       	
       	
		controller.editAuth();			      
		
		controller.authorization.type__c='Test';
		controller.authorization.other_authorization_type__c='Test';
		controller.authorization.received_Date_time__c=date.newinstance(2020, 06, 17);
		
		controller.saveAuth();
		controller.finalizeAuth();
		controller.cloneAuth();
		controller.reviseAuth();
		controller.disregardAuth();   
		controller.redirectToView(myData.theSA.Id, myData.theSA.Id);
		      
		      


    }
}