src/objects/Authorization__c.object
<CustomObject>
    <description>NOTES Authorizations are records from AVATAR for Persons Being Served showing their authorized units and services that can be performed by The MENTOR Network. This should be populated by an integration with AVATAR. Authorizations are master-detail to Service Assignments.</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Used in Apex and VisualForce for item like Drop-downs menus.  Allows central management.</description>
        <formula>Name &amp;
&apos; - &apos; &amp;
TEXT(MONTH(Payer_Effective_Date__c))  &amp; &apos;/&apos; &amp;
TEXT(DAY(Payer_Effective_Date__c))  &amp;  &apos;/&apos; &amp;
TEXT(YEAR(Payer_Effective_Date__c))  &amp;
&apos; - &apos; &amp;
TEXT(MONTH(Payer_End_Date__c))  &amp; &apos;/&apos; &amp;
TEXT(DAY(Payer_End_Date__c))  &amp;  &apos;/&apos; &amp;
TEXT(YEAR(Payer_End_Date__c))  &amp;
&apos; - &apos; &amp;
&apos; ($ &apos; &amp;
 TEXT(Remaining_Dollars__c) &amp;
&apos; ) &apos; &amp;
&apos; (U  &apos; &amp;
 TEXT( Remaining_Units__c ) &amp;
&apos; ) &apos; &amp;
&apos; ( V &apos; &amp;
 TEXT( Remaining_Visits__c ) &amp;
&apos; ) &apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <label>Authorization</label>
    <nameField>
        <label>Authorization ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Authorization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The authorized service which was utilized to deliver the service on which progress is being documented.</description>
        <label>Authorization</label>
        <referenceTo>Authorization__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Code</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Value__c</fullName>
        <label>Service Value</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Notes_ProgressNote_GetFieldsAudit_PDF.cls
public with sharing class Notes_ProgressNote_GetFieldsAudit_PDF {
    public Progress_Note__c RecID {get; set;}
    public Progress_Note__c PN = new Progress_Note__c();
    public Progress_Note__c getPN()
        { return [Select Service_Code__r.Service_Value__c, Authorization__r.Display_Name__c from Progress_Note__c Where ID = :RecID.Id];}
    public Notes_ProgressNote_GetFieldsAudit_PDF(ApexPages.StandardController controller) {
        this.RecID =  (Progress_Note__c)controller.getRecord();
    }

}