src/objects/CareMeridian_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>CareMeridian</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>NeuroRestorative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Redwood_Contract__c.object
<CustomObject>
    <description>Redwood Contract Management</description>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>Redwood</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Redwood Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Redwood Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TMN_Contract__c.object
<CustomObject>
    <description>CAMBRIDGE CONTRACT</description>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <picklist>
            <picklistValues>
                <fullName>Cambridge</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>-Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TabContractExt.cls
public with sharing class TabContractExt {
	public string contracts {get;set;}
	
	public TabContractExt(Apexpages.standardSetController controller) {
		List <TMN_User__c> tmnU = [SELECT id,Operating_Group__c from TMN_User__c WHERE Salesforce_User_Account__c= :UserInfo.getUserId() LIMIT 1];
		contracts = 'TMN_Contract__c';//default value
		if(tmnU.size() > 0){
			if(tmnU[0].Operating_Group__c == 'Care Meridian' || tmnU[0].Operating_Group__c== 'NeuroRestorative'){
				contracts = 'CareMeridian_Contract__c';
			}
			else if(tmnU[0].Operating_Group__c == 'Cambridge'){
				contracts = 'TMN_Contract__c';
			}
			else if(tmnU[0].Operating_Group__c == 'Redwood'){
				contracts = 'Redwood_Contract__c';
			}
		}
	}
    
}