src/objects/Case_Management_Plan__c.object
<CustomObject>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>85</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Over_250__c</fullName>
        <label>Text Over 250</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text_Under_250__c</fullName>
        <label>Text Under 250</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Management Plan</label>
        <referenceTo>Case_Management_Plan__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>X-Ray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doppler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Contributor_Name__c</fullName>
        <description>Contributors and Signature Data OR ISP</description>
        <label>Contributor Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Evaluation_Date__c</fullName>
        <label>Evaluation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISP_Has_condition_changed_evaluation__c</fullName>
        <label>Has condition changed since evaluation?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Risks__c</fullName>
        <label>Risk(s)</label>
        <picklist>
            <picklistValues>
                <fullName>Aspiration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constipation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dehydration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extreme Food or Liquid-Seeking Behavior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suicide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Specify_Other__c</fullName>
        <label>Specify Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Title_Relationship_Person__c</fullName>
        <description>Contributors and Signature Data OR ISP</description>
        <label>Title/Relationship to This Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Type_of_evaluation__c</fullName>
        <label>Type of evaluation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Where_evaluation_is_kept__c</fullName>
        <label>Where evaluation is kept</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Contributors_Signatures</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Contributors &amp; Signatures</label>
    </recordTypes>
    <recordTypes>
        <fullName>Evaluation</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Evaluation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Risk</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Risk</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ORRisktoolPrint.cls
public class ORRisktoolPrint{
	Apexpages.StandardController controller;
	public Case_Management_Plan__c isp {get; set;}
	public List<Evaluation_Response__c> evaluations {get; set;}
	public List<Evaluation_Response__c> contributors = new List<Evaluation_Response__c>();	
	public List<wContributor> wContributors {get; set;}
	public Map<String,Eval_Value__c> YesNovalueMap {get;set;}
	public string YesnokeyCheck {get; set;}
	public Map<string, string> commentsValueMap {get; set;}
	
	public set<string> options = new set<string>{'Yes','Possible','History','No', 'Risk Present', 'No Risk', 'Other (see comments)'};
	
	 public String getPrintView()
    {
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
            '<![endif]>';
    }
	
	public ORRisktoolPrint(Apexpages.StandardController controller){
		this.controller = controller;
		this.isp = (Case_Management_Plan__c)controller.getRecord();
		evaluations = new List<Evaluation_Response__c>();
		evaluations = [SELECT ISP_Risks__c, ISP_Specify_Other__c, ISP_Type_of_evaluation__c, ISP_Evaluation_Date__c, ISP_Has_condition_changed_evaluation__c, ISP_Where_evaluation_is_kept__c
    							FROM Evaluation_Response__c WHERE Case_Management_Plan__c = :this.isp.Id AND Recordtype.DEVELOPERNAME = 'Evaluation'];					
 	    contributors = [SELECT ISP_Contributor_Name__c, ISP_Title_Relationship_Person__c
    							FROM Evaluation_Response__c WHERE Case_Management_Plan__c = :this.isp.Id AND Recordtype.DEVELOPERNAME = 'Contributors_Signatures' order by CreatedDate asc];
        wContributors = new List<wContributor>();
        prepareContributorList(contributors);
        
        YesNovalueMap = new Map<string, Eval_Value__c>();
        YesnokeyCheck = '';
        

 
        commentsValueMap = new Map<String, string>();
        commentsValueMap.put('Behavior', '');
        commentsValueMap.put('Mental Health', '');
        commentsValueMap.put('Financial', '');
        commentsValueMap.put('Safety', '');
        
        for(Eval_Value__c ev: [SELECT Boolean__c,Date_Time__c,Text_Under_250__c, Text_Over_250__c, Eval__r.Composite__c, Eval__r.Category__c, Eval__r.htmlid__c, Eval__r.Field_name__c FROM Eval_Value__c WHERE  What_Id__c = :this.isp.id]){
    		YesNovalueMap.put(ev.Eval__r.Composite__c+'~'+ev.Eval__r.htmlid__c, ev);
    		YesnokeyCheck += ev.Eval__r.Composite__c+'~'+ev.Eval__r.htmlid__c;
        
        	if(ev.Eval__r.Category__c != 'Health and Medical' && ev.Eval__r.Field_Name__c == 'Comments'){
        		string s = commentsValueMap.get(ev.Eval__r.Category__c);
        		s += '  '+ev.Eval__r.Composite__c.SubstringAfterLast('~')+': '+ev.Text_Over_250__c;
        		commentsValueMap.put(ev.Eval__r.Category__c, s);
        	}
        	
        }
        
	}
	
	//This is needed because in word document there are two columns to display the data.
	public void prepareContributorList(List<Evaluation_Response__c> contributors){
		integer j = 0;
		for(integer i=0; i < (contributors.size()+1)/2; i++){
			wContributor wC = new wContributor();
			if(math.mod(j, 2) == 0 && j < contributors.size()){
				wC.name1 = contributors[j].ISP_Contributor_Name__c;
				wC.relation1 = contributors[j].ISP_Title_Relationship_Person__c;
				j = j+1;
			}
			if(math.mod(j, 2) != 0 && j < contributors.size()){
				wC.name2 = contributors[j].ISP_Contributor_Name__c;
				wC.relation2 = contributors[j].ISP_Title_Relationship_Person__c;
				j= j+1;
			}
			
			wContributors.add(wC);
		}
	}
	
	
	public class wContributor{
		public string name1 {get;set;}
		public string relation1 {get; set;}
		public string name2 {get;set;}
		public string relation2 {get; set;}
		
		public wContributor(){
			
		}
	}

}