src/objects/Case_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>PD_End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PD_Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Case Management Plan</relationshipLabel>
        <relationshipName>Case_Management_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <recordTypes>
        <fullName>OR_Combined_ISP</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>OR Combined ISP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/rptCurrent_Combined_ISPs.cls
public with sharing class rptCurrent_Combined_ISPs {
	
    public list<Case_Management_Plan__c> rptData {get; set;}
    
	public rptCurrent_Combined_ISPs() {
		runRpt();
	}
    
    public pageReference runRpt(){
    	boolean inputErr = false;
    	ApexPages.getMessages().clear();
    
		rptData = [SELECT Id, Service_Assignment__r.Person_Being_Served__r.Name, Service_Assignment__c,
					Service_Assignment__r.Name, Service_Assignment__r.Person_Being_Served__c, Name, 
					PD_Start__c, PD_End__c, Status__c, CreatedBy.Name, LastModifiedBy.Name, LastModifiedDate
					FROM Case_Management_Plan__c
					WHERE RecordType.DeveloperName = 'OR_Combined_ISP' AND
						Status__c in ('Inactive Draft', 'Active Final')
					];
		
    	return null; 
    }
}