src/objects/Case_Management_Plan__c.object
<CustomObject>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Management Plan</label>
        <referenceTo>Case_Management_Plan__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISP_Contributor_Name__c</fullName>
        <description>Contributors and Signature Data OR ISP</description>
        <label>Contributor Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Title_Relationship_Person__c</fullName>
        <description>Contributors and Signature Data OR ISP</description>
        <label>Title/Relationship to This Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCI_Contributor_to_Person_Centered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PCI Contributor to Person Centered</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Contributors_Signatures</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Contributors &amp; Signatures</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ORPCIPrintExt.cls
public with sharing class ORPCIPrintExt {
     public Case_Management_plan__c isp {get; set;}
	public List<Evaluation_Response__c> contributors = new List<Evaluation_Response__c>();	
	public List<wContributor> wContributors {get; set;}
    
    public String getPrintView()
    {
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
            '<![endif]>';
    }

    public ORPCIPrintExt(ApexPages.StandardController controller) {
        this.isp = (Case_Management_Plan__c) controller.getRecord();
        contributors = [SELECT ISP_Contributor_Name__c, ISP_Title_Relationship_Person__c
    							FROM Evaluation_Response__c WHERE Case_Management_Plan__c = :this.isp.Id AND Recordtype.DEVELOPERNAME = 'Contributors_Signatures' 
    							AND PCI_Contributor_to_Person_Centered__c = true  order by CreatedDate asc];
        wContributors = new List<wContributor>();
        prepareContributorList(contributors);
    }
    //This is needed because in word document there are two columns to display the data.
	public void prepareContributorList(List<Evaluation_Response__c> contributors){
		integer j = 0;
		for(integer i=0; i < (contributors.size()+1)/2; i++){
			wContributor wC = new wContributor();
			if(math.mod(j, 2) == 0 && j < contributors.size()){
				wC.name1 = contributors[j].ISP_Contributor_Name__c;
				wC.relation1 = contributors[j].ISP_Title_Relationship_Person__c;
				j = j+1;
			}
			if(math.mod(j, 2) != 0 && j < contributors.size()){
				wC.name2 = contributors[j].ISP_Contributor_Name__c;
				wC.relation2 = contributors[j].ISP_Title_Relationship_Person__c;
				j= j+1;
			}
			
			wContributors.add(wC);
		}
	}
	
	
	public class wContributor{
		public string name1 {get;set;}
		public string relation1 {get; set;}
		public string name2 {get;set;}
		public string relation2 {get; set;}
		
		public wContributor(){
			
		}
	}
    
}