src/objects/Case_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Case Management Plan</relationshipLabel>
        <relationshipName>Case_Management_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive Final</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <recordTypes>
        <fullName>OR_Combined_ISP</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>OR Combined ISP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Management Plan</label>
        <referenceTo>Case_Management_Plan__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISP_Describe_Chosen_Services_Supports__c</fullName>
        <label>Describe Chosen Services/Supports</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Identified_needs__c</fullName>
        <label>List identified needs that this service</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Is_there_a_paid_Service__c</fullName>
        <label>Is there a paid Service</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Key_Steps_to_work_toward_outcome__c</fullName>
        <label>Key steps toward the outcome</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Note_if_Written_Implementation__c</fullName>
        <description>OR ISP</description>
        <label>Note if Written Implementation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Paid_Services__c</fullName>
        <description>OR ISP</description>
        <label>Paid Services</label>
        <picklist>
            <picklistValues>
                <fullName>Employment Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Device</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attendant Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Consult/Supports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chore Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Med. Comm. Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Modification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relief Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Supports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Resources</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Per_Frequency__c</fullName>
        <label>Per (Frequency)</label>
        <picklist>
            <picklistValues>
                <fullName>Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan year</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Person_Preference_Service_Delivery__c</fullName>
        <label>Person’s service delivery preference</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Same_as_plan_year__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same as plan year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISP_Service_Element_Service_Code__c</fullName>
        <label>Service Element &amp; Service Code</label>
        <picklist>
            <picklistValues>
                <fullName>149-OR003-Service Related Comm Trans, Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR004-Service Related Comm Trans, Mil-WD-Wk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR004-Service Related Comm Trans, Mil-WE-Comm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR005-Svc Rlt. Comm Trans, Nonmed,Att/Esc-WD-Wk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR005-Svc Rlt. Comm Trans, Nonmed,Att/Esc-WE-Com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR100-Attendant Care-ADL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR101-Attendant Care-ADL-ZE 2:1 Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR101-Attendant Care-IADL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR102-Attendant Care-IADL-ZE 2:1 Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR310-Behavior Support Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR321-Assistive Technology Purchase-Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR322-Assistive Technology Purchase-Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR323-Assistive Technology Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR324-Assisstive Technology Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR325-Assistive Technology Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR326-Transition Svcs: Internet installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR330-Transition Svcs: Cleaning before move-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR331-Transition Svcs: Food stocking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR332-Transition Svcs: Moving expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR333-Transition Svcs: Household goods and furnishings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR342-Transition Svcs: Utility deposits and installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR343-Transition Svcs: Security deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR344-Transition Svcs: Rent deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR380-Specialized Medical Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR406-Community Transition, Extend; per service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR501-Chore Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR507-Relief Care; daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR508-Relief Care; hourly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR526-Attendant Care Sppt,Superv,DD,Home/Comm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>149-OR527-Att Care Sppt,Sup,DD,Home/Comm-ZE 2:1 Staff</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Supports_Services_Provided_by__c</fullName>
        <description>OR ISP</description>
        <label>Other Supports Services Provided by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISP_Timelines_Frequency_when__c</fullName>
        <description>OR ISP</description>
        <label>Timelines:</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Unit_Type__c</fullName>
        <label>Unit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Hour(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mile(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollars (only for one-time authorizations)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Units__c</fullName>
        <label># Units</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ISP_What_is_the_desired_result__c</fullName>
        <description>OR ISP</description>
        <label>Desired Result</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Where_to_Record_progress__c</fullName>
        <label>Where to Record progress</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Who_is_responsible__c</fullName>
        <description>OR ISP</description>
        <label>Who is responsible?</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>This field is created to render just the label on Evaluation Response Component.</description>
        <label>Label</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Additional_Chosen_Services</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Additional Chosen Services</label>
    </recordTypes>
    <recordTypes>
        <fullName>Community_Transportation_Services</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Community Transportation Services</label>
    </recordTypes>
    <recordTypes>
        <fullName>Desired_Outcomes</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Desired Outcomes</label>
    </recordTypes>
    <recordTypes>
        <fullName>Employment_Outcomes</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Employment Outcomes</label>
    </recordTypes>
    <recordTypes>
        <fullName>K_Plan_Services</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>K Plan Services</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other_Services_Supports</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Other Services Supports</label>
    </recordTypes>
    <recordTypes>
        <fullName>Waiver_Services</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Waiver Services</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ORISPPrintTest.cls
@isTest
private class ORISPPrintTest {
	
	@testSetup
	static void setUp() {
		Case_Management_Plan__c testIsp;
		
		TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();

    	List<RecordType> rt = [ select id from Recordtype where sobjecttype = 'Case_Management_Plan__c' and developername = 'OR_Combined_ISP' ];
    	system.assertEquals(1, rt.size());
    		
		testIsp = new Case_Management_Plan__c( recordtypeid = rt[0].Id);
        testIsp.Name = 'Test plan 1';
        testIsp.Service_Assignment__c = testData.theSA.id;
        testIsp.Status__c = 'Active Final';
        insert testIsp;
        
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Desired_Outcomes' ];
    	system.assertEquals(1, rt.size());
        
        // desired outcomes
        Evaluation_Response__c evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_What_is_the_desired_result__c = 'Desired result 1',
        	ISP_Key_Steps_to_work_toward_outcome__c = 'Key steps 1 include...',
        	ISP_Is_there_a_paid_Service__c = 'Yes',
        	ISP_Paid_Services__c = 'Employment Services',
        	ISP_Who_is_responsible__c = 'Respsonsible parties 1',
        	ISP_Timelines_Frequency_when__c = 'Timeline frequency 1',
        	ISP_Where_to_Record_progress__c = 'Progress record location 1',
        	ISP_Note_if_Written_Implementation__c = 'The written note 1'
        );
        insert evalResp;

		// employment outcomes
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Employment_Outcomes' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_What_is_the_desired_result__c = 'Desired result 2',
        	ISP_Key_Steps_to_work_toward_outcome__c = 'Key steps 2 include...',
        	ISP_Is_there_a_paid_Service__c = 'Yes',
        	ISP_Paid_Services__c = 'Employment Services',
        	ISP_Who_is_responsible__c = 'Respsonsible parties 2',
        	ISP_Timelines_Frequency_when__c = 'Timeline frequency 2',
        	ISP_Where_to_Record_progress__c = 'Progress record location 2',
        	ISP_Note_if_Written_Implementation__c = 'The written note 2'
        );
        insert evalResp;

		// other support services
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Other_Services_Supports' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
			ISP_Describe_Chosen_Services_Supports__c = 'Chosen services shall... 1',
			ISP_Supports_Services_Provided_by__c = 'Services provided by 1'
        );
        insert evalResp;

		// kPlan Services
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'K_Plan_Services' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_Service_Element_Service_Code__c = '149-OR100-Attendant Care-ADL',
        	ISP_Units__c = 52,
        	ISP_Unit_Type__c = 'Day(s)',
        	ISP_Per_Frequency__c = 'Week',
        	Label__c = 'Label 1',
        	ISP_Same_as_plan_year__c = true,
			ISP_Describe_Chosen_Services_Supports__c = 'Chosen services shall... 2',
        	ISP_Identified_needs__c = 'Needs identified include... 2',
        	ISP_Person_Preference_Service_Delivery__c = 'Lunchtime'
        );
        insert evalResp;

		// Waiver Services
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Waiver_Services' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
//        	ISP_Service_Element_Service_Code__c = '149-OR406-Community Transition, Extend; per service',
        	ISP_Units__c = 52,
        	ISP_Unit_Type__c = 'Day(s)',
        	ISP_Per_Frequency__c = 'Week',
        	Label__c = 'Label 3',
        	ISP_Same_as_plan_year__c = true,
			ISP_Describe_Chosen_Services_Supports__c = 'Chosen services shall... 3',
        	ISP_Identified_needs__c = 'Needs identified include... 3',
        	ISP_Person_Preference_Service_Delivery__c = 'Lunchtime 3'
        );
        insert evalResp;

		// Community Trans Services
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Community_Transportation_Services' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_Transportation_Type__c = 'Van Transportation',
        	ISP_Same_as_plan_year__c = true,
			ISP_Describe_Chosen_Services_Supports__c = 'Chosen services shall... 4'
        );
        insert evalResp;

		// Additional Services
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and developername = 'Additional_Chosen_Services' ];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_Describe_service_setting__c = 'Service setting shall... 1',
        	ISP_Identified_needs__c = 'The needs identified include...',
			ISP_Person_Preference_Service_Delivery__c = 'Lunchtime 4'
        );
        insert evalResp;

		// Contributors
        rt = [ select id from Recordtype where sobjecttype = 'Evaluation_Response__c' and Name = 'Contributors & Signatures' order by CreatedDate asc];
    	system.assertEquals(1, rt.size());
        
		evalResp = new Evaluation_Response__c (
        	Case_Management_Plan__c = testIsp.Id,
        	recordtypeid = rt[0].Id,
        	ISP_Contributor_Name__c = 'John Hancock',
        	ISP_Title_Relationship_Person__c = 'Parent',
        	ISP_Contributor_Risk_Identification_Tool__c = true,
        	ISP_Signature_Required__c = true,
        	ISP_Present_at_Meeting__c = 'Yes',
        	ISP_Type_of_Contributor__c = 'TypeA',
			ISP_Contributor_Origin_Id__c = 'Origin'
        );
        insert evalResp;
	}
    
    static testMethod void testDesiredOutcomes() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.desiredOutcomes.size());
    	system.assertEquals('Desired result 1', ctl.desiredOutcomes[0].ISP_What_is_the_desired_result__c);
    }
	
    static testMethod void testEmploymentOutcomes() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.employmentOutcomes.size());
    	system.assertEquals('Desired result 2', ctl.employmentOutcomes[0].ISP_What_is_the_desired_result__c);
    }
    
    static testMethod void testOtherServicesSupports() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.otherServicesSupports.size());
    	system.assertEquals('Services provided by 1', ctl.otherServicesSupports[0].ISP_Supports_Services_Provided_by__c);
    }
    
    static testMethod void testKplanServices() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.kPlanServices.size());
    	system.assertEquals('149-OR100-Attendant Care-ADL', ctl.kPlanServices[0].ISP_Service_Element_Service_Code__c);
    }
    
    static testMethod void testWaiverServices() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.waiverServices.size());
    	system.assertEquals('Lunchtime 3', ctl.waiverServices[0].ISP_Person_Preference_Service_Delivery__c);
    }
    
    static testMethod void testCommTransServicess() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.commTransServices.size());
    	system.assertEquals('Chosen services shall... 4', ctl.commTransServices[0].ISP_Describe_Chosen_Services_Supports__c);
    }
    
    static testMethod void testAdditionalServices() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.additionalServices.size());
    	system.assertEquals('Lunchtime 4', ctl.additionalServices[0].ISP_Person_Preference_Service_Delivery__c);
    }
    
    static testMethod void testContributors() {
    	ORISPPrint ctl = initController();
    	
    	system.assertEquals(1, ctl.contributors.size());
    	system.assertEquals('John Hancock', ctl.contributors[0].ISP_Contributor_Name__c);
    }
    
    private static ORISPPrint initController() {
		ApexPages.StandardController sc;
		List<Case_Management_Plan__c> testIsp;
		
		testIsp = [select id from Case_Management_Plan__c where Name = 'Test plan 1' limit 1];
    	sc = new ApexPages.StandardController(testIsp[0]);
    	return new ORISPPrint(sc);
    }
	
    static testMethod void testGetPrintView() {
     	ORISPPrint ctl;
     	ApexPages.StandardController sc;
		List<Case_Management_Plan__c> testIsp;
		
		testIsp = [select id from Case_Management_Plan__c where Name = 'Test plan 1' limit 1];
    	sc = new ApexPages.StandardController(testIsp[0]);
    	ctl = new ORISPPrint(sc);
        System.assertEquals('<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/></w:WordDocument></xml><![endif]>', ctl.getPrintView());
        
    }
}