src/objects/Case_Management_Plan__c.object
<CustomObject>
    <label>Case Management Plan</label>
    <nameField>
        <label>Case Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Case_Management_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Management Plan</label>
        <referenceTo>Case_Management_Plan__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISP_Is_there_a_paid_Service__c</fullName>
        <label>Is there a paid Service</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Key_Steps_to_work_toward_outcome__c</fullName>
        <label>Key steps toward the outcome</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Note_if_Written_Implementation__c</fullName>
        <description>OR ISP</description>
        <label>Note if Written Implementation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Paid_Services__c</fullName>
        <description>OR ISP</description>
        <label>Paid Services</label>
        <picklist>
            <picklistValues>
                <fullName>Employment Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Device</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistive Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attendant Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Consult/Supports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chore Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Med. Comm. Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Modification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relief Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skill Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transition Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Supports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Resources</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISP_Timelines_Frequency_when__c</fullName>
        <description>OR ISP</description>
        <label>Timelines:</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_What_is_the_desired_result__c</fullName>
        <description>OR ISP</description>
        <label>Desired Result</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Where_to_Record_progress__c</fullName>
        <label>Where to Record progress</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ISP_Who_is_responsible__c</fullName>
        <description>OR ISP</description>
        <label>Who is responsible?</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <recordTypes>
        <fullName>Desired_Outcomes</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Desired Outcomes</label>
    </recordTypes>
    <recordTypes>
        <fullName>Employment_Outcomes</fullName>
        <active>true</active>
        <description>This recordtype is used for OR Combined ISP</description>
        <label>Employment Outcomes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ORISPPrint.cls
public with sharing class ORISPPrint {

    public Case_Management_plan__c isp {get; set;}
    public List<Evaluation_Response__c> desiredOutcomes {get; set;}
    public List<Evaluation_Response__c> employmentOutcomes {get; set;}
    
    public String getPrintView()
    {
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
            '<![endif]>';
        }

    public ORISPPrint(ApexPages.StandardController controller) {
        this.isp = (Case_Management_Plan__c) controller.getRecord();
        desiredOutcomes  = new List<Evaluation_Response__c>();
        desiredOutComes = [SELECT ISP_What_is_the_desired_result__c, ISP_Key_Steps_to_work_toward_outcome__c, ISP_Is_there_a_paid_Service__c,ISP_Paid_Services__c, ISP_Who_is_responsible__c, ISP_Timelines_Frequency_when__c, ISP_Where_to_Record_progress__c, ISP_Note_if_Written_Implementation__c 
                                FROM Evaluation_Response__c WHERE Case_Management_Plan__c = :this.isp.Id AND Recordtype.DEVELOPERNAME = 'Desired_Outcomes'];
    	
    	employmentOutcomes = new List<Evaluation_Response__c>();
    	employmentOutcomes = [SELECT ISP_What_is_the_desired_result__c, ISP_Key_Steps_to_work_toward_outcome__c, ISP_Is_there_a_paid_Service__c, ISP_Paid_Services__c, ISP_Who_is_responsible__c, ISP_Timelines_Frequency_when__c, ISP_Where_to_Record_progress__c, ISP_Note_if_Written_Implementation__c
    							FROM Evaluation_Response__c WHERE Case_Management_Plan__c = :this.isp.Id AND Recordtype.DEVELOPERNAME = 'Employment_Outcomes'];
    }

}