src/objects/Clinical_Catalog__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_Name__c</fullName>
        <description>Clinical Catalog Name</description>
        <inlineHelpText>Clinical Catalog Name for this tree</inlineHelpText>
        <label>Catalog Name</label>
        <length>75</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Clinical Catalog</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinical_Catalog_Program__c.object
<CustomObject>
    <fields>
        <fullName>Clinical_Catalog__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clinical Catalog</label>
        <referenceTo>Clinical_Catalog__c</referenceTo>
        <relationshipLabel>Clinical Catalog Programs</relationshipLabel>
        <relationshipName>Clinical_Catalog_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Clinical Catalog Program</label>
    <nameField>
        <label>Clinical_Catalog_Program_Name_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Catalog Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinical_Programs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Clinical Programs used in plan builder</description>
    <fields>
        <fullName>ProgramID__c</fullName>
        <externalId>true</externalId>
        <label>ProgramID</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Service Settings</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Clinical Programs</label>
</CustomObject>

src/classes/CatalogAndProgramsTest.cls
@isTest
private class CatalogAndProgramsTest {

    static testMethod void myUnitTest() {
    	createData();
    	CatalogAndPrograms cp = new CatalogAndPrograms();
    	system.AssertEquals(cp.ctlgs.size(), 3);
    	
    	string ctlg = [select id from Clinical_Catalog__c limit 1].id ;
    	cp.curCtlg = ctlg;
    	system.AssertEquals(cp.editCatalog().getUrl().contains('/apex/catalog_builder_beta?Id=' + ctlg), true );	
    }
    
    static testMethod void updatePrgAssocUnitTest() {
    	createData();
    	CatalogAndPrograms cp = new CatalogAndPrograms();
    	string ctlg = [select id from Clinical_Catalog__c limit 1].id ;
    	cp.curCtlg = ctlg;
    	
    	cp.refreshHere();
    	
    	cp.prgms.get(0).isSelected = true;
    	cp.updatePrgAssoc();
    	system.AssertEquals([select id from Clinical_Catalog_Program__c].size(), 1);
    	
    	cp.prgms.get(0).isSelected = false;
    	cp.updatePrgAssoc();
    	system.AssertEquals([select id from Clinical_Catalog_Program__c].size(), 0);
    	
    }
    
    static void createData(){
    	
    	insert (new Clinical_Programs__c(ProgramID__c = 1, Program_Name__c='IDD', Name ='IDD'));
    	insert (new Clinical_Catalog__c(Catalog_Name__c='Catalog One'));
    	
    	
    }
    
    
}