src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY()-Birthdate +1)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name_SoundEx_Key__c</fullName>
        <label>First Name SoundEx Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Select the person&apos;s legal gender</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name_SoundEx_Key__c</fullName>
        <label>Last Name SoundEx Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Referred__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Referred</label>
        <referenceTo>Person_Being_Referred__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Being_Referred__c.object
<CustomObject>
    <description>Person Being Referred holds demographic information about a person for the referral process</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age (will be overwritten by a trigger if Date of Birth is filled in)</description>
        <inlineHelpText>If Date of Birth is filled in, then Age is overwritten with the calculated value.</inlineHelpText>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of Birth - if this is filled in, then Age is overwritten based on this date.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name_SoundEx_Key__c</fullName>
        <label>First Name SoundEx Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name_SoundEx_Key__c</fullName>
        <label>Last Name SoundEx Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>People Being Referred</relationshipLabel>
        <relationshipName>People_Being_Referred</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>11</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Person Being Referred</label>
    <nameField>
        <displayFormat>PBR-{0}</displayFormat>
        <label>PBR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Being Referred</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <fields>
        <fullName>City__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldPBS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OldPBS</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Referred__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Referred</label>
        <referenceTo>Person_Being_Referred__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals (Person Being Served)</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>MN Specific</description>
        <inlineHelpText>If different than the person&apos;s permanent location</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SearchLogicOnPBSR.cls
public with sharing class SearchLogicOnPBSR {
    private static string RECORD_LIMIT = '50';
    
    public static List<ReferralSearchResults> search(String referralNumber,String lastname,String firstname,Date dob, Double age,String gender){
        system.debug('lastname:' + lastname + ';firstname:' +firstname+';dob:'+dob+';age:'+age+';gender:'+gender);
        List<ReferralSearchResults> results = new List<ReferralSearchResults>();
        if((lastname== null || lastname=='') && (firstname==null || firstname=='') && 
           (referralNumber==null || referralNumber=='')){
            throw new CustomException('Both last and first name cannot be null');
        }
        String searchStringPBR = '';
        string searchStringPBS = '';
       
        List<Person_Being_Referred__c> pbrs = new List<Person_Being_Referred__c>();
        List<Contact> pbsList = new List<Contact>();
        
        if ((lastname!= null && lastname!='') || (firstname!=null && firstname!='')) {
            searchStringPBR= SearchLogicOnPBSR.buildCriteria(lastname,firstname,dob, age,gender,false, true);
            searchStringPBS= SearchLogicOnPBSR.buildCriteria(lastname,firstname,dob, age,gender,true, false);          
            pbrs = Database.query(searchStringPBR);
            pbsList = Database.query(searchStringPBS);
        }
        
     /*  if ((lastname!= null && lastname!='') || (firstname!=null && firstname!='')) {
           searchString= SearchLogicOnPBSR.buildCriteria(lastname,firstname,dob, age,gender,true, false);
            pbsList = Database.query(searchString);
            
       }*/
        
        if(referralNumber!=null && referralNumber!=''){
           List<Person_Being_Referred__c> tmpPbr=[Select name,first_name__c,last_name__c,gender__c,date_of_birth__c,city__c,(SELECT ID,Person_Being_Served__c FROM Referrals__r WHERE Person_Being_Served__c != null LIMIT 1),state__c,zip_code__c,street_1__c,street_2__c,age__c,Person_being_served__c  
                    From person_being_referred__c 
                        Where id in 
                            (select person_being_referred__c from referral__c where name=:referralNumber)
                    limit 1];
        //Sravan- Added extra query and changed the logic to display PBS if searched with refrral number. If no PBS exists person being referred record will be displayed EC-28  09/11/2014 1:32 PM           
            List <Contact> tmpCon = [SELECT name,firstname,lastname,gender__c,birthdate,mailingcity,mailingstatecode,mailingpostalcode,mailingstreet,otherstreet,age__c
            		 FROM Contact
            		 	WHERE ID IN(SELECT Person_Being_Served__c from referral__c WHERE name=:referralNumber)
            		 limit 1];
                  
	             if(tmpCon.size()>0){
	                pbsList.addall(tmpCon);
	              }
	            
	            else{
	            	pbrs.addall(tmpPbr);	
	            } 
	             
        }
        
        for(Person_Being_Referred__c pbr : pbrs)
        {
        	List<Referral__c> r = pbr.Referrals__r;
        	system.debug('size'+r.size());
        	if(pbr.Person_Being_Served__c == null){
	            Integer matchedItems = 0;
	            if (lastname!=null && lastname!='' && pbr.Last_Name__c == lastName) matchedItems +=1;
	            if (firstname!=null && firstname!='' && pbr.First_Name__c == firstName) matchedItems +=1;
	            if (dob!=null && pbr.Date_of_Birth__c == dob) matchedItems +=1;
	            if (age!=null && age!=0 && pbr.Age__c == age) matchedItems +=1;
	            if (gender!=null && gender!='' && pbr.Gender__c == gender) matchedItems +=1;
	            
	        
	            results.add(new ReferralSearchResults(pbr, matchedItems));
        	}
        	
        	if(pbr.Person_Being_Served__c!=null && r.size()>0){
        		Integer matchedItems = 0;
	            if (lastname!=null && lastname!='' && pbr.Last_Name__c == lastName) matchedItems +=1;
	            if (firstname!=null && firstname!='' && pbr.First_Name__c == firstName) matchedItems +=1;
	            if (dob!=null && pbr.Date_of_Birth__c == dob) matchedItems +=1;
	            if (age!=null && age!=0 && pbr.Age__c == age) matchedItems +=1;
	            if (gender!=null && gender!='' && pbr.Gender__c == gender) matchedItems +=1;
	            
	        
	            results.add(new ReferralSearchResults(pbr, matchedItems));
        		
        	}
        }
        
        for(Contact pbs : pbsList)
        {
            Integer matchedItems = 0;
            if (lastname!=null && lastname!='' && pbs.LastName == lastName) matchedItems +=1;
            if (firstname!=null && firstname!='' && pbs.FirstName == firstName) matchedItems +=1;
            if (dob!=null && pbs.Birthdate == dob) matchedItems +=1;
            if (age!=null && age!=0 && pbs.Age__c == age) matchedItems +=1;
            if (gender!=null && gender!='' && pbs.Gender__c == gender) matchedItems +=1;
                        
            results.add(new ReferralSearchResults(pbs, matchedItems));  
        }
        
        
        results.sort();
        return results;
        
    }
    public static String buildCriteria(String lastname, String firstname, Date dob, Double age,String gender,Boolean isContact, Boolean isPBR){
        
        String sobjecttype='';
        
        String namefield='';
        String lastnamefield='';
        String firstnamefield='';
        String genderfield='';
        String dobfield='';
        String cityfield='';
        String statefield='';
        String zipfield='';
        String street1field='';
        String street2field='';
        String ssnfield='';
        String agefield='';
        
        string criteria='';
        string pbsonpbr='';
        string referralSearch ='';
        if(isContact){
            namefield='name';
            lastnamefield='lastname';
            firstnamefield='firstname';
            genderfield='gender__c';
            dobfield='birthdate';
            cityfield='mailingcity';
            statefield='mailingstatecode';
            zipfield='mailingpostalcode';
            street1field='mailingstreet';
            street2field='otherstreet';
            agefield='age__c';
            sobjecttype='contact';
            criteria='Select '+namefield+','+firstnamefield+','+lastnamefield+','+genderfield+','+dobfield+','+cityfield+','+statefield+','+zipfield+','+street1field+','+street2field+','+agefield+' From '+ sobjecttype+' where (';
        }
        if(isPBR){
            namefield='name';
            lastnamefield='last_name__c';
            firstnamefield='first_name__c';
            genderfield='gender__c';
            dobfield='date_of_birth__c';
            cityfield='city__c';
            statefield='state__c';
            zipfield='zip_code__c';
            street1field='street_1__c';
            street2field='street_2__c';
            agefield='age__c';
            ssnfield='ssn__c';
            pbsonpbr='Person_Being_Served__c';
            sobjecttype='person_being_referred__c';
            referralSearch = '(SELECT ID,Person_Being_Served__c FROM Referrals__r WHERE Person_Being_Served__c = null LIMIT 1)';
            criteria='Select '+namefield+','+firstnamefield+','+lastnamefield+','+genderfield+','+dobfield+','+cityfield+','+statefield+','+zipfield+','+street1field+','+street2field+','+agefield+','+referralSearch+','+pbsonpbr+' From '+ sobjecttype+' where (';
        }
       // String criteria='Select '+namefield+','+firstnamefield+','+lastnamefield+','+genderfield+','+dobfield+','+cityfield+','+statefield+','+zipfield+','+street1field+','+street2field+','+agefield+' From '+ sobjecttype+' where (';
        string lNameSearch = '';
        string fNameSearch = '';
        if(lastname!=null && lastname!=''){
            if(lastname.contains('*')){
                lNameSearch+=' ('+lastnamefield +' like \''+lastname.replace('*','%')+'\')';
            }else{
                //if(dob!=null || (age!=null && age!=0)){
                    lNameSearch+=' ('+lastnamefield +' like \''+lastname+'%\''+ ' or last_name_soundex_key__c =\''+SoundEx.ToSoundEx(lastname)+'\') ';
                //}
            }
            criteria += lNameSearch;
        }
        if(firstname!=null && firstname!=''){
            if(lastname!=null && lastname!=''){
                criteria+= ' and ';
            }
            if(firstname.contains('*')){
                fNameSearch+=' ('+firstnamefield+' like \''+firstname.replace('*','%')+'\')';
            }else{
                //if(dob!=null || (age!=null && age!=0)){
                    fNameSearch+=' ('+firstnamefield+' like \''+firstname+'%\''+ ' or first_name_soundex_key__c =\''+SoundEx.ToSoundEx(firstname)+'\')';
                //}
            }
            criteria += fNameSearch;
        }
        criteria += ')';
        
        if(dob!=null || (age!= null && age!=0) || gender!=null && gender!=''){
            String extraCriteria = '';
            if(dob!=null){
                extraCriteria += ' and ';
                extraCriteria+=' ('+dobfield+' = :dob ) ';
            }
            if(age!= null && age!=0){
                extraCriteria += ' and ';
                extraCriteria+=' ('+agefield+' = '+age+ ') ';
            }
            if(gender!=null && gender!=''){
                extraCriteria += ' and ';
                extraCriteria+=' ('+genderfield+' = \''+gender+ '\') ';
            }
            
            if (firstname!=null && firstname!='' && lastname!=null && lastname!='' ) {
                //if both first name and last name are filled in then search on each individually
                criteria += 'or (' + fNameSearch + extraCriteria + ') or (' + lNameSearch + extraCriteria +')';
            }
            else
            {
                //if only first name or only last name, then don't search on each individually
                criteria += extraCriteria;
            }
        }
        /*
        if(ssn!=null && ssn!=''){
            if(isAccount){
                throw new CustomException('There is no ssn field on Person Being Served Object. Set isAccount argument to false or ssn argument to null');
            }
            criteria += ' and ';
            criteria+=' ('+ssnfield+' = \''+ssn+ '\') ';
        }*/
        criteria+= ' limit ' + RECORD_LIMIT;
        return criteria;
    }
    class CustomException extends Exception{
    
    }
}