src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_Text__c</fullName>
        <formula>CASE( 1,
IF( (YEAR(TODAY())- Year(Birthdate)) ==1,1,100),&quot;1 Year&quot;,
IF( (YEAR(TODAY())- Year(Birthdate)) &gt; 1,1,200), TEXT(FLOOR(((TODAY()) - (Birthdate)+1)/365.2425)) + &quot; Years&quot; ,
IF(YEAR(TODAY()) -Year(Birthdate)==0 &amp;&amp; DAY(Birthdate) - DAY(TODAY())&lt;=0 &amp;&amp; MONTH(TODAY()) - MONTH(Birthdate)==1 ,1,300 ) , &quot;1 Month&quot;,

IF(YEAR(TODAY()) -Year(Birthdate)==0 &amp;&amp; MONTH(TODAY()) - MONTH(Birthdate)&gt;1,1,400), TEXT(MONTH(TODAY()) - MONTH(Birthdate)) +&quot; Months&quot;,
IF( (YEAR(TODAY()) -Year(Birthdate)==0) &amp;&amp; (MONTH(TODAY()) - MONTH(Birthdate)==0 || MONTH(TODAY()) - MONTH(Birthdate)==1) &amp;&amp; (DAY(TODAY() -DAY(Birthdate) )==1),1,500), &quot;1 Day&quot;,

IF( (YEAR(TODAY()) -Year(Birthdate)==0) &amp;&amp; (MONTH(TODAY()) - MONTH(Birthdate)==0 || MONTH(TODAY()) - MONTH(Birthdate)==1) &amp;&amp; (DAY(TODAY() -DAY(Birthdate) )&gt;1),1,600), TEXT( DAY(TODAY() -DAY(Birthdate) ))+&quot; Days&quot;,
&quot;0&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will contain the Record type name of the referral from where the PBS is created. This value will be used by developers to conditionally render stuff on PBS page and related objects - Sravan: Sep 11, 2015</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Select the person&apos;s legal gender</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Cat_Seq_Text__c</fullName>
        <description>text version of sequence</description>
        <label>Cat Seq Text</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubCat_Seq_Text__c</fullName>
        <defaultValue>&quot;1001&quot;</defaultValue>
        <label>SubCat Seq Text</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Associated to Event</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Im_Incidents</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_InvolvedParty__c.object
<CustomObject>
    <description>The individuals involved with the event/incident.</description>
    <fields>
        <fullName>Im_Incident__c</fullName>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served Involved</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_InvolvedParty</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_InvolvedParties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Flavor__c</fullName>
        <description>This field will store the Recordtype name of the referral from where the service assignment is created. This will be used by developers to conditionally render stuff on SA page for various flavors. If an adhoc SA is created directly without referral, this field will copy over the value from existing service Assignment available for PBS - Sravan -Sep 11, 2015.</description>
        <label>Flavor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pbsFirstName__c</fullName>
        <formula>Person_Being_Served__r.FirstName</formula>
        <label>pbsFirstName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pbsLastName__c</fullName>
        <formula>Person_Being_Served__r.LastName</formula>
        <label>pbsLastName</label>
        <type>Text</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Approval_Manager__c</fullName>
        <label>Accountable Approval Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Accountable_Manager_Mentor_Email__c</fullName>
        <label>Accountable Manager Mentor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alias_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for alias. Used to set alias and related fields.</description>
        <label>Alias Lookup</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <description>By default, this will be Active for any person in the database. As time goes and the feed only puts in Active users, we&apos;ll need to update the ones in the database but are not in the feed to Inactive.</description>
        <label>Job Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncidentLookup.cls
public with sharing class IncidentLookup {
	@RemoteAction
	public static list<MyRemoteMethods.SelOption> findPBS(String params) {
		map<String, String> values = (Map<String, String>) JSON.deserialize(params, map<String, String>.class);
		String searchTerm = '%' + String.ValueOf(values.get('q')).trim() + '%' ;

		list<MyRemoteMethods.SelOption> retVal = new list<MyRemoteMethods.SelOption>();
		map<Id, Service_Assignment__c> pbsSaMap = new map<Id, Service_Assignment__c>();

		list<Service_Assignment__c> serviceAssignments = [
			select Id, person_being_served__c, pbsLastName__c, pbsFirstName__c,
			       person_being_served__r.Age_Text__c, person_being_served__r.Gender__c
			  from Service_Assignment__c
			 where Status__c = 'Active'
			   and (pbsFirstName__c like :searchTerm OR pbsLastName__c like :searchTerm)
			 order by Name
		];
		for(Service_Assignment__c sa : serviceAssignments){
			pbsSaMap.put(sa.person_being_served__c, sa);
			retVal.add(new MyRemoteMethods.SelOption(sa));
		}
		for(Attachment headShot : [SELECT Id, Name,  ParentId from Attachment where Name LIKE 'HeadShot-Current%' and ParentId IN :pbsSaMap.keySet()]){
			Service_Assignment__c sa = (Service_Assignment__c) pbsSaMap.get(headShot.ParentId);
			//chose a dummy field on the SA object to carrry the pbs headShot attachment id
			sa.Flavor__c = '/servlet/servlet.FileDownload?file=' + headShot.id;
		}
		return retVal;
	}

	@RemoteAction
	public static list<MyRemoteMethods.SelOption> findStaff(String params){
		map<String, String> values = (Map<String, String>) JSON.deserialize(params, map<String, String>.class);
		String searchTerm = '%' + String.ValueOf(values.get('q')).trim() + '%' ;

		list<MyRemoteMethods.SelOption> retVal = new list<MyRemoteMethods.SelOption>();
		for (TMN_User__c t : [select Id, Name, email__c, job_title__c from TMN_User__c where Job_Status__c = 'Active' and Name like :searchTerm order by Name]){
			retVal.add(new MyRemoteMethods.SelOption(t));
		}
		return retVal;
	}

	public Id serviceLocation { get; set; }
	public List<SelectOption> serviceLocations {
		private set;
		get {
			if (serviceLocations != null) {
				return serviceLocations;
			}
			list<TMN_User__c> tmnUser = [
				SELECT id, name, Accountable_Approval_Manager__c,
				       Accountable_Manager_Mentor_Email__c, Alias_lookup__c
				  FROM TMN_User__c
				 WHERE Salesforce_User_Account__c =:UserInfo.getUserId()
			];
			if (tmnUser.size() != 1) {
				throw new Utility.CustomException(Utility.IMPLEMENTATION_EXCEPTION_MESSAGE);
			}
			Service_Location__c[] sls = Utility.getServiceLocationsForTmnUser(tmnUser[0]);
			Id currentServiceLocationId;
			if (sls.size() == 1) {
				currentServiceLocationId = String.valueOf(sls[0].id);
			}
			serviceLocations = Utility.getServiceLocations(currentServiceLocationId);
			return serviceLocations;
		}
	}

	public String eventType { get; set; }
	public List<SelectOption> eventTypes {
		private set;
		get {
			if (eventTypes != null) {
				return eventTypes;
			}
			eventTypes = new List<SelectOption>();
			Map<String, String> eventTypeMap = new Map<String, String>();
			for(Eval__c e : [
				select Composite__c, category__c, sub_category__c
				  from eval__c
				 where eval_type__r.Name IN ('Involved Party')
				   and Visible__c = true
				order by cat_seq_text__c, subcat_seq_text__c
			]){
				if (!eventTypeMap.containsKey(e.Composite__c)) {
					eventTypeMap.put(e.Composite__c, e.sub_category__c); // they want only the subCat
				}
			}
			eventTypes.add(new SelectOption('', ''));
			for (String composite: eventTypeMap.keySet()) {
				eventTypes.add(new SelectOption(composite, eventTypeMap.get(composite)));
			}
			return eventTypes;
		}
	}

	public Boolean finalizedIncidentsOnly { get; set; }

	public Id pbsId { get; set; }
	public Id staffId { get; set; }

	public Service_Assignment__c pbs {
		set;
		get {
			if (!String.isBlank(pbsId)) {
				pbs = [SELECT pbsLastName__c, pbsFirstName__c FROM Service_Assignment__c WHERE Id=:pbsId];
				return pbs;
			}
			return null;
		}
	}

	public TMN_User__c staff {
		set;
		get {
			if (!String.isBlank(staffId)) {
				staff = [SELECT Id, Name FROM Tmn_User__c WHERE Id = :staffId];
				return staff;
			}
			return null;
		}
	}
	public Boolean searchInitiated { get; set; }

	public List<Im_Incident__c> incidents { get; set; }

	public IncidentLookup() {
		searchInitiated = false;
	}

	public PageReference search() {
		// Here's how we narrow down the search: First by Program, then by
		// involved party (PBS & Staff), and lastly by event types
		Im_Incident__c[] incidentsInScope;
		if (!String.isBlank(serviceLocation)) {
			incidentsInScope = [
				SELECT Id
				  FROM Im_Incident__c
				 WHERE Service_Location__c = :serviceLocation
			];
		}
		String query =
			'SELECT Id, Im_Incident__c, Person_Being_Served_Involved__c, Staff_Involved__c' +
			'  FROM Im_InvolvedParty__c';

		if (!String.isBlank(pbsId) || !String.isBlank(staffId) || !String.isBlank(serviceLocation)) {
			query += ' WHERE ';
		}
		String[] conditions = new String[] {};
		if (!String.isBlank(serviceLocation)) {
			conditions.add(' Im_Incident__r.Service_Location__c = :serviceLocation');
		}
		if (!String.isBlank(pbsId) || !String.isBlank(staffId)) {
			String invQuery = '(';
			if (!String.isBlank(pbsId)) {
				invQuery += 'Person_Being_Served_Involved__c = :pbsId';
			}
			if (!String.isBlank(pbsId) && !String.isBlank(staffId)) {
				invQuery += ' OR ';
			}
			if (!String.isBlank(staffId)) {
				invQuery += 'Staff_Involved__c = :staffId';
			}
			invQuery += ')';
			conditions.add(invQuery);
		}
		query += String.join(conditions, ' AND ');
		System.debug('Involved Party Query: ' + query);

		Im_InvolvedParty__c[] involvedParties = Database.query(query);

		// At this point, the involved parties might still have records in them
		// that should not be in the search result, e.g. if the user specifies
		// both the Staff and the Person Being Served, right now involvedParties
		// have them ORed together, so we need to do some work to get rid of
		// unnecessary records.
		if (!String.isBlank(pbsId) && !String.isBlank(staffId)) {
			Im_InvolvedParty__c[] correctedInvolvedParties = new Im_InvolvedParty__c[]{};
			Map<Id, List<Im_InvolvedParty__c>> incidentInvolvedPartyMap = new Map<Id, List<Im_InvolvedParty__c>>();
			for (Im_InvolvedParty__c involvedParty: involvedParties) {
				if (!incidentInvolvedPartyMap.containsKey(involvedParty.Im_Incident__c)) {
					incidentInvolvedPartyMap.put(involvedParty.Im_Incident__c, new List<Im_InvolvedParty__c>());
				}
				incidentInvolvedPartyMap.get(involvedParty.Im_Incident__c).add(involvedParty);
			}
			for (Id incidentId: incidentInvolvedPartyMap.keySet()) {
				Boolean pbsFound = false;
				Boolean staffFound = false;
				for (Im_InvolvedParty__c involvedParty: incidentInvolvedPartyMap.get(incidentId)) {
					if (!String.isBlank(pbsId) && involvedParty.Person_Being_Served_Involved__c == pbsId) {
						pbsFound = true;
					}
					if (!String.isBlank(staffId) && involvedParty.Staff_Involved__c == staffId) {
						staffFound = true;
					}
				}
				if (pbsFound && staffFound) {
					correctedInvolvedParties.addAll(incidentInvolvedPartyMap.get(incidentId));
				}
			}
			involvedParties = correctedInvolvedParties;
		}
		Set<Id> involvedPartyIds = new Set<Id>();
		for (Im_InvolvedParty__c involvedParty: involvedParties) {
			involvedPartyIds.add(involvedParty.Id);
		}

		if (!String.isBlank(eventType)) {
			Eval_Value__c[] values = [
				SELECT Id, What_Id__c
				  FROM Eval_Value__c
				 WHERE Eval__r.Composite__c = :eventType
				   AND What_Id__c IN :involvedPartyIds
			];
			Set<String> involvedPartiesFromValues = new Set<String>();
			for (Eval_Value__c value: values) {
				involvedPartiesFromValues.add(value.What_Id__c);
			}
			Im_InvolvedParty__c[] correctedInvolvedParties = new Im_InvolvedParty__c[]{};
			for (Im_InvolvedParty__c involvedParty: involvedParties) {
				if (involvedPartiesFromValues.contains(involvedParty.Id)) {
					correctedInvolvedParties.add(involvedParty);
				}
			}
			involvedParties = correctedInvolvedParties;
		}

		Set<Id> incidentIds = new Set<Id>();
		for (Im_InvolvedParty__c involvedParty: involvedParties) {
			incidentIds.add(involvedParty.Im_Incident__c);
		}

		String incidentQuery =
			'SELECT Id, Name, Status__c, Final_Level__c, Date_Documented__c,' +
			'       Service_Location__r.Alias__c, Service_Location__r.Program__c' +
			'  FROM Im_Incident__c' +
			' WHERE Id IN :incidentIds';
		if (finalizedIncidentsOnly) {
			incidentQuery += ' AND Status__c = \'Incident-Finalized\'';
		}
		System.debug('Incident query: ' + incidentQuery);

		incidents = Database.query(incidentQuery);

		searchInitiated = true;
		return null;
	}
}