src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY()-Birthdate +1)/365.2425)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Select the person&apos;s legal gender</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Indian/Alaskan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian/Pacific Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caucasian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle Eastern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Racial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>This field is used for the Mentor record type.</description>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for the Mentor record type.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR( TODAY() ) - YEAR( Date_of_Birth__c )</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chessie_ID__c</fullName>
        <label>Chessie ID</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disregarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>if(ISNULL(Middle_Initial__c ),
First_Name__c &amp; &quot; &quot; &amp;  Last_Name__c,
First_Name__c &amp; &quot; &quot; &amp;   Middle_Initial__c &amp; &quot; &quot; &amp; Last_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Household_Id__c</fullName>
        <formula>IF(CONTAINS(RecordType.Name, &apos;Mentor&apos;), Id, IF(CONTAINS(RecordType.Name, &apos;Household Member&apos;), Mentor__c, null))</formula>
        <label>Household Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_Progress_Date__c</fullName>
        <description>This field is used for the Mentor record type.</description>
        <label>In Progress Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for the Mentor record type.</description>
        <label>In Progress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive_Date__c</fullName>
        <description>This field is used for the Mentor record type.</description>
        <label>Inactive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for the Mentor record type.</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Recertification_Date__c</fullName>
        <label>Most Recent Recertification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>Caucasian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Indian/Alaskan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian/Pacific Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Racial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle Eastern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>This field centralizes the Role for Mentors and their Household Members.</description>
        <formula>IF( CONTAINS(RecordType.Name, &apos;Mentor&apos;) , &apos;Mentor&apos;, IF ( CONTAINS(RecordType.Name, &apos;Related Party&apos;),  TEXT( Related_Party_Type__c ) , &apos;&apos; ) )</formula>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suspend_Date__c</fullName>
        <description>This field is used for the Mentor record type.</description>
        <label>Suspend Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suspended__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for the Mentor record type.</description>
        <label>Suspended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>TMN Contact</label>
    <nameField>
        <displayFormat>TMN-CNT-{0000}</displayFormat>
        <label>TMN Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMN Contacts</pluralLabel>
    <recordTypes>
        <fullName>Mentor</fullName>
        <active>true</active>
        <label>Mentor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TMNContacts.cls
global with sharing class TMNContacts {

    @RemoteAction
    global static String getClassName(){
        return 'TMNContacts';
    }
    
    @RemoteAction
    global static List<TMN_Contact__c> getTMNContacts(String filterType, String filter){
        /*
         * Filter can be
         * All, Role (Mentor, Sibling etc...) 
         * 
         * Filter Type can be
         * All, Role, Name
         */
         List<TMN_Contact__c> tmnContacts;
         if (filter == 'All') {
	        tmnContacts = [
	         
	                    select 
	                      name
	                     ,Household_Id__c
	                     ,Full_Name__c
	                     ,Role__c
	                     ,owner_full_name__c
	                     ,createdby.firstname 
	                     ,createdby.lastname
	                     ,createdDate
	                     ,lastModifiedBy.firstname
	                     ,lastModifiedby.lastname
	                     ,lastModifiedDate
	                    from TMN_Contact__c
	                    order by createdDate
	         
	         ];
         } else if (filter == 'Non Mentors') {
         	
	        tmnContacts = [
	         
	                    select 
	                      name
	                     ,Household_Id__c
	                     ,Full_Name__c
	                     ,Role__c
	                     ,owner_full_name__c
	                     ,createdby.firstname 
	                     ,createdby.lastname
	                     ,createdDate
	                     ,lastModifiedBy.firstname
	                     ,lastModifiedby.lastname
	                     ,lastModifiedDate
	                    from TMN_Contact__c
	                    where Household_Id__c =: filterType and role__c != 'Mentor'
	                    order by createdDate
	         
	         ];
         	
         	
         } else {
         	 tmnContacts = [
	                    select 
	                      name
	                     ,Household_Id__c
	                     ,Full_Name__c
	                     ,Role__c
	                     ,owner_full_name__c
	                     ,createdby.firstname 
	                     ,createdby.lastname
	                     ,createdDate
	                     ,lastModifiedBy.firstname
	                     ,lastModifiedby.lastname
	                     ,lastModifiedDate
	                    from TMN_Contact__c
	                    where role__c = 'Mentor'
	                    order by createdDate
	         ];
         	
         }
         
         return tmnContacts;
    }// end getTMNContacts method
    

    @RemoteAction
    global static TMN_Contact__c getTMNContactDetail(String id){
        TMN_Contact__c tmnContact;
        tmnContact = [
                      select 
                         Full_Name__c
						,Chessie_ID__c
						,Date_of_Birth__c
						,Gender__c
						,Age__c
						,Marital_Status__c
						,Race__c
						,Hispanic_Heritage__c
						,DHR_CPA_Race_1__c
						,DHR_CPA_Race_2__c 
						 from tmn_contact__c
        ];        
        return tmnContact;
    }// end getTMNContactDetail


/*
            <apex:pageBlockSection title="Contact Information">
                <apex:outputField value="{!TMN_Contact__c.Street_1__c,Street_2__c}" />

                <apex:outputField value="{!TMN_Contact__c.City__c,State__c}" />

                <apex:pageBlockSectionItem />
                <apex:outputField value="{!TMN_Contact__c.Zip_Code__c}" />

                <apex:outputField value="{!TMN_Contact__c.Primary_Phone__c,Secondary_Phone__c}" />

                <apex:outputField value="{!TMN_Contact__c.Email__c}" />
            </apex:pageBlockSection>
            <apex:pageBlockSection title="Marketing Info" columns="2">
                <apex:outputField value="{!TMN_Contact__c.How_did_you_hear_about_us__c}" />
                <apex:outputField value="{!TMN_Contact__c.How_did_you_hear_Other_Describe__c}" />
                <apex:outputField value="{!TMN_Contact__c.Referral_Type__c}" />
            </apex:pageBlockSection>
            <apex:pageBlockSection title="Mentor Status" columns="2">
                <apex:outputField value="{!TMN_Contact__c.Disregarded__c}" />
                <apex:pageBlockSectionItem />
                <apex:outputField value="{!TMN_Contact__c.Population_This_Home_Is_Associated_With__c}" label="With which population is this home associated?" />
                <apex:pageBlockSectionItem />
                <apex:outputField value="{!TMN_Contact__c.In_Progress__c}" />
                <apex:outputField value="{!TMN_Contact__c.In_Progress_Date__c}" />
                <apex:outputField value="{!TMN_Contact__c.Active__c}" />
                <apex:outputField value="{!TMN_Contact__c.Active_Date__c}" />
                <apex:outputField value="{!TMN_Contact__c.Suspended__c}" />
                <apex:outputField value="{!TMN_Contact__c.Suspend_Date__c}" />
                <apex:outputField value="{!TMN_Contact__c.Inactive__c}" />
                <apex:outputField value="{!TMN_Contact__c.Inactive_Date__c}" />
                <apex:outputField value="{!TMN_Contact__c.Denied__c}" />
                <apex:outputField value="{!TMN_Contact__c.Denied_Date__c}" />
                <apex:pageBlockSectionItem />
                <apex:outputField value="{!TMN_Contact__c.Denied_Reason__c}" />
                <apex:outputField value="{!TMN_Contact__c.Withdrawn__c}" />
                <apex:outputField value="{!TMN_Contact__c.Withdrawn_Date__c}" />
                <apex:pageBlockSectionItem />
                <apex:outputField value="{!TMN_Contact__c.Withdrawn_Reason__c}" />
                <apex:outputField value="{!TMN_Contact__c.Most_Recent_Recertification_Date__c}" />
            </apex:pageBlockSection>
            <apex:pageBlockSection title="System Info">
                <apex:outputField value="{!TMN_Contact__c.OwnerId}" />
                <apex:outputText label="Created By" value="{!TMN_Contact__c.CreatedBy.Name}, {!TMN_Contact__c.CreatedDate}" />
                <apex:outputText label="Last Modified By" value="{!TMN_Contact__c.LastModifiedBy.Name}, {!TMN_Contact__c.LastModifiedDate}" />
*/                
                
} //end class