src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Does_the_person_Identify__c</fullName>
        <label>Person Gender Other than legal</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender_Identity__c</fullName>
        <label>Gender Identity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <inlineHelpText>Select the person&apos;s legal gender</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Guardianship_Type__c</fullName>
        <label>Guardianship Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Guardianship/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Guardianship/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Guardianship_Status__c</fullName>
        <label>Legal/Guardianship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Civil Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservator/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kinship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Guardianship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelter Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Assumes Guardianship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Placement Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/pbsbatchforPersonRegistry.cls
global class pbsbatchforPersonRegistry implements Database.Batchable<sObject>{
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		string query = 'SELECT Id, Gender__c, Does_the_person_Identify__c, Gender_Identity__c, Guardianship_Type__c, Legal_Guardianship_Status__c FROM Contact';
		
		return  Database.getQueryLocator(query);
		
	}
	
	global void execute(Database.BatchableContext BC, List<Contact> scope){
		List<Contact> genderUpdateList = new List<Contact>();
		for(Contact pbs: scope){
			if(pbs.Gender__c == 'Transgender' || pbs.Gender__c == 'Other'){
				pbs.Does_the_person_Identify__c = 'Yes';
				//Sravan - Confirmed with Kristen and added below line- PRI-110
				pbs.Gender_Identity__c = pbs.Gender__c;
				pbs.Gender__c = null;
				if(pbs.Legal_Guardianship_Status__c == 'Self'){
					pbs.Guardianship_Type__c = 'Self';
				}
				genderUpdateList.add(pbs);
			}
			
			else if(!(pbs.Gender__c == 'Transgender' || pbs.Gender__c == 'Other')){
					pbs.Does_the_person_Identify__c = 'No';
					if(pbs.Gender__c == 'M'){
						pbs.Gender__c = 'Male';
					}
					if(pbs.Gender__c == 'F'){
						pbs.Gender__c = 'Female';
					}
					if(pbs.Legal_Guardianship_Status__c == 'Self'){
						pbs.Guardianship_Type__c = 'Self';
					}
				genderUpdateList.add(pbs);	
			}

		}
		
		if(genderUpdateList.size() > 0){
			update genderUpdateList;
		}
	}
	
	global void finish(Database.BatchableContext BC){
		
		List<String> toAddresses = new List<String>{'adam.vernatter@thementornetwork.com', 'dylan.melnik@thementornetwork.com'};
		//toAddresses.add('adam.vernatter@thementornetwork.com', 'dylan.melnik@thementornetwork.com');
		Messaging.singleEmailMessage mail = new Messaging.singleEmailMessage();
		mail.setToAddresses(toAddresses);
		mail.setSenderDisplayName('pbsbatchforPersonRegistry');
		mail.setSubject('pbsbatchforPersonRegistry batch execution is completed.');
		mail.setUseSignature(false);
		string body = 'Batch processing is completed. In production, delete me after you see this message.';
		mail.setplainTextBody(body);
		mail.setSaveAsActivity(false);
		
		Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
		
	}

}