src/objects/Credential_Profile__c.object
<CustomObject>
    <description>An object for creating descriptive / meta-data / look up records for given credentials required of Mentors or Mentor household members.</description>
    <fields>
        <fullName>Optional_for_Co_Applicant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Co-Applicant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Foster_Parent_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Foster Parent Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Foster_Parent_Relative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Foster Parent Relative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Mentor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Mentor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Pet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Pet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Resident_Non_Relative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Optional for Resident Non-Relative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Co_Applicant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Co-Applicant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Foster_Parent_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Foster Parent Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Foster_Parent_Relative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Foster Parent Relative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Mentor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Mentor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Pet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required_for_Pet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_for_Resident_Non_Relative__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Resident Non-Relative</label>
        <type>Checkbox</type>
    </fields>
    <label>Credential Profile</label>
    <nameField>
        <label>Credential Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credential Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Credential_Record__c.object
<CustomObject>
    <description>An object to store licenses, credentials, and accreditations for Mentors and members of Mentor households.</description>
    <fields>
        <fullName>Credential_Profile__c</fullName>
        <label>Credential Profile</label>
        <referenceTo>Credential_Profile__c</referenceTo>
        <relationshipLabel>Credential Records</relationshipLabel>
        <relationshipName>Credential_Records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Credential Record</label>
    <nameField>
        <displayFormat>CredRec-{0000000}</displayFormat>
        <label>Credential Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <fields>
        <fullName>Related_Party_Type__c</fullName>
        <label>Related Party Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent&apos;s Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent&apos;s Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident-Non Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Person Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <recordTypes>
        <fullName>Mentor</fullName>
        <active>true</active>
        <label>Mentor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonHandler.cls
public with sharing class PersonHandler {
    private boolean m_isExecuting = false;

    public PersonHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    }

    public void OnBeforeInsert(Person__c[] newObjects){
        // EXECUTE BEFORE INSERT LOGIC
    }

    public void OnAfterInsert(Person__c[] newObjects){
        // EXECUTE AFTER INSERT LOGIC
		
		// Put incoming list of Person__c records into a more user-friendly variable name, and declare a variable for a list or Person__c IDs. 
    	List<Person__c> thesePersons = newObjects;
		List<Id> personIds = new List<Id>();

		Schema.DescribeSObjectResult personSchemaInfo = Person__c.SObjectType.getDescribe();
		List<Schema.RecordTypeInfo> personRecordTypes = personSchemaInfo.getRecordTypeInfos();
    
        // Get ALL credential profiles into a list so we can later filter out only the ones for a given new person's 'type' without putting a query in a loop.
        List<Credential_Profile__c> credList = new List<Credential_Profile__c>();
        credList = [ SELECT Id, Name, Required_for_Mentor__c, Optional_for_Mentor__c, Required_for_Co_Applicant__c, Optional_for_Co_Applicant__c, 
        			Required_for_Foster_Parent_Relative__c, Optional_for_Foster_Parent_Relative__c, Required_for_Foster_Parent_Child__c, 
        			Optional_for_Foster_Parent_Child__c, Required_for_Resident_Non_Relative__c, Optional_for_Resident_Non_Relative__c,
        			Required_for_Pet__c, Optional_for_Pet__c FROM Credential_Profile__c ];
       System.debug('credList holds: ' + credList);
       // Loop through the person records that were just created, and determine which Credential_Profile__c records matter for them, based on the Person__c        
		for (Person__c p : thesePersons) {
       		System.debug('The persons loop in PersonHandler.cls is executing...');
       		System.debug('What is p in the persons loop in PersonHandler.cls: ' + p);

			string thisPersonsRecordTypeName;

   			for(Schema.RecordTypeInfo sPrts : personRecordTypes) {
   				System.debug('sPrts.Name: ' + sPrts.Name);
   				System.debug('p.RecordTypeId: ' + p.RecordTypeId);
   				System.debug('sPrts.RecordTypeId: ' + sPrts.RecordTypeId);
   				if(p.RecordTypeId==sPrts.RecordTypeId) {
   					thisPersonsRecordTypeName = sPrts.Name;
   				}
   			}

       		// Initialize a list variable for the credential records we'll eventually insert for each person.
       		List<Credential_Record__c> credRecs = new List<Credential_Record__c>();
       		
       		for(Credential_Profile__c cp : credList) {
       			System.debug('This person\'s Record Type ID is: ' + p.RecordTypeId);
       			System.debug('This person\'s RecordType.Name is: ' + p.RecordType.Name);
       			System.debug('This credential\'s cp.Required_for_Mentor__c value is: ' + cp.Required_for_Mentor__c);
       			if(thisPersonsRecordTypeName=='Mentor' && cp.Required_for_Mentor__c==true) {
   					Credential_Record__c credRec = new Credential_Record__c(
   						Credential_Profile__c = cp.Id,
   						Person__c = p.Id
   					);			
   					credRecs.add(credRec);
   					System.debug('Added a Credential Record (' + cp.Name + ') to credRecs for a \'Mentor\' Record Type...');
       			}
       			if(thisPersonsRecordTypeName=='Related Party') {
	   				if(p.Related_Party_Type__c=='Co-Applicant' && cp.Required_for_Co_Applicant__c==true) {
	   					Credential_Record__c credRec = new Credential_Record__c(
	   						Credential_Profile__c = cp.Id,
	   						Person__c = p.Id
	   					);			
	   					credRecs.add(credRec);
       				}
	   				if(p.Related_Party_Type__c=='Foster Parent\'s Relative' && cp.Required_for_Foster_Parent_Relative__c==true) {
	   					Credential_Record__c credRec = new Credential_Record__c(
	   						Credential_Profile__c = cp.Id,
	   						Person__c = p.Id
	   					);			
	   					credRecs.add(credRec);
       				}
	   				if(p.Related_Party_Type__c=='Foster Parent\'s Child' && cp.Required_for_Foster_Parent_Child__c==true) {
	   					Credential_Record__c credRec = new Credential_Record__c(
	   						Credential_Profile__c = cp.Id,
	   						Person__c = p.Id
	   					);			
	   					credRecs.add(credRec);
       				}
	   				if(p.Related_Party_Type__c=='Resident-Non Relative' && cp.Required_for_Resident_Non_Relative__c==true) {
	   					Credential_Record__c credRec = new Credential_Record__c(
	   						Credential_Profile__c = cp.Id,
	   						Person__c = p.Id
	   					);			
	   					credRecs.add(credRec);
       				}
	   				if(p.Related_Party_Type__c=='Pet' && cp.Required_for_Pet__c==true) {
	   					Credential_Record__c credRec = new Credential_Record__c(
	   						Credential_Profile__c = cp.Id,
	   						Person__c = p.Id
	   					);			
	   					credRecs.add(credRec);
       				}       				 
       			}    			
       		}
       		insert credRecs;
       }
        
    }

    public void OnBeforeUpdate(Person__c[] oldObjects, Person__c[] updatedObjects, Map<Id,Person__c> newObjMap){
        // BEFORE UPDATE LOGIC 	
    }

    public void OnAfterUpdate(Person__c[] oldObjects, Person__c[] updatedObjects, Map<Id,Person__c> newObjMap){
        // AFTER UPDATE LOGIC
    }

    public void OnBeforeDelete(Person__c[] ObjectsToDelete, Map<Id,Person__c> oldObjMap){
        // BEFORE DELETE LOGIC
    }

    public void OnAfterDelete(Person__c[] deletedObjects, Map<Id,Person__c> oldObjMap){
        // AFTER DELETE LOGIC
    }

    public void OnUndelete(Person__c[] restoredObjects){
        // AFTER UNDELETE LOGIC
    }

    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
    
}