src/objects/Credential_Profile__c.object
<CustomObject>
    <description>An object for creating descriptive / meta-data / look up records for given credentials required of Mentors or Mentor household members.</description>
    <fields>
        <fullName>Applies_Expiration_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Expiration Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Note__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Received_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Received Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Requested_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Requested Date</label>
        <type>Checkbox</type>
    </fields>
    <label>Credential Profile</label>
    <nameField>
        <label>Credential Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credential Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Credential_Record__c.object
<CustomObject>
    <description>An object to store licenses, credentials, and accreditations for Mentors and members of Mentor households.</description>
    <fields>
        <fullName>Credential_Profile__c</fullName>
        <label>Credential Profile</label>
        <referenceTo>Credential_Profile__c</referenceTo>
        <relationshipLabel>Credential Records</relationshipLabel>
        <relationshipName>Credential_Records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <label>Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <label>Credential Record</label>
    <nameField>
        <displayFormat>CredRec-{0000000}</displayFormat>
        <label>Credential Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <label>Person</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Person Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CredentialController.cls
public class CredentialController {

	public Id personID = apexpages.currentpage().getparameters().get('personid');
    public List<Credential_Record__c> AllRecords  {get;set;}
       
    public CredentialController() {
            AllRecords = [SELECT Name, Requested_Date__c, Received_Date__c, Expiration_Date__c, Note__c, Credential_Profile__r.Name, 
                Credential_Profile__r.Applies_Requested_Date__c, Credential_Profile__r.Applies_Received_Date__c, 
                Credential_Profile__r.Applies_Expiration_Date__c, Credential_Profile__r.Applies_Note__c
                FROM Credential_Record__c WHERE Person__c = :personID ORDER BY Credential_Profile__r.Name];
    }   
}