src/objects/Credential_Profile__c.object
<CustomObject>
    <description>An object for creating descriptive / meta-data / look up records for given credentials required of Mentors or Mentor household members.</description>
    <fields>
        <fullName>Applies_Documented_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Applies: Documented Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Note__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Received_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Received Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applies_Requested_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applies: Requested Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DHR_Scope__c</fullName>
        <description>A field that indicates whether this credential profile applies for the contact, the entire household, or is not applicable, for the DHR report.</description>
        <label>DHR Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Adult, Mentor Minors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OLM_Requirement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A boolean to determine whether or not a credential for Mentor tracking is required by the Office of Licensing and Monitoring.</description>
        <label>OLM Requirement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_for_Mentor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required for Mentor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_Order__c</fullName>
        <label>Section Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credential Profile</label>
    <nameField>
        <label>Credential Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credential Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Credential_Record__c.object
<CustomObject>
    <description>An object to store licenses, credentials, and accreditations for Mentors and members of Mentor households.</description>
    <fields>
        <fullName>Credential_Profile__c</fullName>
        <label>Credential Profile</label>
        <referenceTo>Credential_Profile__c</referenceTo>
        <relationshipLabel>Credential Records</relationshipLabel>
        <relationshipName>Credential_Records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>DHR_Scope__c</fullName>
        <formula>TEXT(Credential_Profile__r.DHR_Scope__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DHR Scope</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMN_Contact__c</fullName>
        <label>TMN Contact</label>
        <referenceTo>TMN_Contact__c</referenceTo>
        <relationshipLabel>Credential Records</relationshipLabel>
        <relationshipName>Credential_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Credential Record</label>
    <nameField>
        <displayFormat>CredRec-{0000000}</displayFormat>
        <label>Credential Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Related_Party_Type__c</fullName>
        <label>Related Party Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent&apos;s Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent&apos;s Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident-Non Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Contact</label>
    <nameField>
        <displayFormat>TMN-CNT-{0000}</displayFormat>
        <label>TMN Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMN Contacts</pluralLabel>
    <recordTypes>
        <fullName>Mentor</fullName>
        <active>true</active>
        <label>Mentor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CredentialAddTEST.cls
@isTest
private class CredentialAddTEST {

    static testMethod void myUnitTest() {
    	
    	Credential_Profile__c HealthInspection_Profile = new Credential_Profile__c(
        	Name = 'Health Inspection',
        	Required_for_Mentor__c = true,
        	OLM_Requirement__c = true,
        	Applies_Requested_Date__c = true,
        	Applies_Received_Date__c = true,
        	Applies_Note__c = true,
        	Applies_Documented_Date__c = true,
        	DHR_Scope__c = 'Household',
        	Section__c = 'Test',
        	Section_Order__c = 1,
        	Order__c = 1
        );
        insert HealthInspection_Profile;
    	
        PageReference credAdd = Page.CredentialAdd;
        Test.setCurrentPage(credAdd);
        
        RecordType mentorRecordType = [ SELECT Id FROM RecordType WHERE Name = 'Mentor' AND SObjectType = 'TMN_Contact__c' ];
        TMN_Contact__c tmnContact = new TMN_Contact__c(
        	RecordType = mentorRecordType
        );
        insert tmnContact;
        
        ApexPages.currentPage().getParameters().put('contactid', tmnContact.Id);
		CredentialAdd controller = new CredentialAdd();
		// set the selected item
		controller.selectedCreds.Add(HealthInspection_Profile.Id);
		controller.SaveAddCred();
		
		String nextPage = controller.CancelCredAdd().getUrl();
		
		System.assertEquals('/apex/Credential?contactid=' + tmnContact.Id, nextPage);
		
		nextPage = controller.SaveAddCred().getUrl();
		
		System.assertEquals('/apex/Credential?contactid=' + tmnContact.Id, nextPage);
		
		
		PageReference credAdd2 = Page.CredentialAdd;
		Test.setCurrentPage(credAdd2);
		
		
		RecordType householdMemberRecordType = [ SELECT Id FROM RecordType WHERE Name = 'Household Member' AND SObjectTYpe = 'TMN_Contact__c' ];
		System.debug('householdMemberRecordType: ' + householdMemberRecordType);
		List<TMN_Contact__c> tmnContactsToInsert = new List<TMN_Contact__c>();
		TMN_Contact__c coApplicant = new TMN_Contact__c(
			RecordTypeId = householdMemberRecordType.Id,
			Related_Party_Type__c = 'Co-Applicant',
			Email__c = 'test@test.com'
		);
		tmnContactsToInsert.add(coApplicant);
		TMN_Contact__c fosterParentChild = new TMN_Contact__c(
			RecordTypeId = householdMemberRecordType.Id,
			Related_Party_Type__c = 'Foster Parent\'s Child'
		);
		tmnContactsToInsert.add(fosterParentChild);
		TMN_Contact__c fosterParentRelative = new TMN_Contact__c(
			RecordTypeId = householdMemberRecordType.Id,
			Related_Party_Type__c = 'Foster Parent\'s Relative'
		);
		tmnContactsToInsert.add(fosterParentRelative);
		TMN_Contact__c nonResident = new TMN_Contact__c(
			RecordTypeId = householdMemberRecordType.Id,
			Related_Party_Type__c = 'Resident-Non Relative'
		);
		tmnContactsToInsert.add(nonResident);
		TMN_Contact__c pet = new TMN_Contact__c(
			RecordTypeId = householdMemberRecordType.Id,
			Related_Party_Type__c = 'Pet'
		);
		tmnContactsToInsert.add(pet);
		insert tmnContactsToInsert;
		System.debug('The coApplicant: ' + coApplicant);
		
		ApexPages.currentPage().getParameters().put('contactid', coApplicant.Id);
		CredentialAdd controller2 = new CredentialAdd();
		
		// set the selected item
		controller2.selectedCreds.Add(HealthInspection_Profile.Id);
		controller2.SaveAddCred();
		
		// make sure that it was inserted
		System.Debug( 'Checking for: ' + coApplicant.Id);
		List<Credential_Record__c> existCreds = [SELECT Credential_Profile__c FROM Credential_Record__c WHERE TMN_Contact__c = :coApplicant.Id];
		system.AssertEquals( 1, existCreds.Size());
		
		ApexPages.currentPage().getParameters().put('contactid', fosterParentChild.Id);
		CredentialAdd controller3 = new CredentialAdd();		

		ApexPages.currentPage().getParameters().put('contactid', fosterParentRelative.Id);
		CredentialAdd controller4 = new CredentialAdd();		

		ApexPages.currentPage().getParameters().put('contactid', nonResident.Id);
		CredentialAdd controller5 = new CredentialAdd();

		ApexPages.currentPage().getParameters().put('contactid', pet.Id);
		CredentialAdd controller6 = new CredentialAdd();
    }
}