src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fidelity Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PB_DocPacket__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External_ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Packet_Name__c</fullName>
        <label>Packet Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PB_DocPacket</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB_DocPackets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PB_DocPacket_Document_JO__c.object
<CustomObject>
    <fields>
        <fullName>DocPacket__c</fullName>
        <label>DocPacket</label>
        <referenceTo>PB_DocPacket__c</referenceTo>
        <relationshipName>DocPacketJOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>PB_Document__c</referenceTo>
        <relationshipName>DocPacketJOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PB_DocPacket_Document_JO</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB_DocPacket_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PB_Document__c.object
<CustomObject>
    <description>Object to hold the list of all the documents and their default attributes</description>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due__c</fullName>
        <label>Due</label>
        <picklist>
            <picklistValues>
                <fullName>72 Hours after Treatment Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 days from Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 days from Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 days from Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 days from Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 days from last completed (recurring…)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 days from Treatment Start Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 days PRIOR to Projected End Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 days AFTER Service End Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective date of the document</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <label>Recurring Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>As Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <label>Recurring</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PB_Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB_Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>TMN Providers</relationshipLabel>
        <relationshipName>TMN_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPD_Number__c</fullName>
        <label>SPD #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>eXPRS_Number__c</fullName>
        <label>eXPRS #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TMN Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Providers</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_Provider_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Date__c</fullName>
        <label>Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualification_Date__c</fullName>
        <label>Disqualification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Disqualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disqualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Type__c</fullName>
        <label>Enrollment Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Enrollment</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>TMN Provider Applications</relationshipLabel>
        <relationshipName>TMN_Provider_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Disqualification__c</fullName>
        <label>Reason for Disqualification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Provider Applications</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TmnProviderApplicationTest.cls
@isTest
public with sharing class TmnProviderApplicationTest {
	public static testmethod void simpleTests() {
		TestUtils.CoreDataGenerator generator = new TestUtils.CoreDataGenerator();
		generator.aliasBuilder.setState('OR');
		generator.serviceLocationBuilder.setState('OR');
		generator.serviceLocationBuilder
			.setServiceType('CM - Case Management')
			.setProgramId('111111000')
			.setLocationNickname('Brokerage 1');
		TestUtils.CoreData coreData = generator.persistData();

		Tmn_Provider_Application__c application = new Tmn_Provider_Application__c();
		TmnProviderApplication controller = new TmnProviderApplication(new ApexPages.StandardController(application));
		System.assertNotEquals(null, controller.redirectNew());  // it should redirect to the new provider page

		Tmn_Provider__c provider = new Tmn_Provider__c(
			First_Name__c = 'First',
			Last_Name__c = 'Last',
			Gender__c = 'Male'
		);
		insert provider;

		PageReference pageRef = Page.TmnProviderApplication;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('applicantId', provider.Id);
		controller = new TmnProviderApplication(new ApexPages.StandardController(application));
		System.assertEquals(null, controller.redirectNew());

		System.assertEquals(false, controller.isViewMode);
		System.assertEquals(true, controller.isEditMode);
		System.assertEquals(false, controller.getIsLocked());
		System.assertEquals('Create New Application', controller.getTitle());
		System.assertEquals('New', controller.application.Enrollment_Type__c);

		System.assertNotEquals(null, controller.save());

		// Testing task system here
		controller.dummyTask = new Task();
		controller.createTasks();  // validation error since no owner id is specified
		controller.populateTasks();
		System.assertEquals(0, controller.tasks.size());

		controller.dummyTask.OwnerId = UserInfo.getUserId();
		controller.createTasks();
		controller.populateTasks();
		System.assert(controller.tasks.size() > 0);

		System.assertNotEquals(null, controller.currentTask);
		controller.showAddTask();
		controller.currentTask.Subject = 'Hello';
		controller.saveTask();
		controller.closeTask();

		pageRef.getParameters().put('taskId', controller.tasks[0].Id);
		controller.showEditTask();
		System.assertNotEquals(null, controller.currentTask.Id);

		// Testing the doc compliance feature
		createDocComplianceObjects();
		controller = new TmnProviderApplication(new ApexPages.StandardController(controller.application));
		System.assertequals(0, controller.getAllAssociatedDocs().size());
		Pb_DocPacket_Document_JO__c[] docPacketAssociations = [ SELECT Id FROM Pb_DocPacket_Document_JO__c ];

		Apexpages.currentPage().getParameters().put('selectedKey', docPacketAssociations[0].Id);
		Apexpages.currentPage().getParameters().put('isSelected', String.valueOf(true));

		System.assertNotEquals(null, controller.treeModel);
		System.assertNotEquals(null, controller.treeData);
		controller.showAddEditDoc();
		System.debug(controller.treeModel);
		controller.updateDocSelection();
		controller.saveDoc();
		controller.cancelSelection();

		System.assertequals(1, controller.getAllAssociatedDocs().size());
		System.assertequals(1, controller.associatedDocs.size());

		// Back to the application flow
		controller.approve();  // should not success since there's a bunch of validation error
		System.assertEquals('Pending Approval', controller.application.Status__c);

		provider.SPD_Number__c = '111111';
		provider.eXPRS_Number__c = '222222';
		provider.Brokerage__c = coreData.serviceLocation.Id;
		update provider;

		application = [ SELECT Id, Name FROM Tmn_Provider_Application__c WHERE Id = :application.Id ];
		controller = new TmnProviderApplication(new ApexPages.StandardController(application));
		System.assertEquals('First Last Application 1', controller.getTitle());
		controller.application.Provider__r = provider;
		controller.application.Application_Date__c = Date.today();
		controller.application.Effective_Date__c = Date.today();
		controller.application.Expiration_Date__c = Date.today().addYears(1);
		controller.application.SPD_Number__c = provider.SPD_Number__c;
		controller.application.eXPRS_Number__c = provider.eXPRS_Number__c;

		controller.approve();
		System.assertEquals('Approved', controller.application.Status__c);

		controller.disqualifyApprovedApplication();  // validation errors
		System.assertEquals('Approved', controller.application.Status__c);
		System.assertEquals(false, controller.application.Disqualified__c);

		controller.application.Disqualification_Date__c = Date.today();
		controller.application.Reason_for_Disqualification__c = 'Test Reason';
		controller.disqualifyApprovedApplication();
		System.assertEquals('Approved', controller.application.Status__c);
		System.assertEquals(true, controller.application.Disqualified__c);
		System.assertEquals(true, [SELECT Id, Disqualified__c FROM Tmn_Provider_Application__c].Disqualified__c);

		pageRef.getParameters().put('applicantId', provider.Id);
		controller = new TmnProviderApplication(new ApexPages.StandardController(new Tmn_Provider_Application__c()));
		System.assertEquals('Re-Enrollment', controller.application.Enrollment_Type__c);

		controller.application.Application_Date__c = Date.today();
		controller.application.Effective_Date__c = Date.today();
		controller.application.Expiration_Date__c = Date.today().addYears(1);
		controller.save();

		controller.disqualify();  // validation errors
		System.assertEquals('Pending Approval', controller.application.Status__c);

		controller.application.Disqualification_Date__c = Date.today();
		controller.application.Reason_for_Disqualification__c = 'Test Reason';
		controller.disqualify();
		System.assertEquals('Disqualified', controller.application.Status__c);
		System.assertEquals(true, controller.application.Disqualified__c);
	}

	private static void createDocComplianceObjects() {
		//create a packet
		PB_DocPacket__c packet = new PB_DocPacket__c(
			RecordTypeId = Schema.SObjectType.Pb_DocPacket__c.getRecordTypeInfosByName().get('Tmn Provider Application').getRecordTypeId(),
			Packet_Name__c = 'OR Brokerage Standard Qualification Document',
			Status__c = 'Active',
			External_ID__c = String.valueOf(Math.abs(Math.random()))
		);
		insert packet;

		//create three documents
		Id rtId = Schema.SObjectType.PB_Document__c.getRecordTypeInfosByName().get('Tmn Provider Application').getRecordTypeId();
		Pb_Document__c[] documents = new Pb_Document__c[] {
			new Pb_Document__c(
				Document_Name__c = 'Provider Enrollment Application/Approval',
				Due__c = 'N/A',
				Effective_Date__c = Date.today(),
				RecordTypeId = rtId,
				External_Id__c = 'TmnProviderApplicationDoc1',
				Recurring__c = 'No',
				Recurring_Frequency__c = 'One-Time',
				Status__c = 'Active',
				Type__c = 'Standard',
				Version__c = 1
			),
			new Pb_Document__c(
				Document_Name__c = 'eXPRS Enrollment Form',
				Due__c = 'N/A',
				Effective_Date__c = Date.today(),
				RecordTypeId = rtId,
				External_Id__c = 'TmnProviderApplicationDoc2',
				Recurring__c = 'No',
				Recurring_Frequency__c = 'One-Time',
				Status__c = 'Active',
				Type__c = 'Standard',
				Version__c = 1
			),
			new Pb_Document__c(
				Document_Name__c = 'Intake Packet',
				Due__c = 'N/A',
				Effective_Date__c = Date.today(),
				RecordTypeId = rtId,
				External_Id__c = 'TmnProviderApplicationDoc3',
				Recurring__c = 'No',
				Recurring_Frequency__c = 'One-Time',
				Status__c = 'Active',
				Type__c = 'Standard',
				Version__c = 1
			),
			new Pb_Document__c(
				Document_Name__c = 'CRIMS Background Check',
				Due__c = 'N/A',
				Effective_Date__c = Date.today(),
				RecordTypeId = rtId,
				External_Id__c = 'TmnProviderApplicationDoc4',
				Recurring__c = 'No',
				Recurring_Frequency__c = 'One-Time',
				Status__c = 'Active',
				Type__c = 'Standard',
				Version__c = 1
			),
			new Pb_Document__c(
				Document_Name__c = 'Fiscal Intermediary Documents',
				Due__c = 'N/A',
				Effective_Date__c = Date.today(),
				RecordTypeId = rtId,
				External_Id__c = 'TmnProviderApplicationDoc5',
				Recurring__c = 'No',
				Recurring_Frequency__c = 'One-Time',
				Status__c = 'Active',
				Type__c = 'Standard',
				Version__c = 1
			)
		};
		insert documents;

		//create the JOs
		Pb_DocPacket_Document_JO__c[] jos = new Pb_DocPacket_Document_JO__c[]{
			new PB_DocPacket_Document_JO__c(
				DocPacket__c = packet.id,
				Document__c = documents[0].id
			),
			new PB_DocPacket_Document_JO__c(
				DocPacket__c = packet.id,
				Document__c = documents[1].id
			),
			new PB_DocPacket_Document_JO__c(
				DocPacket__c = packet.id,
				Document__c = documents[2].id
			),
			new PB_DocPacket_Document_JO__c(
				DocPacket__c = packet.id,
				Document__c = documents[3].id
			),
			new PB_DocPacket_Document_JO__c(
				DocPacket__c = packet.id,
				Document__c = documents[4].id
			)
		};
		insert jos;
	}
}