src/objects/Document__c.object
<CustomObject>
    <description>An object for holding document profiles for the Document Tracker.</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase_or_Level__c</fullName>
        <label>Phase or Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>A field to hold the program name for Fidelity Documents ONLY, in order to provide an easy means of getting the Fidelity Document program on the Document list view.  The inclusion of Fidelity Documents on a given Service Assignment is handled via creation of a cross-reference record in Program_Document_Xref__c, NOT by reference to this field on the Document__c record(s).</description>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The state(s) to which a document is related</description>
        <inlineHelpText>Pick a state(s) to which the document profile will be associated.</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA-Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Case Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fidelity Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Document_Xref__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Program Document Xrefs</relationshipLabel>
        <relationshipName>Program_Document_Xrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program Document Xref</label>
    <nameField>
        <displayFormat>Program_Doc_Xref_{0000000}</displayFormat>
        <label>Program_Document_Xref__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Document Xrefs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Service Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceAssignment_Document_JO__c.object
<CustomObject>
    <description>An object to hold Service Assignment / Document cross-reference records.</description>
    <fields>
        <fullName>Document__c</fullName>
        <description>The Document in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Document in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>File_Status__c</fullName>
        <label>File Status</label>
        <picklist>
            <picklistValues>
                <fullName>Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filed - Not Contract Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - File Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - Document In Initial File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Filed - Unrecoverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A - Non-FCT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <description>The Service Assignment in this Service Assignment / Document cross-reference record.</description>
        <inlineHelpText>The Service Assignment in this Service Assignment / Document cross-reference record.</inlineHelpText>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>ServiceAssignment_Document_JOs</relationshipLabel>
        <relationshipName>ServiceAssignment_Document_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ServiceAssignment_Document_JO</label>
    <nameField>
        <label>ServiceAssignment_Document_JO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ServiceAssignment_Document_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServAssignFidelityChecklistExtTest.cls
@isTest
public with sharing class ServAssignFidelityChecklistExtTest {
    static testmethod void simpleTests() {
    
        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
 
        Document__c doc = new Document__c(
            Type__c = 'Fidelity Document',
            Order__c = 1,
            Phase_or_Level__c = 1,
            state__c = 'NC'
        );
        insert doc;

        Program_Document_Xref__c progDoc = new Program_Document_Xref__c(
            Document__c = doc.Id,
            Program__c = 'IFCS',
            Service_Line__c = 'Intensive In Home - FCT'
        );
        insert progDoc;

        ServiceAssignment_Document_JO__c jo = new ServiceAssignment_Document_JO__c(
            Service_Assignment__c = myData.theSA.id,
            Document__c = doc.Id,
            File_Status__c = 'Filed'
        );
        insert jo;

        ServAssignFidelityChecklistExt controller = new ServAssignFidelityChecklistExt(
            new ApexPages.standardController(myData.theSA)
        );
        controller.findFidelityDocs();
        controller.listOfFidDocFilings[0].selectFidDocStatusBeforeSave = false;
        controller.saveFidDocSelections();
        controller.refreshListOfDocFilings();
        System.assert(ServAssignFidelityChecklistExt.loadSadjo(jo.Id) != null);
        ServAssignFidelityChecklistExt.saveSadjoRemote(jo.Id, 'Test NA Reason',
            'Test Status', true);
        controller.addError('Test Error');
    }
}