src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>85</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropdown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiselect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Time__c</fullName>
        <label>Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_No_Decimal__c</fullName>
        <label>Number No Decimal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Text_Over_250__c</fullName>
        <label>Text Over 250</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text_Under_250__c</fullName>
        <label>Text Under 250</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID_Object__c</fullName>
        <label>What ID Object</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <recordTypes>
        <fullName>CNA_Workbook</fullName>
        <active>true</active>
        <description>Used for CNAs during shift activities</description>
        <label>CNA Workbook</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CNANoteInput_Test.cls
@isTest
private class CNANoteInput_Test {

    static testMethod void simpleTest() {
    	
    	// set up the eval
    	List<Eval__c> newrows  = new List<Eval__c>();
    	
    	Eval_type__c newevaltype = new Eval_type__c ( name='CNA Workbook', category__c = 'Care Meridian');
    	insert newevaltype;
    	newevaltype = [ select id from eval_type__c where name='CNA Workbook' and category__c = 'Care Meridian' LIMIT 1];
    	
    	Eval__c newRec = new Eval__c( eval_Type__c = newevaltype.id,
    									category__c = 'Diagnostics',
    									sub_category__c = 'Vitals',
    									field_name__c = 'Blood Pressure',
    									field_type__c = 'string',
    									length__c = 10,
    									htmlid__c = 'signsBP');
    									
		newrows.add( newRec);
    	newRec = new Eval__c( eval_Type__c = newevaltype.id,
    									category__c = 'Diagnostics',
    									sub_category__c = 'Vitals',
    									field_name__c = 'Date/Time',
    									field_type__c = 'Datetime',
    									length__c = 50,
    									htmlid__c = 'signsDateTime');


    	newrows.add( newRec );
    	
    	newRec = new Eval__c( eval_Type__c = newevaltype.id,
    									category__c = 'Diagnostics',
    									sub_category__c = 'Vitals',
    									field_name__c = 'Temperature',
    									field_type__c = 'String',
    									length__c = 50,
    									htmlid__c = 'signsTemp');


    	newrows.add( newRec );
    	
    	insert newrows;
    	
    	// need a PBS, evaluation
		TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();
		testData.LoadData('CA');
		
		ID rtID = [select id from recordtype where sobjecttype='Evaluation__c' and developername = 'CNA_Workbook'].ID;
		
        Evaluation__c eval = new Evaluation__c(recordtypeid = rtID, serviceassignment__c= testData.theSA.Id);
        insert eval;
    	string XML = 
        '<?xml version="1.0" encoding="UTF-8"?>'+ 
		'<form first-page="111.111">' +
		  '<submit email="test@thementornetwork.com" />' +
		  '<field type="boxed" name="eval-signsTime_1" normalized-score="1" resemblance-score="1">1210</field>' +
		  '<field type="boxed" name="eval-signsTime_2" normalized-score="0.919" resemblance-score="0.699">1315</field>' +
		  '<field type="boxed" name="eval-signsTime_3" normalized-score="1" resemblance-score="1">0909</field>' +
		  '<field type="boxed" name="eval-signsBP1_1" normalized-score="1" resemblance-score="1">111</field>' +
		  '<field type="boxed" name="eval-signsBP2_1" normalized-score="1" resemblance-score="1">11</field>' +
		  '<field type="boxed" name="eval-signsTemp_1" normalized-score="1" resemblance-score="1">100</field>' +
		  '<field type="boxed" name="eval-signsHeartRate_1" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsO2Sat_1" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsLbs_1" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsoz_1" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signskgs_1" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsBP1_2" normalized-score="0.957" resemblance-score="0.795">190</field>' +
		  '<field type="boxed" name="eval-signsBP2_2" normalized-score="0.959" resemblance-score="0.701">17</field>' +
		  '<field type="boxed" name="eval-signsTemp_2" normalized-score="0.957" resemblance-score="0.797">142</field>' +
		  '<field type="boxed" name="eval-signsHeartRate_2" normalized-score="0.941" resemblance-score="0.733">210</field>' +
		  '<field type="boxed" name="eval-signsO2Sat_2" normalized-score="0.991" resemblance-score="0.94">77</field>' +
		  '<field type="boxed" name="eval-signsLbs_2" normalized-score="0.87" resemblance-score="0.63">999</field>' +
		  '<field type="boxed" name="eval-signsoz_2" normalized-score="0.99" resemblance-score="0.759">15</field>' +
		  '<field type="boxed" name="eval-signskgs_2" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signskg_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsoz_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signslbs_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsO2Sat_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsHeartRate_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsTemp_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsBP2_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsBP1_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="boxed" name="eval-signsDate_1" normalized-score="1" resemblance-score="1">03222015</field>' +
		  '<field type="boxed" name="eval-signsDate_2" normalized-score="0.741" resemblance-score="0.727">03232015</field>' +
		  '<field type="boxed" name="eval-signsDate_3" normalized-score="1" resemblance-score="1">03242015</field>' +
		  '<field type="boxed" name="eval-signstempPoints_1" normalized-score="1" resemblance-score="1">a</field>' +
		  '<field type="boxed" name="eval-signstempPoints_2" normalized-score="1" resemblance-score="0.947">7</field>' +
		  '<field type="boxed" name="eval-signstempPoints_3" normalized-score="1" resemblance-score="1"></field>' +
		  '<field type="textfield" name="PBSName" normalized-score="1" resemblance-score="1"></field>' +
  		  '<field type="textfield" name="Guardian" normalized-score="1" resemblance-score="1"></field>' +
  		  '<field type="textfield" name="ADField" normalized-score="1" resemblance-score="1"></field>' +
  		  '<field type="textfield" name="PBSNumber" normalized-score="1" resemblance-score="1"></field>' +
  		  '<field type="textfield" name="GuardianPhone" normalized-score="1" resemblance-score="1"></field>' +
  		  '<field type="textfield" name="CodeStatus" normalized-score="1" resemblance-score="1"></field>' +
  		   '<field type="textfield" name="DOB" normalized-score="1" resemblance-score="1"></field>' +
			'</form>';

		System.debug(xml);
	    CNANoteInput handler = new CNANoteInput();
	    handler.handle(eval.Id, 'xml', Blob.valueOf(xml), new RestRequest(), new RestResponse());
    	
    	// handler writes entries to eval_value__c - select those and assert we have correct values
    	Eval_value__c[] evList = [select eval_section_id__c, eval__c, what_id__c, what_id_object__c, boolean__c, text_under_250__c, text_over_250__c, number_no_decimal__c, date_time__c
    					from eval_value__c
    					where eval_section_type__c = 'CNA Workbook'
    					and	what_id__c = :eval.ID
    					and what_id_object__c = 'Evaluation__c'
    					order by eval_section_id__c];
    
    	system.debug( evList );
    	
    	// assert the values are correct 
    	System.AssertEquals( evList.size(), 6);
    	
    						
    }
    
   
}