src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Head_to_Toe_Signed_At__c</fullName>
        <label>Head to Toe Signed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Head_to_Toe_Status__c</fullName>
        <label>Head to Toe Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Being_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field that indicates whether or not a signature is in progress.  Allows the EvaluationHandler class, kicked off by after update trigger action, to know that a signature is in progress.  Then, Is_Signed__c can be set to true, and Is_Being_Signed__c can be set back to false at end of After Update code.</description>
        <label>Is Being Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field that indicates whether or not the evaluation is signed.</description>
        <label>Is Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_End_Time__c</fullName>
        <label>Shift End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Start_Time__c</fullName>
        <label>Shift Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Signed_At__c</fullName>
        <label>Signed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <recordTypes>
        <fullName>CMShiftAssessment</fullName>
        <active>true</active>
        <description>This record type is used for Shift Assessments for Care Meridian.</description>
        <label>CMShiftAssessment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EndOfShiftEsign.cls
public with sharing class EndOfShiftEsign implements AuthenticatedAction {
	public PageReference handle(Id recordId, Id userId) {
		String recId = String.valueOf(recordId);
		Evaluation__c assessment = [
			SELECT Id, OwnerId, Status__c, Head_to_toe_Status__c, Is_Being_Signed__c, Is_Signed__c,
			       Shift_Start_time__c, Shift_End_time__c, Recordtype.Name, ServiceAssignment__c
			  FROM Evaluation__c
			 WHERE id=: recordId
		];
		if (assessment.Recordtype.name == 'CMShiftAssessment') {
			if (assessment.Head_to_toe_Status__c == 'Draft') {
				assessment.Head_to_Toe_Status__c = 'Final';
				assessment.Head_to_Toe_Signed_At__c = System.Now();
			}
			assessment.Status__c = 'End of Shift';
			assessment.Signed_At__c = System.now();
			assessment.Signed_By__c = UserInfo.getUserId();
		} else if (assessment.RecordType.Name == 'CNA Workbook') {
			assessment.Signed_At__c = system.Now();
			assessment.Status__c = 'End of Shift';
			assessment.Signed_By__c = UserInfo.getUserId();
		}
		update assessment;

		return null;
	}
}