src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CareMeridianEvaluationAttachFileTest.cls
@isTest
public with sharing class CareMeridianEvaluationAttachFileTest {
    static testmethod void simpleTests() {
        PageReference pageRef = Page.CareMeridianEsignPostBack;
        Test.setCurrentPage(pageRef);
        Referral__c referral = new Referral__c();
        insert referral;
        Evaluation__c evaluation = new Evaluation__c(Referral__c=referral.Id);
        insert evaluation;
        CareMeridianEvaluationAttachFile controller = new CareMeridianEvaluationAttachFile();
        ApexPages.currentPage().getParameters().put('id', evaluation.Id);
        ApexPages.currentPage().getParameters().put('img', 'SGVsbG8gV29ybGQ=');
        controller.upload();
        System.assertNotEquals(0, [SELECT ID FROM Attachment WHERE ParentId=:referral.Id].size());
    }
}