src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>Agencies_notified__c</fullName>
        <label>What external parties were notified?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Calculated_Level_Explanation__c</fullName>
        <label>Calculated Level Explanation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Calculated_Level__c</fullName>
        <label>Calculated Level</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Level_Reason__c</fullName>
        <label>Final Level Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Final_Level__c</fullName>
        <label>Final Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Incident_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Reviewer</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_Incidents (Incident Reviewer)</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notified_Staff__c</fullName>
        <label>Who else on staff was notified?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Associated to Event</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Im_Incidents</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_Happened__c</fullName>
        <label>What Happened?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>When_did_it_happen__c</fullName>
        <label>When did it happen?</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>When_was_the_Supervisor_notified__c</fullName>
        <label>When was the Supervisor notified?</label>
        <type>DateTime</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_InvolvedParty__c.object
<CustomObject>
    <description>The individuals involved with the event/incident.</description>
    <fields>
        <fullName>Im_Incident__c</fullName>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served Involved</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Person Being Served</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Host Home Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Family Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Im_InvolvedParty</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_InvolvedParties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncidentManagementTest.cls
@isTest
public with sharing class IncidentManagementTest {
	@testSetup
	public static void setUpData() {
		TestUtils.userBuilder userBuilder = new TestUtils.UserBuilder();
		TestUtils.TmnUserBuilder tmnUserBuilder = new TestUtils.TmnUserBuilder();
		User qualifierUser = userBuilder
			.setFirstName('Qualifier')
			.setLastName('Person')
			.setUserAlias('qualif')
			.setEmail('qualifier@tmn.com')
			.getResult();
		User reviewerUser = userBuilder
			.setFirstName('Reviewer')
			.setLastName('Person')
			.setUserAlias('reviewer')
			.setEmail('reviewer@tmn.com')
			.getResult();

		insert qualifierUser;
		insert reviewerUser;

		PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'iServe_Incident_Reviewer'];
		insert new PermissionSetAssignment[] {
			new PermissionSetAssignment(
				AssigneeId = qualifierUser.Id,
				PermissionSetId = ps.Id
			),
			new PermissionSetAssignment(
				AssigneeId = reviewerUser.Id,
				PermissionSetId = ps.Id
			)
		};

		User currentUser = [ SELECT Id FROM User WHERE Id = :UserInfo.getUserId() ];
		// This is necessary since we can't mix setup and non-setup DML operations
		// in the same context. The User and PermissionSet creations above are
		// counted as setup objects, while the objects below are non-setup ones.
		System.runAs(qualifierUser) {
			TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();

			TMN_User__c qualifierTmnUser = tmnUserBuilder
				.setUserId(qualifierUser.Id)
				.setApprovalLevel(3)
				.setAlias(testData.alias)
				.setManagerEmail('reviewer@tmn.com')
				.getResult();
			TMN_User__c reviewerTmnUser = tmnUserBuilder
				.setUserId(reviewerUser.Id)
				.setApprovalLevel(10)
				.getResult();

			insert qualifierTmnUser;
			insert reviewerTmnUser;

			Eval_Type__c[] evalTypes = new Eval_Type__c[]{
				new Eval_Type__c(Name='Involved Party', Category__c='Incident Management'),
				new Eval_Type__c(Name='Involved Party Qualifying', Category__c='Incident Management')
			};
			insert evalTypes;
			TestUtils.EvalBuilder evalBuilder = new TestUtils.EvalBuilder();
			evalBuilder.setEvalTypeId(evalTypes[0].Id);
			Eval__c[] evals = new Eval__c[]{
				evalBuilder
					.setCategory('Allegations of Abuse/Neglect')
					.setSubCategory('Allegation of Neglect')
					.setHtmlId('IsValid')
					.setFieldType('Hidden')
					.setFieldSubType('Boolean')
					.setInvolvedPartyType('PBS')
					.getResult(),
				evalBuilder.setSubCategory('Allegation of Abuse - Physical').getResult(),
				evalBuilder.setSubCategory('Allegation of Abuse - Sexual').getResult()
			};
			insert evals;
		}
	}

	public static testmethod void testCreatingQualifier() {
		Service_Location__c serviceLocation = [SELECT Id FROM Service_Location__c];
		User qualifier = [SELECT Id FROM User WHERE Email='qualifier@tmn.com'];

		System.runAs(qualifier) {
			Im_Incident__c incident = new Im_Incident__c();
			IncidentManagement controller = new IncidentManagement(
					new ApexPages.standardController(incident)
			);
			System.assertEquals(false, controller.getIsLocked());
			System.assertEquals(false, controller.isViewMode);
			System.assertEquals(true, controller.isEditMode);
			System.assertEquals(true, controller.isQualifyingStage);
			System.assertEquals(false, controller.isIncidentStage);
			System.assertEquals('Create Qualifier', controller.name);
			System.assertEquals(serviceLocation.Id, controller.incident.Service_Location__c);
			List<MyRemoteMethods.SelOption> staffOptions = IncidentManagement.getStaffForProgram(
				String.format(
					'\'{\' "programLocation": "{0}", "q": "" \'}\'',
					new String[] { serviceLocation.Id }
				)
			);
			System.assertEquals(2, staffOptions.size(), 'Staff Notified should contain the qualifier and reviewer');
			controller.incident.Notified_Staff__c = staffOptions[0].Id + ',' + staffOptions[1].Id;
			System.assert(controller.notifiedStaffNames.indexOf('Qualifier') != -1);
			System.assert(controller.notifiedStaffNames.indexOf('Reviewer') != -1);
			System.assertEquals(2, controller.serviceLocations.size(), 'Service Locations should contain a None option and the actual Location');
			controller.incident.Agencies_Notified__c = 'Funding Source';
			System.assertNotEquals('', controller.agenciesNotifiedOptions);

			controller.incident.Service_Location__c = null;
			controller.save();  // validation errors here
			System.assertNotEquals(0, ApexPages.getMessages().size());

			controller.incident.When_Did_It_Happen__c = DateTime.now().addDays(2);
			controller.incident.When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(1);
			controller.save();  // validation errors here
			System.assertNotEquals(0, ApexPages.getMessages().size());

			controller.incident.Service_Location__c = serviceLocation.Id;
			controller.incident.What_Happened__c = 'Random Stuff';
			controller.incident.When_Did_It_Happen__c = DateTime.now().addDays(-2);
			controller.incident.When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(-1);
			controller.save();  // should be good to go here
			System.assertNotEquals(null, controller.incident.Id);
			System.assertEquals('Event-Qualifying', controller.incident.Status__c);
		}
	}
	public static testMethod void testCloseEvent() {
		Service_Location__c serviceLocation = [SELECT Id FROM Service_Location__c];
		User qualifier = [SELECT Id FROM User WHERE Email='qualifier@tmn.com'];

		System.runAs(qualifier) {
			Im_Incident__c incident = new Im_Incident__c(
				Status__c = 'Event-Qualifying',
				Service_Location__c = serviceLocation.Id,
				What_Happened__c = 'Random Stuff',
				When_Did_It_Happen__c = DateTime.now().addDays(-2),
				When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(-1)
			);
			insert incident;
			IncidentManagement controller = new IncidentManagement(
				new ApexPages.standardController(incident)
			);
			controller.close();
			System.assertEquals('Event-Closed', controller.incident.Status__c);
			System.assertEquals(true, controller.getIsLocked());
		}
	}

	public static testMethod void testQualifyingAsIncident() {
		Service_Location__c serviceLocation = [SELECT Id FROM Service_Location__c];
		User qualifier = [SELECT Id FROM User WHERE Email='qualifier@tmn.com'];

		System.runAs(qualifier) {
			Im_Incident__c incident = new Im_Incident__c(
				Name = 'E-0000000000Q',
				Status__c = 'Event-Qualifying',
				Service_Location__c = serviceLocation.Id,
				What_Happened__c = 'Random Stuff',
				When_Did_It_Happen__c = DateTime.now().addDays(-2),
				When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(-1)
			);
			insert incident;
			IncidentManagement controller = new IncidentManagement(
				new ApexPages.standardController(incident)
			);
			System.assertEquals(incident.Name + ' - Qualifying', controller.name);

			List<MyRemoteMethods.SelOption> pbsOptions = IncidentManagement.getPBSForProgram(
				String.format(
					'\'{\' "programLocation": "{0}", "q": "" \'}\'',
					new String[] { serviceLocation.Id }
				)
			);
			System.assertEquals(1, pbsOptions.size());

			Map<String, object> validateResult = IncidentManagement.validateEvent(controller.incident.Id);
			System.assertEquals(false, (Boolean) validateResult.get('goodToSubmit'), 'The event validation should fail since there is no event type added yet');
			Im_InvolvedParty__c involvedPbs = new Im_InvolvedParty__c(
					Im_Incident__c = controller.incident.Id,
					Person_Being_Served_Involved__c = [SELECT Id FROM Service_Assignment__c].Id,
					Nickname__c = 'Test PBS',
					Type__c = 'Person Being Served'
			);
			insert involvedPbs;
			String eventTypes = IncidentManagement.getInvolvedPartyEventTypes('{ "involvedParty": "' + involvedPbs.Id + '", "involvedPartyType": "Person Being Served" }');
			System.assert(eventTypes.indexOf('Allegation of Neglect') != -1);

			validateResult = IncidentManagement.validateEvent(controller.incident.Id);
			System.assertEquals(false, (Boolean) validateResult.get('goodToSubmit'), 'The event validation should fail since there is no event added yet');

			TestUtils.EvalValueBuilder valueBuilder = new TestUtils.EvalValueBuilder();
			valueBuilder = valueBuilder
				.setEvalType('Involved Party')
				.setWhatIdObject('Im_InvolvedParty__c')
				.setWhatId(involvedPbs.Id);
			Eval_Value__c[] values = new Eval_Value__c[]{
				valueBuilder.setCategory('Allegations of Abuse/Neglect').setSubCategory('Allegation of Neglect').setHtmlId('IsValid').setValue(true).getResult()
			};
			insert values;
			validateResult = IncidentManagement.validateEvent(controller.incident.Id);
			System.assertEquals(true, (Boolean) validateResult.get('goodToSubmit'), 'The event validation should pass now');

			List<MyRemoteMethods.Im_PartyData> involvedParties = IncidentManagement.getInvolvedParties(controller.incident.Id);
			System.assertEquals(1, involvedParties.size());

			List<String> partyDetails = IncidentManagement.getEventDetails(involvedPbs.Id, false);
			System.assertNotEquals(0, partyDetails.size());

			controller.qualifyEvent();
			controller.reloadCalculatedLevel();
			System.assertEquals('3', controller.incident.Calculated_Level__c);
			System.assertNotEquals('', controller.incident.Calculated_Level_Explanation__c);
			System.assertEquals('Incident-Draft', controller.incident.Status__c);

			// Update the event here
			Eval__c eval = [
				SELECT Id
				  FROM Eval__c
				 WHERE Category__c = 'Allegations of Abuse/Neglect'
				   AND Sub_Category__c = 'Allegation of Neglect'
				   AND HtmlId__c = 'IsValid'
				];
			IncidentManagement.saveFields(involvedPbs.Id, '[{"name": "'+ eval.Id +'_esi", "value": false}]');
			Eval_Value__c value = [
				SELECT Id, Boolean__c
				  FROM Eval_Value__c
				 WHERE Eval__c = :eval.Id
				   AND What_Id__c = :involvedPbs.Id
			];
			System.assertEquals(true, value.Boolean__c);
		}
	}

	public static testMethod void testReadyForReviewIncident() {
		Service_Location__c serviceLocation = [SELECT Id FROM Service_Location__c];
		User qualifier = [SELECT Id FROM User WHERE Email='qualifier@tmn.com'];
		Tmn_User__c reviewer = [SELECT Id FROM Tmn_User__c WHERE Email__c='reviewer@tmn.com'];

		System.runAs(qualifier) {
			Im_Incident__c incident = new Im_Incident__c(
				Name = 'I-0000000001',
				Status__c = 'Incident-Draft',
				Service_Location__c = serviceLocation.Id,
				What_Happened__c = 'Random Stuff',
				When_Did_It_Happen__c = DateTime.now().addDays(-2),
				When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(-1)
			);
			insert incident;
			IncidentManagement controller = new IncidentManagement(
				new ApexPages.standardController(incident)
			);
			List<MyRemoteMethods.SelOption> reviewers = IncidentManagement.getIncidentReviewers(
				String.format(
					'\'{\' "programLocation": "{0}", "q": "" \'}\'',
					new String[] { serviceLocation.Id }
				)
			);
			System.assertEquals(1, reviewers.size());
			System.assertEquals(reviewer.Id, reviewers[0].Id);
			controller.readyForReview();  // should fail validation since final level and reviewer is not filled in yet

			ApexPages.Message[] messages = ApexPages.getMessages();
			System.assertEquals(2, messages.size());

			controller.incident.Incident_Reviewer__c = reviewer.Id;
			controller.incident.Final_Level__c = '4';
			controller.readyForReview();
			System.assertNotEquals(0, ApexPages.getMessages().size());  // Level Reason required

			controller.incident.Final_Level_Reason__c = 'Reason';
			controller.readyForReview();
			System.assertEquals('Incident-Ready for Review', controller.incident.Status__c);
		}
	}

	public static testMethod void testFinalizeIncident() {
		Service_Location__c serviceLocation = [SELECT Id FROM Service_Location__c];
		User qualifier = [SELECT Id FROM User WHERE Email='qualifier@tmn.com'];
		User reviewer = [SELECT Id FROM User WHERE Email='reviewer@tmn.com'];

		System.runAs(qualifier) {
			Im_Incident__c incident = new Im_Incident__c(
				Name = 'I-0000000001',
				Status__c = 'Incident-Ready for Review',
				Service_Location__c = serviceLocation.Id,
				What_Happened__c = 'Random Stuff',
				When_Did_It_Happen__c = DateTime.now().addDays(-2),
				When_Was_the_Supervisor_Notified__c = DateTime.now().addDays(-1)
			);
			insert incident;
		}
		System.runAs(reviewer) {
			Im_Incident__c incident = [ SELECT Id FROM Im_Incident__c ];
			IncidentManagement controller = new IncidentManagement();
			System.assertEquals(false, controller.isQualifyingStage);
			System.assertEquals(false, controller.isIncidentStage);
			controller.handle(incident.Id, UserInfo.getUserId());
			incident = [ SELECT Id, Status__c FROM Im_Incident__c WHERE Id=:incident.Id ];
			System.assertEquals('Incident-Finalized', incident.Status__c);

			Test.setCurrentPage(Page.IncidentManagement);
			System.currentPageReference().getParameters().put('mode', 'view');
			controller = new IncidentManagement(
				new ApexPages.standardController(incident)
			);
			controller.showAddLogEntry();
			controller.currEntry.evalResp.Narrative_Note__c = 'n'.repeat(200);
			controller.saveLogEntry();

			System.assertEquals(1, controller.getAddendumEntries().size());
			System.assertEquals('n'.repeat(99) + '...', controller.getAddendumEntries()[0].briefDesc);

			controller.showEditLogEntry();
			controller.saveLogEntry();
			controller.currEntryId = controller.currEntry.evalResp.Id;
			controller.showEditLogEntry();
			controller.disregardLogEntry();

			System.assertEquals(2, controller.getAddendumEntries().size());
		}
	}
}