src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Being_Referred__c.object
<CustomObject>
    <description>Person Being Referred holds demographic information about a person for the referral process</description>
    <label>Person Being Referred</label>
    <nameField>
        <displayFormat>PBR-{0}</displayFormat>
        <label>PBR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Being Referred</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <fields>
        <fullName>Person_Being_Referred__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Referred</label>
        <referenceTo>Person_Being_Referred__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Related_Party__c.object
<CustomObject>
    <description>REFERRALS - Parties having a relationship with the Person Being Referred</description>
    <fields>
        <fullName>Person_Being_Referred__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Referred</label>
        <referenceTo>Person_Being_Referred__c</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referring Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Payee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NeuroEvaluationViewControllerTest.cls
@isTest
public with sharing class NeuroEvaluationViewControllerTest {
    static testmethod void simpleTests() {
        Person_Being_Referred__c pbr = new Person_Being_Referred__c();
        insert pbr;
        Referral__c referral = new Referral__c(Person_Being_Referred__c=pbr.Id);
        insert referral;
        Evaluation__c evaluation = new Evaluation__c(Referral__c=referral.Id);
        insert evaluation;
        Related_party__c rp = new Related_Party__c(
            Name='Test Party',
            Type__c='Guardian',
            Person_Being_Referred__c=pbr.Id
        );
        insert rp;
        NeuroEvaluationViewController controller = new NeuroEvaluationViewController(new ApexPages.StandardController(evaluation));
        System.assertNotEquals(0, controller.mobilitySliderOptions.size());
        System.assertNotEquals(0, controller.selfCareSliderOptions.size());
        System.assertNotEquals(0, controller.communicationSliderOptions.size());
        System.assertEquals(null, controller.bodyMapUrl);
        System.assertEquals(0, controller.annotations.size());
        System.assertNotEquals(null, controller.relatedParties);
        controller.showAddRelatedParty();
        System.assertEquals(null, controller.currentRelatedParty.Id);
        controller.currentRelatedPartyId = rp.Id;
        controller.showEditRelatedParty();
        System.assertEquals(rp.Id, controller.currentRelatedParty.Id);
        controller.currentRelatedParty.Name = 'New Name';
        controller.saveRelatedParty();
    }
}