src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Is_Being_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field that indicates whether or not a signature is in progress.  Allows the EvaluationHandler class, kicked off by after update trigger action, to know that a signature is in progress.  Then, Is_Signed__c can be set to true, and Is_Being_Signed__c can be set back to false at end of After Update code.</description>
        <label>Is Being Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CareMeridianEvaluationAttachFile.cls
public with sharing class CareMeridianEvaluationAttachFile {
    public String myId {get; set;}
    public String strImg {get; set;}
    public Blob img { get; set;}
    public String attachID { get; set;}

    public Attachment attachment { set;
        get {
           if (attachment == null) {
               attachment = new Attachment();
           }
           return attachment;
        }
    }
    String LongDate = ' ';

    // Init LongDate with the current Datetime in long date format
    public String getLongDate() {
        Datetime cDT = System.now();
        LongDate = cDT.format('MM-dd-yyyy hh:mm:ss a z');
        return LongDate;
    }

    public PageReference upload() {
        System.debug('Inside upload');
        myId = ApexPages.currentPage().getParameters().get('id'); //  this will be the id of the evaluation passed up from ajax post
        strImg = ApexPages.currentPage().getParameters().get('img'); // the canvas img output, base-64 encoded string

        // decode the img string back to binary data
        img = EncodingUtil.base64Decode(strImg);

        attachment.OwnerId = Userinfo.getUserId();

        // get the progress note for this id
        Evaluation__c evaluation = [
            SELECT ID, Name, Referral__c FROM Evaluation__c WHERE Id=:myId LIMIT 1
        ];

        // create name for attachment based on note name + date posted
        attachment.Name = evaluation.Name  + ' ' + getLongDate() + ' Esigned.jpg';
        attachment.ParentId = evaluation.Referral__c;

        // attachment body is the actual canvas jpg image
        attachment.Body = img;

        try {
            System.debug('Attachment to insert: ' + attachment);
            insert attachment;
            evaluation.Is_Being_Signed__c = true;
            update evaluation;
            attachID = attachment.Id;
        } catch (DMLException e) {
            System.debug('Error: ' + e);
            return null;
        } finally {
            attachment = new Attachment();
        }
        return null;
    }
}