src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>85</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>htmlid__c</fullName>
        <label>htmlid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Boolean__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Text_Over_250__c</fullName>
        <label>Text Over 250</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text_Under_250__c</fullName>
        <label>Text Under 250</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID_Object__c</fullName>
        <label>What ID Object</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>What_ID__c</fullName>
        <label>What ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Batch_CNA_Intake_Merge.cls
global without sharing class Batch_CNA_Intake_Merge implements Database.Batchable<sObject>, Database.Stateful {
	global final Id observedDateTimeId;
	global final Id mLConsumedId;
	global final Id isValidId;
	global final Id errorMsgId;

	global Map<String, Boolean> sectionErrorFound;

	global Batch_CNA_Intake_Merge() {
		this.sectionErrorFound = new Map<String, Boolean>();

		List<Eval__c> evalsToUpdate = new List<Eval__c>();

		Boolean mlConsumedFound = false;
		for (Eval__c mealRecord: [
			SELECT Id, Sub_Category__c, Visible__c, HtmlId__c
			  FROM Eval__c
			 WHERE Eval_Type__r.Name = 'CNA Workbook'
			   AND Category__c = 'Intake'
			   AND Sub_Category__c = 'Meals'
		]) {
			if (mealRecord.HtmlId__c == 'ObservedDateTime20') {
				this.observedDateTimeId = mealRecord.Id;
			} else if (mealRecord.HtmlId__c == 'intakemLConsumed') {
				if (!mlConsumedFound) {  // There are 2 in the systems that satisfy this right now
					this.mLConsumedId = mealRecord.Id;
					mealRecord.Visible__c = true;
					mlConsumedFound = true;
				}
			} else if (mealRecord.HtmlId__c == 'IsValid') {
				this.isValidId = mealRecord.Id;
			} else if (mealRecord.HtmlId__c == 'ErrorMsg') {
				this.errorMsgId = mealRecord.Id;
			}
			mealRecord.Sub_Category__c = 'All';
			evalsToUpdate.add(mealRecord);
		}
		System.assertNotEquals(null, observedDateTimeId);
		System.assertNotEquals(null, mLConsumedId);
		System.assertNotEquals(null, isValidId);
		System.assertNotEquals(null, errorMsgId);

		update evalsToUpdate;
	}

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(
			'SELECT Id, Eval__r.HtmlId__c, Eval_Section_Id__c, Text_Under_250__c,' +
			'       Text_Over_250__c, What_ID__c, What_ID_Object__c, Eval__r.Visible__c' +
			'  FROM Eval_Value__c' +
			' WHERE Eval__r.Eval_Type__r.Name = \'CNA Workbook\'' +
			'   AND Eval__r.Category__c = \'Intake\'' +
			'   AND Eval__r.Sub_Category__c = \'Liquid\''
		);
	}

	global void execute(Database.BatchableContext bc, List<sObject> scope) {
		//  We don't need these this in a *global* context, so we initialize them here to avoid serialization
		List<Eval_Value__c> valuesToDelete = new List<Eval_Value__c>();

		List<Eval_Value__c> values = (List<Eval_Value__c>) scope;
		for (Eval_Value__c value: values) {
			String compositeKey = value.Eval_Section_Id__c + '+' + value.What_Id__c;
			if (!sectionErrorFound.keySet().contains(compositeKey)) {
				sectionErrorFound.put(compositeKey, false);
			}
			if (value.Eval__r.Visible__c) {
				value.Eval_Section_Type__c = 'Activity Log';
				if (value.Eval__r.HtmlId__c == 'mLConsumed') {
					value.Eval__c = this.mLConsumedId;
				} else if (value.Eval__r.HtmlId__c == 'liquidDateTime') {
					value.Eval__c = this.observedDateTimeId;
				} else if (value.Eval__r.HtmlId__c == 'IsValid') {
					value.Boolean__c = false;
					value.Eval__c = this.isValidId;
				} else if (value.Eval__r.HtmlId__c == 'ErrorMsg') {
					value.Text_Over_250__c = '<li>Tube Fed field is mandatory.</li>' + value.Text_Over_250__c;
					value.Eval__c = this.errorMsgId;
					sectionErrorFound.put(compositeKey, true);
				}
			} else {
				valuesToDelete.add(value);
			}
		}
		update values;
		delete valuesToDelete;
	}

	global void finish(Database.BatchableContext bc) {
		List<Eval_Value__c> valuesToInsert = new List<Eval_Value__c>();
		for (String compositeKey: sectionErrorFound.keySet()) {
			if (!sectionErrorFound.get(compositeKey)) {
				valuesToInsert.add(new Eval_Value__c(
					Eval__c = errorMsgId,
					Text_Over_250__c = '<li>Tube Fed field is mandatory.</li>',
					Eval_Section_Id__c = compositeKey.split('\\+', 0)[0],
					What_Id__c = compositeKey.split('\\+', 0)[1],
					What_Id_Object__c = 'Evaluation__c'
				));
			}
		}
		insert valuesToInsert;
		delete [
			SELECT Id, Field_Name__c, HtmlId__c, Visible__c
			  FROM Eval__c
			 WHERE Eval_Type__r.Name = 'CNA Workbook'
			   AND Category__c = 'Intake'
			   AND Sub_Category__c = 'Liquid'
		];
	}
}