src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Is_Being_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A field that indicates whether or not a signature is in progress.  Allows the EvaluationHandler class, kicked off by after update trigger action, to know that a signature is in progress.  Then, Is_Signed__c can be set to true, and Is_Being_Signed__c can be set back to false at end of After Update code.</description>
        <label>Is Being Signed</label>
        <type>Checkbox</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Evaluation_Response__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Evaluation Responses</relationshipLabel>
        <relationshipName>Evaluation_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evaluation Response</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Evaluation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NursingEvaluationEsign.cls
public with sharing class NursingEvaluationEsign implements AuthenticatedAction{
	public PageReference handle(Id recordId, Id userId) {
        Evaluation_Response__c currentResponse = new Evaluation_Response__c();
        currentResponse.RecordTypeId = Utility.getEvaluationResponseRecordType('E-Signature');
        currentResponse.Evaluation__c = recordId;
        insert currentResponse;
        Evaluation__c assessment = new Evaluation__c(
            Id = recordId,
            Is_Being_Signed__c = true
        );
        update assessment;
        return null;
    }

}