src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Sub_Category__c</fullName>
        <description>Have another category level for grouped fields.</description>
        <label>Sub Sub Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EvalRepeaters.cls
public with sharing class EvalRepeaters {
	public ID evaluationID { get; set;}
	public string evalname{get; set;}
	public string operatingGroup{get; set;}
	
	public list<EvalRepeaterWrapper> evals;
	public list<EvalRepeaterWrapper> getEvals(){
		evals = new list<EvalRepeaterWrapper>();
		
		List<AggregateResult> evalTypes = [select	category__c, sub_category__c, sub_sub_category__c
											 from 	eval__c
											where	eval_type__r.name = :evalname 
											  and 	eval_type__r.Category__c = :operatingGroup
										group  by 	category__c, sub_category__c, sub_sub_category__c];
										
		for (AggregateResult ag : evalTypes){
			evals.add(new EvalRepeaterWrapper(String.valueOf(ag.get('category__c')), String.valueOf(ag.get('sub_category__c')), 
												String.valueOf(ag.get('sub_sub_category__c')) ));
		}
		return evals;
	}
	
	public EvalRepeaters(){
		
	}






	public class EvalRepeaterWrapper{
		public string cat {get; set;}
		public string subcat{get; set;}
		public string subsubcat{get; set;}
		
		public EvalRepeaterWrapper(String cat, string subcat, string subsubcat){
			this.cat = cat;
			this.subcat = subcat;
			this.subsubcat = subsubcat;
		}
	}

}