src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Dialysis_Onset__c</fullName>
        <label>Dialysis Onset</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation_Date__c</fullName>
        <label>Evaluation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_End_Time__c</fullName>
        <label>Shift End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Start_Time__c</fullName>
        <label>Shift Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <recordTypes>
        <fullName>CMShiftAssessment</fullName>
        <active>true</active>
        <description>This record type is used for Shift Assessments for Care Meridian.</description>
        <label>CMShiftAssessment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MissingShiftDocReportTests.cls
@isTest
public with sharing class MissingShiftDocReportTests {
	public static testmethod void simpleTests() {
		MissingShiftDocReport controller = new MissingShiftDocReport();
		controller.runReport();  // this will generate errors because start date is later than end date
		controller.dummyEvaluation.Evaluation_Date__c = Date.Today().addDays(3);
		controller.dummyEvaluation.Dialysis_Onset__c = Date.Today().addDays(1);
		controller.runReport();

		// Generate test data here
		TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
		Id nsdRecordTypeId = Utility.getEvaluationRecordType('CMShiftAssessment');
		Id cnaRecordTypeId = Utility.getEvaluationRecordType('CNA Workbook');
		insert new Evaluation__c[] {
			new Evaluation__c(
				RecordTypeId = nsdRecordTypeId,
				Status__c = 'Draft',
				Shift_Start_Time__c = Date.Today().addDays(-4),
				Shift_End_Time__c = Date.Today().addDays(-2),
				ServiceAssignment__c = myData.theSA.Id
			),
			new Evaluation__c(  // this won't be included because of Status
				RecordTypeId = cnaRecordTypeId,
				Status__c = 'Final',
				Shift_Start_Time__c = Date.Today().addDays(-3),
				Shift_End_Time__c = Date.Today().addDays(-3),
				ServiceAssignment__c = myData.theSA.Id
			)
		};

		controller = new MissingShiftDocReport();
		controller.leftSelectedPrograms.add((String) controller.leftPrograms[0].getValue());
		controller.addPrograms();
		controller.rightSelectedPrograms.add((String) controller.rightPrograms[0].getValue());
		controller.removePrograms();
		controller.leftSelectedPrograms.add((String) controller.leftPrograms[0].getValue());
		controller.addPrograms();
		controller.dummyEvaluation.Evaluation_Date__c = Date.Today().addDays(-5);
		controller.dummyEvaluation.Dialysis_Onset__c = Date.Today();
		controller.selectedPbs = new Id[]{ myData.theSA.Id };
		controller.runReport(); // this will run correctly
	}
}