src/objects/Eval__c.object
<CustomObject>
    <description>List of fields that make up a particular Evaluation.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Users can name a set of fields.</description>
        <inlineHelpText>Name a group of fields</inlineHelpText>
        <label>Category</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eval_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval Type</label>
        <referenceTo>Eval_Type__c</referenceTo>
        <relationshipLabel>Evals</relationshipLabel>
        <relationshipName>Evals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Sub_Type__c</fullName>
        <description>We may have to boolean types, one for a checkbox and another for a radio button...</description>
        <label>Field Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropdown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropdown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiselect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>Users can sub categorize a group of fields.</description>
        <inlineHelpText>Users can sub categorize a group of fields.</inlineHelpText>
        <label>Sub Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Eval</label>
    <nameField>
        <label>Eval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Type__c.object
<CustomObject>
    <description>Type of Evaluation</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Eval Type</label>
    <nameField>
        <label>EvalType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Eval_Value__c.object
<CustomObject>
    <description>Values of the fields defined in the Eval Object</description>
    <fields>
        <fullName>Eval__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Eval</label>
        <referenceTo>Eval__c</referenceTo>
        <relationshipName>EvalValues</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Eval Value</label>
    <nameField>
        <label>EvalValues Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>ServiceAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift_End_Time__c</fullName>
        <label>Shift End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Start_Time__c</fullName>
        <label>Shift Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disregard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EvalRepeatersTest.cls
@isTest
private class EvalRepeatersTest {

    static testMethod void myUnitTest() {
    	
    	TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
        Evaluation__c evaluation = new Evaluation__c(Status__c = 'Draft', ServiceAssignment__c = myData.theSA.Id, shift_start_time__c = Datetime.newInstance(2015,04,27,0,0,0), shift_end_time__c = Datetime.newInstance(2015,05,2,0,0,0));
        insert evaluation;
        
        list<eval__c> evals = TMN_Generic_Core_TestData.getEvalTestRecords();

        list<GenerateEvalComponent.FormKeyVal> evalVals = new list<GenerateEvalComponent.FormKeyVal>();
        for (Eval__c e : [select id, Field_Type__c, Field_Sub_Type__c
                            from eval__c where eval_type__r.name = 'Head to Toe'
                                                   and category__c = 'TEST'
                                                   and sub_category__c = 'TEST_TEST'
                                                   and visible__c = true]){
            GenerateEvalComponent.FormKeyVal val = new GenerateEvalComponent.FormKeyVal();
            val.name= e.id;
            if (e.Field_Type__c == 'Hidden' && e.Field_Sub_Type__c == 'Boolean')
                    val.value = 'True';
            else if (e.Field_Type__c == 'Hidden' && e.Field_Sub_Type__c == 'String')
                    val.value = 'Error Message';
            else if(e.Field_Type__c == 'Boolean' && e.Field_Sub_Type__c == 'Checkbox') 
                    val.value = '1';
            else if(e.Field_Type__c == 'Boolean' && e.Field_Sub_Type__c == 'Dropdown') 
                    val.value = 'Yes';
            else if(e.Field_Type__c == 'Int' ) 
                    val.value = '12';
            else if(e.Field_Type__c == 'Date') 
                    val.value = '11/12/2013';
            else if(e.Field_Type__c == 'DateTime') 
                    val.value = '04/27/2015 18:00';
            else if(e.Field_Type__c == 'Multiselect') {
                    val.value = 'TEST';
                    GenerateEvalComponent.FormKeyVal val1 = new GenerateEvalComponent.FormKeyVal();
                    val1.name= e.id;
                    val1.value = 'TEST1';
                    evalVals.add(val1);
            }                    
            

            evalVals.add(val);
        }

        Eval_Type__c evlTyp = [Select Name, id from Eval_Type__c where Name = 'Head to Toe'];
        GenerateEvalComponent.saveFields(evaluation.id, UserInfo.getUserId() + '-' + DateTime.now().formatLong(), 
                                        'Shift', evlTyp.Name, 'TEST', 'TEST_TEST', JSON.serialize(evalVals));
        
        system.assert([select id from eval_value__c].size() > 0 );
        
        Test.setCurrentPage(Page.EvalDynamic);
        Apexpages.currentPage().getParameters().put('evalID', evaluation.id);
        Apexpages.currentPage().getParameters().put('evaltype', evlTyp.Name);
        Apexpages.currentPage().getParameters().put('opGrp', 'Care Meridian');
        
        EvalRepeaters evalRepeaters = new EvalRepeaters();
                                                
        system.assert(evalRepeaters.getEvals().size() > 0 );
        system.assert(!evalRepeaters.getAnyErrors());
        system.assert(evalRepeaters.getAnyEmpty());
    }
    
}