src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Call_Reference_Number__c</fullName>
        <label>Call Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <label>Group Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Network_Phone__c</fullName>
        <label>Network Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <label>Network</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Name__c</fullName>
        <label>Payer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Type__c</fullName>
        <label>Payer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance HMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance PPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance POS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance EPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Indemnity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medi-Cal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Medicare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Medicaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Medi-Cal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Pay - Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Pay - Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRICARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Comp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA - Fee for Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA - Pilot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payer_Verification_Date__c</fullName>
        <label>Payer Verification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Policy_Holder__c</fullName>
        <label>Policy Holder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Number__c</fullName>
        <label>Policy ID #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <picklist>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Med_Ind_Phys_Group_Phone__c</fullName>
        <label>Primary Med/Ind Phys Group Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Med_Ind_Phys_Group__c</fullName>
        <label>Primary Med/Ind Phys Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Representing__c</fullName>
        <label>Representing (Payer)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TPA_Phone__c</fullName>
        <label>TPA Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TPA__c</fullName>
        <label>TPA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Coverage__c</fullName>
        <label>Coverage Level</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Verified_By__c</fullName>
        <label>Verified By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified_With__c</fullName>
        <label>Verified With</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Party__c.object
<CustomObject>
    <description>REFERRALS - Parties having a relationship with the Person Being Referred</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_1_Type__c</fullName>
        <label>Phone 1 Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone_2_Type__c</fullName>
        <label>Phone 2 Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referring Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Payee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PersonSummaryTest.cls
@isTest
private class PersonSummaryTest {
	static testMethod void testException() {
        PageReference pageRef = Page.PersonSummary;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getParameters().put('id', '123123');
        PersonSummary ps = new PersonSummary();
        system.assert(true,Apexpages.hasMessages());
    }

    static testMethod void testExceptionForSAID() {
    	TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
        PageReference pageRef = Page.PersonSummary;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getParameters().put('id', myData.theSA.id);
        PersonSummary ps = new PersonSummary();
        system.assert(true,Apexpages.hasMessages());
    }
        
    static testMethod void myUnitTest() {
        TMN_Generic_Core_TestData myData = new TMN_Generic_Core_TestData();
        createAdditionalTestData(myData.contactID);
        PageReference pageRef = Page.PersonSummary;
        Test.setCurrentPage(pageRef);
        Apexpages.currentPage().getParameters().put('id', myData.contactID);
        PersonSummary ps = new PersonSummary();

        system.assert(true,ps.getContact().Id==myData.contactID);
        system.assert(true,ps.getServiceProviders().size()>0);
        system.assert(true,ps.getEmergencyContacts().size()>0);
        system.assert(true,ps.getSa().Funding_Sources__r[0].Type_of_Coverage__c=='Primary');
        system.assert(true,ps.getFsFlds().size()>0);
        system.assert(true,ps.getFundingSrcFldLbls().size()>0);
        system.assert(true,ps.getFundingSrcFldVals().size()>0);
    }

	private static void createAdditionalTestData(Id pbsID){
        list<Related_Party__c> rps = new list<Related_Party__c>();
        rps.add(new Related_Party__c(Person_Being_Served__c = pbsID, Name='RP1', Phone__c='1231231231', Address__c='313 Congress St', 
		                      Phone_2__c='3213213213', Type__c='Physician - Alternate', Comments__c='Physician - Alternate', 
		                      Phone_1_Type__c='Home', Phone_2_Type__c='Cell')); 
        rps.add(new Related_Party__c(Person_Being_Served__c = pbsID, Name='RP2', Phone__c='1231231231', Address__c='313 Congress St', 
                              Phone_2__c='3213213213', Type__c='Physician - Alternate', Comments__c='Physician - Alternate', 
                              Phone_1_Type__c='Home', Phone_2_Type__c='Cell')); 
        rps.add(new Related_Party__c(Person_Being_Served__c = pbsID, Name='RP3', Phone__c='1231231231', Address__c='313 Congress St', 
                              Phone_2__c='3213213213', Type__c='Spouse', Comments__c='Spouse', 
                              Phone_1_Type__c='Home', Phone_2_Type__c='Cell')); 
        rps.add(new Related_Party__c(Person_Being_Served__c = pbsID, Name='RP4', Phone__c='1231231231', Address__c='313 Congress St', 
                              Phone_2__c='3213213213', Type__c='Caregiver', Comments__c='Caregiver', 
                              Phone_1_Type__c='Home', Phone_2_Type__c='Cell'));
        insert rps;
        
        Service_Assignment__c sa = [select id from Service_Assignment__c where person_being_served__c = : pbsID limit 1]; 
        
        insert (new Funding_Source__c (Type_of_Coverage__c='Primary',Payer_Name__c='Primary',Policy_Type__c='Primary',TPA__c='Primary',
                    TPA_Phone__c='1231231231',Primary_Med_Ind_Phys_Group__c='Primary',Primary_Med_Ind_Phys_Group_Phone__c='Primary',
                    Network__c='Primary', Network_Phone__c='1231231231', Verified_By__c='Primary', Payer_Verification_Date__c= system.today(), 
                    Verified_With__c='Primary', Representing__c='Primary', Payer_Type__c='Primary', Call_Reference_Number__c='1231231231', 
                    Policy_Number__c='Primary', Group_Name__c='Primary', Group_Number__c='Primary', Policy_Holder__c='Primary', 
                    Relationship_To_Patient__c='Spouse',More_than_1_5_Yrs_of_Disability__c=true,Patient_Over_64_Years_of_Age__c=true, 
                    Comment__c='test', Service_Assignment__c=sa.id));
    }

}