src/objects/Funding_Source__c.object
<CustomObject>
    <description>REFERRAL - Funding Source</description>
    <fields>
        <fullName>Auth_Excess_Justification__c</fullName>
        <label>Auth Excess Justification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date_of_Cost_therapy_Auth__c</fullName>
        <label>Effective Date of Cost/therapy Auth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Source_Status__c</fullName>
        <label>Funding Source Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <label>Funding Source</label>
        <picklist>
            <picklistValues>
                <fullName>AHCCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autism Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Health Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonnie Frazier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridgeway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage Admin Fee (DD148)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAC Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CADI Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cenpatico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child  Protective Services (CPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clackamas County MHDDSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Care of Central Wisconsin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Living Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContinuUS Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curry County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dane County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debbie McDaniel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Developmental Disabilities (DDD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of Vocational Rehabilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert Regional Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Douglas County</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OT_Auth_Units__c</fullName>
        <label>OT Auth Units</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PT_Auth_units__c</fullName>
        <label>PT Auth units</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Funding Sources</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_Date_of_Cost_therapy_Auth__c</fullName>
        <label>Term Date of Cost/therapy Auth</label>
        <type>Date</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>FS-{0}</displayFormat>
        <label>Funding Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Sources</pluralLabel>
    <recordTypes>
        <fullName>NeuroRestorative</fullName>
        <active>true</active>
        <label>NeuroRestorative</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>The date the clinician administered the service.</description>
        <label>Date of Service</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <description>Please indicate the funding source.</description>
        <inlineHelpText>Please indicate the funding source.</inlineHelpText>
        <label>Funding Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Therapy_Discipline__c</fullName>
        <description>Used for neurorestorative il role and used for therapy record type</description>
        <label>Therapy Discipline</label>
        <picklist>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counseling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Woodshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Productive Activity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Contact__c</fullName>
        <inlineHelpText>Meeting type that took place.</inlineHelpText>
        <label>Type of Contact</label>
        <picklist>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face-To-Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telehealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Unit(s)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <recordTypes>
        <fullName>Therapy</fullName>
        <active>true</active>
        <description>Progress Note for NeuroRestorative IL</description>
        <label>Therapy</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/neuroreportofserviceController.cls
public with sharing class neuroreportofserviceController {
    public transient List<lineItem> lineitems {get;set;}
    public Funding_Source__c fSource {get; set;}
    /*public Date startDate {get;set;}
    public Date EndDate {get; set;}
    public User caseManager {get; set;}*/
    public string SOQL{get; set;}
    private Apexpages.standardController controller;
    set<string> statuses = new Set<string>{'Active', 'Active Final'};
   
    public neuroreportofserviceController(Apexpages.StandardController controller){
        lineItems = new List<lineItem>();
        this.controller = controller;
        this.fSource = (Funding_Source__c)controller.getRecord();
        
    }
    
    public pageReference doSearch(){
    	/*if(fSource.Effective_Date_of_Cost_therapy_Auth__c == null){
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter Effective Date'));
    		return null;
    	}
    	if(fSource.Term_Date_of_Cost_therapy_Auth__c == null){
    		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please enter Term Date'));
    		return null;
    	}*/
    	Datetime startdt = DateTime.newInstance( fSource.Effective_Date_of_Cost_therapy_Auth__c, Time.newInstance(0,0,0,0));
        Datetime enddt = DateTime.newInstance ( fSource.Term_Date_of_Cost_therapy_Auth__c, Time.newInstance(0, 0, 0, 0));  
    	SOQL = '';
    	SOQL = 'SELECT Id, OT_Auth_Units__c, PT_Auth_Units__c, Service_Assignment__c, Case_Manager__c, Auth_Excess_Justification__c  FROM Funding_Source__c WHERE Funding_Source_Status__c IN :statuses AND Recordtype.Name = \'NeuroRestorative\'';
    	SOQL = SOQL+ ' AND Effective_Date_of_Cost_therapy_Auth__c >= '+ startdt.format('yyyy-MM-dd');
    	SOQL = SOQL+ ' AND Term_Date_of_Cost_therapy_Auth__c <= '+ enddt.format('yyyy-MM-dd');
    	
    	if(string.isNotBLANK(fSource.Case_Manager__c)){
    		string cm = string.valueOf(fSource.Case_Manager__c);
    		SOQL = SOQL+ ' AND Case_Manager__c = \''+fSource.Case_Manager__c+'\'';
    	}
    	lineItems = new List<lineItem>();
    	List<Funding_Source__c> temp = Database.Query(SOQL);
    	Map<string, Funding_Source__c> fundingMap = new Map<string, Funding_Source__c>();
    	set<id> servAssigns = new set<id>();
    	
    	for(Funding_Source__c fs: temp){
    		if(fs.Auth_Excess_Justification__c != null){
    			fundingMap.put(fs.Id+'~'+fs.Service_Assignment__c, fs);
    			servAssigns.add(fs.Service_Assignment__c);	
    		}
    	}
    	
    	Map<id, Decimal> otMap = new Map<id, Decimal>();
    	Map<id, Decimal> ptMap = new Map<id, Decimal>();
    	
    	
    	for(AggregateResult ar: [SELECT Sum(Units__c) units,Service_Assignment__c sa, Therapy_Discipline__c td FROM Progress_Note__c WHERE (Date_of_Service__c >= :fSource.Effective_Date_of_Cost_therapy_Auth__c AND  Date_of_Service__c <= :fSource.Term_Date_of_Cost_therapy_Auth__c) AND Type_of_Contact__c != 'No-Show' AND Recordtype.Name = 'Therapy' AND Therapy_Discipline__c != null AND Service_Assignment__c IN: servAssigns GROUP BY Service_Assignment__c, Therapy_Discipline__c]){
    		if((String)ar.get('td') == 'OT'){
    			otMap.put((id)ar.get('sa'),(Decimal)ar.get('units'));
    		}
    		if((String)ar.get('td') == 'PT'){
    			ptMap.put((id)ar.get('sa'),(Decimal)ar.get('units'));
    		}
    	}
    	
    	
    	for(Funding_Source__c fs: fundingMap.values()){
    		if(servAssigns.contains(fs.Service_Assignment__c)){
    			//servPNRollup spn = servPNMap.get(fs.Service_Assignment__c);
    			lineitems.add(new lineitem(fs,ptMap.get(fs.Service_Assignment__c),otMap.get(fs.Service_Assignment__c)));
    		}else{
    			lineitems.add(new lineitem(fs,0,0));
    		}
    	}
       
        return null;
    }
    
    
    
    
    
    
    
    
  /* public class servPNRollup{
   	public id SAId {get;set;}
   	public Decimal OT{get; set;}
   	public Decimal PT {get; set;}
   	
   	public servPNRollup (AggregateResult ar){
   		this.SAId = (Id)ar.get('sa');
   		if((string)ar.get('td') == 'OT'){
   			this.OT = (Decimal)ar.get('units');
   		}
   		if((string)ar.get('td') == 'PT'){
   			this.PT = (Decimal)ar.get('units');
   		}
   	
   	}
   	
   	public servPNRollup (id sa, Decimal pt, Decimal ot){
   		this.SAId = sa;
   		this.OT = ot;
   		this.PT = pt;
   	
   	}
   	
   }*/
    
    
    
    public class lineItem {
        
        public Funding_Source__c fundingSource {get;set;}
        public Decimal ptRollup {get;set;}
        public Decimal otRollup {get;set;}
        
        public lineItem(Funding_Source__c f, Decimal pt, Decimal ot){
            this.fundingSource = f;
            this.ptRollup = pt;
            this.otRollup = ot;
            
        }
        
        
    }

}