src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>ReportedEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the id of the initial event... need to populated it on the copy of the reported event that the qualifier will work on.</description>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>ReportedEvent</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Im_IncidentExtension.cls
public with sharing class Im_IncidentExtension {
	public Im_Incident__c incident { get; set; }

	public Im_IncidentExtension(ApexPages.StandardController stdController) {
		if (!Test.isRunningTest()) {
			stdController.addFields(new String[] { 'Status__c',  'ReportedEvent__c'});
		}
		incident = (Im_Incident__c) stdController.getRecord();
	}
	public PageReference redirectImIncidect() {
		if (incident.status__c == 'Event-Draft' && incident.ReportedEvent__c == null){
			DSPSubmitTxn txn = new DSPSubmitTxn();
			txn.requestType = 'Incident';
			txn.inputArgs = incident.id;
			return  txn.submitTxnRequest();
		}
		return new PageReference('/apex/IncidentManagement?id=' + this.incident.Id);
	}
}