src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>ReportedEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the id of the initial event... need to populated it on the copy of the reported event that the qualifier will work on.</description>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>ReportedEvent</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program Associated to Event</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Im_Incidents</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_Incidents (Supervisor)</relationshipLabel>
        <relationshipName>Supervised_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor_for_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Not required if Supervisor field is the same.</description>
        <inlineHelpText>Not required if Supervisor field is the same.</inlineHelpText>
        <label>Supervisor for Location</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_Incidents (Supervisor for Location)</relationshipLabel>
        <relationshipName>LocationSupervisorIncidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Im_IncidentTriggerTests.cls
@isTest
public with sharing class Im_IncidentTriggerTests {
	public static testmethod void createTasks() {
		Im_incident__c event;
		Im_Incident__c incident;
		Task[] eventTasks;
		Task[] incidentTasks;

		Service_Location__c sl = TestUtils.createServiceLocation();
		Id supervisorId = TestUtils.createTmnUser().Id;

		event = new Im_Incident__c(
			Status__c = 'Event-Draft',
			Service_location__c = sl.Id,
			Supervisor__c = supervisorId,
			Supervisor_for_Location__C = supervisorId
		);
		insert event;
		eventTasks = [SELECT Id, OwnerId FROM Task WHERE WhatId = :event.Id];

		System.assertEquals(
			1,
			eventTasks.size(),
			'There should be 1 Task for the event'
		);
		event = [ SELECT Id, OwnerId FROM Im_Incident__c WHERE Id=:event.Id ];
		System.assertEquals(
			event.OwnerId,
			eventTasks[0].OwnerId,
			'The event task should be assigned to the correct person'
		);

		//Submit the event
		event.Status__c = 'Event-Submitted';
		update event;
		eventTasks = [SELECT Id, OwnerId FROM Task WHERE WhatId = :event.Id];
		System.assertEquals(
			0,
			eventTasks.size(),
			'The event task should be deleted after qualifier is created'
		);

		incident = [ SELECT Id FROM Im_Incident__c WHERE ReportedEvent__c = :event.Id ];
		incidentTasks = [SELECT Id, OwnerId FROM Task WHERE WhatId = :incident.Id];
		System.assertEquals(
			1,
			incidentTasks.size(),
			'There should be 1 Task for the qualifier'
		);
		incident = [ SELECT Id, OwnerId FROM Im_Incident__c WHERE Id=:incident.Id ];
		System.assertEquals(
			incident.OwnerId,
			incidentTasks[0].OwnerId,
			'The qualifier task should be assigned to the correct person'
		);
		incident.Status__c = 'Incident-Draft';
		update incident;
		incidentTasks = [SELECT Id, OwnerId FROM Task WHERE WhatId = :incident.Id];
		System.assertEquals(
			1,
			incidentTasks.size(),
			'There should be only 1 Task for the Incident'
		);
	}
}