src/objects/Im_Incident__c.object
<CustomObject>
    <fields>
        <fullName>ReportedEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the id of the initial event... need to populated it on the copy of the reported event that the qualifier will work on.</description>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>ReportedEvent</relationshipLabel>
        <relationshipName>Im_Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event-Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event-Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Disregarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incident-Ready for Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supervisor_for_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Not required if Supervisor field is the same.</description>
        <inlineHelpText>Not required if Supervisor field is the same.</inlineHelpText>
        <label>Supervisor for Location</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_Incidents (Supervisor for Location)</relationshipLabel>
        <relationshipName>LocationSupervisorIncidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_Incident</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Im_InvolvedParty__c.object
<CustomObject>
    <description>The individuals involved with the event/incident.</description>
    <fields>
        <fullName>Im_Incident__c</fullName>
        <label>Im_Incident</label>
        <referenceTo>Im_Incident__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Involved</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Im_InvolvedParties</relationshipLabel>
        <relationshipName>Im_InvolvedParties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Im_InvolvedParty</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Im_InvolvedParties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Im_IncidentTriggerHandler.cls
public without sharing class Im_IncidentTriggerHandler {
    private boolean m_isExecuting = false;

    public Im_IncidentTriggerHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    }
    
    public void OnBeforeInsert(Im_Incident__c[] oldObjects, Im_Incident__c[] updatedObjects, Map<Id, Im_Incident__c> oldObjMap, Map<Id,Im_Incident__c> newObjMap){
	}


    public void OnAfterInsert(Im_Incident__c[] oldObjects, Im_Incident__c[] updatedObjects, Map<Id, Im_Incident__c> oldObjMap, Map<Id,Im_Incident__c> newObjMap){
	
	}
	
	public void OnAfterUpdate(Im_Incident__c[] oldObjects, Im_Incident__c[] updatedObjects, Map<Id, Im_Incident__c> oldObjMap, Map<Id,Im_Incident__c> newObjMap){
		map<Id, Im_Incident__c> incidentTasksToDel = new  Map<Id, Im_Incident__c>();
		map<Id, Im_Incident__c> incidentsToClone = new  Map<Id, Im_Incident__c>();
        for(Im_Incident__c event : updatedObjects){
			if ((event.Status__c == 'Event-Submitted') || (event.Status__c == 'Event-Disregarded')) incidentTasksToDel.put(event.id, event);				
        	if (event.Status__c == 'Event-Submitted') incidentsToClone.put(event.id, event);
    	}
    	
    	if (incidentTasksToDel.keySet().size() > 0) deleteTasksForIncidents(incidentTasksToDel);
    	if (incidentsToClone.keySet().size() > 0) cloneIncidents(incidentsToClone);
	}
	
	private void deleteTasksForIncidents(Map<Id,Im_Incident__c> incidentTasksToDel){
		list<Task> tasks2del = new list<Task>();
		delete [select id from Task where whatId IN : incidentTasksToDel.keySet()];
	}
	
	
	private void cloneIncidents(Map<Id,Im_Incident__c> incidentsToClone){
		list<String> selectFields = new list<string>();
		set<Id> incidentIds = incidentsToClone.keySet();
        Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get('Im_Incident__c').getDescribe().Fields.getMap();
        if (fMap != null) {
        	for (Schema.SObjectField ft : fMap.values()){ // loop through all field tokens (ft)
            	Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                selectFields.add(fd.getName());
            }
		}
		selectFields.addAll(new List<String>{'Supervisor_for_Location__r.Salesforce_User_Account__c'});
		
		list<String> selectFields2 = new list<string>();
		Map<String, Schema.SObjectField> fMap2 = Schema.getGlobalDescribe().get('Im_InvolvedParty__c').getDescribe().Fields.getMap();
        if (fMap2 != null) {
        	for (Schema.SObjectField ft : fMap2.values()){ // loop through all field tokens (ft)
            	Schema.DescribeFieldResult fd = ft.getDescribe(); // describe each field (fd)
                selectFields2.add(fd.getName());
            }
		}
        String strSQL =  'SELECT ' + String.join(selectFields, ',') + ', (SELECT ' + String.join(selectFields2, ',') + ' FROM Im_InvolvedParties__r )' + ' FROM Im_Incident__c WHERE Id IN :incidentIds ';
        system.debug('Incident clone strSQL: ' + strSQL);
        list<Im_Incident__c> incidents = Database.query(strSQL);
		
		for (Im_Incident__c incident : incidents){
			//clone(Boolean preserveId, Boolean isDeepClone, Boolean preserveReadonlyTimestamps, Boolean preserveAutonumber)
			Im_Incident__c incidentClone = incident.clone(false, true, false, false);
			incidentClone.Status__c = 'Event-Draft';
			incidentClone.ReportedEvent__c = incident.id; // the orignal incident reported
			incidentClone.OwnerId = incident.Supervisor_for_Location__r.Salesforce_User_Account__c; // we need to do this so that the task is created for this user
			insert incidentClone;
			
			list<Im_InvolvedParty__c> involvedPartiesClones = new list<Im_InvolvedParty__c>();
			for(Im_InvolvedParty__c invPrty : incident.Im_InvolvedParties__r){
				Im_InvolvedParty__c involvedParty = invPrty.clone(false, true, false, false);
				involvedParty.Im_Incident__c = incidentClone.id;
				involvedPartiesClones.add(involvedParty);
			}
			insert involvedPartiesClones;
		}
		
		//clone evalValues
		
		
	}
}