src/objects/Log_History__c.object
<CustomObject>
    <description>This object is used to track the submission history related to mentor Tracking.</description>
    <fields>
        <fullName>Action_Date_Time__c</fullName>
        <label>Action Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Run</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>By_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>By User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Log_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Submission__c</fullName>
        <label>Date of Submission</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Log History</label>
    <nameField>
        <label>Log History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Create_LogHistory.cls
/*********************************************************************\
@ Created By : Sravan Reddy Pinninti
@ Description: This class is used to create records in the Log History object.
@ Created Date: 03/27/2014
@ Last Modified By :
@ Last Modified Reason: 

/**********************************************************************/

Public with sharing class Create_LogHistory{
    

Public void CreateLogHistory(string action,string objName,Date subDate,string recId, string coms){
      Log_History__c lgh = new Log_History__c();
       lgh.By_User__c = Userinfo.getUserId();
       lgh.Action_Date_Time__c = datetime.now();

       if(string.isNotBlank(action)){
        lgh.Action__c = action;
        }
       

       if(string.isNotBlank(objName)){
       lgh.Object_Name__c = objName;

       }
       
       if(subDate!=null){
       lgh.Date_of_Submission__c = subDate;
       }
       
       if(string.isNotBlank(recId)){
       lgh.Record_Id__c = recId;
       }
       
       if(string.isNotBlank(coms)){
       lgh.Comments__c = coms;
       }


       insert lgh;

  

    }

}