src/objects/PB_AssocDocRecurrence__c.object
<CustomObject>
    <fields>
        <fullName>PB_AssociatedDoc__c</fullName>
        <label>PB_AssociatedDoc</label>
        <referenceTo>PB_AssociatedDoc__c</referenceTo>
        <relationshipLabel>PB_AssocDocRecurrences</relationshipLabel>
        <relationshipName>PB_AssocDocRecurrences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PB_AssocDocRecurrence</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>PB_AssocDocRecurrence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB_AssocDocRecurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PB_AssociatedDoc__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document</label>
        <referenceTo>PB_Document__c</referenceTo>
        <relationshipLabel>AssociatedDocs</relationshipLabel>
        <relationshipName>AssociatedDocs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Calculated based on PBS&apos;s Admission Start Date or Entered (If &quot;Other&quot; in Due)</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PB_AssociatedDoc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AssociatedDocs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PB_Document__c.object
<CustomObject>
    <description>Object to hold the list of all the documents and their default attributes</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recurring_Interval__c</fullName>
        <label>Recurring Interval</label>
        <picklist>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PB_Document</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PB_Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PB_RecurringAssocDocs.cls
global class PB_RecurringAssocDocs implements Database.Batchable<sObject> {
   global final String query;

    global PB_RecurringAssocDocs(String q){
            query=q;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<PB_AssociatedDoc__c> scope){
        sendBatchStartEmail();
 
        List<PB_AssocDocRecurrence__c> recurrs = new List<PB_AssocDocRecurrence__c>();
        for(PB_AssociatedDoc__c assocDoc : scope){
        	
        	recurrs.add(new PB_AssocDocRecurrence__c(PB_AssociatedDoc__c = assocDoc.id,
                                                     Status__c = assocDoc.Status__c,
                                                     Status_Date__c = assocDoc.Status_Date__c));
            assocDoc.Due_Date__c = getDueDate(assocDoc.Status_Date__c, assocDoc.Document__r.Recurring_Interval__c);
            assocDoc.Status__c = 'Pending';
            assocDoc.Status_Date__c = Null;            
        }

        insert recurrs;
        update scope;
    }
   
    private Date getDueDate(Date dueDate, String recurr){
        system.debug('getDueDate inputs: ' + dueDate + '  ' + recurr);
        Date recurrDueDate;
        if (recurr == 'Annually')  recurrDueDate = dueDate.addYears(1); 
        else if (recurr == 'Monthly') recurrDueDate = dueDate.addMonths(1);
        else if (recurr == 'Quarterly') recurrDueDate = dueDate.addMonths(3);
        return recurrDueDate;
    }
    
    global void finish(Database.BatchableContext BC){
        Messaging.reserveSingleEmailCapacity(1);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                List<User> userIDs = [SELECT Id FROM User WHERE Name = 'Neeraj Gupta'];
                Id userID = userIds[0].Id;
                
                // Set receiver of email "target" to the User Id of the script author.
                mail.setTargetObjectId(userID);
                
                // Specify the address used when the recipients reply to the email.                 
                mail.setReplyTo('notifications@thementornetwork.com');
         
                // Specify the name used as the display name.      
                mail.setSenderDisplayName('ESD Batch Jobs');
         
                // Specify the subject line the your email.      
                mail.setSubject('Recurring Admission Documents Batch Confirmation');
                         
                // Set to True if you want to BCC yourself on the email.    
                mail.setBccSender(false);
                          
                // Optionally append the salesforce.com email signature to the email. 
                // The email address of the user executing the Apex Code will be used.             
                mail.setUseSignature(false);
                           
                // Specify the text content of the email.                     
                mail.setPlainTextBody(
                'Hello!  The Recurring Admission Documents (PB_RecurringAssocDocs.cls) batch job ran.  '
                + '/r/n/r/n'
                + 'Datetime of Execution: ' + System.now()
                + '/r/n'
                + 'Thanks!'
                + 'r/n'
                + 'The MENTOR ESD Application'
                );
                
                mail.setHtmlBody(
                'Hello!  The Recurring Admission Documents (PB_RecurringAssocDocs.cls) batch job ran.  '
                + '<br /><br />'
                + 'Datetime of Execution: ' + System.now()
                + '<br /><br />'
                + 'Thanks!'
                + '<br />'
                + 'The MENTOR ESD Application'
                );
                
                mail.setSaveAsActivity(false);
                
                // Send the email you have created. 
                    
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
   }
   
       private void sendBatchStartEmail(){
                Messaging.reserveSingleEmailCapacity(1);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
                List<User> userIDs = [SELECT Id FROM User WHERE Name = 'Neeraj Gupta'];
                Id userID = userIds[0].Id;
                
                // Set receiver of email "target" to the User Id of the script author.
                mail.setTargetObjectId(userID);
                
                // Specify the address used when the recipients reply to the email.                 
                mail.setReplyTo('notifications@thementornetwork.com');
         
                // Specify the name used as the display name.      
                mail.setSenderDisplayName('ESD Batch Jobs');
         
                // Specify the subject line the your email.      
                mail.setSubject('Starting Recurring Admission Documents Batch');
                         
                // Set to True if you want to BCC yourself on the email.    
                mail.setBccSender(false);
                          
                // Optionally append the salesforce.com email signature to the email. 
                // The email address of the user executing the Apex Code will be used.             
                mail.setUseSignature(false);
                           
                // Specify the text content of the email.                     
                mail.setPlainTextBody(
                'Hello!  The Recurring Admission Documents (PB_RecurringAssocDocs.cls) batch job starting....'
                + '/r/n/r/n'
                + 'Datetime of Execution: ' + System.now()
                + '/r/n'
                + 'Thanks!'
                + 'r/n'
                + 'The MENTOR ESD Application'
                );
                
                mail.setHtmlBody(
                'Hello!  The Recurring Admission Documents (PB_RecurringAssocDocs.cls) batch job starting....'
                + '<br /><br />'
                + 'Datetime of Execution: ' + System.now()
                + '<br /><br />'
                + 'Thanks!'
                + '<br />'
                + 'The MENTOR ESD Application'
                );
                
                mail.setSaveAsActivity(false);
                
                // Send the email you have created. 
                    
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
   }
}