src/objects/Person_Being_Referred__c.object
<CustomObject>
    <description>Person Being Referred holds demographic information about a person for the referral process</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age (will be overwritten by a trigger if Date of Birth is filled in)</description>
        <inlineHelpText>If Date of Birth is filled in, then Age is overwritten with the calculated value.</inlineHelpText>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of Birth - if this is filled in, then Age is overwritten based on this date.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <label>Person Being Referred</label>
    <nameField>
        <displayFormat>PBR-{0}</displayFormat>
        <label>PBR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Being Referred</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PersonBeingReferred_TriggerHandler.cls
/*
Created By     : Doug Surfleet (Appirio)
Updated Date   : April 24, 2013
Description    : Trigger handler for PersonBeingReferred object.
*/
public class PersonBeingReferred_TriggerHandler {
	
	/*
	Method		   : UpdateAge
	Params		   : Person_Being_Referred sObject
	Description    : Updates the Age field if the Date of Birth is filled in.
	Created By     : Doug Surfleet (Appirio)
	Updated Date   : April 24, 2013
	*/
	public static void UpdateAge(Person_Being_Referred__c pbr) {
		if (pbr.Date_of_Birth__c != null) {
			Date now = Date.today();
			decimal months = Decimal.valueOf(pbr.Date_of_Birth__c.MonthsBetween(now));
			decimal age = months.divide(12,0,System.RoundingMode.DOWN);
			pbr.age__c = age;
		}
	}

}