src/objects/Person_Being_Referred__c.object
<CustomObject>
    <description>Person Being Referred holds demographic information about a person for the referral process</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age (will be overwritten by a trigger if Date of Birth is filled in)</description>
        <inlineHelpText>If Date of Birth is filled in, then Age is overwritten with the calculated value.</inlineHelpText>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Age_days__c</fullName>
        <label>Age_days</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Age_month__c</fullName>
        <label>Age_month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Age_year__c</fullName>
        <inlineHelpText>If Date of Birth is filled in, then Age is overwritten with the calculated value.</inlineHelpText>
        <label>Age_year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of Birth - if this is filled in, then Age is overwritten based on this date.</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Person Being Referred</label>
    <nameField>
        <displayFormat>PBR-{0}</displayFormat>
        <label>PBR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Being Referred</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <fields>
        <fullName>Person_Being_Referred__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Referred</label>
        <referenceTo>Person_Being_Referred__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/referralResults_Controller.cls
/*******************************************************************************
 Name           : referralResults_Controller
 Created By     : Doug Surfleet (Appirio)
 Created Date   : 4/15/13
 Description    : Extension Controller for Referral Search Resulting of existing users
*******************************************************************************/

public with sharing class referralResults_Controller {

  public integer submitCount{ get; set; }
	
  public String referralId {get;set;}
  
  public String pbrId {get;set;}
  public String retURL {get;set;}
  public String viewmode {get;set;}
   //public List<Referral__c> refResults { get; set; }
  public List<ReferralSearchResults> refResults { get; set; }
  
  public String referralEditUrl { get { return REFERRAL_EDIT_URL; } }
  
  // Allow for pre-filled information
  public String referralNumber { get; set; }
  public String personFirstName { get; set;}
  public String personLastName { get; set;}
  public String personGender { get; set;}
  public String personAge { get; set;}
  public Date personDOB { get; set; }
  public List<SelectOption> genderList { get; set;}
  private Boolean searchImmediately;
 
  public static final String REFERRAL_EDIT_URL = '/apex/referral';

  /*****************************************************************************
    Method Name : Constructor
    Description : To initialize all data members of Class.
  *****************************************************************************/ 
     public referralResults_Controller() {
		submitCount = -1;
		populateGenderList();
		
        // Fill in the information from the GET request (for new referrals only)
       searchImmediately = false;
        if (ApexPages.currentPage().getParameters().get('referralNumber') != null) {
            referralNumber = ApexPages.currentPage().getParameters().get('referralNumber');
            searchImmediately = true;
        }
        if (ApexPages.currentPage().getParameters().get('firstName') != null) {
            personFirstName = ApexPages.currentPage().getParameters().get('firstName');
            searchImmediately = true;
        }
        if (ApexPages.currentPage().getParameters().get('lastName') != null) {
            personLastName = ApexPages.currentPage().getParameters().get('lastName');
            searchImmediately = true;
        }
        if (ApexPages.currentPage().getParameters().get('retURL') != null) {
            retURL = ApexPages.currentPage().getParameters().get('retURL');
            searchImmediately = true;
        }
        
        if (ApexPages.currentPage().getParameters().get('dob') != null) {
            personDOB = Date.parse(ApexPages.currentPage().getParameters().get('dob'));
            searchImmediately = true;
        }
        if (ApexPages.currentPage().getParameters().get('age') != null) {
            personAge = ApexPages.currentPage().getParameters().get('age');
            searchImmediately = true;
        }
        personGender = ApexPages.currentPage().getParameters().get('gender');
        if (ApexPages.currentPage().getParameters().get('viewmode') != null) {
            viewmode = ApexPages.currentPage().getParameters().get('viewmode');
        }
        referralId = ApexPages.currentPage().getParameters().get('referralId');
        pbrId = ApexPages.currentPage().getParameters().get('pbrId');
        system.debug('referralid: ' + referralId);
        if(referralId != null && referralId != 'null') {
                Referral__c ref = [select id,name,Person_Being_Referred__r.First_Name__c,Person_Being_Referred__r.Last_Name__c,Person_Being_Referred__r.Date_of_Birth__c,Person_Being_Referred__r.Age__c,Person_Being_Referred__r.Gender__c,Person_Being_Referred__r.Age_year__c, Person_Being_Referred__r.Age_text__c, Person_Being_Referred__r.Age_days__c, Person_Being_Referred__r.Age_month__c from Referral__c where id=:referralId];
                system.debug(ref);
                personFirstName = ref.Person_Being_Referred__r.First_Name__c;
                personLastName = ref.Person_Being_Referred__r.Last_Name__c;
                personAge = String.valueOf(ref.Person_Being_Referred__r.Age_text__c);
                personGender = ref.Person_Being_Referred__r.Gender__c;
                personDOB = ref.Person_Being_Referred__r.Date_of_Birth__c;
                searchImmediately = true;
        }else if(pbrId != null && pbrId != 'null'){
            Person_Being_Referred__c pbr=[select First_Name__c,Last_Name__c,Date_of_Birth__c,Age__c,Gender__c,Age_year__c,Age_text__c,Age_days__c,Age_month__c from Person_Being_Referred__c where id=:pbrId];
            
            personFirstName = pbr.First_Name__c;
            personLastName = pbr.Last_Name__c;
            personAge = String.valueOf(pbr.Age_text__c);
            personGender = pbr.Gender__c;
            personDOB = pbr.Date_of_Birth__c;
            referralId = null;  
            searchImmediately = true;
        }else{referralId = null; pbrId = null;}
        if (searchImmediately) {
            searchRefs();
        }
    }
 
    
    public void searchRefs() {
		
		
        try
        {
        	double age2 = null;
        	if ( !string.IsBlank(personAge))
        		age2 = double.valueOf(personAge);
        	
        		
        	refResults = SearchLogicOnPBSR.search(referralNumber,personLastName, personFirstName, Date.valueOf(personDOB), age2, personGender);
            system.debug(refResults);
            
            // for the browser back count
            if (!searchImmediately) 
				submitCount -= 1;
            else	// reset the immediate flag
            	searchImmediately = false;
		
           // return null;
        } catch(exception e) {
            ApexPages.addMessages(e);
            //return null;
        }
        
        
    }
    
    private void populateGenderList() {
    	
    	genderList = new list<SelectOption>();
      
      	// Get the object type of the SObject.
      	Schema.sObjectType objType = Person_Being_Referred__c.getSObjectType(); 
      	
      	// Describe the SObject using its object type.
      	Schema.DescribeSObjectResult objDescribe = objType.getDescribe();       
      	
      	// Get a map of fields for the SObject
      	map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
      	 
      	// Get the list of picklist values for this field.
      	list<Schema.PicklistEntry> values = fieldMap.get('Gender__c').getDescribe().getPickListValues();
      	
      	genderList.Add( new SelectOption('',''));
      	
      	// Add these values to the selectoption list.
      	for (Schema.PicklistEntry a : values)
      	{ 
        	genderList.add(new SelectOption(a.getLabel(), a.getValue())); 
      	}
      	
      	

    }
    public Boolean canCreateReferral {
    get {
      return Schema.sObjectType.Referral__c.isCreateable();
    }
    }
    
    public Boolean canUpdateReferral {
    get {
      return Schema.sObjectType.Referral__c.isUpdateable();
    }
  }
  
}