src/objects/Person_Being_Referred__c.object
<CustomObject>
    <description>Person Being Referred holds demographic information about a person for the referral process</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age (will be overwritten by a trigger if Date of Birth is filled in)</description>
        <inlineHelpText>If Date of Birth is filled in, then Age is overwritten with the calculated value.</inlineHelpText>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Person Being Referred</label>
    <nameField>
        <displayFormat>PBR-{0}</displayFormat>
        <label>PBR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Being Referred</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PersonBeingReferred_TriggerHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PersonBeingReferred_TriggerHandler_Test {

    static testMethod void PersonBeingServedAgeUpdateTest() { 
    	test.startTest();
    	Person_Being_Referred__c noAge = Referral_CreateTestData.createPersonBeingReferred(null, Date.today().addYears(-18));
     	system.assert(noAge.Age__c == 18);

    	Person_Being_Referred__c ageOnly = Referral_CreateTestData.createPersonBeingReferred(18, null);
    	system.assert(ageOnly.Age__c == 18);
 
     	Person_Being_Referred__c ageAndDate = Referral_CreateTestData.createPersonBeingReferred(18, Date.today().addYears(-20));
    	system.assert(ageAndDate.Age__c == 20);
    	test.stopTest();
    }
}