src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Admission_State__c</fullName>
        <formula>TEXT( Admission__r.State__c )</formula>
        <label>Admission State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disregard_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <description>indicates note was marked to be diregarded</description>
        <label>Disregard Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProgressNoteNotificationRunBatch.cls
public class ProgressNoteNotificationRunBatch implements schedulable {
    public void execute(SchedulableContext sc){
        String query = 'SELECT Id, OwnerId, Owner.FirstName, Owner.LastName, CreatedDate, Person_Being_Served__c, Person_Being_Served__r.Account.Id FROM Progress_Note__c WHERE Status__c != \'Final\' AND RecordType.Name != \'Shift Note\' AND CreatedDate >= 2013-12-27T00:00:00Z and Admission_State__c != \'AZ\' And Disregard_Note__c = False';
        ID batchprocessid = Database.executeBatch(new ProgressNoteNotifications(query), 50);
    }
}