src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Foster_Parents__c</fullName>
        <label>Foster Parents</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>created for NeuroRestorative IL role and rec type called &quot;Therapy&quot;</description>
        <label>Type of Treatment</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Related_Party__c.object
<CustomObject>
    <description>REFERRALS - Parties having a relationship with the Person Being Referred</description>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Party</relationshipLabel>
        <relationshipName>Related_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Caregiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family/Friends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Co-Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Alternate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician - Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referring Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative Payee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Notes_ProgressNote_RelatedPartyInclude.cls
public with sharing class Notes_ProgressNote_RelatedPartyInclude {
	public Progress_Note__c thePN { get; set;}

	public List<string> strSelectedParties { get; set; }
	public List<SelectOption> soRelParties { get; set; } 
    
    public Notes_ProgressNote_RelatedPartyInclude(ApexPages.StandardController controller) {
        thePN = (Progress_Note__c)controller.getRecord();
        strSelectedParties = new List<string>();
        soRelParties = new List<SelectOption>();
        LoadData(thePN);
    } 
    
    private void LoadData(Progress_Note__c tmp){
        thePN = [select id, Name, Person_Being_Served__c, Foster_Parents__c from Progress_Note__c where id= :tmp.id limit 1];
        if ( thePN.ID == null )
        	return;
        	
        List<Related_party__c> relParties = [ select id, name, type__c from related_party__c where person_being_served__c = :thePN.Person_Being_Served__c and type__c in ('Mentor', 'Mentor Co-Applicant')];
		for ( Related_Party__c rp : relParties ) {
			// create the list of options
			soRelParties.Add( new SelectOption( rp.Name, rp.Name));
		}   
		
		if(!String.isBlank(thePN.Foster_Parents__c))
              strSelectedParties = thePN.Foster_Parents__c.split(';');
                     
    }
    
    public PageReference SaveParties() {
    	string fosters ='';
        for(String f : strSelectedParties )
        	fosters += f+';';
        
        if(fosters !=''){
                fosters = fosters.Substring (0,fosters.length() -1);
                thePN.Foster_Parents__c = fosters;
        }
        else
            thePN.Foster_Parents__c ='';
    	
    	
    	update thePN;
    	return null;
    }
    
    public PageReference SaveScheduling() {
    	update thePN;
    	return null;
    }
    
}