src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Number_of_Required_Signatures__c</fullName>
        <label>Number of Required Signatures</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Signature_on_File__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <label>Signature on File</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CMEsignAZOPT.cls
public with sharing class CMEsignAZOPT implements AuthenticatedAction {
    public PageReference handle(Id recordId, Id userId) {
        string recId = string.valueOf(recordId);
        Progress_note__C progNote = [Select Id, Status__c,Signature_on_File__c,Number_of_Required_Signatures__c from progress_note__c where id =:recordId];
        if ( progNote.Number_of_Required_Signatures__c > 0 ) {
            
                progNote.Signature_on_File__c = 'Y';
                update progNote;            
        }
        return null;
    }
}