src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service ended</description>
        <inlineHelpText>Enter the date and time service ended</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Notes_ProgressNote_DurationInclude.cls
public with sharing class Notes_ProgressNote_DurationInclude {
	
	public Progress_Note__c thePN { get; set;}
	public Boolean diffStartEndDates { get; set; }
	
    public Notes_ProgressNote_DurationInclude(ApexPages.StandardController controller) {
        this.thePN = (Progress_Note__c)controller.getRecord();
        this.diffStartEndDates = false;
        LoadData(thePN);
    } 
    
    private void LoadData(Progress_Note__c tmp){
        thePN = [select id, Name, Start_Time__c, End_Time__c, Duration__c from Progress_Note__c where id= :tmp.id limit 1];
        
        if ( thePN.id != null ) {
	     	Date dtStart = thePN.Start_Time__c.Date();
	    	Date dtEnd = thePN.End_Time__c.Date();
	    	
	    	diffStartEndDates = ( dtStart != dtEnd );
	    	
        }     
    }
    
}