src/objects/Progress_Note__c.object
<CustomObject>
    <description>NOTES Progress Notes are the notes taken for a Person Being Served on their progress towards meeting the goals on a Plan. Progress Notes are Master-detail to Plans.</description>
    <fields>
        <fullName>CM_Billable_Category__c</fullName>
        <label>Billable Category</label>
        <picklist>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Esigned_At__c</fullName>
        <label>Esigned At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Esigned_By__c</fullName>
        <label>Esigned By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Narrative__c</fullName>
        <label>Narrative</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Appt_Date_Time__c</fullName>
        <inlineHelpText>Next Scheduled Appointment with this person.</inlineHelpText>
        <label>Next Appt. Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>People_Present__c</fullName>
        <description>Enter names of other people present with the person being served during this session.</description>
        <inlineHelpText>Enter names of other people present with the person being served during this session.</inlineHelpText>
        <label>People Present</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Purpose_Service_is_Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Default Check Box means this service is Billable, if this service is NOT Billable please Uncheck the box</inlineHelpText>
        <label>Purpose/Service is Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RW_Signature_required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Signature required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Enter the date and time service delivery started</description>
        <inlineHelpText>Enter the date and time service delivery started</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type_of_Contact__c</fullName>
        <inlineHelpText>Meeting type that took place.</inlineHelpText>
        <label>Type of Contact</label>
        <picklist>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face-To-Face</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telehealth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <label>Progress Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CM_ESign_PDFController.cls
public with sharing class CM_ESign_PDFController {
    public Progress_Note__c pNote { get; set; }
    public CM_ESign_PDFController() {
    	user u = [select firstname,lastname from user where Id = :UserInfo.getUserId() LIMIT 1];
    	pNote =  [SELECT Id,Start_Time__c, Type_of_Contact__c, People_Present__c, RW_Signature_required__c, Purpose_Service_is_Billable__c, CM_Billable_Category__c, Narrative__c,
    				Next_Appt_Date_Time__c, Esigned_By__c, Esigned_At__c FROM Progress_Note__c WHERE Id= :ApexPages.currentPage().getParameters().get('id') ];
    				if(pNote.Esigned_By__c == null){
    					pNote.Esigned_By__c = u.firstname + ' ' + u.lastname;
    					pNote.Esigned_At__c = dateTime.now();
    				}
    }
}