src/objects/Project__c.object
<CustomObject>
    <description>RWN Project</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Neuro_Restorative</fullName>
        <active>true</active>
        <label>Neuro Restorative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project_Task__c.object
<CustomObject>
    <description>RWN Project</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectTaskVSPageLayout.cls
public with sharing class ProjectTaskVSPageLayout {
    public Project_Task__c projTask {get; set;}
    public ProjectTaskVSPageLayout(ApexPages.StandardController controller) {
        projTask = (Project_Task__c) controller.getRecord();       
    }
    public pageReference CheckForRD(){
        if(projTask.Project__r.RecordType.DeveloperName=='Neuro_Restorative'){
            PageReference ref = new PageReference('/apex/proj_nr_form?id=' + projTask.Project__r.id + '&gotoID=' + projTask.id);            
            return ref;
    }
        return null;
    }
    
    
    

}