src/objects/Prospects__c.object
<CustomObject>
    <description>PMC</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entry_Point__c</fullName>
        <defaultValue>&quot;Employee&quot;</defaultValue>
        <description>Entry Point</description>
        <inlineHelpText>Entry Point</inlineHelpText>
        <label>Entry Point</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Multiple_Inquiry_Comments__c</fullName>
        <inlineHelpText>If a prospect submits a web inquiry more than once their entries will be combined into one record to avoid duplicates.  Any additional details including any changes to their contact info will be displayed in this field.</inlineHelpText>
        <label>Multiple Inquiry Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <description>Primary Phone</description>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Prospect_Comments__c</fullName>
        <description>Entered by prospects on the web</description>
        <inlineHelpText>Entered by prospects on the web</inlineHelpText>
        <label>Prospect Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cid__c</fullName>
        <description>Web Campaign ID</description>
        <inlineHelpText>Web Campaign ID</inlineHelpText>
        <label>Web External Campaign ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>org__c</fullName>
        <description>Organic Referral</description>
        <inlineHelpText>Organic Referral</inlineHelpText>
        <label>Web Organic Referral</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>rs__c</fullName>
        <description>Web External Campaign ID</description>
        <inlineHelpText>Web External Campaign ID</inlineHelpText>
        <label>Web Referral Source ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tag__c</fullName>
        <label>Web tag</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tp__c</fullName>
        <label>Web Targeted Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Prospect</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProspectInsert2.cls
public class ProspectInsert2{

    public Prospects__c myProspect {get; set;}
    public boolean success {get;set;}
    
    public ProspectInsert2(){
        myProspect = new Prospects__c();
        myProspect.Entry_Point__c = 'Web';
        success = false;
        if(ApexPages.currentPage().getParameters().containsKey('cid__c'))
            myProspect.cid__c = ApexPages.currentPage().getParameters().get('cid__c');
        if(ApexPages.currentPage().getParameters().containsKey('org__c'))
            myProspect.org__c = ApexPages.currentPage().getParameters().get('org__c');
        if(ApexPages.currentPage().getParameters().containsKey('rs__c'))
            myProspect.rs__c = ApexPages.currentPage().getParameters().get('rs__c');
        if(ApexPages.currentPage().getParameters().containsKey('tp__c'))
            myProspect.tp__c = ApexPages.currentPage().getParameters().get('tp__c');
        if(ApexPages.currentPage().getParameters().containsKey('tag__c'))
            myProspect.tag__c = ApexPages.currentPage().getParameters().get('tag__c');
    }
        

    
            public PageReference SubmitMADAH(){
      try{
              list <Prospects__c> myList = [select Id,Email__c,Multiple_Inquiry_Comments__c from Prospects__c where Email__c = :myProspect.Email__c];
        
                if(myList.size()> 0){
                    prospects__c temp = myList[0];
                    date currentDate = date.Today();
                    string strCurrentDate = currentDate.month()+'/'+currentDate.day()+'/'+currentDate.year();
                    string currentInquiryComment = temp.Multiple_Inquiry_Comments__c;
            
            
                    if(currentInquiryComment==null){currentInquiryComment='';}
                    temp.Multiple_Inquiry_Comments__c = currentInquiryComment+'<b>Date Inquiry Added: </b>'+strCurrentDate+'<br/><b>Name: </b>'+myProspect.First_Name__c+' '+myProspect.Name+'<br/><b>Phone #: </b>'+myProspect.Primary_Phone__c+'<br/><b>Comments: </b>'+myProspect.Prospect_Comments__c+'<br/><br/>';
            

                    update temp;  
                }
            else{insert myProspect;}
        }
        catch (DMLException ex){
            ApexPages.addMessages(ex);
            return null;
        }
    
       
          PageReference tyPage = Page.ProspectWebRegistrationFormThankyouMADAH;
        //  tyPage.setRedirect(true);
          return tyPage;

    }
    
    private static testmethod void controllerTest(){
        //Campaign c = new Campaign();
        //c.name = 'Test Campaign';
        //insert c;
        //ApexPages.currentPage().getParameters().put('campaignid', c.id);
            ProspectInsert2 controller = new ProspectInsert2();    
    String nextPage = controller.SubmitMADAH().getUrl();
        
        ApexPages.currentPage().getParameters().put('cid__c', '00000000000000');
        ApexPages.currentPage().getParameters().put('rs__c', '00000000000000');
        ApexPages.currentPage().getParameters().put('org__c', '00000000000000');
        ApexPages.currentPage().getParameters().put('tp__c', '00000000000000');
        ApexPages.currentPage().getParameters().put('tag__c', '00000000000000');
        ProspectInsert2 pi11 = new ProspectInsert2();
        pi11.myProspect.zip__c = '55555';
        pi11.myProspect.Entry_Point__c = 'Web';
        pi11.myProspect.State__c = 'AL';
        controller.SubmitMADAH();
        System.assertEquals(false, pi11.success);
        System.assertEquals('/apex/prospectwebregistrationformthankyoumadah', nextPage );
        
        
     
               
    }
}