src/objects/Referral__c.object
<CustomObject>
    <description>REFERRAL - Stores data related to clients being referred</description>
    <fields>
        <fullName>Guardianship_Type__c</fullName>
        <label>Guardianship Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Guardianship/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Guardianship/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Guardian_Status__c</fullName>
        <label>Legal/Guardianship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Civil Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservator/Conservatorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Care Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kinship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Guardianship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelter Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Assumes Guardianship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Placement Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <label>Referral Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/referralbatchforPersonRegistry.cls
global class referralbatchforPersonRegistry implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		string query = 'SELECT Id, Legal_Guardian_Status__c, Guardianship_Type__c FROM Referral__c WHERE Legal_Guardian_Status__c =\'Self\'';
		
		return  Database.getQueryLocator(query);
		
	}
	
	global void execute(Database.BatchableContext BC, List<Referral__c> scope){
		List<Referral__c> guardianshipUpdateList = new List<Referral__c>();
		for(Referral__c ref: scope){
			ref.Guardianship_Type__c = 'Self';
			guardianshipUpdateList.add(ref);
		}
		
		if(guardianshipUpdateList.size() > 0){
			update guardianshipUpdateList;
		}
		
	}
	
	global void finish(Database.BatchableContext BC){
		List<String> toAddresses = new List<String>();
		toAddresses.add('adam.vernatter@thementornetwork.com');
		Messaging.singleEmailMessage mail = new Messaging.singleEmailMessage();
		mail.setToAddresses(toAddresses);
		mail.setSenderDisplayName('Referral Batch');
		mail.setSubject('Referral Batch to update Guardianship type is completed');
		mail.setUseSignature(false);
		string body = 'Batch processing is completed. I do not know what to do next';
		mail.setplainTextBody(body);
		mail.setSaveAsActivity(false);
		
		Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
		
	}

}