src/objects/Seizure__c.object
<CustomObject>
    <fields>
        <fullName>End_DateTime__c</fullName>
        <label>End DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Seizures</relationshipLabel>
        <relationshipName>Seizures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start DateTime</label>
        <type>DateTime</type>
    </fields>
    <label>Seizure</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Seizure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seizures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SeizureTrackingRptTest.cls
@isTest
private class SeizureTrackingRptTest {

   static testmethod void simpleTests(){
        TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();
        
        Datetime stEndTime = Datetime.newInstance(2015,1,5).addDays(-2);
        
        List<Seizure__c> seizures = new List<Seizure__c>();

        For(integer i=0; i < 10; i++){
            Seizure__c s = new Seizure__c();
            s.Service_Assignment__c = testData.theSA.Id;
            s.Start_DateTime__c = stEndTime.addHours(i);
            s.End_DateTime__c = stEndTime.addHours(i+1);
            seizures.add(s);
        }
        insert seizures;
        
        PageReference pageRef = Page.SeizureTrackingRpt;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('saId', testData.theSA.Id);
        
        SeizureTrackingRpt controller = new SeizureTrackingRpt();
        controller.startdtStr = 'January 2015';
        
        controller.runreport();
        system.assert(controller.getSeizures().size() == 10);
    }
    
}