src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Staff Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose a clinician from the list</errorMessage>
            <filterItems>
                <field>TMN_User__c.Operating_Group__c</field>
                <operation>equals</operation>
                <valueField>$User.Operating_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Personal_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Personal_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Agent</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment Personal Agent</label>
    <nameField>
        <label>Service Assignment Personal Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment Personal Agent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Provider_JO__c.object
<CustomObject>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TMN_Provider__c</fullName>
        <label>TMN Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service_Assignment_Provider_JO</label>
    <nameField>
        <displayFormat>PJO-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Assignment_Provider_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Provider__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Providers</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TmnProviderTriggerHandler.cls
public without sharing class TmnProviderTriggerHandler {
	private boolean m_isExecuting = false;

	public TmnProviderTriggerHandler(boolean isExecuting){
		m_isExecuting = isExecuting;
	}

	public void onBeforeInsert(Tmn_Provider__c[] oldObjects, Tmn_Provider__c[] updatedObjects, Map<Id, Tmn_Provider__c> oldObjMap, Map<Id,Tmn_Provider__c> newObjMap) {
		generateSoundExKeys(updatedObjects);
		updateNames(updatedObjects);
	}

	public void onBeforeUpdate(Tmn_Provider__c[] oldObjects, Tmn_Provider__c[] updatedObjects, Map<Id, Tmn_Provider__c> oldObjMap, Map<Id,Tmn_Provider__c> newObjMap) {
		generateSoundExKeys(updatedObjects);
		updateNames(updatedObjects);
	}

	public void onAfterUpdate(Tmn_Provider__c[] oldObjects, Tmn_Provider__c[] updatedObjects, Map<Id, Tmn_Provider__c> oldObjMap, Map<Id,Tmn_Provider__c> newObjMap) {
		Tmn_Provider__c[] disqualifiedProviders = new Tmn_Provider__c[]{};
		Tmn_Provider__c[] expiredProviders = new Tmn_Provider__c[]{};

		for (Tmn_Provider__c provider: updatedObjects) {
			if (provider.Status__c == 'Disqualified') {
				disqualifiedProviders.add(provider);
			} else if (provider.Status__c == 'Expired') {
				expiredProviders.add(provider);
			}
		}
		if (disqualifiedProviders.size() > 0) {
			notifyPersonalAgents(disqualifiedProviders, Status.DISQUALIFIED);
		}
		if (expiredProviders.size() > 0) {
			notifyPersonalAgents(expiredProviders, Status.EXPIRED);
		}
	}

	private static void generateSoundExKeys(Tmn_Provider__c[] updatedObjects) {
		SoundExTriggerUtil util = new SoundExTriggerUtil();
		util.generateKeys(updatedObjects);
	}

	private static void updateNames(Tmn_Provider__c[] updatedObjects) {
		for (Tmn_Provider__c provider: updatedObjects) {
			provider.Name = String.format('{0} {1}', new String[]{ provider.First_Name__c, provider.Last_Name__c });
		}
	}

	private enum Status { DISQUALIFIED, EXPIRED }

	private static void notifyPersonalAgents(Tmn_Provider__c[] providers, Status providerStatus) {
		Service_Assignment_Provider_JO__c[] associations = [
			SELECT Id, Tmn_Provider__c, Service_Assignment__c, Tmn_Provider__r.Name,
			       Service_Assignment__r.Name,
			       Service_Assignment__r.Person_Being_Served__r.CreatedById
			  FROM Service_Assignment_Provider_JO__c
			 WHERE Tmn_Provider__c IN :providers
		];
		Map<Id, Id> saToPbsOwner = new Map<Id, Id>();
		Map<Id, Id[]> saToUsersNotified = new Map<Id, Id[]>();
		Map<Id, Service_Assignment_Provider_JO__c[]> saToAssociations = new Map<Id, Service_Assignment_Provider_JO__c[]>();
		for (Service_Assignment_Provider_JO__c association: associations) {
			saToPbsOwner.put(association.Service_Assignment__c, association.Service_Assignment__r.Person_Being_Served__r.CreatedById);
			saToUsersNotified.put(association.Service_Assignment__c, new Id[]{});
			if (!saToAssociations.containsKey(association.Service_Assignment__c)) {
				saToAssociations.put(association.Service_Assignment__c, new Service_Assignment_Provider_JO__c[]{});
			}
			saToAssociations.get(association.Service_Assignment__c).add(association);
		}
		Service_Assignment_Personal_Agent__c[] personalAgentAssociations = [
			SELECT Id, Service_Assignment__c, Personal_Agent__r.Salesforce_User_Account__c
			  FROM Service_Assignment_Personal_Agent__c
			 WHERE Service_Assignment__c IN :saToUsersNotified.keySet()
			   AND Status__c = 'Active'
		];
		for (Service_Assignment_Personal_Agent__c paAssociation: personalAgentAssociations) {
			saToUsersNotified.get(paAssociation.Service_Assignment__c).add(paAssociation.Personal_Agent__r.Salesforce_User_Account__c);
		}
		// If no Active Personal Agents was found, notify the PBS Owner
		for (Id saId: saToUsersNotified.keySet()) {
			if (saToUsersNotified.get(saId).size() == 0) {
				saToUsersNotified.get(saId).add(saToPbsOwner.get(saId));
			}
		}

		// Actually creating Task for these users
		Task[] tasksToCreate = new Task[]{};
		for (Id saId: saToUsersNotified.keySet()) {
			for (Id userId: saToUsersNotified.get(saId)) {
				for (Service_Assignment_Provider_JO__c association: saToAssociations.get(saId)) {
					Task task = new Task(
						Status = 'In Progress',
						Priority = 'High',
						OwnerId = userId,
						WhatId = saId,
						RecordTypeId = TmnProvider.TASK_RECORD_TYPE
					);
					if (providerStatus == Status.DISQUALIFIED) {
						task.Subject = 'Provider Disqualification Notification';
						task.Description = String.format(
							'Provider {0} for Service Assignment: {1} has been disqualified. Please select another approved provider for this Person Being Served.',
							new String[]{
								association.Tmn_Provider__r.Name,
								association.Service_Assignment__r.Name
							}
						);
					} else if (providerStatus == Status.EXPIRED) {
						task.Subject = 'Provider Expiration Notification';
						task.Description = String.format(
							'Provider {0} for Service Assignment: {1} has expired. Please perform the applicable provider renewal activities or select another approved provider for this Person Being Served.',
							new String[]{
								association.Tmn_Provider__r.Name,
								association.Service_Assignment__r.Name
							}
						);
					}
					tasksToCreate.add(task);
				}
			}
		}
		insert tasksToCreate;
	}
}