src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>PBS_ServiceLocation_Count__c</fullName>
        <label>PBS ServiceLocation Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceAssignmentTriggeredActions.cls
/*
 *
 *  EC-16 : Trigger to store the service location count for the person being served. 
 *
 */

public with sharing class ServiceAssignmentTriggeredActions {

	public void OnBeforeInsert(Service_Assignment__c[] newObjects){
        boolean found;
        List<SAaggregates> currCounts = getSAaggregateList();	
		// loop through all the inserted service assignments
		for(Service_Assignment__c sa :newObjects ){
			// update the ServiceLocationCount only if the sevice location is present
			if (sa.Service_Location__c != null){
				found = false;
				// loop through the aggregate count resluts, if found, that means this person had been at this location before, so increment the count to +1. And update the same in the lookup results
				for (SAaggregates res : currCounts){
					if (sa.Person_Being_Served__c == res.personBeingServed  &&  sa.Service_Location__c == res.serviceLocation ){
						sa.PBS_ServiceLocation_Count__c = res.totalPlusOne();
						found = true;
						break;
					}
				}
	            // if not found in the existing list, then mark it as the first entry into this service location; 
	            // Also, need to add this service assignment to the aggregate results
	            if (!found){
	                sa.PBS_ServiceLocation_Count__c = 1;
	                currCounts.add(new SAaggregates(sa.Service_Location__c, sa.Person_Being_Served__c, 1));             
	            }
            }            
		}
		
	}


    public void OnBeforeUpdate(Service_Assignment__c[] oldObjects, Service_Assignment__c[] updatedObjects, Map<Id,Service_Assignment__c> oldObjMap){
        boolean found;
        List<SAaggregates> currCounts = getSAaggregateList();
        
        // loop through all the updated service assignments
        for(Service_Assignment__c sa :updatedObjects){
            // update the ServiceLocationCount if the service location was added to the service assignment
            if (sa.Service_Location__c != null && oldObjMap.get(sa.id).Service_Location__c == null && sa.PBS_ServiceLocation_Count__c == null ){
                found = false;
                // loop through the aggregate count resluts, if found, that means this person had been at this location before, so increment the count to +1. And update the same in the lookup results
                for (SAaggregates res : currCounts){
                    if (sa.Person_Being_Served__c == res.personBeingServed  &&  sa.Service_Location__c == res.serviceLocation ){
                        sa.PBS_ServiceLocation_Count__c = res.totalPlusOne();
                        found = true;
                        break;
                    }
                }
	            // if not found in the existing list, then mark it as the first entry into this service location; 
	            // Also, need to add this service assignment to the aggregate results
	            if (!found){
	                sa.PBS_ServiceLocation_Count__c = 1;
	                currCounts.add(new SAaggregates(sa.Service_Location__c, sa.Person_Being_Served__c, 1));             
	            }                
            }
            // To update the exisiting service assignment records.
            else if (sa.Service_Location__c != null && (sa.PBS_ServiceLocation_Count__c == null || sa.PBS_ServiceLocation_Count__c == 0 )){
                for (SAaggregates res : currCounts){
                    if (sa.Person_Being_Served__c == res.personBeingServed  &&  sa.Service_Location__c == res.serviceLocation ){
                        sa.PBS_ServiceLocation_Count__c = res.total;
	                    --res.total;
	                    break;
                    }
                }            	
            }
        }
    }

    private List<SAaggregates> getSAaggregateList(){
    	List<SAaggregates> aggregates = new List<SAaggregates>();
        List<AggregateResult> currCounts = [SELECT Service_Location__r.id slID, Person_Being_Served__c, count (id) total FROM Service_Assignment__c where Service_Location__c != null group by Person_Being_Served__c, Service_Location__r.id];
        for (AggregateResult res : currCounts) {
        	aggregates.add(new SAaggregates( (Id) res.get('slID'), String.valueOf(res.get('Person_Being_Served__c')), Integer.valueOf(res.get('total'))));
        	
        }
        return aggregates;          	
    }    
    
    
    class SAaggregates{
    	public Id serviceLocation; 
        public String personBeingServed;
        public Integer total;
    	
        public SAaggregates(Id serviceLocation, String personBeingServed, Integer total){
	        this.serviceLocation = serviceLocation; 
	        this.personBeingServed = personBeingServed;
	        this.total = total;
        }
        public Integer totalPlusOne(){
        	return ++this.total;
        }
    } 
    
    
   /* 
    class ServiceAssignmentWrapper implements Comparable {

	    public Service_Assignment__c servAssig;

	    // Constructor 
	    public ServiceAssignmentWrapper(Service_Assignment__c s) {
	        servAssig = s;
	    }
	    
	    // Compare service Assigment based on the created date 
	    global Integer compareTo(Object compareTo) {

	        ServiceAssignmentWrapper compareToSA = (ServiceAssignmentWrapper)compareTo;
	        // The return value of 0 indicates that both elements are equal. 	    
	        Integer returnValue = 0;
	        if (servAssig.id > compareToSA.servAssig.id) {
                // Set return value to a negative value. 	    
	            returnValue = -1;
	        } else if (servAssig.id < compareToSA.servAssig.id) {
                // Set return value to a positive value. 
	            returnValue = 1;
	        }
	        return returnValue;
	    }
    }
    */
    
}