src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/T_Event__c.object
<CustomObject>
    <fields>
        <fullName>Default_Address__c</fullName>
        <label>Default Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Default_End_Time__c</fullName>
        <label>Default_End_Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Start_Time__c</fullName>
        <label>Default_Start_Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Vehicle</label>
        <referenceTo>T_Event__c</referenceTo>
        <relationshipLabel>T_Events</relationshipLabel>
        <relationshipName>T_Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>T_Events</relationshipLabel>
        <relationshipName>T_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Common pick up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common drop off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Transportation</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>T_Event</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T_Events</pluralLabel>
    <recordTypes>
        <fullName>Route</fullName>
        <active>true</active>
        <description>The routes associated to a service location</description>
        <label>Route</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vehicle</fullName>
        <active>true</active>
        <label>Vehicle</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/T_RoutesController.cls
public with sharing class T_RoutesController {
private static final Id ROUTE_REC_TYPE_ID=Utility.getEventRecordType('Route');
public Id routeId {get; set;}
public list<T_Route> routeList {get; set;}
public T_Route currentRoute {get; set;}
private T_TransportationSetup cntrlr;
public T_RoutesController(T_TransportationSetup parent){
	this.cntrlr = parent;
    refreshRouteList();
}

public void editRoute(){
    T_Event__c r = [select name,Id,RecordTypeId,CreatedDate,CreatedById,CreatedBy.Name,Service_Location__r.Name,
                               Service_Location__c,Service_Location__r.Location_NickName__c,Type__c,Default_Start_Time__c,
                               Default_End_Time__c,Default_Address__c,Status__c, default_vehicle__r.name, default_vehicle__c
                          From T_Event__c where Id =: routeId];
	this.currentRoute = new T_Route(r);
}

public void newRoute(){
    this.currentRoute = new T_Route();
}

public void saveRoute(){
	T_Event__c r = getRouteSobject(this.currentRoute);
    if (validateRoute(this.currentRoute)){
    	try{
		  upsert r;
    	}catch(Exception e){
    		Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
    	}
	    refreshRouteList();
    }
}
private boolean validateRoute(T_Route route){
	if (String.IsEmpty(route.routeName)) {
	   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Route Name: You must enter a value.'));
	   return false;
	} else if (String.IsEmpty(route.routeType)){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Route Type: You must enter a value.'));
       return false;
    } else if (String.IsEmpty(route.serviceLocId)){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Location Of Service: You must select a value.'));
       return false;
    } else if (String.IsEmpty(route.address)){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Address: You must enter a value..'));
       return false;
    } else if (String.IsEmpty(route.startTime)){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Default Start Time: You must enter a value.'));
       return false;
    } else if (String.IsEmpty(route.endTime)){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Default End Time: You must enter a value.'));
       return false;
    }
    return true;
}

private void refreshRouteList(){
	this.routeList = new list<T_Route>();
	for(T_Event__c r : [select name,Id,RecordTypeId,CreatedDate,CreatedById,CreatedBy.Name,Service_Location__r.Name,
						       Service_Location__c,Service_Location__r.Location_NickName__c,Type__c,Default_Start_Time__c,
						       Default_End_Time__c,Default_Address__c,Status__c, default_vehicle__r.name, default_vehicle__c 
						  From T_Event__c 
						 where RecordTypeId =: ROUTE_REC_TYPE_ID
						 order by Service_Location__c, Name, CreatedDate]){
		this.routeList.add(new T_Route(r));
	}
}
public static list<SelectOption> getRouteTypeOpts(){
    list<SelectOption> lst = new list<SelectOption>();
    lst.add(new SelectOption('',''));
    lst.addAll(Utility.getPicklistValues(new T_Event__c(recordTypeId=ROUTE_REC_TYPE_ID), 'Type__c'));
    return lst;
}
public static list<SelectOption> getRouteStatusOpts(){
    list<SelectOption> lst = new list<SelectOption>();
    lst.addAll(Utility.getPicklistValues(new T_Event__c(recordTypeId=ROUTE_REC_TYPE_ID), 'Status__c'));
    return lst;
}
public list<SelectOption> getDefaultVehicleOpts(){
    list<SelectOption> lst = new list<SelectOption>();
    T_VehiclesController vehicles = new T_VehiclesController(this.cntrlr);
    lst.add(new selectOption('', '--Select Vehicle--'));
    for (T_Event__c v : vehicles.vehicleList){
        lst.add(new selectOption(v.Id, v.Name));    	
    }
    return lst;
}

public static T_Event__c getRouteSobject(T_Route r){
	return ((r.routeId instanceof Id) ? 
	         new T_Event__c(id=r.routeId, Name=r.routeName, Type__c=r.routeType, Service_Location__c=r.serviceLocId,
	                        recordTypeId=ROUTE_REC_TYPE_ID, Default_Address__c=r.address, Default_Start_Time__c=r.startTime, Default_End_Time__c=r.endTime, status__c=r.status, default_vehicle__c=r.vehicleId) :
             new T_Event__c(Name=r.routeName, Type__c=r.routeType, Service_Location__c=r.serviceLocId,
                            recordTypeId=ROUTE_REC_TYPE_ID, Default_Address__c=r.address, Default_Start_Time__c=r.startTime, Default_End_Time__c=r.endTime, status__c=r.status, default_vehicle__c=r.vehicleId)
            );
}
private Datetime createDatetimeToken(String timeStr){
	if (String.IsEmpty(timeStr)) return null;
	else {
		String[] timeParts = timeStr.substringBefore(' ').split(':');
        if (timeStr.substringAfter(' ').equalsIgnoreCase('PM')) {
        	return DateTime.newInstance(Date.newInstance(1,1,2000),Time.newInstance(Integer.valueOf(timeParts[0])+12, Integer.valueOf(timeParts[1]),0,0));
        } else {
        	return DateTime.newInstance(Date.newInstance(1,1,2000),Time.newInstance(Integer.valueOf(timeParts[0]), Integer.valueOf(timeParts[1]),0,0));
        }
	}
}
public class T_Route {
	public String routeId {get;set;}
    public String routeName {get;set;}
    public String routeType {get;set;}
    public Id serviceLocId {get; set;}
    public String serviceLocNickName {get; set;}
    public String serviceLocName {get; set;}
    public String address {get; set;}
    public Id vehicleId {get; set;}
    public String vehicleName {get; set;}
    public String startTime {get; set;}
    public String endTime {get; set;}
    public String status {get;set;}
    public String createdBy {get;set;}
    public Id createdById {get;set;}
    public datetime createdDate {get; set;}
    public T_Route(){this.routeId=Null;}
    public T_Route(T_Event__c r){
    	this.routeId = r.id;
        this.routeName = r.Name;
        this.routeType = r.Type__c;
        this.serviceLocId = r.Service_Location__c;
        this.address = r.Default_Address__c;
        this.startTime = r.Default_Start_Time__c;
        this.endTime = r.Default_End_Time__c;
        this.serviceLocNickName = (r.Service_Location__c != null ? r.Service_Location__r.Location_Nickname__c : '');
        this.serviceLocName = (r.Service_Location__c != null ? r.Service_Location__r.Name : '');
        this.status = r.Status__c;
        this.createdBy = (r.createdBy == null ? UserInfo.getName() : r.createdBy.Name );
        this.createdById = (r.createdBy == null ? UserInfo.getUserId() : r.createdBy.Id );
        this.createdDate = (r.createdDate == null ? system.now() : r.createdDate );
        this.vehicleId = r.default_Vehicle__c;
        this.vehicleName = (r.default_Vehicle__c == null ? '' : r.default_Vehicle__r.Name );
    }
}
}