src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Provider_JO__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TMN_Provider__c</fullName>
        <label>TMN Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service_Assignment_Provider_JO</label>
    <nameField>
        <displayFormat>PJO-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Assignment_Provider_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TMN_Provider__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Providers</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_Provider_Application__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>TMN Provider Applications</relationshipLabel>
        <relationshipName>TMN_Provider_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Provider Applications</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProviderServiceAgreementTests.cls
@isTest
public with sharing class ProviderServiceAgreementTests {
	@testSetup
	public static void setUpData() {
		TestUtils.CoreDataGenerator generator = new TestUtils.CoreDataGenerator();
		generator.aliasBuilder
			.setState('OR')
			.setName('038025');  // Mid Valley
		generator.serviceLocationBuilder.setState('OR');
		generator.serviceLocationBuilder
			.setServiceType('CM - Case Management')
			.setProgramId('111111000')
			.setLocationNickname('Brokerage 1');
		TestUtils.CoreData coreData = generator.persistData();

		Tmn_Provider__c[] providers = new Tmn_Provider__c[]{
			new Tmn_Provider__c(
				First_Name__c = 'First',
				Last_Name__c = 'Person',
				Status__c = 'Approved'
			)
		};
		insert providers;

		Tmn_Provider_Application__c[] applications = new Tmn_Provider_Application__c[]{
			new Tmn_Provider_Application__c(
				Provider__c = providers[0].Id,
				Effective_Date__c = Date.today().addMonths(-1),
				Expiration_Date__c = Date.today().addMonths(1),
				Status__c = 'Approved'
			)
		};
		insert applications;
	}

	public static testmethod void simpleTests() {
		PageReference pageRef = Page.ProviderServiceAgreement;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('saId', [SELECT Id FROM Service_Assignment__c LIMIT 1].Id);
		Service_Assignment_Provider_JO__c agreement = new Service_Assignment_Provider_JO__c();
		ProviderServiceAgreement controller = new ProviderServiceAgreement(new ApexPages.StandardController(agreement));
		System.assertEquals(false, controller.isViewMode);
		System.assertEquals(true, controller.isNewMode);
		System.assertEquals(true, controller.isEditMode);
		System.assertEquals(false, controller.getIsLocked());
		System.assertEquals(true, controller.isMidValley);
		System.assertEquals(false, controller.isMetro);
		System.assertEquals(true, controller.canFinalize);
		System.assertEquals(0, controller.getServiceCodes().size());
		System.assertEquals(0, controller.getCheckedServiceCodes().size());
		System.assertEquals(null, controller.getAssociatedIsp());
		System.assertEquals(false, controller.getHasInactiveDraftIsp());
		System.assertEquals(0, controller.getCommonLawEmployerOptions().size());
		System.assertEquals('N/a', controller.getCommonLawEmployer());
		System.assertEquals(0, controller.getEmergencyContactOptions().size());
		System.assertEquals('N/a', controller.getEmergencyContact());
		System.assertEquals(0, controller.getRisks().size());
		System.assertEquals('New Provider Service Agreement Association', controller.getTitle());

		System.assertEquals(null, controller.save()); // Validation error here
		controller.agreement.Tmn_Provider__c = [SELECT Id FROM Tmn_Provider__c].Id;
		controller.agreement.Start_Date__c = Date.today();
		controller.agreement.End_Date__c = Date.today().addDays(-1);

		// Validation errors since start date > end date
		System.assertEquals(null, controller.save());

		controller.agreement.End_Date__c = Date.today().addYears(2);

		// Validation errors since since end date > start date + 13 months
		System.assertEquals(null, controller.save());

		controller.agreement.Start_Date__c = Date.today().addMonths(-2);
		controller.agreement.End_Date__c = Date.today().addDays(15);

		// Validation errors since start date not within application range
		System.assertEquals(null, controller.save());

		controller.agreement.Start_Date__c = Date.today();
		controller.save();
	}
}