src/objects/Service_Code__c.object
<CustomObject>
    <description>Notes</description>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Rollup__c</fullName>
        <label>Program Rollup</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Value__c</fullName>
        <label>Program Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Service #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>ProgramID__c</fullName>
        <label>ProgramID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Rollup__c</fullName>
        <description>the program for reporting</description>
        <label>Program Rollup</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ServiceLocationTriggerHandler.cls
public with sharing class ServiceLocationTriggerHandler {

	private boolean m_isExecuting = false;

    public ServiceLocationTriggerHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    }
    
    public void OnAfterInsert( Service_Location__c [] newObjects){
        updateServiceCodeInfo( null, newObjects );
        
    }
    public void OnAfterUpdate( Service_Location__c[] oldObjects, Service_Location__c [] newObjects){
        updateServiceCodeInfo( oldObjects, newObjects );
        
    }
    
    private void updateServiceCodeInfo (Service_Location__c[] oldObjects, Service_Location__c[] newObjects ) {
		
		Map<ID, Service_Location__c> oldSLMap = new Map<ID, Service_Location__c>();
		
		if ( oldObjects != null )
			oldSLMap.putAll( oldObjects);
			
		Service_Location__c oldSL;
		
		Map<String, Service_Location__c> slMap = new Map<String, Service_Location__c>();
		for ( Service_Location__c sl : newObjects ) {
			
			oldSL = oldSLMap.get(sl.ID);
			
			// if an update, check for change to specific fields
			if ( oldSL != null ) {
				if ( oldSL.Program_Rollup__c != sl.Program_Rollup__c || oldSL.Program__c != sl.Program__c )
					slMap.put( sl.ProgramID__c, sl);
			} else {
				// always put new locations in for update
				slMap.put( sl.ProgramID__c, sl);
			}
		}
		
		
		// get all the service codes with this program code
		List<Service_Code__c> servcodes = [ select id, program_code__c, program_rollup__c from service_code__c where program_code__c in :slMap.keySet() ];
		
		for ( Service_code__c sc : servcodes ) {
			
			//update from service location
			sc.Program_Rollup__c = slMap.get( sc.Program_code__c ).Program_Rollup__c;
			sc.Program_Value__c = slMap.get(sc.Program_code__c).Program__c;
			
		}
		if (servcodes.size() > 0 )
			update servcodes;
		    	
    }
    
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
}