src/objects/Service_Assignment__c.object
<CustomObject>
    <description>NOTES Service Assignments describe the services that can be performed for a Person Being Served. This object is master-detail to Admissions.</description>
    <fields>
        <fullName>Clinician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Staff Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please choose a clinician from the list</errorMessage>
            <filterItems>
                <field>TMN_User__c.Operating_Group__c</field>
                <operation>equals</operation>
                <valueField>$User.Operating_Group__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_Being_Served__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Being Served</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location where service is being performed</description>
        <label>Service Location</label>
        <referenceTo>Service_Location__c</referenceTo>
        <relationshipLabel>Service Assignment</relationshipLabel>
        <relationshipName>Service_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Assignment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment</label>
    <nameField>
        <label>Service Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Personal_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Personal_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Agent</label>
        <referenceTo>TMN_User__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service Assignment Personal Agent</relationshipLabel>
        <relationshipName>Service_Assignment_Personal_Agent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Assignment Personal Agent</label>
    <nameField>
        <label>Service Assignment Personal Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Assignment Personal Agent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Assignment_Provider_JO__c.object
<CustomObject>
    <fields>
        <fullName>Disregard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disregard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Assignment__c</fullName>
        <label>Service Assignment</label>
        <referenceTo>Service_Assignment__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Service Agreement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TMN_Provider__c</fullName>
        <label>TMN Provider</label>
        <referenceTo>TMN_Provider__c</referenceTo>
        <relationshipLabel>Service_Assignment_Provider_JOs</relationshipLabel>
        <relationshipName>Service_Assignment_Provider_JOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service_Assignment_Provider_JO</label>
    <nameField>
        <displayFormat>PJO-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Assignment_Provider_JOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Location__c.object
<CustomObject>
    <description>REFERRALS - Alias/Program/Location for &quot;location working referral&quot; and &quot;anticipated admission location&quot;</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Location</label>
    <nameField>
        <label>Alias</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TMN_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Providers</pluralLabel>
    <recordTypes>
        <fullName>OR</fullName>
        <active>true</active>
        <label>OR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EndofServiceProvisioningBatch.cls
global class EndofServiceProvisioningBatch implements Database.Batchable<sObject>, Schedulable{
    private final static date todaydate = system.today();
    global Database.QueryLocator start(Database.BatchableContext BC){
        string query = 'SELECT Service_Assignment__c, Service_Assignment__r.Name,Service_Assignment__r.Status__c,Service_Assignment__r.Person_Being_Served__r.ownerid,Service_Assignment__r.Person_Being_Served__r.Name,Service_Assignment__r.Person_Being_Served__c,status__c,Service_Assignment__r.service_location__r.service_type__c,TMN_Provider__c,TMN_Provider__r.Name,TMN_Provider__r.Status__c,End_Date__c, Start_Date__c from Service_Assignment_Provider_JO__c WHERE Service_Assignment__r.service_location__r.service_type__c =\'CM - Case Management\' AND Service_Assignment__r.Status__c = \'Active\' AND Disregard__c = False AND TMN_Provider__r.Status__c = \'Approved\' AND ((End_Date__c =: todaydate AND Status__c = \'Active\') OR ( Start_Date__c =: todaydate AND Status__c = \'Pending\'))';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Service_Assignment_Provider_JO__c> scope){
        System.debug('List --->' + scope);
        id tpaId = [SELECT Id FROM RecordType WHERE SObjectType = 'Task' and name = 'Tmn Provider Application'][0].id;
        list<id> providerIds = New List<Id>();
        Map<Id, Id[]> saToUsersNotified = new Map<Id, Id[]>();
        List<id> ServiceAssignmentIds = New list<id>(); 
        list<task> listNotificationTask = New List<Task>();
        Map<id,string> SrvcAssgnIdtoPersonalAgentName = New Map<Id,string>();
        for(Service_Assignment_Provider_JO__c srvcProvJO:scope){
            providerIds.add(srvcProvJO.TMN_Provider__c);
            ServiceAssignmentIds.add(srvcProvJO.Service_Assignment__c);
            saToUsersNotified.put(srvcProvJO.Service_Assignment__c, new Id[]{});
        }
        list<Service_Assignment_Provider_JO__c> juncObjeRecordsToUpdate = new List<Service_Assignment_Provider_JO__c>();
        list<Service_Assignment_Personal_Agent__c> pagentList = [SELECT Id,Service_Assignment__c,Personal_Agent__r.Salesforce_User_Account__c,Personal_Agent__r.Last_name__c,Status__c FROM Service_Assignment_Personal_Agent__c WHERE Service_Assignment__c IN: ServiceAssignmentIds AND Status__c =: 'Active' ];
        for (Service_Assignment_Personal_Agent__c paAssociation: pagentList) {
            saToUsersNotified.get(paAssociation.Service_Assignment__c).add(paAssociation.Personal_Agent__r.Salesforce_User_Account__c);
        }
        
        Map<String,id> srvcAssignmentToActiveTaskIdMap = New Map<String,Id>();
        list<task> serviceProvisioningTasklist = [select id,whatid,Description from task where whatid In:ServiceAssignmentIds And Subject = 'End of Service Provisioning Notification' And status != 'Completed' ];
        if(serviceProvisioningTasklist.size()>0){
            for(task t:serviceProvisioningTasklist ){
                srvcAssignmentToActiveTaskIdMap.put(t.whatid + t.Description,t.id);
            }
        }
        for(Service_Assignment_Provider_JO__c srvcProvJO:scope){
            if(srvcProvJO.status__c == 'Pending' ){
                srvcProvJO.Status__c = 'Active';
                juncObjeRecordsToUpdate.add(srvcProvJO);
            }
            else if(srvcProvJO.status__c == 'Active' && srvcProvJO.TMN_Provider__r.status__c == 'Approved'){
                srvcProvJO.Status__c = 'Expired'; 
                if(srvcAssignmentToActiveTaskIdMap != Null && srvcAssignmentToActiveTaskIdMap.containsKey(srvcProvJO.Service_Assignment__c + 'Document: Service Assignment between provider ' + srvcProvJO.TMN_Provider__r.Name + ' and Person Being Served ' + srvcProvJO.Service_Assignment__r.Person_Being_Served__r.Name + 'for Service Assignment: ' + srvcProvJO.Service_Assignment__r.Name + ' has reached its end date. Please perform the applicable service provisoning renewal activities for this Person Being Served.')){
                }else{
                    // If no Active Personal Agents was found, notify the PBS Owner
                    for (Id saId: saToUsersNotified.keySet()) {
                        if (saToUsersNotified.get(saId).size() == 0) {
                            saToUsersNotified.get(saId).add(srvcProvJO.Service_Assignment__r.Person_Being_Served__r.ownerid);
                        }
                    }
                    Id saId = srvcProvJO.Service_Assignment__c;
                    for (Id userId: saToUsersNotified.get(saId)) {
                        
                            Task NotificationTask = New Task();
                            NotificationTask.Subject = 'End of Service Provisioning Notification';
                            NotificationTask.Description = 'Service Assignment between provider ' + srvcProvJO.TMN_Provider__r.Name + ' and Person Being Served ' + srvcProvJO.Service_Assignment__r.Person_Being_Served__r.Name + 'for Service Assignment: ' + srvcProvJO.Service_Assignment__r.Name + ' has reached its end date. Please perform the applicable service provisoning renewal activities for this Person Being Served.' ;
                            NotificationTask.Priority = 'Normal';
                            notificationTask.recordtypeid = tpaId; 
                            NotificationTask.Status = 'In Progress'; 
                            NotificationTask.WhoId = srvcProvJO.Service_Assignment__r.Person_Being_Served__c;    
                            NotificationTask.whatid = srvcProvJO.Service_Assignment__c;
                            if(userId != Null)
                                NotificationTask.ownerId = userId;
                            else
                                NotificationTask.ownerId = srvcProvJO.Service_Assignment__r.Person_Being_Served__r.ownerid; 
                            listNotificationTask.add(NotificationTask);
                    }
                }
                juncObjeRecordsToUpdate.add(srvcProvJO);
            }
        }
        if(listNotificationTask.size()>0){
            Database.insert(listNotificationTask,false);
        }
        if(juncObjeRecordsToUpdate.size()>0){
            update juncObjeRecordsToUpdate;
        }
    }

    global void finish(Database.BatchableContext BC){
    }
    
    //Scheduling the batch
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new EndofServiceProvisioningBatch(), 30);
    }




}