src/objects/Therapy_Hour__c.object
<CustomObject>
    <label>Therapy_Hour</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapy_Hours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>Discipline__c</fullName>
        <label>Discipline</label>
        <picklist>
            <picklistValues>
                <fullName>Dietitian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speech Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-Massage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counseling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Woodshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Productive Activity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <description>By default, this will be Active for any person in the database. As time goes and the feed only puts in Active users, we&apos;ll need to update the ones in the database but are not in the feed to Inactive.</description>
        <label>Job Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TherapyHoursTest.cls
@isTest
private class TherapyHoursTest {
    static testMethod void myUnitTest() {
    	
   	
        // create a test account with discipline
    	User testuser = TMN_Generic_Core_TestData.createUser('iServe-TherapistMobile','ther', 'therapist@tmn.test.com', 'Test', 'Therapist', 'Care Meridian');
    	TMN_Generic_Core_TestData.permsetAssign(new String[] {'iServe_TherapistMobile'}, testuser.Id);
    	TMN_User__c myuser = [ select id, discipline__c, job_status__c from tmn_user__c where salesforce_user_account__c = :testuser.id LIMIT 1];
    	myuser.discipline__c = 'PT';
    	myuser.job_status__c = 'Active';
    	update myuser;
        
        system.runas( testuser ) {	
        TMN_Generic_Core_TestData testData = new TMN_Generic_Core_TestData();
        
        PageReference pageRef = Page.TherapyHours;
        Test.setCurrentPage(pageRef);
        TherapyHours th = new TherapyHours();
        system.assertequals(true, th.getProgramslist().contains('--Select--'));
        Integer i = th.getProgramsList().indexOf('a0v');
        String selpgm = '';
        system.debug (' index is ' + i );
        if ( i > 0) {
        	selpgm=th.getProgramsList().substring( i, i+18);
        	system.debug( selpgm);
        }
        String formData = '{"selectprograms":"' + selpgm + '","pbsList":"' + testData.theSA.Id + '","entryType":"Individual Treatment","startDateTime":"2015-10-01T01:00","endDateTime":"2015-10-01T02:00","narrativeNotes":"the test class entry."}';
        TherapyHours.saveFields(formData);
        system.assertequals(1, [select id from Therapy_Hour__c].size() );
        
        }
    }

}