src/objects/TMN_Provider_Application__c.object
<CustomObject>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TMN Provider Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMN Provider Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TmnProviderExpirationBatch.cls
global with sharing class TmnProviderExpirationBatch implements Database.Batchable<sObject>, Schedulable {
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([
			SELECT Id, Status__c
			  FROM Tmn_Provider_Application__c
			 WHERE Status__c = 'Approved'
			   AND Expiration_Date__c <= :Date.today()
		]);
	}

	global void execute(Database.BatchableContext BC, List<Tmn_Provider_Application__c> applications) {
		Tmn_Provider_Application__c[] applicationsToUpdate = new Tmn_Provider_Application__c[]{};

		for (Tmn_Provider_Application__c application: applications) {
			applicationsToUpdate.add(
				new Tmn_Provider_Application__c(
					Id = application.Id,
					Status__c = 'Expired'
				)
			);
		}
		update applicationsToUpdate;
	}

	global void finish(Database.BatchableContext BC) {}

	//Scheduling the batch
	global void execute(SchedulableContext sc) {
		Database.executeBatch(new TmnProviderExpirationBatch(), 100);
	}
}