src/objects/TMN_Contract__c.object
<CustomObject>
    <description>CAMBRIDGE CONTRACT</description>
    <fields>
        <fullName>Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approver_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>-Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ViewContractExtension.cls
public with sharing class ViewContractExtension {
    public TMN_Contract__c tmnContract {get; set;}
    public Apexpages.standardController controller; 
    
    public ViewContractExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        if(!test.isRunningTest()) {
            controller.addFields(new list<string>{'Approver_1__c'});
        }
        tmnContract = (TMN_Contract__c)controller.getRecord();
        
    }
    public PageReference Submit() {
        // Create an approval request for the this evaluation
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setObjectId(tmnContract.id);
        req1.setNextApproverIds(new Id[]{tmnContract.Approver_1__c});
        Approval.ProcessResult result = Approval.process(req1);
        return new PageReference('/'+tmnContract.id);   
    }
    
}