src/objects/TMN_User__c.object
<CustomObject>
    <fields>
        <fullName>CPR_Expires__c</fullName>
        <label>CPR Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discipline__c</fullName>
        <label>Discipline</label>
        <picklist>
            <picklistValues>
                <fullName>Dietitian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speech Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-Massage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupational Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counseling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Woodshop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Productive Activity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Expires__c</fullName>
        <label>Insurance Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <description>By default, this will be Active for any person in the database. As time goes and the feed only puts in Active users, we&apos;ll need to update the ones in the database but are not in the feed to Inactive.</description>
        <label>Job Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Leave</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expires__c</fullName>
        <label>License Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mentor_Cell_Phone__c</fullName>
        <label>Mentor Cell Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Office_Phone__c</fullName>
        <label>Office Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Salesforce_User_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The actual Salesforce account for this user.</inlineHelpText>
        <label>Salesforce User Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TMN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>phone_ext__c</fullName>
        <label>phone_ext</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TMNAccess</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMNAccess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Operating_Group__c</fullName>
        <label>Operating Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TherapistLicExpiring.cls
public without sharing class TherapistLicExpiring {
    private String soql {get;set;}
    public list<TMN_User__c> therapistList {get;set;}
    public String sortDir {
        get {if(sortDir == null) { sortDir = 'Asc nulls last'; } return sortDir;}
        set;
    }
    public String sortField {
        get  { if (sortField == null) {sortField = 'First_Name__c'; } return sortField;  }
        set;
    }
    public String sortColumn { get; set; }
    public String sortOrder { get; set; }
    public TherapistLicExpiring() {
    	sortField = 'First_Name__c';
        soql = 'SELECT Id, Name, First_Name__c, Last_Name__c, Discipline__c, License_Expires__c, Insurance_Expires__c, CPR_Expires__c, Office_Phone__c, phone_ext__c, Mentor_Cell_Phone__c, Personal_Email__c, Salesforce_User_Account__c, job_Status__c ' +
                   'FROM TMN_User__c Where Discipline__c != \'\' and operating_group__c = \'Care Meridian\' and Salesforce_User_Account__r.IsActive = true ' +
                   'and (License_Expires__c <= NEXT_N_DAYS:30 OR License_Expires__c = null OR Insurance_Expires__c <= NEXT_N_DAYS:30 OR Insurance_Expires__c = null OR CPR_Expires__c <= NEXT_N_DAYS:30 OR CPR_Expires__c = null)'; 
        runQuery();
    }
    public void toggleSort() {
        sortDir = sortDir.equals('asc') ? 'desc nulls Last' : 'asc';
        runQuery();
    }
    public void runQuery() {
       try {
            therapistList = Database.query(soql + ' order by ' + sortField + ' ' + sortDir);
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There is an error retrieving the Therapist records.'));
        }
        
    }
}