src/objects/TMN_Corp_Contract__c.object
<CustomObject>
    <description>Corp Contracts - Procurement.</description>
    <fields>
        <fullName>Total_Required_Feilds_Answered__c</fullName>
        <label>Total Required Feilds Answered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Required_Fields__c</fullName>
        <label>Total Required Fields</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Corp Contract</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corp Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CorpContract_CountReqFields.cls
public with sharing class CorpContract_CountReqFields {

    public CorpContract_CountReqFields(ApexPages.StandardController controller) {

    }
    public CorpContract_CountReqFields() {

    }    


    
    public static void DoCount(List<TMN_Corp_Contract__c> contracts){
        Set<string> Fields = new Set<string>();
        Fields.clear();
        
                for(Schema.FieldSetMember f :
                 SObjectType.TMN_Corp_Contract__c.FieldSets.ProcureReqFields.getFields()) {
                    Fields.Add(f.getFieldPath());
                    
            }
            
            for(TMN_Corp_Contract__c local: contracts){
                        Integer TotalFields = 0;
                        Integer TotalAnsweredFields = 0;
                        for(String f: Fields){
                                TotalFields += 1;
                                        
                                if(local.get(f) !=Null){
                                        {TotalAnsweredFields +=1 ;}
                                }
                        }
                        local.Total_Required_Feilds_Answered__c = TotalAnsweredFields;
                        local.Total_Required_Fields__c = TotalFields;
            }
            
            
        
                   
                        
    }
static testMethod void testMyController()
   {      
       TMN_Corp_Contract__c contract = new TMN_Corp_Contract__c();
       insert contract;       
   }   

}