src/objects/TMN_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>TMN_Contact__c</referenceTo>
        <relationshipLabel>Related Parties</relationshipLabel>
        <relationshipName>Related_Parties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TMN Contact</label>
    <nameField>
        <displayFormat>TMN-CNT-{0000}</displayFormat>
        <label>TMN Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TMN Contacts</pluralLabel>
    <recordTypes>
        <fullName>Mentor</fullName>
        <active>true</active>
        <label>Mentor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MentorViewAllController.cls
public with sharing class MentorViewAllController {
    public TMN_Contact__c contact { get; set; }

    public MentorViewAllController(ApexPages.standardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new String[] {'Mentor__c', 'RecordType.Name'});
        }
        contact = (TMN_Contact__c) stdController.getRecord();
    }

    public PageReference routeRequest() {
        // If a request is made to a non-mentor record (e.g. a Co-applicant),
        // reroute that request to the main Mentor page and go to Household
        // Member section.
        System.debug('Contact: ' + contact);
        if (contact.RecordType.Name.indexOf('Mentor') == -1) {
            PageReference ref = new PageReference('/apex/MentorView?id=' + contact.Mentor__c);
            ref.setAnchor('householdMembers');
            return ref;
        }
        return new PageReference('/apex/MentorView?id=' + contact.Id);
    }
}