src/objects/Transaction_Queue__c.object
<CustomObject>
    <description>Stores requests from user without permissions to be fulfilled by a login with higher auth</description>
    <fields>
        <fullName>Date_Time_Fulfilled__c</fullName>
        <description>Date/time result was saved to table</description>
        <label>Date/Time Fulfilled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fulfilled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the request has been fulfilled</description>
        <label>Fulfilled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requesting_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>user id that requested txn</description>
        <label>Requesting User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transaction_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Code__c</fullName>
        <description>Result code of transaction (success/error/etc).</description>
        <label>Result Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Value__c</fullName>
        <description>JSON string containing serialized response to request</description>
        <label>Return Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Transaction Queue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TxnQueueResponseController.cls
public with sharing class TxnQueueResponseController {

	public String TxnResponse { get; private set; }
	public ActionPlan_FormWithoutSharing  response { get; private set; }
	

//Constructor
	public TxnQueueResponseController(){

		ID txnID;
		
		// pick up the txnid off the URL
		try {
			txnID = ApexPages.CurrentPage().getParameters().get('txnID');
		if ( txnID == null) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid transaction ID'));
			return;
			}
		} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid transaction ID'));
			return;
		}
		
		ID thisUser = UserInfo.getUserID();
		
		// get the txn result
		Transaction_Queue__c thisTxn =[ select id, result_code__c, fulfilled__c, date_time_fulfilled__c, return_value__c
								from transaction_queue__c
								where id = :txnID];
								//and requesting_user__c = :thisUser];
		
		TxnResponse = thisTxn.return_value__c;
		
		response = (ActionPlan_FormWithoutSharing) JSON.deserialize(thisTxn.return_value__c, ActionPlan_FormWithoutSharing.class);
		
		system.debug(response);
	}
	
	
}