src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Legal_Custodian_Update_By__c</fullName>
        <description>User who last updated the legal custodian field</description>
        <label>Legal Custodian Update By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Custodian_Update_Date__c</fullName>
        <description>Date that the legal custodian field was last updated</description>
        <label>Legal Custodian Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legal_Custodian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legal Custodian</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/UserTriggeredActions.cls
public with sharing class UserTriggeredActions {

    private boolean m_isExecuting = false;

    public UserTriggeredActions(boolean isExecuting){
        m_isExecuting = isExecuting;
    }

    public void OnBeforeUpdate(list<user> updatedObjects, Map<Id,user> oldObjMap){
        // BEFORE UPDATE LOGIC
            
            
            
            for(user newusr : updatedobjects){
                    
            user old = oldObjMap.get(newusr.id);
            
            boolean oldCust;
            boolean newCust;
            if (old.legal_custodian__c != null) oldCust = old.legal_custodian__c;
            if (newusr.legal_custodian__c != null) newCust = newusr.legal_custodian__c;
            //System.Debug('What is in the old user:' + oldAssnUser);
            //System.Debug('What is in the new user:' + newAssnUser);
                    
            //If legal custodian value has changed update the update date and update by field 
            if (oldCust != NewCust)
            {
               newusr.legal_custodian_Update_Date__c = date.today();
               newusr.legal_custodian_Update_By__c = Userinfo.getname();
            }
        
       }

    
    }

   
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }

}